.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, Quickwit_individual_CLA.md
=> Added CONTRIBUTING.md file

quickwit-metastore/Cargo.toml, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-storage/Cargo.toml, quickwit-storage/src/lib.rs, quickwit-storage/src/object_storage/error.rs, quickwit-storage/src/storage.rs, quickwit-storage/tests/s3_storage.rs
Also, this adds a mock interface for the storage trait.
=> Fixes testsuite feature for the storage crate.

quickwit-doc-mapping/src/lib.rs
Can you fix the compilation with the lint directive?
=> Missing docs docmapping.

quickwit-cli/src/main.rs, quickwit-core/src/index.rs, quickwit-metastore/src/lib.rs, quickwit-metastore/src/metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-storage/src/ram_storage.rs, quickwit-storage/src/storage_resolver.rs
Changes APIs around SplitId, IndexUri, IndexId, etc. according to the specification in #55.
Closes issue #55
=> Attempts to address the IndexUri, IndexId, SplitId confusion.

quickwit-core/src/index.rs, quickwit-core/src/indexing/index.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-metastore/src/metastore_resolver.rs, quickwit-storage/src/lib.rs
=> Add SingleFileMetastoreFactory in MetastoreUriResolver resolver

quickwit-metastore/src/metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs
Introducing get_index and put_index to remove boilerplate.
=> Refactoring SingleFileMetastore.

quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-metastore/src/metastore_resolver.rs
The indexing needed some enhancements
Added temporary changes to MetastoreUriResolver so we can resolve multiple protocols
=> Support multiple protocol on MetastoreUriResolver

quickwit-cli/src/main.rs, quickwit-core/src/index.rs, quickwit-core/src/indexing/index.rs, quickwit-core/src/lib.rs
@evanxg852000 Can you add the docs for the different methods? Some of the specs should be on notion.
@guilload can you review them?
=> Added lint forbidding missing docs in quickwit-core

quickwit-core/src/indexing/split.rs
=> Avoid merging segments if there is only one #99

quickwit-metastore/src/error.rs, quickwit-metastore/src/metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-metastore/src/metastore_resolver.rs
Fixes typos and wording in metastore code. Cleans up some code (mostly variable renames).
```
cargo test
```
=> Fix metastore docs and clean up some code

quickwit-core/Cargo.toml, quickwit-directories/Cargo.toml, quickwit-doc-mapping/Cargo.toml, quickwit-search/Cargo.toml, quickwit-search/src/collector.rs, quickwit-search/src/filters.rs, quickwit-search/src/leaf.rs, quickwit-search/src/lib.rs
Need to prune docs that don't fall in time range before they get to Collector. 
[See Issue](https://github.com/quickwit-inc/quickwit/issues/123)
**Note: Let's hold this till (https://github.com/tantivy-search/tantivy/issues/1084) in merged into our internal tantivy as to avoid cascading todos.*
=> Time Range filter in QuicwitCollector

quickwit-cli/src/main.rs, quickwit-doc-mapping/src/default_doc_mapper/default_mapper.rs
(See Issue 133](https://github.com/quickwit-inc/quickwit/issues/133)
=> Checking timestamp field is fast field.

quickwit-doc-mapping/src/default_doc_mapper/default_mapper.rs, quickwit-search/src/collector.rs, quickwit-search/src/filters.rs, quickwit-search/src/lib.rs
Optimize filtering if the predicate is always matched [see issue](https://github.com/quickwit-inc/quickwit/issues/139)
- implemented optimization
- added test for filtering
=> Filtering Optimization

quickwit-doc-mapping/Cargo.toml, quickwit-doc-mapping/src/default_doc_mapper/default_mapper.rs, quickwit-doc-mapping/src/default_doc_mapper/field_mapping_entry.rs
- Fix #173
- handle null json value 
- clean error messages
=> Fix issue #173

quickwit-directories/src/caching_directory.rs, quickwit-directories/src/hot_directory.rs, quickwit-search/src/leaf.rs
... and plugged it into quickwit.
Also added some unit tests.
=> Added unlimited mode to the `CacheDirectory`. (#165)

quickwit-telemetry/Cargo.toml
=> Removing last dependency to openssl

quickwit-doc-mapping/src/default_doc_mapper/default_mapper.rs
=> Forbid '_source' as a field name

quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs
Move code to lib.rs, to improve testability
=> move cli code to lib.rs

quickwit-cli/Cargo.toml, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-cli/tests/cli.rs, quickwit-cli/tests/prepare_tests.sh
move code to CreateIndexArgs constructor
add lib test
add serial for test dependency
add prepare_test script to create and clean s3 test data bucket
=> move code to constructor

quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-cli/tests/cli.rs, quickwit-serve/src/args.rs
use CreateIndex constructor and make fields private
replace matches! with assert_eq
add test comment
=> add equality comparator

quickwit-cli/src/cli.yaml, quickwit-cli/src/main.rs, quickwit-cli/tests/cli.rs, quickwit-cluster/src/cluster.rs, quickwit-common/Cargo.toml, quickwit-common/src/lib.rs, quickwit-proto/proto/search_api.proto, quickwit-proto/src/quickwit.rs, quickwit-search/Cargo.toml, quickwit-search/src/client_pool.rs, quickwit-search/src/client_pool/search_client_pool.rs, quickwit-search/src/lib.rs, quickwit-search/src/rendezvous_hasher.rs, quickwit-search/src/root.rs, quickwit-search/src/service.rs, quickwit-serve/Cargo.toml, quickwit-serve/src/args.rs, quickwit-serve/src/error.rs, quickwit-serve/src/grpc.rs, quickwit-serve/src/grpc_adapter.rs, quickwit-serve/src/lib.rs, quickwit-serve/src/rest.rs
Implement distributed search.
https://github.com/quickwit-inc/quickwit/issues/120
=> Distributed search

.github/workflows/publish.yml, installer, quickwit-cli/Cargo.toml, quickwit-cli/tests/helpers.rs, quickwit-telemetry/src/sender.rs
=> Naming the cli binary 'quickwit' instead of quickwit-cli

quickwit-cli/src/lib.rs, quickwit-search/Cargo.toml, quickwit-search/src/lib.rs, quickwit-search/src/search_result_json.rs, quickwit-serve/src/rest.rs
=> Proper json serialization in search CLI.

quickwit-cli/src/lib.rs
=> Add stats output even when fed from stdin.

quickwit-cli/src/lib.rs, quickwit-core/src/indexing/document_indexer.rs, quickwit-core/src/indexing/split.rs, quickwit-core/src/test_utils.rs, quickwit-doc-mapping/src/all_flatten_mapper.rs, quickwit-doc-mapping/src/default_doc_mapper/default_mapper.rs, quickwit-doc-mapping/src/default_doc_mapper/mod.rs, quickwit-doc-mapping/src/lib.rs, quickwit-doc-mapping/src/mapper.rs, quickwit-doc-mapping/src/wikipedia_mapper.rs, quickwit-metastore/src/metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-search/src/collector.rs, quickwit-search/src/lib.rs, quickwit-search/src/root.rs, quickwit-search/src/service.rs
=> rename DocMapper to IndexConfig

quickwit-proto/Cargo.toml
=> Fixing build broken due to update of prost-build.

quickwit-cli/src/lib.rs, quickwit-index-config/src/query_builder.rs, quickwit-proto/proto/search_api.proto, quickwit-proto/src/quickwit.rs, quickwit-search/src/lib.rs, quickwit-serve/src/rest.rs
Closes https://github.com/quickwit-inc/quickwit/issues/225
Added `search fields` to rest API and making use of it in the CLI
=> Using Search Fields from CLI & API

install.sh, quickwit-cli/src/cli.yaml
=> Update install.sh and remove CLI from cli about.

Cargo.lock, README.md, quickwit-common/src/lib.rs, quickwit-storage/Cargo.toml, quickwit-storage/src/storage_resolver.rs
=> add QuickwitEnv to enable localstack on localhost

quickwit-common/src/lib.rs
=> remove trailing / in index uri

install.sh
Closes https://github.com/quickwit-inc/quickwit/issues/276
Just now falling back to GLIBC gnu when musl is not detected. 
Testing on the different OS to make sure nothing was broken
OS openSUSE-Leap-15 (works)
OS Fedora-Workstation-Live-x86_64-29-1.2 (works)
OS CentOS-7-x86_64 (works) - musl version detected & installed
OS manjaro-xfce-17.1.7-stable-x86_64 (works)
=> Error message in Installer

.github/workflows/coverage.yml, quickwit-cli/tests/cli.rs
=> fix coverage closes #265

README.md
=> Fixing typo to Quickstart

quickwit-cli/src/main.rs, quickwit-cluster/src/cluster.rs, quickwit-common/src/lib.rs, quickwit-core/src/indexing/index.rs, quickwit-core/src/indexing/split.rs, quickwit-directories/src/caching_directory.rs
Fix some typo inside comments/docs
Hello,
This PR includes several fix of comments/docs I found while reviewing the code.
Please kindly check 🙏
=> Some fix of comments

quickwit-proto/proto/search_api.proto, quickwit-proto/src/quickwit.rs, quickwit-search/src/collector.rs, quickwit-search/src/root.rs
=> rename aggregated_results to attempted_splits #124

Cargo.lock, quickwit-cli/Cargo.toml, quickwit-cli/src/lib.rs
Closes https://github.com/quickwit-inc/quickwit/issues/284
Implemented throughput calculation based on interval
run it and see behavior
=> Throughput based on interval

Cargo.lock, quickwit-core/Cargo.toml, quickwit-directories/Cargo.toml, quickwit-proto/Cargo.toml, quickwit-search/Cargo.toml, quickwit-serve/Cargo.toml, quickwit-telemetry/Cargo.toml
Closes https://github.com/quickwit-inc/quickwit/issues/325
- Ran `cargo +nightly udeps ` to list unused dependencies
- Removed unused dependencies
executed create, index, search locally after deps removal.
=> Remove unused deps

.github/workflows/dockerhub.yaml, .github/workflows/release.yml, docker/Dockerfile, docs/getting-started/installation.md, docs/getting-started/quickstart.md, quickwit-cli/tests/helpers.rs
Closes https://github.com/quickwit-inc/quickwit/issues/270
Add workflow to build & push docker image to docker hub
- Make and publish a release
- Pull and run the image
=> Docker image build & push

docs/reference/cli.md
Closes https://github.com/quickwit-inc/quickwit/issues/312
Added section in cli reference for `gc` command
=> CLI doc for gc command

docs/overview/features.md
Dearest Reviewer,
I noticed a missing paren. I could not let that stand.
Thanks for the amazing code. I am enjoying reading it.
Becker
=> Doc update

quickwit-storage/src/cache/mod.rs, quickwit-storage/src/cache/storage_with_cache.rs
=> use cache in StorageWithCache fixes #343

quickwit-core/src/index.rs, quickwit-core/src/lib.rs, quickwit-metastore/src/error.rs
Fixing a few things as I'm going through the code and docs.
See commit messages.
n/a
=> Fix miscellaneous items

docs/reference/cli.md, quickwit-cli/src/cli.yaml
A user recently opened an issue regarding serving multiple indexes. See #345 and #350. 
I updated the docs, providing clearer instructions and a few more examples.
n/a
=> Improve `serve` command docs

quickwit-cluster/src/cluster.rs
The loop was using 100% of one core.
Closes #370
=> Lightens the cluster monitoring loop

quickwit-search/src/client.rs
Closes https://github.com/quickwit-inc/quickwit/issues/367
- handling grpc client error
- found & fixed blocking bug
=> handle gRPC client error

docs/reference/index-config.md, quickwit-index-config/src/default_index_config/field_mapping_entry.rs, quickwit-index-config/src/default_index_config/field_mapping_type.rs
Closes https://github.com/quickwit-inc/quickwit/issues/351
- Implemented few changes to support u64 type
Used with the CLI command to create, index, and search data
=> Support for u64

docs/reference/search-api.md
Closes https://github.com/quickwit-inc/quickwit/issues/366
Added documentation for export endpoint
=> Export documentation

quickwit-core/src/indexing/document_indexer.rs, quickwit-index-config/src/all_flatten_config.rs, quickwit-index-config/src/config.rs, quickwit-index-config/src/default_index_config/default_config.rs, quickwit-index-config/src/wikipedia_config.rs, quickwit-search/src/collector.rs, quickwit-search/src/leaf.rs, quickwit-search/src/lib.rs, quickwit-search/src/root.rs, quickwit-search/src/search_stream/collector.rs, quickwit-search/src/search_stream/leaf.rs, quickwit-search/src/service.rs
Closes https://github.com/quickwit-inc/quickwit/issues/365
- Few changes to make sure the query is built at the split level
- Changed to make sure Field are accessed on the correct split schema
Create, Index, Search index
=> Build query at split level

quickwit-cli/src/lib.rs, quickwit-cli/tests/cli.rs, quickwit-core/src/indexing/document_indexer.rs, quickwit-core/src/indexing/split.rs, quickwit-core/src/test_utils.rs, quickwit-index/src/lib.rs, quickwit-metastore/Cargo.toml, quickwit-metastore/src/metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-search/src/leaf.rs, quickwit-search/src/lib.rs, quickwit-search/src/root.rs, quickwit-search/src/search_stream/leaf.rs, quickwit-search/src/search_stream/root.rs
Closes https://github.com/quickwit-inc/quickwit/issues/383
Changed `Box<dyn IndexConfig>` to `Arc<dyn IndexConfig>`
=> Using Arc<dyn IndxeConfig> instead of Box

quickwit-actors/src/actor.rs, quickwit-actors/src/actor_handle.rs, quickwit-actors/src/async_actor.rs, quickwit-actors/src/scheduler.rs, quickwit-actors/src/sync_actor.rs, quickwit-actors/src/tests.rs, quickwit-actors/src/universe.rs, quickwit-index/src/actors/indexer.rs, quickwit-index/src/actors/packager.rs, quickwit-index/src/actors/publisher.rs, quickwit-index/src/actors/source/file_source.rs, quickwit-index/src/actors/source/vec_source.rs, quickwit-index/src/actors/uploader.rs
=> Message as ActorContext argument.

quickwit-index/Cargo.toml, quickwit-index/src/actors/packager.rs, quickwit-index/src/actors/publisher.rs, quickwit-index/src/actors/uploader.rs, quickwit-index/src/models/manifest.rs, quickwit-index/src/models/packaged_split.rs, quickwit-index/src/models/uploaded_split.rs, quickwit-metastore/src/metastore.rs, quickwit-metastore/src/tests.rs, quickwit-search/src/root.rs, quickwit-search/src/search_stream/root.rs, quickwit-storage/src/bundle_storage.rs, quickwit-storage/src/lib.rs
- add bundle storage
- use bundle storage in actor
=> add bundle storage

quickwit-cli/tests/cli.rs, quickwit-core/src/index.rs, quickwit-core/src/indexing/index.rs, quickwit-core/src/indexing/split.rs, quickwit-index/src/actors/publisher.rs, quickwit-index/src/actors/uploader.rs, quickwit-index/src/lib.rs, quickwit-index/src/models/uploaded_split.rs, quickwit-metastore/src/lib.rs, quickwit-metastore/src/metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-metastore/src/tests.rs, quickwit-search/src/lib.rs, quickwit-search/src/root.rs, quickwit-search/src/search_stream/root.rs, quickwit-storage/src/bundle_storage.rs
- store BundleAndSplitMetadata in metastore
- rename
- fmt
=> store BundleAndSplitMetadata in metastore

Cargo.lock, quickwit-index/Cargo.toml, quickwit-index/src/lib.rs, quickwit-index/src/source/mod.rs, quickwit-index/src/source/source_factory.rs
Added a SourceConfig object, and loading method in the SourceLoader.
Closes #426
=> Plugged checkpoint in the current indexing pipeline.

quickwit-storage/src/bundle_storage.rs, quickwit-storage/src/cache/storage_with_cache.rs, quickwit-storage/src/lib.rs, quickwit-storage/src/local_file_storage.rs, quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit-storage/src/prefix_storage.rs, quickwit-storage/src/ram_storage.rs, quickwit-storage/src/storage.rs
Also more accurate contract on the delete method.
=> Adding file_num_bytes to the Storage trait.

quickwit-proto/proto/search_api.proto, quickwit-proto/src/quickwit.rs, quickwit-search/src/client_pool.rs, quickwit-search/src/client_pool/search_client_pool.rs, quickwit-search/src/leaf.rs, quickwit-search/src/lib.rs, quickwit-search/src/root.rs, quickwit-search/src/search_stream/root.rs, quickwit-search/src/service.rs
=> pass bundle offsets in search

quickwit-metastore/src/checkpoint.rs
Fix bug in `CheckpointDelta::add`. When a delta was already recorded for a given partition, the current delta was overridden instead of being updated.
Added unit test.
=> Fix bug in `CheckpointDelta::add`

quickwit-actors/src/lib.rs
=> increase actor heartbeat timeout in dev builds

quickwit-actors/src/actor.rs, quickwit-actors/src/actor_handle.rs, quickwit-actors/src/async_actor.rs, quickwit-actors/src/lib.rs, quickwit-actors/src/observation.rs, quickwit-actors/src/progress.rs, quickwit-actors/src/scheduler.rs, quickwit-actors/src/sync_actor.rs, quickwit-actors/src/tests.rs, quickwit-actors/src/universe.rs, quickwit-index/src/actors/publisher.rs, quickwit-index/src/actors/uploader.rs, quickwit-index/src/lib.rs, quickwit-index/src/source/file_source.rs, quickwit-index/src/source/vec_source.rs
Removed the supervising code in the actor handle.
Renames spawn_async_actor.
=> Adding the capacity for an actor to spawn another actor.

.github/workflows/ci.yml
Open #472 to reenable it later.
=> Disabling failpoint on CI

quickwit-actors/src/scheduler.rs
=> Fixes a race condition in the scheduler.

examples/index_configs/hdfslogs_index_config.json, examples/index_configs/wikipedia_index_config.json
=> Add tags field to config examples.

quickwit-cli/src/cli.yaml, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-cli/tests/cli.rs, quickwit-cli/tests/helpers.rs, quickwit-serve/src/args.rs
=> Use the couple (metastore-uri, index-id) as CLI main arguments.

quickwit-index-config/src/config.rs, quickwit-proto/proto/search_api.proto, quickwit-proto/src/quickwit.rs, quickwit-search/src/leaf.rs, quickwit-search/src/root.rs, quickwit-search/src/search_stream/root.rs, quickwit-search/src/service.rs
- pass index config to leaf nodes
- pass index_uri to leaf, remove metastore call
- remove metastore call in fetch_docs
- remove metastore call in stream request
=> remove metastore calls in leaves

quickwit-cli/src/lib.rs, quickwit-cli/tests/cli.rs, quickwit-core/src/index.rs, quickwit-core/src/test_utils.rs, quickwit-indexing/failpoints/mod.rs, quickwit-indexing/src/actors/pipeline_supervisor.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-search/src/lib.rs, quickwit-serve/src/lib.rs, quickwit-storage/src/lib.rs, quickwit-storage/src/object_storage/mod.rs, quickwit-storage/src/object_storage/s3_compatible_storage_uri_resolver.rs, quickwit-storage/src/storage_resolver.rs, quickwit-storage/tests/s3_storage.rs
=> Add a StorageUriResolver singleton and a specific resolver for tests.

quickwit-actors/src/tests.rs
=> Fixing race condition in `test_default_message_async`.

quickwit-actors/src/actor.rs, quickwit-actors/src/actor_handle.rs, quickwit-actors/src/async_actor.rs, quickwit-actors/src/lib.rs, quickwit-actors/src/scheduler.rs, quickwit-actors/src/spawn_builder.rs, quickwit-actors/src/sync_actor.rs, quickwit-actors/src/tests.rs, quickwit-actors/src/universe.rs, quickwit-cli/src/lib.rs, quickwit-indexing/src/actors/indexer.rs, quickwit-indexing/src/actors/packager.rs, quickwit-indexing/src/actors/pipeline_supervisor.rs, quickwit-indexing/src/actors/publisher.rs, quickwit-indexing/src/actors/uploader.rs, quickwit-indexing/src/lib.rs, quickwit-indexing/src/source/file_source.rs, quickwit-indexing/src/source/vec_source.rs
A change in the API was required to be able to
create non DAG network of actors.
The spawn builder makes it possible to inject
a specific mailbox.
=> Added a SpawnBuilder to build actors.

Cargo.lock, docker-compose.yml, quickwit-actors/src/actor.rs, quickwit-actors/src/async_actor.rs, quickwit-common/src/lib.rs, quickwit-indexing/Cargo.toml, quickwit-indexing/src/actors/indexer.rs, quickwit-indexing/src/source/file_source.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/mod.rs, quickwit-indexing/src/source/vec_source.rs, quickwit-metastore/Cargo.toml, quickwit-metastore/src/checkpoint.rs, quickwit-metastore/src/error.rs
Implement a Kafka source, #398.
Implement a Kafka source using `rust-rdkafka`.
Unit tests and integrations tests.
=> Implement Kafka source

.github/workflows/coverage.yml
Add Kafka broker and ZooKeeper services to coverage workflow. This should fix the coverage workflow.
=> Add Kafka broker and ZooKeeper services to coverage workflow

.github/workflows/ci.yml, .licenserc.yaml, Makefile
- fix config
- fix image repo (current image is never updated)
- remove license check from CI since now part of lint step (cargo fmt)
Ran locally.
=> Fix license eye

quickwit-directories/src/lib.rs, quickwit-directories/src/union_directory.rs
Added an union directory.
It makes it possible to stack different directory implementation as different layers.
It is required for merging splits.
=> Added UnionDirectory in preparation for merges.

quickwit-index-config/src/config.rs, quickwit-indexing/src/actors/pipeline_supervisor.rs
=> Tags is a mandatory field in the schema. Panic if it's not there.

Cargo.lock, quickwit-indexing/Cargo.toml, quickwit-indexing/src/actors/merge_executor.rs, quickwit-indexing/src/actors/merge_planner.rs, quickwit-indexing/src/actors/merge_split_downloader.rs, quickwit-indexing/src/actors/mod.rs, quickwit-indexing/src/actors/packager.rs, quickwit-indexing/src/actors/pipeline_supervisor.rs, quickwit-indexing/src/actors/publisher.rs, quickwit-indexing/src/merge_policy.rs, quickwit-indexing/src/models/commit_policy.rs, quickwit-indexing/src/models/merge_planner_message.rs, quickwit-indexing/src/models/merge_scratch.rs, quickwit-indexing/src/test_utils.rs
See detail on #399.
Closes #399
=> Adds a working merge pipeline.

quickwit-metastore/src/metastore/single_file_metastore.rs
Serialize pretty JSON metastore file.
=> Serialize pretty JSON metastore file

quickwit-cli/src/lib.rs, quickwit-metastore/src/metastore/single_file_metastore.rs
Got some errors while playing with the CLI and the error messages were not helpful. I was able to found the issues only after displaying the path of the metastore files.
=> Improve error messages

quickwit-directories/src/bundle_directory.rs
=> add exists test in bundle

quickwit-metastore/src/metastore/single_file_metastore.rs
Closes https://github.com/quickwit-inc/quickwit/issues/524 
Ran the cli commands while tampering `index_id` in `quickwit.json` file.
=> Handle index_id mismatch

quickwit-cli/src/cli.yaml, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-indexing/src/actors/pipeline_supervisor.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/mod.rs, quickwit-indexing/src/source/source_factory.rs, quickwit-indexing/src/test_utils.rs
Read `SourceConfig` from file. 
- added a unit test
- indexed data with Kafka source loading the Kafka source conf from local file
=> Read `SourceConfig` from file

Cargo.lock, quickwit-cli/src/lib.rs, quickwit-core/src/index.rs, quickwit-core/src/lib.rs, quickwit-indexing/Cargo.toml, quickwit-indexing/src/actors/garbage_collector.rs, quickwit-indexing/src/actors/mod.rs, quickwit-indexing/src/actors/pipeline_supervisor.rs, quickwit-indexing/src/garbage_collection.rs, quickwit-indexing/src/lib.rs
Closes https://github.com/quickwit-inc/quickwit/issues/457
- Run indexing, gc, and new command with `-overwrite`
=> Garbage collect actor

quickwit-indexing/src/source/kafka_source.rs
The actor/source API changed slightly after #563 was merged. Hard to spot the issue with our current setup since the Kafka source is a feature.
Unit test
=> Fix Kafka source after API change

quickwit-indexing/src/source/kafka_source.rs
I noticed that the `fetch_metadata` and `fetch_watermarks` methods on the Kafka client are actually blocking... This PR moves those calls in blocking tasks.
Unit tests
=> Spawn blocking Kafka client calls in blocking tasks

.github/workflows/coverage.yml, docker-compose.yml, quickwit-metastore/src/metastore/postgresql_metastore.rs
Fix and optimize code coverage CI workflow:
- add Postgres service
- add services health checks for faster startup
- avoid compiling cargo-llvm-cov and install from binary
- add artifacts caching
https://github.com/quickwit-inc/quickwit/runs/3704095533
=> Fix and optimize code coverage CI workflow

.github/workflows/coverage.yml, .github/workflows/publish_main_docker_image.yaml
=> Skip code coverage and Docker publish CI workflows for non-Rust changes

quickwit-index-config/src/default_index_config/default_config.rs, quickwit-indexing/src/models/indexed_split.rs
- Allowing missing tag_fields in conf
- Allowing missing timestamp_field in conf
- Removing println of sort field in IndexedSplit.
=> Fixing minor papercuts.

quickwit-actors/src/actor_handle.rs, quickwit-indexing/src/actors/uploader.rs
- Acquisition of the semaphore in the upload in the protect zone to
avoid timeout
- Better logging.
=> Added more logging + 1 bugfix in the indexing pipeline

quickwit-actors/src/spawn_builder.rs
=> logging spawn

quickwit-indexing/src/source/kafka_source.rs
=> Limit Kafka source batch size to 5mb

quickwit-indexing/src/actors/garbage_collector.rs
=> Increased the GC grace period as a temporary fix.

quickwit-indexing/src/actors/indexer.rs, quickwit-indexing/src/source/kafka_source.rs
=> Protect indexer

quickwit-cli/tests/cli.rs, quickwit-core/src/index.rs, quickwit-indexing/src/actors/garbage_collector.rs, quickwit-indexing/src/garbage_collection.rs, quickwit-metastore/src/metastore/mod.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-metastore/src/tests.rs
As titled. Fixes #607.
```sh
make docker-compose-up
QUICKWIT_ENV=local cargo test --all-features
```
=> Rename `mark_as_deleted` to `mark_for_deletion`

quickwit-metastore/src/metastore/postgresql_metastore.rs
Implement `get_conn()` method and remove duplicated code. Performing this small refactor as I'm taking a look at a bug with the Postgres metastore.
```sh
cargo build --all-features
```
=> Implement `get_conn()` method and remove duplicated code

quickwit-indexing/src/actors/garbage_collector.rs, quickwit-indexing/src/actors/merge_executor.rs, quickwit-indexing/src/actors/merge_planner.rs, quickwit-indexing/src/actors/merge_split_downloader.rs, quickwit-indexing/src/actors/publisher.rs, quickwit-indexing/src/actors/uploader.rs, quickwit-indexing/src/merge_policy.rs, quickwit-storage/src/storage_with_upload_cache.rs
=> Tweak and log

quickwit-cli/src/cli.yaml, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-directories/src/bundle_directory.rs, quickwit-storage/src/bundle_storage.rs
add extract-split method to cli. closes #625
locally
=> add extract-split closes #625

quickwit-storage/src/bundle_storage.rs
=> factor chunk ranges into method

quickwit-indexing/src/garbage_collection.rs
Log deletion errors in GC
Ran test suite locally.
=> Log deletion errors in GC

quickwit-core/src/index.rs, quickwit-indexing/src/actors/garbage_collector.rs, quickwit-indexing/src/garbage_collection.rs
Delay deletion of splits by 2 minutes.
fixes #605
=> Delay deletion of splits marked for deletion

Cargo.lock, docker-compose.yml, quickwit-indexing/Cargo.toml, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/kinesis/api.rs, quickwit-indexing/src/source/kinesis/mod.rs, quickwit-indexing/src/source/mod.rs
Implement basic API for interacting with Kinesis data streams. My Kinesis source branch was getting quite large so I decided to split my work into multiple PRs. Here is the first one.
Added tests and ran `make test-all`.
=> Implement basic API for interacting with Kinesis data streams

.github/workflows/coverage.yml
As entitled.
https://github.com/quickwit-inc/quickwit/runs/4073330576?check_suite_focus=true#logs
=> Use `kinesalite` as Kinesis provider for LocalStack

Cargo.lock, quickwit-actors/src/actor.rs, quickwit-actors/src/lib.rs, quickwit-indexing/Cargo.toml, quickwit-indexing/failpoints/mod.rs, quickwit-indexing/src/actors/indexer.rs, quickwit-indexing/src/actors/merge_executor.rs, quickwit-indexing/src/actors/packager.rs, quickwit-indexing/src/controlled_directory.rs, quickwit-indexing/src/lib.rs, quickwit-indexing/src/models/indexed_split.rs
The goal of the ContolledDirectory is
- to register a progress every time a write
is done.
- get a handle to abort a merge or a demux
operation if the killswitch has been activated.
Closes #704.
=> Introduces a ControlledDirectory.

quickwit-search/src/search_stream/root.rs
=> Stream leaf request are performed in parallel.

quickwit-search/src/search_stream/leaf.rs, quickwit-storage/src/cache/quickwit_cache.rs
=> Makes the number of concurrent split stream configurable.

quickwit-indexing/src/actors/pipeline_supervisor.rs, quickwit-indexing/src/actors/publisher.rs, quickwit-indexing/src/models/raw_doc_batch.rs, quickwit-indexing/src/source/kafka_source.rs
-  #730 will be handled in another PR
=> Small fixes: logging + pipeline stuff

Cargo.lock, quickwit-indexing/src/source/kinesis/api.rs, quickwit-indexing/src/source/kinesis/helpers.rs, quickwit-indexing/src/source/kinesis/mod.rs, quickwit-indexing/src/source/kinesis/shard_consumer.rs, quickwit-storage/Cargo.toml
Implement shard consumer, next building for implementing a Kinesis source.
Added some unit tests.
The Kinesis mock providers do not behave correctly on shard merge or split. Those tests are currently disabled.
=> Implement Kinesis shard consumer

Cargo.lock, Cargo.toml, quickwit-config/Cargo.toml, quickwit-config/resources/tests/index_object/hdfs-logs.json, quickwit-config/resources/tests/index_object/hdfs-logs.toml, quickwit-config/resources/tests/index_object/hdfs-logs.yaml, quickwit-config/src/index_config.rs, quickwit-config/src/lib.rs, quickwit-index-config/Cargo.toml, quickwit-index-config/src/default_index_config/field_mapping_entry.rs, quickwit-index-config/src/lib.rs
Pushing a rough implementation to have a basis for discussion.
=> Implement `IndexConfig`

Cargo.lock, quickwit-core/Cargo.toml, quickwit-directories/Cargo.toml, quickwit-index-config/Cargo.toml, quickwit-indexing/Cargo.toml, quickwit-indexing/src/actors/indexer.rs, quickwit-indexing/src/actors/packager.rs, quickwit-search/Cargo.toml, quickwit-storage/Cargo.toml
tantivy now detects error in segment index workers,
and returns a Result on `add_document`.
Close #730
=> Updating tantivy version

quickwit-indexing/src/actors/merge_executor.rs
Added protect guard for merge/demux.
The ControlledDirectory trick seems insufficient
to handle the prevent timeout on the merge/demux
operation.
This PR reintroduce protect_guard for the two operations.
=> Added protect guard for merge/demux.

Cargo.lock, quickwit-cli/Cargo.toml, quickwit-cli/src/lib.rs, quickwit-cli/tests/cli.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/mod.rs, quickwit-metastore/Cargo.toml, quickwit-metastore/src/lib.rs, quickwit-metastore/src/metastore/mod.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-serve/src/lib.rs, quickwit-storage/src/bundle_storage.rs, quickwit-storage/src/cache/storage_with_cache.rs, quickwit-storage/src/local_file_storage.rs, quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit-storage/src/prefix_storage.rs, quickwit-storage/src/ram_storage.rs, quickwit-storage/src/storage.rs
This adds various checks for config, storage and metastore. This fixes #701.
`cargo test --all-features`
=> add checks before indexing and serve

quickwit-indexing/src/actors/merge_executor.rs
=> Add bunch of record progress on demux

quickwit-directories/src/bundle_directory.rs
add comment to read_split_footer
=> add comment to read_split_footer

Cargo.lock, quickwit-search/Cargo.toml, quickwit-search/src/leaf.rs, quickwit-search/src/lib.rs, quickwit-search/src/search_stream/leaf.rs, quickwit-search/src/thread_pool.rs
Closes #785
Tested on our index 
curl "http://0.0.0.0:8080/api/v1/happy-plazza/search?uery=my+OR+the+OR+quickwit&maxHits=0"
```
{
"numHits": 651377284,
"hits": [],
"elapsedTimeMicros": 13615346
}
```
```
{
"numHits": 651377284,
"hits": [],
"elapsedTimeMicros": 2708861
}
```
I did not observe any improvement nor regression on stream.
=> Introduces a thread pool for our CPU intensive task

CODE_STYLE.md
First stab at a code style document.
It is not in marble.
The idea is for us to edit incrementally as we encounter
interesting point in code reviews.
=> Added CODE_STYLE.md

quickwit-indexing/src/source/mod.rs, quickwit-indexing/src/source/void_source.rs
Add empty source. Could be useful for testing mainly or if you want to launch a long-running job.
=> Add empty source

quickwit-actors/src/actor_handle.rs, quickwit-actors/src/async_actor.rs, quickwit-actors/src/sync_actor.rs, quickwit-actors/src/tests.rs
=> Finalize, override exit status on finalize error and then exit.

quickwit-indexing/src/merge_policy.rs, quickwit-indexing/src/split_store/indexing_split_store.rs
=> Maturity fixes

quickwit-indexing/failpoints/mod.rs
fix failpoints test
fixes #826
=> fix failpoints test

quickwit-index-config/src/config.rs, quickwit-index-config/src/lib.rs, quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/actors/mod.rs, quickwit-indexing/src/actors/packager.rs, quickwit-indexing/src/models/packaged_split.rs, quickwit-metastore/src/metastore/mod.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/metastore/single_file_metastore.rs, quickwit-metastore/src/tests.rs, quickwit-search/src/lib.rs, quickwit-search/src/root.rs, quickwit-search/src/search_stream/root.rs, quickwit-serve/src/lib.rs
Closes https://github.com/quickwit-inc/quickwit/issues/437
Related to https://github.com/quickwit-inc/quickwit/issues/823
unittest
=> Limit tag split values & escaping

Cargo.lock, quickwit-cli/src/index.rs, quickwit-cli/src/lib.rs, quickwit-cli/src/service.rs, quickwit-cli/tests/cli.rs, quickwit-common/Cargo.toml, quickwit-common/src/checklist.rs, quickwit-common/src/lib.rs, quickwit-indexing/src/lib.rs, quickwit-metastore/src/lib.rs, quickwit-serve/src/lib.rs
It avoids the interleaving of log lines.
The printing format is also improved.
Most notably we now display the error details.
Closes #808
=> Printing checklist report all at once.

quickwit-cli/src/index.rs, quickwit-cli/src/lib.rs, quickwit-cli/src/service.rs, quickwit-cli/tests/cli.rs
=> Add a function to run connectivity checks for an given index.

quickwit-cli/tests/helpers.rs, quickwit-index-config/src/config.rs, quickwit-index-config/src/default_index_config/default_config.rs, quickwit-index-config/src/lib.rs, quickwit-indexing/src/actors/packager.rs, quickwit-metastore/src/metastore/mod.rs
Closes https://github.com/quickwit-inc/quickwit/issues/850
- Removed special _tags fields
- Adde restrictions to tags field type
unit test
=> Removed special _tags field

Cargo.lock, quickwit-core/Cargo.toml, quickwit-directories/Cargo.toml, quickwit-directories/src/bundle_directory.rs, quickwit-directories/src/caching_directory.rs, quickwit-directories/src/debug_proxy_directory.rs, quickwit-directories/src/hot_directory.rs, quickwit-directories/src/lib.rs, quickwit-directories/src/storage_directory.rs, quickwit-directories/src/union_directory.rs, quickwit-index-config/Cargo.toml, quickwit-index-config/src/default_index_config/field_mapping_entry.rs, quickwit-indexing/Cargo.toml, quickwit-indexing/src/controlled_directory.rs, quickwit-search/Cargo.toml, quickwit-storage/Cargo.toml
Updates tantivy.
Adds a read_only_directory macro to keep the code dry
Closes #838.
=> Updates tantivy (#838)

quickwit-indexing/src/actors/indexing_pipeline.rs
fixes #463
add spawn command for supervisor with retry
=> add retry for failing spawn_pipeline

Cargo.lock, quickwit-cli/Cargo.toml, quickwit-cli/src/cli.rs, quickwit-cli/src/cli.yaml, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-cli/src/service.rs, quickwit-cli/src/source.rs
Implement source describe and list commands:
```sh
quickwit source describe --index-id <index ID> --source-id <source ID>
quickwit source list --index-id <index ID>
```
- Unit tests
- Ran commands
=> Implement source describe and list commands

quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/actors/mod.rs, quickwit-indexing/src/actors/packager.rs
Closes https://github.com/quickwit-inc/quickwit/issues/912
- fixed tag collection logic to properly handle u64, i64, and f64 types
unit tests
=> Fix tags collection for  numbers (u64, i64, and f64)

quickwit-cli/src/index.rs, quickwit-index-config/src/lib.rs, quickwit-index-config/src/query_builder.rs, quickwit-index-config/src/sort_by.rs, quickwit-proto/proto/search_api.proto, quickwit-proto/src/cluster.rs, quickwit-proto/src/lib.rs, quickwit-proto/src/quickwit.rs, quickwit-search/src/cluster_client.rs, quickwit-search/src/collector.rs, quickwit-search/src/lib.rs, quickwit-search/src/retry/search.rs, quickwit-search/src/retry/search_stream.rs, quickwit-search/src/root.rs, quickwit-serve/Cargo.toml, quickwit-serve/src/rest.rs
=> Add query param for sorting search results

quickwit-cli/Cargo.toml
=> fix clap to exact version

quickwit-backward-compat/build.rs, quickwit-backward-compat/test-data/index-metadata/v0-4a463f5078aa6acf314c95936336fa68.expected.json, quickwit-backward-compat/test-data/index-metadata/v0-4a463f5078aa6acf314c95936336fa68.json, quickwit-cli/src/index.rs, quickwit-metastore/migrations/postgresql/2021-12-17-102648_add_timestamp_fields_to_indexes/down.sql, quickwit-metastore/migrations/postgresql/2021-12-17-102648_add_timestamp_fields_to_indexes/up.sql, quickwit-metastore/src/metastore/mod.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/metastore/single_file_metastore/metadata_set.rs, quickwit-metastore/src/postgresql/model.rs, quickwit-metastore/src/postgresql/schema.rs, quickwit-metastore/src/tests.rs
Closes https://github.com/quickwit-inc/quickwit/issues/797
Unit tests
=> Added update_timestamp field to Index

quickwit-proto/src/cluster.rs, quickwit-proto/src/quickwit.rs
=> Fix proto generated code format.

quickwit-cli/src/index.rs, quickwit-proto/src/cluster.rs, quickwit-proto/src/quickwit.rs, quickwit-search/src/lib.rs
=> Return errors in search response in single_node_search.

quickwit-cli/tests/helpers.rs, quickwit-indexing/failpoints/mod.rs, quickwit-indexing/src/test_utils.rs, quickwit-metastore/README.md, quickwit-metastore/src/lib.rs, quickwit-metastore/src/metastore/file_backed_metastore/file_backed_metastore_factory.rs, quickwit-metastore/src/metastore/file_backed_metastore/index.rs, quickwit-metastore/src/metastore/file_backed_metastore/mod.rs, quickwit-metastore/src/metastore/file_backed_metastore/store_operations.rs, quickwit-metastore/src/metastore/mod.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/metastore_resolver.rs
=> Renaming SingleFileMetastore and MetadataSet

CONTRIBUTING.md, Cargo.lock, quickwit-actors/Cargo.toml, quickwit-actors/src/async_actor.rs, quickwit-actors/src/sync_actor.rs, quickwit-cli/Cargo.toml, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs
add optional tokio-console feature
=> add optional tokio-console feature

docs/reference/index-config.md, docs/tutorials/tutorial-hdfs-logs-distributed-search-aws-s3.md, docs/tutorials/tutorial-hdfs-logs.md
=> remove index sorting from docs

CONTRIBUTING.md
=> update docs for tokio

quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/actors/merge_planner.rs, quickwit-indexing/src/actors/publisher.rs, quickwit-indexing/src/actors/uploader.rs
=> Reenable backpressure in the indexing pipeline

quickwit-indexing/src/source/kafka_source.rs
=> Fixing the build

quickwit-config/src/config.rs, quickwit-config/src/index_config.rs
=> update config comments

CONTRIBUTING.md, Makefile, docs/reference/cli.md, docs/reference/telemetry.md, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-common/src/lib.rs, quickwit-storage/src/object_storage/s3_compatible_storage_uri_resolver.rs, quickwit-telemetry/src/lib.rs
=> rename ENV variables from QUICKWIT_ to QW_

Cargo.lock, quickwit-actors/src/universe.rs, quickwit-cli/src/cli.yaml, quickwit-cli/src/index.rs, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-cli/src/service.rs, quickwit-cli/tests/cli.rs, quickwit-common/src/uri.rs, quickwit-config/Cargo.toml, quickwit-config/src/config.rs, quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/actors/indexing_server.rs, quickwit-indexing/src/actors/mod.rs, quickwit-indexing/src/lib.rs, quickwit-indexing/src/source/file_source.rs, quickwit-indexing/src/source/mod.rs, quickwit-indexing/src/source/vec_source.rs, quickwit-indexing/src/test_utils.rs, quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs, quickwit-metastore/src/metastore/index_metadata.rs, quickwit-storage/src/storage_resolver.rs
First stab at an indexing server that spawns and observes multiple indexing pipelines.
In progress
=> Implement lightweight indexing server

quickwit-cli/src/cli.yaml, quickwit-cli/src/source.rs
Implement delete source CLI command.
- ran `make test-all` command
=> Implement delete source CLI command

.github/workflows/publish_release_docker_image.yaml
=> Fix typo in workflow yaml file

quickwit-cli/src/cli.yaml, quickwit-cli/src/source.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/mod.rs
Implement add source CLI command
- ran `make test-all` command
=> Implement add source CLI command

quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/actors/indexing_server.rs, quickwit-indexing/src/models/indexing_statistics.rs
Fix #992 
I fixed also the pipeline retry that was not working as expected.
=> Fix merge pipeline spawning & pipeline retry.

Cargo.lock, quickwit-cli/Cargo.toml, quickwit-cli/src/lib.rs
It was necessary for me to compile quickwit-cli for some reason.
=> Updating the tabled version.

docs/reference/search-api.md
=> update API docs

docs/tutorials/add-full-text-search-to-your-olap-db.md
=> type -> event_type in the clickhouse tutorial

config/quickwit.yaml, quickwit-config/resources/tests/config/quickwit.json, quickwit-config/resources/tests/config/quickwit.toml, quickwit-config/resources/tests/config/quickwit.yaml, quickwit-config/src/config.rs, quickwit-search/src/search_stream/leaf.rs
Closes https://github.com/quickwit-inc/quickwit/issues/1003
unittest
=> Move concurrent_split_stream_env to SearcherConfig

.github/workflows/coverage.yml, quickwit-cli/tests/helpers.rs, quickwit-config/src/index_config.rs, quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit-doc-mapper/src/doc_mapper.rs, quickwit-indexing/failpoints/mod.rs, quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-search/src/service.rs
Ok, now the PR title is too long... I ended doing all this in one PR everything was mixed up. I added some comments to guide you.
Fix:
=> Rename old index_config to doc_mapper, fix failpoints tests and fetch index chekckpoint when spawning pipeline, add failpoint test to coverage

Dockerfile, config/quickwit.yaml, config/tutorials/hdfs-logs/searcher-1.yaml, config/tutorials/hdfs-logs/searcher-2.yaml, config/tutorials/hdfs-logs/searcher-3.yaml, docker/Dockerfile, docs/tutorials/tutorial-hdfs-logs-distributed-search-aws-s3.md, quickwit-cli/tests/cli.rs, quickwit-cli/tests/helpers.rs, quickwit-config/resources/tests/config/quickwit.json, quickwit-config/resources/tests/config/quickwit.toml, quickwit-config/resources/tests/config/quickwit.yaml, quickwit-config/src/config.rs, quickwit-serve/src/lib.rs
=> Refactor config to put host and port at the root of quickwit config.

config/quickwit.yaml, docs/guides/configure-aws-env.md
=> Update aws env guide and put link in quickwit config file.

quickwit-metastore/src/metastore_resolver.rs
PostgresMetastore.
Both seem to be supported by other tools like psql.
Closes #1015.
=> Support both postgres and postgresql as protocol in the

docs/reference/quickwit-config.md
=> Add quickwit config doc page.

docs/design/querying.md
Updated querying docs page from Notion
=> Updated querying docs

docs/reference/index-config.md
We recently integrated index-id and index-uri in
the index-reference.
In addition this PR makes more minor change like
adding a source in the example configuration.
=> Making the index reference doc up to date.

docs/reference/cli.md, docs/reference/index-config.md, docs/reference/quickwit-config.md, docs/reference/rest-api.md
fix links
rename index name to index id
=> update rest api docs, fix links

docs/reference/index-config.md, docs/reference/metastore-config.md, docs/reference/storage-uri.md
- fix tables in index config
- fix notion links
- fix caution, tip block
- fix caution blocks
=> fix tables, fix links, fix blocks

docs/administration/cloud-env.md
=> fix cloud env chars

quickwit-search/src/root.rs
=> add test for startOffset out of bounds

quickwit-cluster/src/cluster.rs
=> increase timeout for flaky test

quickwit-indexing/src/actors/uploader.rs
=> Return error on semaphore AcquireError in uploader

quickwit-cli/build.rs
Fix CLI build script. It no longer fails outside of a git repo or without git installed. Fix #1104.
`cargo build && cargo r -- -V` within and outside git repo, and without git installed.
=> Fix CLI build script

.github/workflows/publish_cross_images.yml
Fix nightly builds & activate manual workflow trigger to easily update docker images
https://github.com/quickwit-oss/quickwit/issues/1115
=> Fix for nightly builds

docs/design/architecture.md, docs/reference/index-config.md
=> Backport docs corrections from quickwit.io

quickwit-search/src/collector.rs, quickwit-search/src/leaf.rs, quickwit-search/src/root.rs
This PR also makes some small optimizations
=> ISSUE-1118 Check collector logic at root and optimize

install.sh
Fix install script for shell interpreters that don't support array syntax.
https://github.com/quickwit-oss/quickwit/issues/1116
=> Fix install script

Cargo.lock, quickwit-search/src/leaf.rs
=> Warming up terms and fastfields in concurrently.

CHANGELOG.md, Cargo.lock, quickwit-actors/Cargo.toml, quickwit-cli/Cargo.toml, quickwit-cluster/Cargo.toml, quickwit-common/Cargo.toml, quickwit-config/Cargo.toml, quickwit-core/Cargo.toml, quickwit-directories/Cargo.toml, quickwit-doc-mapper/Cargo.toml, quickwit-indexing/Cargo.toml, quickwit-metastore/Cargo.toml, quickwit-proto/Cargo.toml, quickwit-search/Cargo.toml, quickwit-serve/Cargo.toml, quickwit-storage/Cargo.toml, quickwit-swim/Cargo.toml, quickwit-telemetry/Cargo.toml
Prepare v0.2.1 release
`cargo build`
=> Prepare v0.2.1 release

quickwit-cli/src/index.rs, quickwit-cli/src/main.rs, quickwit-cli/tests/cli.rs, quickwit-doc-mapper/src/query_builder.rs, quickwit-proto/build.rs, quickwit-proto/proto/search_api.proto, quickwit-proto/src/lib.rs, quickwit-proto/src/quickwit.rs, quickwit-search/src/cluster_client.rs, quickwit-search/src/collector.rs, quickwit-search/src/lib.rs, quickwit-search/src/retry/search.rs, quickwit-search/src/root.rs, quickwit-search/src/search_response_rest.rs, quickwit-serve/src/rest.rs
the webserver accepts now POST and GET requests
add support for aggregation
=> accept post requests, plug aggregation

.gitignore, Makefile, rust-toolchain.toml
.gitignore updates
removed Makefile commands
added rust-toolchain file.
=> Minor project configuration changes.

.github/workflows/ci.yml, quickwit-actors/src/mailbox.rs, quickwit-common/src/uri.rs, quickwit-directories/src/bundle_directory.rs, quickwit-indexing/src/actors/merge_executor.rs, quickwit-indexing/src/merge_policy.rs, quickwit-indexing/src/source/kinesis/api.rs, quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs, quickwit-metastore/src/metastore/file_backed_metastore/mod.rs, quickwit-metastore/src/metastore/file_backed_metastore/store_operations.rs, quickwit-metastore/src/metastore/mod.rs, quickwit-metastore/src/split_metadata.rs, quickwit-search/src/leaf.rs, quickwit-storage/src/prefix_storage.rs, quickwit-storage/src/retry.rs
Closes #1152
Correct some item links and fix some typo.
Some CI stuff will be added if I handled it. :D
`cargo doc --open` and check the result to see if it is right.
=> docs: fix a bunch of broken item links

docs/administration/cloud-env.md
At the moment, the doc has a little format issue. So fix it. :D
=> docs: fix a typo

docs/guides/tutorial-hdfs-logs-distributed-search-aws-s3.md, docs/guides/tutorial-hdfs-logs.md, docs/reference/cli.md, docs/reference/rest-api.md, quickwit-cli/src/cli_doc_ext.toml, quickwit-cli/tests/cli.rs
=> Bugfix in unit tests and updating the doc.

docs/reference/rest-api.md
Closes  #1198
Related to #1200
=> docs: update REST API document

Cargo.lock, quickwit-cluster/Cargo.toml, quickwit-cluster/src/cluster.rs, quickwit-cluster/src/error.rs, quickwit-cluster/src/service.rs, quickwit-config/src/config.rs, quickwit-proto/proto/cluster.proto, quickwit-proto/src/cluster.rs, quickwit-search/src/lib.rs, quickwit-search/src/search_client_pool.rs, quickwit-serve/Cargo.toml, quickwit-serve/src/cluster_api/grpc_adapter.rs, quickwit-serve/src/lib.rs
- implemented fixes for our service ports story 
- implemented cluster state gRPC method
- unit test
- tested with CLI
https://github.com/quickwit-oss/quickwit/issues/1191
=> Fix REST, gRPC, and UDP ports

quickwit-indexing/src/source/kafka_source.rs, quickwit-metastore/src/backward_compatibility_tests/index_metadata.rs, quickwit-metastore/src/checkpoint.rs, quickwit-metastore/test-data/file-backed-index/v0-f43be15d8611ab4d84b0eaec0607907c.expected.json, quickwit-metastore/test-data/file-backed-index/v0-f43be15d8611ab4d84b0eaec0607907c.json, quickwit-metastore/test-data/index-metadata/v1-e52f66301963300ef942997308b4f3ac.expected.json, quickwit-metastore/test-data/index-metadata/v1-e52f66301963300ef942997308b4f3ac.json
Only numeric position are 20 char long.
=> No i32 / u32 shortened format.

Cargo.lock, quickwit-cli/Cargo.toml, quickwit-cli/src/index.rs
Saw this issue when i was browsing discord, anyways was a quick fix so I made this pr :+1: 
Closes #1203
=> fix time format

Cargo.lock, Cargo.toml, deny.toml, quickwit-cli/Cargo.toml, quickwit-proto/Cargo.toml, quickwit-proto/build.rs, quickwit-proto/proto/push_api.proto, quickwit-proto/src/lib.rs, quickwit-proto/src/quickwit_push_api.rs, quickwit-pushapi/Cargo.toml, quickwit-pushapi/DESIGN.md, quickwit-pushapi/src/errors.rs, quickwit-pushapi/src/lib.rs, quickwit-pushapi/src/position.rs, quickwit-pushapi/src/push_api_service.rs, quickwit-pushapi/src/queue.rs, quickwit-serve/Cargo.toml, quickwit-serve/src/error.rs, quickwit-serve/src/format.rs, quickwit-serve/src/lib.rs, quickwit-serve/src/push_api/grpc_adapter.rs, quickwit-serve/src/push_api/mod.rs, quickwit-serve/src/push_api/rest_handler.rs, quickwit-serve/src/rest.rs, rustfmt.toml
First stab at the PushAPI.
This PR adds a push API actor that wraps a rocksdb database to host different queue.
Refer to `quickwit-pushapi/DESIGN.md` for more detailed information.
=> PushAPIService first stab

quickwit-config/src/lib.rs, quickwit-config/src/source_config.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/kinesis/api.rs, quickwit-indexing/src/source/kinesis/helpers.rs, quickwit-indexing/src/source/kinesis/kinesis_source.rs, quickwit-indexing/src/source/kinesis/mod.rs, quickwit-indexing/src/source/kinesis/shard_consumer.rs, quickwit-indexing/src/source/mod.rs
Implement Kinesis source.
In progress.
=> Implement Kinesis source

quickwit-cli/src/split.rs
Add `quickwit split mark` command
Add unit test
=> Add `quickwit split mark-for-deletion` command

quickwit-indexing/src/lib.rs
=> Removing dead code

quickwit-metastore/src/metastore/file_backed_metastore/file_backed_metastore_factory.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/metastore_resolver.rs
=> single postgre instance

quickwit-doc-mapper/src/query_builder.rs
=> reenable test

quickwit-indexing/src/source/kafka_source.rs
- Fixed `SourceConfig` import in test
- Renamed `KafkaSourceContext` to `RdKafkaContext` to avoid confusion with newly introduced `SourceContext`
`make test-all` bro!
=> Fix Kafka source tests

quickwit-cli/src/cli_doc_ext.toml, quickwit-cli/src/index.rs, quickwit-indexing/src/actors/indexing_service.rs, quickwit-indexing/src/actors/mod.rs, quickwit-indexing/src/lib.rs, quickwit-indexing/src/models/indexing_service_message.rs, quickwit-indexing/src/models/mod.rs, quickwit-indexing/src/test_utils.rs, quickwit-serve/src/error.rs, quickwit-serve/src/indexing_api/rest_handler.rs, quickwit-serve/src/lib.rs
=> rename IndexingServer to IndexingService

quickwit-serve/src/search_api/rest_handler.rs
for elastic search compatibility
=> rename aggregations to aggs

docs/reference/aggregation.md, docs/reference/index-config.md, docs/reference/rest-api.md
closes #1350
closes #1198
Add new document for aggregations, reference document in rest-api.md
=> document aggregation

docs/reference/index-config.md, quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
=> validate tokenizer, fix docs

quickwit-actors/src/runner.rs, quickwit-indexing/src/actors/merge_split_downloader.rs
Actor failures are logged as an ERROR.
Merge download error are logged on site.
Closes #1396
=> Improved logging.

quickwit-indexing/src/actors/publisher.rs
=> Avoiding logging an error upon source truncation.

quickwit-storage/src/object_storage/s3_compatible_storage.rs
As explained in the documentation, we should
default to US EAST 1 if no region is specified and
the AWS instance metadata is not available.
Closes #1367
=> Defaulting AWS_REGION to US_EAST_1.

Makefile
Add `build-docs` command to Makefile
`make build-docs`
=> Add `build-docs` command to Makefile

quickwit-search/src/collector.rs, quickwit-search/src/lib.rs
Included query sort field in the list of fast_fields to prefetch
Closes https://github.com/quickwit-oss/quickwit/issues/1424
=> Fix query sortBy on other fast fields

quickwit-serve/src/ingest_api/rest_handler.rs
Added a limit on push API body allowed size.
Closes https://github.com/quickwit-oss/quickwit/issues/1446
=> PushAPI body Limit

Makefile, build/cross-images/aarch64-unknown-linux-musl.dockerfile
Removed `build-ui` from dependent step of `cross-images`
=> Minor fix on Makefile:cross-images

quickwit-config/src/index_config.rs
=> Empty field mappings

config/quickwit.yaml, quickwit-config/src/config.rs
=> Default metastore is polling the filesystem.

quickwit-serve/src/ingest_api/mod.rs, quickwit-serve/src/ingest_api/rest_handler.rs, quickwit-serve/src/rest.rs
Closes https://github.com/quickwit-oss/quickwit/issues/1452
=> Remove bulk endpoint

docs/configuration/index-config.md
=> Fix typos in index-config.md.

.github/workflows/publish_nightly_packages.yml, .github/workflows/publish_release_packages.yml
Disable Docker image until we resolve `musl` build with rocksdb
=> Disable docker image build

quickwit-search/src/fetch_docs.rs, quickwit-search/src/lib.rs
Limits the concurrency of fetching docs to 10
Addresses #1449
=> limit concurrency of fetching docs

Cargo.lock, quickwit-cli/src/index.rs, quickwit-cli/tests/cli.rs, quickwit-config/Cargo.toml, quickwit-config/src/config.rs, quickwit-config/src/index_config.rs, quickwit-config/src/lib.rs, quickwit-config/src/source_config.rs, quickwit-core/src/index.rs, quickwit-indexing/src/source/mod.rs, quickwit-serve/src/error.rs
Validate index ID, source ID, ... Fixes #1007.
- ran `make test-all`
=> Validate object identifiers 

Cargo.lock, quickwit-cli/Cargo.toml, quickwit-cli/src/lib.rs
=> Bump tabled from 0.6 to 0.7

quickwit-ui/src/components/JsonEditor.tsx, quickwit-ui/src/components/QueryEditor/QueryEditor.tsx, quickwit-ui/src/providers/LocalStorageProvider.tsx
=> Fix quickwit-ui build

docs/configuration/index-config.md, docs/develop/split-format.md, quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs, quickwit-doc-mapper/src/default_doc_mapper/field_mapping_type.rs, quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs, quickwit-doc-mapper/src/lib.rs, quickwit-indexing/src/actors/indexer.rs, quickwit-metastore/src/metastore/index_metadata.rs
Removed date field from doc_mapper
Closes https://github.com/quickwit-oss/quickwit/issues/1474
=> Removed date field support

.github/actions/build/action.yml, .github/actions/build/build.yml, .github/workflows/publish_nightly_packages.yml, Makefile
I did the refactoring on the current nightly build only.
The next steps would be:
- handle `--features` args for musl build
- add a parameter to use cross or not.
=> Refactor build workflows and build quickwit-ui in it. 

quickwit-serve/src/rest.rs
@fmassot maybe a redirect will be a decent quick and dirty solution?
Closes #1383
=> Redirects / to your ui/search.

docs/reference/rest-api.md
Closes https://github.com/quickwit-oss/quickwit/issues/1440
=> Docs for ingest API 

docs/configuration/source-config.md, quickwit-config/src/lib.rs
Update source docs since the command for adding a new source has changed.
Inspected rendered markdown.
=> Update source docs

docs/configuration/source-config.md
Document Kinesis source.
Inspected rendered markdown.
=> Document Kinesis source

docs/configuration/index-config.md
=> fix example

docs/tutorials/tutorial-hdfs-logs.md
=> Remove distributed search from hdfs-local

docs/tutorials/add-full-text-search-to-your-olap-db.md
=> Convert query params to snake_case.

quickwit-search/src/root.rs
orthogonal to https://github.com/quickwit-oss/quickwit/pull/1539
unit test
10_000 is already quite expensive, 350MB for a single request, hdfs dataset
=> set max value for max_hits to 10_000

docs/get-started/installation.md, docs/get-started/quickstart.md
- Document dependencies for Arch Linux :)
- Fix some typos
N/A
=> Document dependencies for Arch Linux :)

quickwit-doc-mapper/src/query_builder.rs
Checks if default search is not specified and query has no search field declared for dynamic mapping.
Closes https://github.com/quickwit-oss/quickwit/issues/1526
=> Fix default search field on dynamic mapping

quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/actors/indexing_service.rs, quickwit-indexing/src/actors/ingest_api_garbage_collector.rs, quickwit-indexing/src/actors/mod.rs, quickwit-indexing/src/lib.rs, quickwit-indexing/src/models/indexing_service_message.rs, quickwit-indexing/src/models/mod.rs, quickwit-ingest-api/src/ingest_api_service.rs, quickwit-ingest-api/src/queue.rs, quickwit-proto/proto/ingest_api.proto, quickwit-proto/src/quickwit_ingest_api.rs, quickwit-serve/src/rest.rs
Implements the ingest API queue garbage collector
- unittest
Closes https://github.com/quickwit-oss/quickwit/issues/1229
=> Garbage Collect IngestAPI queues

docs/tutorials/kafka.md
tutorial.
(Quickwit requires the topic to be created)
=> Reorder the kafka topic creation and the source creation in the kafka

README.md, ROADMAP.md
Publish roadmap in README. Fixes #1361.
Inspected rendered markdown visually
=> Publish roadmap

quickwit-aws/src/error.rs, quickwit-aws/src/retry.rs, quickwit-common/src/uri.rs, quickwit-directories/src/bundle_directory.rs, quickwit-directories/src/caching_directory.rs, quickwit-directories/src/debug_proxy_directory.rs, quickwit-directories/src/hot_directory.rs, quickwit-directories/src/storage_directory.rs, quickwit-doc-mapper/src/tag_pruning.rs, quickwit-indexing/failpoints/mod.rs, quickwit-indexing/src/merge_policy.rs, quickwit-indexing/src/models/indexed_split.rs, quickwit-indexing/src/models/packaged_split.rs, quickwit-indexing/src/models/raw_doc_batch.rs, quickwit-indexing/src/models/scratch_directory.rs, quickwit-indexing/src/source/file_source.rs, quickwit-indexing/src/source/ingest_api_source.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/kinesis/api.rs, quickwit-indexing/src/source/kinesis/kinesis_source.rs, quickwit-indexing/src/source/kinesis/shard_consumer.rs, quickwit-indexing/src/source/vec_source.rs, quickwit-metastore/src/checkpoint.rs, quickwit-search/src/search_stream/leaf.rs, quickwit-storage/src/bundle_storage.rs, quickwit-storage/src/local_file_storage.rs, quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit-storage/src/ram_storage.rs
Clippy comments on feature guarded code.
Flaky test fix
=> Minor fixes

quickwit-actors/src/actor.rs, quickwit-indexing/src/source/kinesis/kinesis_source.rs, quickwit-indexing/src/source/kinesis/shard_consumer.rs
Guard Kinesis API calls against actor timeout.
```
cargo build --features kinesis
```
=> Guard Kinesis API calls against actor timeout

docs/introduction.md
Backport CTA in docs intro. Update wording. Fixes #1403.
N/A
=> Backport CTA in docs intro

Cargo.lock, quickwit-core/Cargo.toml, quickwit-directories/Cargo.toml, quickwit-doc-mapper/Cargo.toml, quickwit-indexing/Cargo.toml, quickwit-search/Cargo.toml, quickwit-storage/Cargo.toml
compression_level is only available on the main branch
=> use tantivy main

CONTRIBUTING.md, docs/configuration/index-config.md, docs/guides/aws-setup.md, docs/tutorials/kinesis.md, quickwit-ui/README.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
=> docs(various): Improve readability

docker-compose.yml, quickwit-metastore/migrations/postgresql/1_create-indexes.up.sql, quickwit-metastore/migrations/postgresql/2_create-splits.up.sql
=> Removed `CREATE TRIGGER IF EXISTS` as it is too recent.

quickwit-config/resources/tests/config/quickwit.wrongkey.yaml, quickwit-config/src/config.rs
=> Reject config with unknown fields.

.github/workflows/ci.yml, Makefile, quickwit-common/src/uri.rs, quickwit-config/src/config.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, scripts/check_license_headers.sh
Fix metastore URI credentials leak. Fix #1672.
=> Fix metastore URI credentials leak

docs/tutorials/tutorial-hdfs-logs.md
See: [https://github.com/quickwit-oss/quickwit/issues/1703](https://github.com/quickwit-oss/quickwit/issues/1703)
=> Closes #1703

Cargo.lock, quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs, quickwit-metastore/src/metastore/file_backed_metastore/mod.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/tests.rs
Ensure replaced splits are in published state. Fix #1764. 
=> Ensure replaced splits are in published state

quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/source/file_source.rs, quickwit-indexing/src/source/ingest_api_source.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/kinesis/kinesis_source.rs, quickwit-indexing/src/source/mod.rs, quickwit-indexing/src/source/source_factory.rs, quickwit-indexing/src/source/vec_source.rs, quickwit-indexing/src/source/void_source.rs
Per title.
```sh
make fmt
cargo build --all-features
make test-all
```
=> [Kafka source] Fix code formatting and Kinesis source

config/tutorials/gh-archive/index-config.yaml, docs/configuration/index-config.md, docs/tutorials/kafka.md, docs/tutorials/kinesis.md, docs/tutorials/tutorial-hdfs-logs-distributed-search-aws-s3.md, quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit-indexing/src/actors/indexer.rs
- added support for datetime field in index settings timestamp_field 
- updated tutorials taking into account bool & datetime types
Closes https://github.com/quickwit-oss/quickwit/issues/1521
Closes https://github.com/quickwit-oss/quickwit/issues/1636  (overlap)
=> Datetime & bool types tutorial update 

Cargo.lock, quickwit-config/src/index_config.rs, quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs, quickwit-doc-mapper/src/doc_mapper.rs, quickwit-doc-mapper/src/lib.rs, quickwit-doc-mapper/src/routing_expression/mod.rs, quickwit-indexing/Cargo.toml, quickwit-indexing/src/actors/indexer.rs, quickwit-metastore/src/backward_compatibility_tests/index_metadata.rs
Implements index partitioning
This PR is a working first stab to
implement index partitioning.
Second stab at https://github.com/quickwit-oss/quickwit/issues/1796
=> Partition key

Cargo.lock, quickwit-proto/Cargo.toml, quickwit-proto/src/quickwit.rs, quickwit-proto/src/quickwit_ingest_api.rs
=> Bump tonic to 0.8.0 and prost to 0.11.0

Cargo.lock, quickwit-directories/src/hot_directory.rs, quickwit-search/Cargo.toml, quickwit-search/build.rs, quickwit-search/src/rendezvous_hasher.rs
Per title.
```sh
cargo test -p quickwit-search -- test_utils_sort_by_rendez_vous_hash
cargo +nightly test -p quickwit-search -- test_utils_sort_by_rendez_vous_hash
```
=> Fix rendezvous hashing test

quickwit-search/src/cluster_client.rs, quickwit-search/src/retry/mod.rs, quickwit-search/src/retry/search.rs, quickwit-search/src/retry/search_stream.rs, quickwit-search/src/root.rs
Per title. Same issue as #1834.
```sh
cargo test -p quickwit-search
cargo +nightly test -p quickwit-search
```
=> Fix root search retry test

quickwit-cli/src/index.rs
Closes #1509 
<sup>_I think_</sup>
=> Show error rate if Indexing some of the documents failed

docs/concepts/querying.md, docs/configuration/index-config.md
=> Edit docs for fieldnorms

build/cross-images/aarch64-unknown-linux-gnu.dockerfile, build/cross-images/x86_64-unknown-linux-gnu.dockerfile
- updated cross docker  images 
- installed up-to-date protobuf-compiler
=> Fix nightly build

Cargo.lock, quickwit-aws/Cargo.toml, quickwit-aws/src/lib.rs, quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
Fetch credentials from IAM role for service account when available. 
Pending
=> Fetch credentials from IAM role for service account when available

quickwit-cli/src/index.rs
The success rate was not calculated properly. 
_<sup>also colored text yay</sub>_
=> Fix index ingest error message

quickwit-cli/src/index.rs, quickwit-cluster/src/cluster.rs, quickwit-config/src/source_config.rs, quickwit-indexing/src/actors/indexing_service.rs, quickwit-indexing/src/actors/ingest_api_garbage_collector.rs, quickwit-indexing/src/lib.rs, quickwit-indexing/src/source/file_source.rs, quickwit-indexing/src/source/ingest_api_source.rs, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/mod.rs, quickwit-indexing/src/test_utils.rs, quickwit-ingest-api/src/ingest_api_service.rs, quickwit-ingest-api/src/lib.rs, quickwit-ingest-api/src/queue.rs, quickwit-serve/src/lib.rs
Enable concurrent ingest API services.
Add unit tests.
=> Enable concurrent ingest API services

Cargo.lock, Makefile, quickwit-cli/Cargo.toml, quickwit-cli/src/index.rs, quickwit-cli/src/lib.rs, quickwit-cli/src/main.rs, quickwit-cli/src/source.rs, quickwit-core/src/index.rs, quickwit-core/src/lib.rs, quickwit-metastore/src/checkpoint.rs, quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs, quickwit-metastore/src/metastore/file_backed_metastore/mod.rs, quickwit-metastore/src/metastore/grpc_metastore/grpc_adapter.rs, quickwit-metastore/src/metastore/grpc_metastore/mod.rs, quickwit-metastore/src/metastore/mod.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/tests.rs, quickwit-proto/proto/metastore_api.proto, quickwit-proto/src/quickwit_metastore_api.rs, quickwit-serve/src/index_api/rest_handler.rs
Per title.
- ran `make test-all` command
=> Implement `index clear` and `source reset-checkpoint` CLI commands

quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit-doc-mapper/src/lib.rs, quickwit-indexing/src/actors/indexer.rs, quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit-indexing/src/actors/publisher.rs, quickwit-indexing/src/models/publish_lock.rs, quickwit-metastore/src/metastore/postgresql_model.rs
=> Add publisher lock tests

.github/workflows/ci.yml, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/kinesis/helpers.rs, quickwit-indexing/src/source/kinesis/kinesis_source.rs, quickwit-metastore/src/error.rs, quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit-metastore/src/metastore/postgresql_model.rs, quickwit-metastore/src/metastore_resolver.rs
Fixes #1889 
Also satisfied the clippy. (he was mad)
=> Enable `--all-features` for cargo clippy

config/quickwit.yaml, config/tutorials/gh-archive/index-config.yaml, config/tutorials/gh-archive/kafka-source.yaml, quickwit-actors/Cargo.toml, quickwit-actors/src/actor.rs, quickwit-actors/src/universe.rs, quickwit-indexing/Cargo.toml, quickwit-indexing/src/source/kafka_source.rs, quickwit-indexing/src/source/void_source.rs
Added more fine-grained tests for the Kafka source.
=> Add some Kakfa source tests

distribution/kubernetes/configmap.yaml, distribution/kubernetes/discovery-service.yaml, distribution/kubernetes/indexer-service.yaml, distribution/kubernetes/indexer-statefulset.yaml, distribution/kubernetes/janitor-deployment.yaml, distribution/kubernetes/namespace.yaml, distribution/kubernetes/searcher-service.yaml, distribution/kubernetes/searcher-statefulset.yaml, distribution/kubernetes/secrets.yaml, quickwit-cli/src/lib.rs, quickwit-metastore/src/metastore/file_backed_metastore/mod.rs, quickwit-serve/src/lib.rs, quickwit-storage/src/bundle_storage.rs, quickwit-storage/src/cache/storage_with_cache.rs, quickwit-storage/src/debouncer.rs, quickwit-storage/src/local_file_storage.rs, quickwit-storage/src/object_storage/azure_compatible_storage.rs, quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit-storage/src/prefix_storage.rs, quickwit-storage/src/ram_storage.rs, quickwit-storage/src/storage.rs
Add Kubernetes example manifest files
Tested on Minikube cluster
=> Add indexer and searcher statefulsets along with discovery service

Cargo.lock, quickwit-config/Cargo.toml, quickwit-config/resources/tests/index_config/hdfs-logs.json, quickwit-config/resources/tests/index_config/hdfs-logs.toml, quickwit-config/resources/tests/index_config/hdfs-logs.yaml, quickwit-config/src/index_config.rs, quickwit-config/src/lib.rs, quickwit-config/src/source_config.rs, quickwit-core/src/index.rs, quickwit-core/src/lib.rs, quickwit-metastore/src/backward_compatibility_tests/index_metadata.rs, quickwit-metastore/src/metastore/index_metadata.rs, quickwit-metastore/test-data/file-backed-index/v0-376d2611b43771e119cae07bbf5dc343.expected.json, quickwit-metastore/test-data/file-backed-index/v0-376d2611b43771e119cae07bbf5dc343.json, quickwit-metastore/test-data/index-metadata/v1-c1a8d1c0530bc79cce47f80fa8ef4024.expected.json, quickwit-metastore/test-data/index-metadata/v1-c1a8d1c0530bc79cce47f80fa8ef4024.json
Define the retention policy in the index config with three parameters:
- period
- cutoff reference
- schedule
Added a bunch of unit tests
=> Retention policy configuration and ser/deserialization

docs/reference/storage-uri.md
`(/docs/guides/azure-setup)` -> `(../guides/azure-setup)`
The issue was that it didn't know the branch.
Ran yarn build successfully to test
=> Fix docs link and tested with yarn build

docs/guides/scaleway-setup.md
Add Scaleway setup in documentation.
#1913
=> Add Scaleway setup

quickwit-config/src/index_config.rs, quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs, quickwit-doc-mapper/src/routing_expression/mod.rs, quickwit-metastore/src/backward_compatibility_tests/index_metadata.rs, quickwit-metastore/test-data/file-backed-index/v0-2a979e032677baac480d1135e111dad3.expected.json, quickwit-metastore/test-data/file-backed-index/v0-2a979e032677baac480d1135e111dad3.json, quickwit-metastore/test-data/file-backed-index/v0-376d2611b43771e119cae07bbf5dc343.expected.json, quickwit-metastore/test-data/file-backed-index/v0-3f4c4707c98ac8d42281d9803c51ebf2.expected.json, quickwit-metastore/test-data/file-backed-index/v0-3f4c4707c98ac8d42281d9803c51ebf2.json, quickwit-metastore/test-data/file-backed-index/v0-41c287d5b41d3247e3394574c7f3618c.expected.json, quickwit-metastore/test-data/file-backed-index/v0-6e3177e8924ef49dbdd8dcac421b0642.expected.json, quickwit-metastore/test-data/file-backed-index/v0-7ccb0811468081880595c160fa16fef7.expected.json, quickwit-metastore/test-data/file-backed-index/v0-7e1e1d06f4d5d051134c6ec82c09a55f.expected.json, quickwit-metastore/test-data/file-backed-index/v0-92a02bbda38485cfb39171b0b2fee51f.expected.json, quickwit-metastore/test-data/file-backed-index/v0-e38b8460d4545e0b771a1d525ad60747.expected.json, quickwit-metastore/test-data/file-backed-index/v0-f4bcb5a22eb3fb4f663463adb38a057b.expected.json, quickwit-metastore/test-data/index-metadata/v1-09bff45900c26213ec9fe5b2dcd255b2.expected.json, quickwit-metastore/test-data/index-metadata/v1-09bff45900c26213ec9fe5b2dcd255b2.json, quickwit-metastore/test-data/index-metadata/v1-14d5f2c75d6bcfcb18f6bdc4e2078ede.expected.json, quickwit-metastore/test-data/index-metadata/v1-34e92fbfeacb14c55ebbce1d9221b3b3.expected.json, quickwit-metastore/test-data/index-metadata/v1-34e92fbfeacb14c55ebbce1d9221b3b3.json, quickwit-metastore/test-data/index-metadata/v1-3c75661948f42bcfac040ec9248f060a.expected.json, quickwit-metastore/test-data/index-metadata/v1-47a77429a39539b19dc9618a699b4135.expected.json, quickwit-metastore/test-data/index-metadata/v1-4c9424432d57f312a1517f46bf3a7697.expected.json, quickwit-metastore/test-data/index-metadata/v1-c1a8d1c0530bc79cce47f80fa8ef4024.expected.json, quickwit-metastore/test-data/index-metadata/v1-e0e29fb587b2adaf08d4f87be05de255.expected.json, quickwit-metastore/test-data/index-metadata/v1-e921638af694b03174f964229922c285.expected.json, quickwit-metastore/test-data/index-metadata/v1-f045123931c0ab45d9babd93f838b197.expected.json, quickwit-search/src/fetch_docs.rs
The `max_num_partitions` is used to apply
a modulo to partition_ids.
=> Adding a `max_num_partitions` parameter.

quickwit-janitor/src/actors/garbage_collector.rs
Added logging to gc actor in janitor service since this actor not be supervised
=> Added logging to Gc actor.

quickwit-janitor/src/actors/garbage_collector.rs
Fixed garbage collector reschedule bug when there is an error on listing indexes.
=> Fix Gc reschedule bug

quickwit-common/src/uri.rs, quickwit-metastore/src/metastore/mod.rs, quickwit-serve/Cargo.toml, quickwit-serve/src/lib.rs, quickwit-serve/src/tests.rs
=> Log some warnings instead of failing during cluster configuration check

.github/workflows/ci.yml, .github/workflows/ui-ci.yml
Fix CI triggers to run CI jobs only when related files changes in the PRs
=> Fix CI triggers

quickwit/Cargo.lock, quickwit/quickwit-cli/Cargo.toml, quickwit/quickwit-cli/src/split.rs, quickwit/quickwit-cli/update_on_config.md
=> Bump humansize from 1.1.1 to 2.0.0

quickwit/quickwit-doc-mapper/src/doc_mapper.rs, quickwit/quickwit-doc-mapper/src/lib.rs, quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit/quickwit-indexing/src/actors/mod.rs, quickwit/quickwit-indexing/src/actors/packager.rs, quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs
=> Add tag fields to delete task pipeline packager.

quickwit/quickwit-indexing/failpoints/mod.rs
Per title
```
cargo test --test failpoints --features fail/failpoints
```
=> Fix failpoints

distribution/kubernetes/configmap.yaml, distribution/kubernetes/janitor-deployment.yaml, distribution/kubernetes/metastore-deployment.yaml, distribution/kubernetes/searcher-statefulset.yaml
Per title.
Deployed in local minikube
=> [Kube] Add metastore service deployment

quickwit/quickwit-indexing/src/source/kafka_source.rs
Per title.
```
cargo test --manifest-path quickwit/Cargo.toml --all-features -p quickwit-indexing
```
=> Fix consumer group name collision

quickwit/quickwit-ui/src/components/IndexSummary.tsx, quickwit/quickwit-ui/src/utils/models.ts
Fixes #2006 
I also changed the style a little bit. (Thanks @Fursum)
It currently looks like this:
=> Fix misleading UI numbers

CONTRIBUTING.md
=> Fix `cargo test` command in CONTRIBUTING.md

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-storage/Cargo.toml, quickwit/quickwit-storage/src/object_storage/azure_compatible_storage.rs, quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit/quickwit-storage/tests/azure_storage.rs
Upgraded azure blob storage dependencies
Closes https://github.com/quickwit-oss/quickwit/issues/2053
=> Upgraded azure dependencies

quickwit/quickwit-metastore/src/metastore/index_metadata.rs, quickwit/quickwit-serve/Cargo.toml
Per title.
```
cargo test --manifest-path quickwit/Cargo.toml -p quickwit-serve
```
=> Fix test dependency

docs/reference/metrics.md, quickwit/quickwit-storage/src/metrics.rs
=> Add `quickwit_` prefix to cache metrics

docs/configuration/index-config.md, quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_parsing.rs
=> Parse timestamp expressed in nanoseconds

quickwit/quickwit-indexing/src/split_store/local_split_store.rs
Fix #2110
Test updated to check that quota is correctly updated.
=> Update split store quota when a split is moved out the cache.

docs/configuration/index-config.md
added documentation for retention policy
Closes https://github.com/quickwit-oss/quickwit/issues/2095
=> Document retention policy

quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
=> fix and clarify required fast fields

quickwit/quickwit-indexing/src/actors/indexer.rs, quickwit/quickwit-indexing/src/actors/merge_executor.rs, quickwit/quickwit-indexing/src/actors/uploader.rs, quickwit/quickwit-indexing/src/merge_policy/mod.rs, quickwit/quickwit-indexing/src/metrics.rs, quickwit/quickwit-indexing/src/split_store/local_split_store.rs, quickwit/quickwit-janitor/src/actors/retention_policy_executor.rs, quickwit/quickwit-storage/src/object_storage/azure_compatible_storage.rs, quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs
In summary, this PR adds:
- instrumenting`process_merge` and `process_delete_and_merge`
- add metrics to monitor `concurrent_upload_available_permits`
- increment storage download metric to copy_to_file as it was not monitored
=> Minor fixes on wording/logging and add metric on uploader permits.

quickwit/quickwit-cli/Cargo.toml, quickwit/quickwit-cli/src/index.rs, quickwit/quickwit-cli/src/lib.rs, quickwit/quickwit-cli/src/main.rs, quickwit/quickwit-cli/src/service.rs, quickwit/quickwit-serve/src/lib.rs, quickwit/quickwit-serve/src/test_utils/cluster_sandbox.rs, quickwit/quickwit-serve/src/tests.rs
=> Use config enabled services to start quickwit server.

quickwit/quickwit-actors/src/lib.rs, quickwit/quickwit-actors/src/supervisor.rs, quickwit/quickwit-indexing/src/actors/merge_executor.rs, quickwit/quickwit-indexing/src/actors/merge_split_downloader.rs, quickwit/quickwit-indexing/src/actors/packager.rs, quickwit/quickwit-indexing/src/actors/publisher.rs, quickwit/quickwit-indexing/src/actors/uploader.rs, quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs, quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
=> Add supervisor for delete pipeline actors.

docs/reference/cli.md
Updated source `enable`/`disable` source CLI commands docs
Follow up of  https://github.com/quickwit-oss/quickwit/pull/2068
=> Update source CLI docs

quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs
=> Remove info log on downloaded bytes.

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit/quickwit-indexing/src/actors/indexing_service.rs, quickwit/quickwit-indexing/src/actors/merge_pipeline.rs, quickwit/quickwit-indexing/src/actors/merge_planner.rs, quickwit/quickwit-indexing/src/actors/mod.rs, quickwit/quickwit-indexing/src/actors/uploader.rs, quickwit/quickwit-indexing/src/models/merge_statistics.rs, quickwit/quickwit-indexing/src/models/mod.rs
Refactoring the merge pipeline.
Originally evance works. merge --rebase.
=> Merge pipeline refactoring.

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-aws/src/error.rs, quickwit/quickwit-common/src/lib.rs, quickwit/quickwit-indexing/src/models/indexing_directory.rs, quickwit/quickwit-storage/Cargo.toml, quickwit/quickwit-storage/src/bundle_storage.rs, quickwit/quickwit-storage/src/cache/storage_with_cache.rs, quickwit/quickwit-storage/src/debouncer.rs, quickwit/quickwit-storage/src/lib.rs, quickwit/quickwit-storage/src/local_file_storage.rs, quickwit/quickwit-storage/src/object_storage/azure_blob_storage.rs, quickwit/quickwit-storage/src/object_storage/error.rs, quickwit/quickwit-storage/src/object_storage/mod.rs, quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit/quickwit-storage/src/prefix_storage.rs, quickwit/quickwit-storage/src/ram_storage.rs, quickwit/quickwit-storage/src/storage.rs
Add `batch_delete` method to `Storage` trait and add implement for various structs.
Add a bunch of unit tests
=> Add `bulk_delete` method to `Storage` trait and add implementations

quickwit/quickwit-indexing/src/actors/merge_executor.rs, quickwit/quickwit-indexing/src/actors/merge_pipeline.rs, quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs
=> Add doc mapper in merge executor.

quickwit/quickwit-indexing/src/actors/doc_processor.rs, quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit/quickwit-indexing/src/actors/merge_planner.rs, quickwit/quickwit-indexing/src/actors/uploader.rs, quickwit/quickwit-indexing/src/metrics.rs
=> Update indexing metrics names & labels.

docs/reference/metrics.md, quickwit/quickwit-common/src/io.rs
IO metric description updated too.
=> Update metrics docs.

quickwit/quickwit-search/src/search_response_rest.rs
Close https://github.com/quickwit-oss/quickwit/issues/2243
=> Refactor SearchResponseRest TryFrom

quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
=> Remove the sequencer from the merge pipeline

quickwit/quickwit-common/src/io.rs, quickwit/quickwit-common/src/metrics.rs, quickwit/quickwit-indexing/src/actors/doc_processor.rs, quickwit/quickwit-indexing/src/actors/merge_planner.rs, quickwit/quickwit-indexing/src/actors/uploader.rs, quickwit/quickwit-indexing/src/metrics.rs, quickwit/quickwit-janitor/src/actors/delete_task_planner.rs, quickwit/quickwit-janitor/src/metrics.rs, quickwit/quickwit-metastore/src/metastore/instrumented_metastore.rs, quickwit/quickwit-metastore/src/metrics.rs
Per title.
The compiler is doing all the work :)
=> Implement safe int counter vec as `IntCounterVec<const N:usize>`

quickwit/quickwit-cli/src/index.rs, quickwit/quickwit-cli/src/main.rs, quickwit/quickwit-cluster/src/cluster.rs, quickwit/quickwit-common/src/kill_switch.rs, quickwit/quickwit-config/src/templating.rs, quickwit/quickwit-indexing/src/actors/doc_processor.rs, quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit/quickwit-indexing/src/actors/merge_executor.rs, quickwit/quickwit-indexing/src/actors/merge_pipeline.rs, quickwit/quickwit-indexing/src/controlled_directory.rs, quickwit/quickwit-ingest-api/src/queue.rs, quickwit/quickwit-metastore/src/backward_compatibility_tests/mod.rs, quickwit/quickwit-metastore/src/checkpoint.rs, quickwit/quickwit-metastore/src/metastore/file_backed_metastore/lazy_file_backed_index.rs, quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs, quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit/quickwit-search/src/fetch_docs.rs, quickwit/quickwit-search/src/search_client_pool.rs, quickwit/quickwit-serve/src/ingest_api/rest_handler.rs, quickwit/quickwit-storage/src/object_storage/azure_blob_storage.rs, quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit/quickwit-storage/src/split.rs, quickwit/rust-toolchain.toml
Clippy is *fire* this release
Closes #2235
=> Bump Rust version to 1.65

docs/configuration/source-config.md, quickwit/quickwit-indexing/src/source/kafka_source.rs
As per title.
```
cargo test --manifest-path quickwit/Cargo.toml --all-features -p quickwit-indexing -- --nocapture kafka
```
=> Subscribe to topic in blocking consumer poll loop

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
Update index timestamp outside of transactions.
Ran metastore tests.
=> Update index timestamp outside of transactions

quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs
Per title. Pass number of metastore servers in the pool via watch channel between pool task and metastore.
Added asserts in current test suite
=> Implement connectivity check for gRPC metastore client

config/tutorials/otel-logs/index-config.yaml, quickwit/quickwit-cli/src/main.rs, quickwit/quickwit-opentelemetry/src/otlp/logs.rs, quickwit/quickwit-opentelemetry/src/otlp/trace.rs, quickwit/quickwit-serve/src/grpc.rs
Example of ingestion from otel collector from a file
```
"num_hits": 33,
"hits": [
{
"attributes": {
"log.file.name": "test.log"
},
"body": "2022-11-13T15:23:16.391Z  WARN quickwit_config::config: Peer seed list is empty.",
"resource": {
},
"timestamp": "2022-11-13T15:24:02.984787Z"
},
{
"attributes": {
"log.file.name": "test.log"
},
"body": "2022-11-13T15:23:16.391Z  INFO quickwit_cli: Loaded Quickwit config. config_uri=file:///Users/francois.massot@contentsquare-ext.com/Documents/quickwit/repos/quickwit/config/quickwit.yaml config=QuickwitConfig { version: 0, cluster_id: \"quickwit-default-cluster\", node_id: \"node-young-Xc4Z\", enabled_services: {Indexer, Janitor, Metastore, Searcher}, rest_listen_addr: 127.0.0.1:7280, gossip_listen_addr: 127.0.0.1:7280, grpc_listen_addr: …
```
=> Add support for ingesting logs from otel collector.

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
Remove metastore transactions whenever possible. I will remove the transactions for `mark_splits_for_deletion` and `delete_splits` in follow-up PRs.
Ran Postgres metastore tests.
=> Remove metastore transactions whenever possible

quickwit/quickwit-janitor/src/actors/garbage_collector.rs, quickwit/quickwit-janitor/src/actors/retention_policy_executor.rs, quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs, quickwit/quickwit-metastore/src/metastore/instrumented_metastore.rs, quickwit/quickwit-metastore/src/metastore/mod.rs, quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
=> Rename `ListSplitsQuery.index` to `index_id`

quickwit/quickwit-metastore/src/error.rs, quickwit/quickwit-metastore/src/metastore/grpc_metastore/grpc_adapter.rs, quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs, quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit/quickwit-metastore/src/metastore/postgresql_model.rs
=> Use serialization/deserialization errors instead of internal error

quickwit/quickwit-actors/src/actor_handle.rs, quickwit/quickwit-actors/src/lib.rs, quickwit/quickwit-indexing/src/actors/indexing_service.rs, quickwit/quickwit-indexing/src/actors/mod.rs, quickwit/quickwit-janitor/src/janitor_service.rs, quickwit/quickwit-janitor/src/lib.rs, quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs, quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit/quickwit-serve/src/health_check_api/handler.rs, quickwit/quickwit-serve/src/lib.rs, quickwit/quickwit-serve/src/rest.rs, quickwit/quickwit-serve/src/test_utils/rest_client.rs, quickwit/quickwit-serve/src/tests.rs
Implement basic liveness probes for indexer and janitor service
Ran quickwit and killed the metastore while  `curl`ing the livness endpoint.
=> Implement liveness probes for indexer and janitor service

config/tutorials/gh-archive/index-config-for-clickhouse.yaml, config/tutorials/gh-archive/index-config.yaml, config/tutorials/gh-archive/kafka-source.yaml, config/tutorials/gh-archive/kinesis-source.yaml, config/tutorials/hdfs-logs/index-config.yaml, config/tutorials/otel-logs/index-config.yaml, config/tutorials/otel-trace/index-config.yaml, config/tutorials/wikipedia/index-config.yaml
tested for each index/source files.
=> Update index and source configs versions.

quickwit/quickwit-ui/package.json, quickwit/quickwit-ui/yarn.lock
=> Move JS dev dependencies in package.json devDependencies.

quickwit/quickwit-ui/src/components/IndexSideBar.tsx, quickwit/quickwit-ui/src/components/IndexSummary.tsx, quickwit/quickwit-ui/src/components/IndexesTable.tsx, quickwit/quickwit-ui/src/components/QueryEditor/config.ts, quickwit/quickwit-ui/src/components/SearchResult/ResultTable.tsx, quickwit/quickwit-ui/src/utils/models.ts, quickwit/quickwit-ui/src/views/IndexView.test.jsx, quickwit/quickwit-ui/src/views/IndexView.tsx, quickwit/quickwit-ui/src/views/IndexesView.test.jsx, quickwit/quickwit-ui/src/views/SearchView.test.jsx, quickwit/quickwit-ui/src/views/SearchView.tsx
This PR adjusts the models in our UI so that it works with the current system on `main`, this was broken after the changes in #2224 
Re-ran all the UI unit tests to ensure nothing was missed.
=> Update UI models to work with new versioned response system.

quickwit/quickwit-indexing/src/actors/ingest_api_garbage_collector.rs
I could not reproduce the failure, but I have reduced the time it takes since it was already flagged as **slow**. 
I have also added some namespace on the index_id.
https://github.com/quickwit-oss/quickwit/issues/2296
=> Fix test_ingest_api_garbage_collector flaky test

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit/quickwit-metastore/src/tests.rs
Per title. Fixes #2143.
Ran metastore test suite
=> Fix Postgres index already exists

quickwit/quickwit-indexing/src/source/kafka_source.rs
Move the Kafka consumer entirely in the poll loop to ensure that `rd_kafka_consumer_close` is always executed in a blocking task.
I was not able to reproduce the bug we observed in production :/
=> Fix tokio runtime error on consumer drop

Makefile, quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-proto/src/jaeger.api_v2.rs, quickwit/quickwit-proto/src/jaeger.storage.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.collector.logs.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.collector.metrics.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.collector.trace.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.common.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.logs.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.metrics.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.resource.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.trace.v1.rs, quickwit/quickwit-proto/src/quickwit.rs, quickwit/quickwit-proto/src/quickwit_ingest_api.rs, quickwit/quickwit-proto/src/quickwit_metastore_api.rs
Upgraded the deps using `cargo-edit` and `cargo-upgrades`. I'm attempting to fix Dependabot in another PR.
=> Upgrade Rust dependencies

.github/dependabot.yml
=> Attempt to fix dependabot workflow for Rust

quickwit/quickwit-janitor/src/garbage_collection.rs
I could not reproduce, but I made the tests faster and deterministic. 
Ran both tests 500 times.
=> Fix flaky GC tests

docs/configuration/index-config.md, docs/internals/date-time.md
=> improve datetime docs

quickwit/quickwit-doc-mapper/src/doc_mapper.rs, quickwit/quickwit-doc-mapper/src/query_builder.rs, quickwit/quickwit-search/src/collector.rs, quickwit/quickwit-search/src/leaf.rs, quickwit/quickwit-search/src/search_stream/leaf.rs
=> put all warmup related info in WarmupInfo

docs/configuration/index-config.md, quickwit/quickwit-config/resources/tests/index_config/hdfs-logs.json, quickwit/quickwit-config/resources/tests/index_config/hdfs-logs.toml, quickwit/quickwit-config/resources/tests/index_config/hdfs-logs.yaml, quickwit/quickwit-config/src/index_config/mod.rs, quickwit/quickwit-config/src/index_config/serialize.rs, quickwit/quickwit-config/src/lib.rs, quickwit/quickwit-indexing/src/actors/indexer.rs, quickwit/quickwit-indexing/src/actors/merge_executor.rs, quickwit/quickwit-indexing/src/actors/uploader.rs, quickwit/quickwit-indexing/src/test_utils.rs, quickwit/quickwit-janitor/src/actors/retention_policy_executor.rs, quickwit/quickwit-janitor/src/retention_policy_execution.rs, quickwit/quickwit-metastore/src/split_metadata_version.rs, quickwit/quickwit-metastore/src/tests.rs, quickwit/quickwit-metastore/test-data/file-backed-index/v3-50b88fe82ce92dc71262c7a473c79f7e.expected.json, quickwit/quickwit-metastore/test-data/file-backed-index/v3-50b88fe82ce92dc71262c7a473c79f7e.json, quickwit/quickwit-metastore/test-data/index-metadata/v3-ceba9077b620ebfec0dd46067419da18.expected.json, quickwit/quickwit-metastore/test-data/index-metadata/v3-ceba9077b620ebfec0dd46067419da18.json, quickwit/quickwit-search/src/tests.rs
Removed  `RetentionPolicy.cuttoff_reference` 
Closes https://github.com/quickwit-oss/quickwit/issues/2374
Related to https://github.com/quickwit-oss/quickwit/issues/2199
=> Fix retention policy bug

docs/guides/storage-setup/azure-setup.md
Explains the Azure URI format and components
Closes https://github.com/quickwit-oss/quickwit/issues/2238
=> Improve Azure docs (URI)

config/quickwit.yaml
Fix Quickwit config
`quickwit run` in repo
=> Fix Quickwit config embedded in Docker images

quickwit/quickwit-cli/src/split.rs
-  Remove `--mark-for-deletion` option from `split ls` command
- Add ability to display the raw data in JSON
```bash
quickwit split ls --index gh-archive --output-format prettyjson | jq -r .[].split_id
01GJSTADKC90742AZ1CDZFYAW0
01GJSSE19S042HDWMV6KV20AA0
01GJSTC8H5KHYWBWGYD4Y4E0Q2
01GJSTE4CK9WJJ8X1776MPYT7P
01GJST14NWGB3BFT0KBTR60Z34
01GJST3086VYXFJSV49X9NB2RJ
01GJST4VXVD4FMTDEB679TS64E
01GJSTHT9M54HH5PJEP8VMJ743
01GJST8J5G7V2TJZFAT3T7XRPX
01GJSTKNKP6VMSKE7VBS03V2GV
01GJST6Q1X8ZH1ZBEZFG39TMP4
01GJSTFZ1A1X3KWHS4ST7WQTG9
```
=>  Remove `--mark-for-deletion` option from `split ls` command

quickwit/quickwit-janitor/src/retention_policy_execution.rs
Per title.
Ran `make test-all`.
=> Use pretty sample in retention policy executor

quickwit/quickwit-ui/src/components/IndexSideBar.tsx, quickwit/quickwit-ui/src/views/SearchView.test.jsx
=> Fix spinner on index selection #2420.

quickwit/quickwit-indexing/failpoints/mod.rs
Fixed index config for failpoint_tests
=> Fix failtpoint tests (timestamp field) 

docs/get-started/installation.md
=> Document supported hardware architectures

docs/configuration/index-config.md
=> update docs, move timestamp_field to doc mapping

config/tutorials/gh-archive/index-config-for-clickhouse.yaml, config/tutorials/gh-archive/index-config.yaml, config/tutorials/gh-archive/kinesis-source.yaml, config/tutorials/hdfs-logs/index-config-partitioned.yaml, config/tutorials/otel-logs/index-config.yaml, config/tutorials/otel-trace/index-config.yaml, config/tutorials/wikipedia/index-config.yaml
All udpated configs were tested.
=> Fix tutorials index configs.

quickwit/quickwit-indexing/src/source/file_source.rs
fix #2474
Ingested a doc with `./quickwit index ingest --index index-name`: before an ERROR would get printed after about a second about an actor getting killed.
Now there is no such message, and the document is properly indexed (appear in search)
=> allow slow input on stdin when ingesting docs

quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs
Stop accepting any non-recognised format as `strftime` format and check if it contains special strftime markers.
Closes https://github.com/quickwit-oss/quickwit/issues/2479
=> Stop using strfime format as fallback

docs/reference/aggregation.md
=> add datetime example in aggregations

docs/concepts/querying.md, docs/configuration/index-config.md, quickwit/quickwit-config/src/index_config/mod.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs, quickwit/quickwit-doc-mapper/src/routing_expression/mod.rs
This PR also allows `null` as a value for the partitioning key in the configuration file.
Closes #2472
=> Document index partitioning.

docs/reference/rest-api.md
=> inlcude POST in REST API docs

quickwit/quickwit-serve/src/cluster_api/rest_handler.rs, quickwit/quickwit-serve/src/delete_task_api/handler.rs, quickwit/quickwit-serve/src/health_check_api/handler.rs, quickwit/quickwit-serve/src/indexing_api/rest_handler.rs, quickwit/quickwit-serve/src/ingest_api/rest_handler.rs, quickwit/quickwit-serve/src/node_info_handler.rs, quickwit/quickwit-serve/src/search_api/rest_handler.rs
=> replace warp and_then with then where applicable

quickwit/quickwit-core/src/index.rs, quickwit/quickwit-metastore/src/error.rs, quickwit/quickwit-serve/src/index_api/rest_handler.rs
=> Fix status code for metastore errors and index service errors.

config/tutorials/hdfs-logs/index-config-partitioned.yaml, config/tutorials/hdfs-logs/index-config-retention-policy.yaml, config/tutorials/hdfs-logs/index-config.yaml, docs/tutorials/tutorial-hdfs-logs.md
Updates the HDFS logs tutorial to reflect all the changes we've made.
Ran through all the steps in the tutorial ensuring they work.
=> Update local HDFS tutorial

config/tutorials/gh-archive/index-config.yaml, docs/tutorials/kinesis.md
I set a `commit_timeout_secs` at 10 seconds and reduce the number of messages pushed to the kinesis stream to have a nicer XP with the tutorial.
=> Update kinesis tutorial.

docs/tutorials/add-full-text-search-to-your-olap-db.md
Updates the ClickHouse tutorial.
I've also corrected some naming around `GitHub` and `ClickHouse`.
Ran through the commands listed in the tutorial.
=> Update ClickHouse tutorial

docs/reference/cli.md, quickwit/quickwit-cli/src/cli_doc_ext.toml, quickwit/quickwit-cli/src/generate_markdown.rs
Updates CLI service doc
Closes https://github.com/quickwit-oss/quickwit/issues/2384
=> Updated CLI doc

.github/workflows/publish_release_packages.yml
=> Fix release binaries action

docs/reference/cli.md, quickwit/quickwit-cli/src/cli_doc_ext.toml
I tested the generation of the docs on the website.
=> Fix doc links.

.github/workflows/publish_release_packages.yml, quickwit/quickwit-ui/Makefile
Added ui build to mac and fix version env vars
=> Fix build (UI)

docs/configuration/index-config.md
Closes #2539 
Updates the index configs to be in line with the 0.4 schemas.
=> Update `configuration` section of docs

quickwit/quickwit-common/src/lib.rs
=> Display remaining number of items rather than ellipsis

.github/actions/build-binary/action.yml, quickwit/Cross.toml
=> Populate build info when building binaries

build/cross-images/aarch64-unknown-linux-gnu.dockerfile, build/cross-images/x86_64-unknown-linux-gnu.dockerfile
=> Update cross images version for aarch64 and x86_64.

config/tutorials/otel-logs/index-config.yaml, config/tutorials/otel-logs/vector.toml, docs/tutorials/send-logs-from-vector-to-quickwit.md
=> Updated vector tutorial

quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit/quickwit-doc-mapper/src/doc_mapper.rs, quickwit/quickwit-indexing/src/actors/doc_processor.rs
DocMapper takes str instead of String.
Without extra changes, this makes no difference.
=> Minor refactor

quickwit/quickwit-jaeger/src/lib.rs
=> Remove `IntoSearchRequest` and `FromSearchResponse` traits

docs/configuration/node-config.md
Partially fix #2594. I will remove the SWIM stuff in another PR.
=> Complete node-config docs.

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-directories/src/caching_directory.rs, quickwit/quickwit-directories/src/debug_proxy_directory.rs, quickwit/quickwit-directories/src/hot_directory.rs, quickwit/quickwit-directories/src/storage_directory.rs, quickwit/quickwit-search/src/leaf.rs
=> Bump tantivy version

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-directories/src/debug_proxy_directory.rs
=> Bump tantivy version again

quickwit/quickwit-opentelemetry/src/otlp/mod.rs, quickwit/quickwit-opentelemetry/src/otlp/trace.rs, quickwit/quickwit-serve/src/lib.rs
Per title.
Launched indexer two times.
=> Create OTel trace index on indexer startup

quickwit/quickwit-core/src/index.rs, quickwit/quickwit-serve/src/index_api/rest_handler.rs
=> Add a rest handler to get `source_config`

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit/quickwit-doc-mapper/src/query_builder.rs, quickwit/quickwit-search/src/tests.rs
Per title. I need this feature for the Jaeger integration (filters on span start timestamp or duration).
Added unit tests.
=> Enable range queries on datetime and u64 fields

docs/reference/rest-api.md, docs/reference/storage-uri.md
=> Update storage uri docs page / add partition_by_field in REST API

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-proto/Cargo.toml
=> Bump various dependencies

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-jaeger/Cargo.toml, quickwit/quickwit-jaeger/src/lib.rs, quickwit/quickwit-opentelemetry/src/otlp/mod.rs, quickwit/quickwit-opentelemetry/src/otlp/trace.rs
Per title.
Added unit tests + tested a few queries
=> Implement span duration filter

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs, quickwit/quickwit-jaeger/src/lib.rs, quickwit/quickwit-opentelemetry/src/otlp/trace.rs, quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs
=> Bump base64 dependency

quickwit/quickwit-opentelemetry/src/otlp/trace.rs
=> Trace Jaeger service

.github/workflows/coverage.yml, quickwit/quickwit-indexing/failpoints/mod.rs, quickwit/quickwit-indexing/src/test_utils.rs
=> Add log info for coverage failpoint.

quickwit/quickwit-indexing/src/actors/indexer.rs, quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit/quickwit-indexing/src/actors/merge_executor.rs, quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
=> Protect some futures in various actors

README.md
Update tutorial links in README
Fixes: https://github.com/quickwit-oss/quickwit/issues/2703
=> Update tutorial links in README

quickwit/quickwit-opentelemetry/src/otlp/trace.rs
Records positions for logs so users can issue phrase queries. To do so, I took the logs out of the `events` field and moved them into their standalone field so that I could configure a tokenizer and enable positions in order the go around the current known limitations of the JSON field.
Ran those queries and inspected hits:
```
event_names:"spawning" AND event_names:"pipeline" -> 1 hit
```
```
event_names:"spawning pipeline" -> 0 hit
```
The original logline being "Spawning merge pipeline."
=> Record positions for logs

quickwit/quickwit-jaeger/src/lib.rs, quickwit/quickwit-jaeger/src/metrics.rs
=> Instrument Jaeger service

quickwit/quickwit-common/src/lib.rs, quickwit/quickwit-common/src/rendezvous_hasher.rs, quickwit/quickwit-control-plane/src/indexing_plan.rs, quickwit/quickwit-indexing/src/test_utils.rs, quickwit/quickwit-search/src/lib.rs, quickwit/quickwit-search/src/root.rs, quickwit/quickwit-search/src/search_job_placer.rs
=> Using rendez-vous hashing to sort nodes used for scheduling.

quickwit/quickwit-core/src/index.rs, quickwit/quickwit-serve/src/index_api/rest_handler.rs
To have a CLI that uses the REST API (required for #2717) , we need to add new endpoints:
I also removed the usage of `IndexService` when it was not useful and used the metastore directly to call the right methods.
We need to improve the code of the REST API (organization and harmonization of structs, for example to fix #2493 and #2491). I suggest doing that in another PR.
=> Add missing REST endpoints.

quickwit/quickwit-serve/src/index_api/rest_handler.rs
=> Fix splits filtering REST endpoint with default values.

quickwit/quickwit-opentelemetry/src/otlp/trace.rs
Return unavailable status code when rate limited. This is a retriable error code, clients should retry. The OTel collector does retry.
```
otel-collector  | 2023-01-31T16:54:57.346Z	info	exporterhelper/queued_retry.go:426	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "otlp/qw", "error": "rpc error: code = Unavailable desc = Failed to store spans due to rate limiting.", "interval": "4.958036981s"}
```
=> Return resource exhausted status code when rate limited

docker-compose.yml, quickwit/quickwit-indexing/src/source/pulsar_source.rs
=> Fix pulsar admin port

quickwit/quickwit-metastore/src/metastore/metastore_with_control_plane_triggers.rs
=> Add control plane notification on source toggle.

quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
Adding a test that was failing with the previous implementation.
=> Fix file backed metastore concurrency issue, closing #2781.

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-serve/src/rest.rs
Tested locally.
I upgrade utoipa version too.
=> Fmassot  fix swagger UI

README.md
Replaced all discord links with discord.quickwit.io
=> Replaced old discord links with discord.quickwit.io

quickwit/quickwit-serve/src/lib.rs
=> Launch readyness task after grpc server is started.

quickwit/quickwit-jaeger/src/lib.rs
Per title.
- Tested within Jaeger UI (see query URL)
=> Quote service and span names in tracing search queries

config/tutorials/stackoverflow/index-config.yaml, docs/get-started/quickstart.md
=> Update quickstart with the new CLI.

docs/reference/cli.md, quickwit/quickwit-cli/src/cli_doc_ext.toml, quickwit/quickwit-cli/src/generate_markdown.rs
All commands in examples have been executed locally.
=> Update CLI docs with new CLI.

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-codegen/Cargo.toml, quickwit/quickwit-codegen/src/codegen.rs, quickwit/quickwit-codegen/src/lib.rs, quickwit/quickwit-codegen/tests/codegen.rs, quickwit/quickwit-codegen/tests/hello/error.rs, quickwit/quickwit-codegen/tests/hello/hello.proto, quickwit/quickwit-codegen/tests/hello/hello.rs, quickwit/quickwit-codegen/tests/hello/mod.rs
Per title.
- Inspected generated code
=> Generate service trait from proto service definition

CONTRIBUTING.md
Removes UI commands form the Development section and adds a list of useful make commands.
By manually running commands added to the document.
Closes #2822
=> Refactor Development section in Contributing guide

monitoring/otel-collector-config.yaml, quickwit/quickwit-jaeger/src/lib.rs, quickwit/quickwit-opentelemetry/src/otlp/logs.rs, quickwit/quickwit-opentelemetry/src/otlp/metrics.rs, quickwit/quickwit-opentelemetry/src/otlp/mod.rs, quickwit/quickwit-opentelemetry/src/otlp/trace.rs, quickwit/quickwit-serve/src/grpc.rs, quickwit/quickwit-serve/src/lib.rs
- Complete data model
- Create index on startup
- Instrumentation
=> Complete OTLP logs service implementation

docs/reference/cli.md, quickwit/quickwit-cli/src/cli_doc_ext.toml
Updated scoring query example with a term that has an observable effect
Closes https://github.com/quickwit-oss/quickwit/issues/2790
=> Updated scoring example

quickwit/quickwit-jaeger/src/lib.rs
Per title.
Tested in Jaeger UI
=> Limit stream spans gRPC message to ~4MiB

quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
Closes https://github.com/quickwit-oss/quickwit/issues/2851
=> Make _id in bulk API optional

quickwit/quickwit-cli/Cargo.toml, quickwit/quickwit-indexing/Cargo.toml
=> Add pulsar to release feature sets.

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-cli/Cargo.toml, quickwit/quickwit-cli/src/index.rs, quickwit/quickwit-janitor/src/garbage_collection.rs, quickwit/quickwit-rest-client/src/rest_client.rs
Fix #2880 
Added a test that is failing before the modification.
=> Do not send mark for deletion request if no split

quickwit/quickwit-cli/src/source.rs, quickwit/quickwit-cli/tests/cli.rs, quickwit/quickwit-rest-client/src/rest_client.rs, quickwit/quickwit-serve/src/index_api/rest_handler.rs
Fix source toggle, wrong path, and wrong body. What is annoying is that the API did not return an error.
=> Fix source toggle bug in REST client.

quickwit/quickwit-config/src/source_config/mod.rs
=> Enable multiple pipelines for pulsar source.

quickwit/quickwit-serve/src/rest.rs, quickwit/quickwit-serve/src/test_utils/rest_client.rs, quickwit/quickwit-serve/src/tests.rs
Redirect only GET request to UI. Now POST request on the root url returns a 405. Fix #2830.
Test added.
=> Redirect only GET request to UI.

config/tutorials/stackoverflow/pulsar-source.yaml, config/tutorials/stackoverflow/send_messages_to_pulsar.py, docs/get-started/tutorials/pulsar.md
Add a Pulsar tutorial with local install of a pulsar standalone instance and a quickwit standalone instance.
=> Add Pulsar tutorial

docs/configuration/source-config.md
The source config docs needed to be updated.
=> Update source config docs.

quickwit/quickwit-codegen/quickwit-codegen-example/src/error.rs, quickwit/quickwit-ingest-api/src/queue.rs
Just commit `make fix` changes.
=> Commit make fix changes.

config/tutorials/wikipedia/index-config.yaml, docs/reference/cli.md, docs/reference/rest-api.md, quickwit/quickwit-cli/src/cli_doc_ext.toml
Minor fixes.
Check rendering on website.
=> Update CLI doc.

quickwit/quickwit-indexing/src/source/pulsar_source.rs
This test shows that we are indexing several times the same documents.
=> Create test with a pulsar source that constantly fails

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-common/src/tower/buffer.rs, quickwit/quickwit-common/src/tower/estimate_rate.rs, quickwit/quickwit-common/src/tower/mod.rs, quickwit/quickwit-common/src/tower/rate.rs, quickwit/quickwit-common/src/tower/rate_estimator.rs, quickwit/quickwit-common/src/tower/rate_limit.rs
=> Add custom Tower middlewares

docs/configuration/index-config.md, docs/configuration/node-config.md, docs/configuration/source-config.md, docs/deployment/deployment-modes.md, docs/deployment/kubernetes.md, docs/reference/rest-api.md
=> Clean table and remove obsolete docs.

quickwit/quickwit-cli/src/split.rs, quickwit/quickwit-common/src/tower/rate_limit.rs, quickwit/quickwit-config/src/service.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs, quickwit/quickwit-doc-mapper/src/routing_expression/mod.rs, quickwit/quickwit-rest-client/src/models.rs, quickwit/quickwit-search/src/cluster_client.rs, quickwit/quickwit-search/src/tests.rs, quickwit/quickwit-serve/src/format.rs
Checking license headers
Running cargo clippy --fix.
=> Changes made by make fix

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-serve/Cargo.toml, quickwit/quickwit-serve/src/rest.rs, quickwit/quickwit-ui/package.json, quickwit/quickwit-ui/src/components/SideBar.tsx, quickwit/quickwit-ui/src/index.css, quickwit/quickwit-ui/src/views/ApiView.tsx, quickwit/quickwit-ui/src/views/App.tsx, quickwit/quickwit-ui/swaggerUIMock.js, quickwit/quickwit-ui/yarn.lock
=> Issue/3025 Integrate Swagger UI to the API

quickwit/quickwit-ui/src/views/SearchView.tsx
=> Fix #3027.

quickwit/quickwit-config/src/service.rs
=> Serializing services in snake_case to align with what the user inputs

quickwit/quickwit-ui/src/components/IndexSideBar.tsx
Fix the UI issue when the list of fields is very long.
=> Add overflow rule on index side bar.

install.sh
=> Add aarch64-apple-darwin case in install.sh.

docs/get-started/tutorials/add-full-text-search-to-your-olap-db.md, docs/get-started/tutorials/tutorial-hdfs-logs-distributed-search-aws-s3.md, docs/get-started/tutorials/tutorial-hdfs-logs.md
=> Update docs on hdfs-logs tutorials.

quickwit/quickwit-indexing/src/source/ingest_api_source.rs
fix #3036
I tried to ingest about ~50GB of data without being able to trigger the issue again
=> fix timeout in ingest api source

README.md
Following [redditor comment](https://www.reddit.com/r/selfhosted/comments/11zbr3u/comment/jdbxn09/?context=3).
=> Fix summary of AGPL in README.md

quickwit/quickwit-serve/src/lib.rs
Tested locally
`2023-03-25T21:33:54.794Z DEBUG quickwit_serve: Metastore is available. metastore_uri=Uri { uri: "file:///Users/fmassot/Documents/quickwit/tests/qwdata/indexes" }`
=> Add warning log when metastore is not available.

quickwit/Cargo.lock, quickwit/Cargo.toml
=> Fixing build on non x86_64

quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_parsing.rs
=> Handling date without time. Time is then 00:00:00

quickwit/quickwit-search/src/fetch_docs.rs, quickwit/quickwit-storage/src/local_file_storage.rs
related to #3146
includes a commit I forgot to push in #3162 (use `buffer_unordered` instead of custom buffering)
wrap sequence of io operation in a `tokio::task::spawn_blocking` to limit back and forth between the main pool and the blocking pool. This seems to  yield a 2-3% latency improvement in search queries on a local index
manual tests to measure latency
=> fix more issues with search latency 

docs/configuration/index-config.md, quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs, quickwit/quickwit-doc-mapper/src/tokenizers.rs
add lowercase tokenizer
document fast field tokenizer
unit test for serialization
locally tested config with custom tokenizer
closes #3126 closes #3158
=> add lowercase tokenizer, document fast field tokenizer

quickwit/quickwit-common/src/tower/rate_estimator.rs
Per title.
- Added some test cases
=> Fix rate estimator bucket race condition

docs/configuration/index-config.md
add missing dynamic_mapping configuration example
document fast parameter
add dynamic_mapping paragraph
rephrase
=> improve dynamic mapping docs

quickwit/quickwit-ui/src/components/TimeRangeSelect.tsx
fix #3221 
verify the ui is now fine
=> fix datepicker showing start date instead of end date

docs/configuration/node-config.md, quickwit/Cargo.lock, quickwit/quickwit-common/Cargo.toml, quickwit/quickwit-common/src/net.rs, quickwit/quickwit-config/Cargo.toml, quickwit/quickwit-config/src/lib.rs, quickwit/quickwit-config/src/quickwit_config/serialize.rs, quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
Use hostname as default node ID. The problem I'm trying to solve is described in the following [issue](https://github.com/quickwit-oss/quickwit/issues/2875).
In progress:
=> Use short hostname as default node ID

quickwit/quickwit-directories/src/bundle_directory.rs, quickwit/quickwit-directories/src/hot_directory.rs, quickwit/quickwit-storage/src/bundle_storage.rs, quickwit/quickwit-storage/src/lib.rs, quickwit/quickwit-storage/src/split.rs, quickwit/quickwit-storage/src/versioned_component.rs
=> Adds a magic number and versioning to hot directory data and bundle

quickwit/quickwit-actors/benches/bench.rs
=> Fix actor bench

quickwit/quickwit-search/src/root.rs
return only the tantivy error in case aggregation parsing fails.
The correct solution would be to split tracing and tantivy aggregations.
=> improve agg error message

quickwit/quickwit-codegen/src/codegen.rs, quickwit/quickwit-ingest/build.rs, quickwit/quickwit-ingest/src/codegen/ingest_service.rs, quickwit/quickwit-ingest/src/doc_batch.rs, quickwit/quickwit-ingest/src/ingest_api_service.rs, quickwit/quickwit-ingest/src/ingest_service.proto, quickwit/quickwit-ingest/src/lib.rs, quickwit/quickwit-opentelemetry/src/otlp/logs.rs, quickwit/quickwit-opentelemetry/src/otlp/trace.rs, quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
- Remove and optimize some gross allocations.
- Backward compatible renames and type changes.
=> Remove/optimize some allocations in the REST API ingest handlers

quickwit/quickwit-indexing/src/source/kinesis/kinesis_source.rs
=> Ignore flaky Kinesis source test

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-serve/Cargo.toml, quickwit/quickwit-serve/src/cluster_api/rest_handler.rs, quickwit/quickwit-serve/src/delete_task_api/handler.rs, quickwit/quickwit-serve/src/elastic_search_api/model/error.rs, quickwit/quickwit-serve/src/elastic_search_api/model/mod.rs, quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs, quickwit/quickwit-serve/src/format.rs, quickwit/quickwit-serve/src/index_api/rest_handler.rs, quickwit/quickwit-serve/src/indexing_api/rest_handler.rs, quickwit/quickwit-serve/src/ingest_api/rest_handler.rs, quickwit/quickwit-serve/src/json_api_response.rs, quickwit/quickwit-serve/src/lib.rs, quickwit/quickwit-serve/src/rest.rs, quickwit/quickwit-serve/src/search_api/rest_handler.rs
=> Add elasticsearch error and refactor API response.

quickwit/quickwit-indexing/src/source/file_source.rs, quickwit/quickwit-indexing/src/source/ingest_api_source.rs, quickwit/quickwit-indexing/src/source/kafka_source.rs, quickwit/quickwit-indexing/src/source/mod.rs, quickwit/quickwit-indexing/src/source/pulsar_source.rs, quickwit/quickwit-indexing/src/source/source_factory.rs, quickwit/quickwit-indexing/src/source/vec_source.rs, quickwit/quickwit-indexing/src/source/void_source.rs
Per title.
`cargo test --manifest-path quickwit/Cargo.toml -p quickwit-indexing --lib --all-features -- --nocapture`
=> Fix Pulsar tests

quickwit/Cargo.lock, quickwit/quickwit-codegen/Cargo.toml, quickwit/quickwit-codegen/example/Cargo.toml, quickwit/quickwit-codegen/example/build.rs, quickwit/quickwit-codegen/example/src/codegen/hello.rs, quickwit/quickwit-codegen/example/src/hello.proto, quickwit/quickwit-codegen/example/src/lib.rs, quickwit/quickwit-codegen/src/codegen.rs, quickwit/quickwit-common/src/lib.rs, quickwit/quickwit-common/src/stream_utils.rs, quickwit/quickwit-control-plane/build.rs, quickwit/quickwit-control-plane/src/codegen/control_plane_service.rs, quickwit/quickwit-ingest/build.rs, quickwit/quickwit-ingest/src/codegen/ingest_service.rs
and some additional minor fixes.
=> Add support for server-side streaming for code-generated clients

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
Simulated pipelines don't play nicely with accelerated times it seems.
See #2862
Fixes #3206
Fixing a flaky test.
=> Fix test_indexing_pipeline_all_failures_handling

quickwit/quickwit-metastore/src/backward_compatibility_tests/mod.rs, quickwit/quickwit-metastore/test-data/file-backed-index/v0.6.expected.json, quickwit/quickwit-metastore/test-data/file-backed-index/v0.6.json
Fixes regression that was missing changes in the current serialization version.
Fixes #3374
By changing and removing the serialization test files.
=> Make bwc test fail if anything changes

quickwit/quickwit-jaeger/src/integration_tests.rs, quickwit/quickwit-jaeger/src/lib.rs
Following the fix for ingesting OTLP array values, I omitted to update the code that converts OLTP attributes to Jaeger tags.
=> Fix array conversion from OTLP attributes to Jaeger tags

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-codegen/example/src/codegen/hello.rs, quickwit/quickwit-control-plane/src/codegen/control_plane_service.rs, quickwit/quickwit-ingest/src/codegen/ingest_service.rs, quickwit/quickwit-proto/src/jaeger.storage.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.collector.logs.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.collector.metrics.v1.rs, quickwit/quickwit-proto/src/opentelemetry.proto.collector.trace.v1.rs, quickwit/quickwit-proto/src/quickwit.rs, quickwit/quickwit-proto/src/quickwit_indexing_api.rs, quickwit/quickwit-proto/src/quickwit_metastore_api.rs
Bump a bunch of deps. The AWS SDK PR needs to be merged first.
=> Bump criterion, hyper-rustls, tonic, and opentelemetry crates

quickwit/quickwit-jaeger/src/integration_tests.rs, quickwit/quickwit-jaeger/src/lib.rs, quickwit/quickwit-opentelemetry/src/otlp/traces.rs, quickwit/quickwit-proto/build.rs, quickwit/quickwit-proto/src/opentelemetry.proto.trace.v1.rs
- index span status
- modify Jaeger query builder to allow `error=true/false` queries
- added unit tests
- updated existing unit tests
=> Index and search span status

quickwit/quickwit-cli/src/lib.rs, quickwit/quickwit-cli/src/metrics.rs
Metric tested with a local prometheus + grafana
=> Use debug level for busy detector and add metric.

quickwit/quickwit-query/src/json_literal.rs
=> Bugfix: interpret_str was not overloaded for number types.

quickwit/quickwit-ui/src/components/SearchResult/Row.tsx, quickwit/quickwit-ui/src/utils/models.ts
=> Fix timestamp in nanos display in UI

quickwit/quickwit-cli/src/main.rs, quickwit/quickwit-cli/src/service.rs, quickwit/quickwit-telemetry/src/lib.rs, quickwit/quickwit-telemetry/src/payload.rs, quickwit/quickwit-telemetry/src/sender.rs
Notable changes:
- Add features to telemetry info
- Each event send the activated features and the services that are running.
I need to make a small test.
=> Add features to telemetry info.

quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs, quickwit/rest-api-tests/rest_api_test.py, quickwit/rest-api-tests/scenarii/es_compatibility/0004-term_aggregations.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/_setup.quickwit.yaml
=> Enable term aggregation es-compat test now that we have fastfield

quickwit/quickwit-query/src/tokenizers.rs
=> fix clippy

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
This change increased the interval from 1 sec to 10 sec, probably by accident https://github.com/quickwit-oss/quickwit/pull/2810/files#diff-6ce25f13609087e65b3b59920bbad56f04acb83abdde64b68fbd214441c941f7R455
=> reduce actor observe interval from 10s to 1s

.github/workflows/coverage.yml, quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/Makefile, quickwit/quickwit-aws/src/lib.rs, quickwit/quickwit-config/src/storage_config.rs, quickwit/quickwit-storage/Cargo.toml, quickwit/quickwit-storage/src/lib.rs, quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit/quickwit-storage/tests/s3_storage.rs
Added tests and fixed one bug.
Tested on Amazon S3, Alibaba, GCS, and R2.
=> Add tests for bulk delete and virtual-hosted-style vs path-style access

quickwit/quickwit-actors/src/lib.rs
Tested locally.
Now the log appears only if `QW_ACTOR_HEARTBEAT_SECS` cannot be parsed.
```console
2023-06-02T07:19:42.341Z  WARN quickwit_actors: Failed to parse `QW_ACTOR_HEARTBEAT_SECS=0A` in seconds > 0, using default heartbeat (30 seconds).
```
=> Handle correclty std::env::var errors.

config/quickwit.yaml, docs/configuration/node-config.md, quickwit/quickwit-config/resources/tests/config/quickwit.json, quickwit/quickwit-config/resources/tests/config/quickwit.toml, quickwit/quickwit-config/resources/tests/config/quickwit.yaml, quickwit/quickwit-config/src/storage_config.rs
Added minimal doc for storage and metastore configs. There's some overlap with existing content, so I want to "refactor" our storage and metastore documentation content in follow-up PRs.
=> Document storage and metastore configs

docs/get-started/tutorials/tutorial-hdfs-logs.md
updated hdfs tutorial to use index ingest instead of tool local-ingest
Closes https://github.com/quickwit-oss/quickwit/issues/3499
=> Updated hdfs tutorial

docs/reference/cli.md, quickwit/quickwit-cli/src/generate_markdown.rs, quickwit/quickwit-cli/src/service.rs
Replaces lists of options with tables in CLI docs.
Fixes #3504
By generating the quickwit website to ensure that it looks good after Docusaurus treatment.
=> Improve CLI docs

docs/reference/cli.md
Adds the commit timeout documentation.
Fixes #3476
Ran it through a spellchecker.
=> Add commit timeout docs

quickwit/quickwit-opentelemetry/src/otlp/logs.rs
Updated otel index configs with relevant fast fields
Note: aggregation also works
Closes https://github.com/quickwit-oss/quickwit/issues/3535
=> Update otel indexes config

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-doc-mapper/src/doc_mapper.rs, quickwit/quickwit-query/src/elastic_query_dsl/phrase_prefix_query.rs, quickwit/quickwit-query/src/query_ast/full_text_query.rs, quickwit/quickwit-query/src/query_ast/phrase_prefix_query.rs, quickwit/quickwit-query/src/query_ast/user_input_query.rs, quickwit/quickwit-query/src/tokenizers.rs
=> Bump tantivy version, and add phrase prefix query support.

quickwit/rest-api-tests/Pipfile, quickwit/rest-api-tests/Pipfile.lock, quickwit/rest-api-tests/README.md
Per title.
Ran commands described in README.
=> Add Pipfile and instructions for running REST API tests

quickwit/Cargo.lock, quickwit/Cargo.toml
- Bump rdkafka dep to 0.32
- Enable zstd feature
=> Bump rdkafka dep

quickwit/quickwit-serve/src/elastic_search_api/model/mod.rs, quickwit/quickwit-serve/src/elastic_search_api/model/search_body.rs, quickwit/quickwit-serve/src/elastic_search_api/model/search_query_params.rs, quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0008-sort_by.yaml
=> Support single string as sort field, objects, etc

quickwit/quickwit-cli/src/lib.rs, quickwit/quickwit-cli/src/service.rs, quickwit/quickwit-cli/src/tool.rs, quickwit/quickwit-config/src/storage_config.rs, quickwit/quickwit-storage/src/storage_resolver.rs
Ensure the metastore resolver uses the configured storage resolver.
=> Fix metastore resolver

config/quickwit.yaml, docs/configuration/node-config.md, quickwit/quickwit-config/resources/tests/config/quickwit.json, quickwit/quickwit-config/resources/tests/config/quickwit.toml, quickwit/quickwit-config/resources/tests/config/quickwit.yaml, quickwit/quickwit-config/src/quickwit_config/serialize.rs, quickwit/quickwit-config/src/storage_config.rs, quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs, quickwit/quickwit-storage/tests/s3_storage.rs
Add storage flavors for S3-compatible storage providers that deviate from the reference API.
=> Add storage flavors

quickwit/quickwit-search/src/collector.rs
Not my finding. All credit to @trinity.
Just extracting the bugfix to release 0.6.2.
=> Bugfix on date sorting (Thanks to @trinity-1686a)

quickwit/quickwit-proto/build.rs, quickwit/quickwit-proto/protos/quickwit/search_api.proto, quickwit/quickwit-proto/src/lib.rs, quickwit/quickwit-proto/src/quickwit.rs, quickwit/quickwit-search/src/cluster_client.rs, quickwit/quickwit-search/src/collector.rs, quickwit/quickwit-search/src/leaf.rs, quickwit/quickwit-search/src/leaf_cache.rs, quickwit/quickwit-search/src/root.rs, quickwit/quickwit-search/src/search_stream/leaf.rs, quickwit/quickwit-search/src/tests.rs, quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs, quickwit/quickwit-serve/src/search_api/rest_handler.rs, quickwit/quickwit-storage/src/storage_resolver.rs, quickwit/rest-api-tests/scenarii/sort_orders/0001-sort-elasticapi.yaml, quickwit/rest-api-tests/scenarii/sort_orders/_setup.quickwit.yaml
=> sort by two fast fields

quickwit/Cargo.lock, quickwit/quickwit-codegen/README.md, quickwit/quickwit-codegen/example/build.rs, quickwit/quickwit-codegen/src/codegen.rs, quickwit/quickwit-control-plane/build.rs, quickwit/quickwit-ingest/Cargo.toml, quickwit/quickwit-ingest/build.rs
Adds a method that allows supplying a prost config.
By running existing tests.
=> Make Codegen script more configurable

quickwit/quickwit-cli/src/main.rs
=> Fix ANSI config.

quickwit/quickwit-cluster/src/node.rs, quickwit/quickwit-serve/src/lib.rs
This pool is also interested in updates of indexing tasks. We must also watch `ClusterChange::Update` notifications.
=> Fix `IndexerPool` setup

docs/configuration/index-config.md, quickwit/quickwit-datetime/src/date_time_parsing.rs, quickwit/quickwit-datetime/src/lib.rs, quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
Parse Unix timestamps passed as a string.
=> Parse timestamp strings

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
=> Making sure indexing pipeline terminates rapidly on our happy path.

.github/workflows/coverage.yml
I broke the coverage test see https://github.com/quickwit-oss/quickwit/actions/runs/5891714522/workflow
Hopefully, this pr fix it. Manually trigger it: https://github.com/quickwit-oss/quickwit/actions/runs/5892006325/job/15980341315
=> fix coverage

CONTRIBUTING.md, docker-compose.yml, quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-cli/Cargo.toml, quickwit/quickwit-cli/src/lib.rs, quickwit/quickwit-cli/src/main.rs
=> Jaeger now accepts OTLP protocol, remove jaeger exporter stuff.

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit/quickwit-metastore/src/tests.rs
=> Fix invalid internal tag used for postgres dollar quoted.

docs/configuration/node-config.md
=> Add config examples per section for node config doc page.

docs/reference/es_compatible_api.md, quickwit/quickwit-doc-mapper/src/query_builder.rs, quickwit/quickwit-query/src/elastic_query_dsl/match_bool_prefix.rs, quickwit/quickwit-query/src/elastic_query_dsl/match_query.rs, quickwit/quickwit-query/src/elastic_query_dsl/mod.rs, quickwit/quickwit-query/src/elastic_query_dsl/phrase_prefix_query.rs, quickwit/quickwit-query/src/query_ast/full_text_query.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0010-match_phrase_prefix_query.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/0017-match-bool-prefix-query.yaml
=> Added supprt for match bool prefix

quickwit/rest-api-tests/run_tests.py, quickwit/rest-api-tests/scenarii/aggregations/0001-aggregations.yaml, quickwit/rest-api-tests/scenarii/aggregations/_ctx.yaml, quickwit/rest-api-tests/scenarii/aggregations/_setup.quickwit.yaml, quickwit/rest-api-tests/scenarii/aggregations/_teardown.quickwit.yaml
=> add rest-regression aggs test

.github/actions/cargo-build-macos-binary/action.yml, .github/actions/cross-build-binary/action.yml, .github/workflows/ui-ci.yml, CONTRIBUTING.md, Dockerfile
=> Upgrade Node.js

.github/actions/cargo-build-macos-binary/action.yml, .github/actions/cross-build-binary/action.yml, .github/workflows/ci.yml
=> Replace action-rs/toolchain with manual config

quickwit/quickwit-storage/src/split_cache/split_table.rs
This is important to improve the hit rate of the split cache. Before the PR, we used a last modified time of 0.
As a result, once the cache reached saturation, a newly reported split could trigger the eviction of an old split that got accessed once.
In other words, cache population could only happen when splits got accessed. This is really a bad situation because the split cache does not get any hint when splits are deleted. It only relies on eviction to release space.
After this workaround, splits that are not accessed ends up having a lower priority than new splits after
30mn without any access.
=> Changes the last modified timestamp of newly reported splits.

config/tutorials/stackoverflow/index-config.yaml, docs/configuration/index-config.md, docs/get-started/quickstart.md
update quickstart to show the usage of document dynamic mapping
Update the quickstart document. and show the usage of dynamic mapping to simplify  index configuration
Closes #3541
=> update quickstart document

quickwit/quickwit-query/src/elastic_query_dsl/bool_query.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0009-bool_query.yaml
=> Support null values for ES bool query array fields.

docs/reference/es_compatible_api.md, quickwit/quickwit-query/src/elastic_query_dsl/match_phrase_query.rs
add documents about multi match query and match phrase query
add documents about multi match query and match phrase query
fix link error in match phrase query
Closes #3728
=> add documents about multi match and match phrase

quickwit/quickwit-cli/src/service.rs, quickwit/quickwit-cluster/src/lib.rs, quickwit/quickwit-config/src/node_config/mod.rs, quickwit/quickwit-config/src/node_config/serialize.rs, quickwit/quickwit-serve/src/grpc.rs, quickwit/quickwit-serve/src/lib.rs, quickwit/quickwit-serve/src/rate_modulator.rs
=> Minor refactoring

quickwit/quickwit-common/src/binary_heap.rs, quickwit/quickwit-common/src/lib.rs, quickwit/quickwit-proto/src/search/mod.rs, quickwit/quickwit-search/src/collector.rs, quickwit/quickwit-search/src/leaf.rs, quickwit/quickwit-search/src/service.rs, quickwit/quickwit-search/src/tests.rs, quickwit/quickwit-search/src/thread_pool.rs
fix https://github.com/quickwit-oss/quickwit/issues/3298
supersedes #3545. Recent changes in sorting and how the search semaphore is acquired made that PR very hard to rebase. Porting the changes manually to a new branch seemed easier
=> optimize sort by date and docid

quickwit/quickwit-actors/src/supervisor.rs, quickwit/quickwit-actors/src/tests.rs, quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs
=> Embed the supervizee observable state in the supervisor observable

quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/gc.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.md, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-proto/protos/quickwit/ingester.proto, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
Optimize replication task process loop.
=> Optimize replication task process loop

quickwit/quickwit-search/src/fetch_docs.rs
logic.
Previously the code was strangely combining spawning each individual tasks in to a different tokio task, and using a futures_unordered to wait for their results.
=> Adding tracing to fetch docs operations and changing the conccurrency

quickwit/Cargo.lock, quickwit/quickwit-datetime/Cargo.toml, quickwit/quickwit-datetime/src/date_time_format.rs, quickwit/quickwit-query/src/json_literal.rs
=> Stricter date parsing.

quickwit/quickwit-control-plane/src/control_plane.rs
... at least in the control plane code.
The idea is that we want to let client use that as a regular code path for `create_if_not_exists`.
Closes #3983
=> Avoid logging error on create index when index already exists.

quickwit/quickwit-metastore/src/split_metadata.rs
=> Trim tags in SpliMetadata debug

.gitattributes
=> Editing the gitattributes to remove the codegen directories from PR.

docs/operating/monitoring.md
Documentation "Monitoring with Grafana" was not correctly updated. This PR aligned the doc with with latest version.
No need.
=> doc: words correction

quickwit/Cargo.lock, quickwit/Cargo.toml
The precompiled binary was removed in 1.0.84
=> Unpin serde dependency version

quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs, quickwit/quickwit-integration-tests/src/tests/index_tests.rs, quickwit/quickwit-rest-client/src/models.rs, quickwit/quickwit-rest-client/src/rest_client.rs, quickwit/quickwit-search/src/root.rs, quickwit/quickwit-serve/src/index_api/rest_handler.rs, quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
(We might want to fix #4070 before merging)
=> Added an integration test for ingest v2

docs/operating/monitoring.md
Just a minor wording inconsistency.
:eye:
=> fix(doc): reword monitoring

quickwit/quickwit-cli/src/index.rs, quickwit/quickwit-cli/src/lib.rs
As far as I can tell this is just overengineering..
=> Removing search/ingest specific client building method.

quickwit/quickwit-indexing/src/source/ingest_api_source.rs, quickwit/quickwit-ingest/src/codegen/ingest_service.rs, quickwit/quickwit-ingest/src/ingest_api_service.rs, quickwit/quickwit-ingest/src/ingest_service.proto
=> Bugfix: truncating the ingest v1 source on initialization.

quickwit/quickwit-indexing/src/source/ingest/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-proto/protos/quickwit/ingester.proto, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs, quickwit/quickwit-proto/src/ingest/ingester.rs
Removed the feature since it was unused, which simplifies the code. This PR also fixes #4118.
=> Remove `to_position_inclusive` parameter from fetch stream

quickwit/Cargo.lock, quickwit/quickwit-indexing/src/source/ingest/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/shard_table.rs
Add a retry layer on top of the failover layer.
Added a bunch of unit tests
=> Implement fetch stream retry

README.md
This PR includes both fixes and improvements to the `README.md` file.
- **Broken `LICENSE.md` Link**: A typo in the `LICENSE.md` link caused it to lead to a 404 error. This has been corrected, and the link now correctly points to the `LICENSE.md` file.
- **Broken Email Link**: The email link was not functioning properly. This has been fixed, and the link now correctly opens a new email draft.
- **Contributing Section**: Direct links have been added to the GitHub issues labeled "Good first issue" and the process to create a fork of Quickwit. These additions will help new contributors get started more easily.
- **Community Section**: The community section has been enhanced with more direct links to relevant resources, making it easier for users to engage with our community.
This PR was …
=> (Minor fixes and improvements) Update LICENSE.md

docs/reference/es_compatible_api.md
Complete the Query DSL doc to make sure it starts by query
The markdown table is formatted by VSCode.
=> Complete the Query DSL doc

quickwit/quickwit-serve/src/lib.rs
=> Computes the rate limiting burst value as a function of the ingest

quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs, quickwit/quickwit-proto/protos/quickwit/metastore.proto, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
- Bugfix in the metastore: an index deletion should result in a contorl plane restarting depending on the nature of the error.
- Added mssing doc in the metastore.
=> Minor fixes & doc

quickwit/quickwit-telemetry/src/sender.rs
=> disable telemetry in tests

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-cluster/src/change.rs, quickwit/quickwit-cluster/src/cluster.rs, quickwit/quickwit-cluster/src/lib.rs, quickwit/quickwit-cluster/src/node.rs, quickwit/quickwit-common/src/pubsub.rs, quickwit/quickwit-common/src/shared_consts.rs, quickwit/quickwit-common/src/tower/rate.rs, quickwit/quickwit-indexing/src/models/shard_positions.rs, quickwit/quickwit-indexing/src/source/ingest/mod.rs, quickwit/quickwit-ingest/Cargo.toml, quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs, quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/models.rs, quickwit/quickwit-ingest/src/ingest_v2/rate_limiter.rs, quickwit/quickwit-ingest/src/ingest_v2/rate_meter.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/ingest_v2/shard_table.rs, quickwit/quickwit-proto/src/ingest/mod.rs, quickwit/quickwit-proto/src/types/mod.rs, quickwit/quickwit-serve/src/lib.rs
- Broadcast shard ingestion throughput and state via Chitchat
- Update router shard table (closed shards only)
=> Broadcast shard ingestion rate and state via Chitchat

quickwit/quickwit-metastore/src/tests/shard.rs
Added some tests for the `open_shards` API.
=> Extend Shard API test suite

quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
Per title. Removes the following warning:
> WARN quickwit_ingest::ingest_v2::broadcast: rate limiter `stackoverflow:01HG1F1XWR77GK86PBZFAXFSEK/_ingest-source/1` not found
=> Initialize rate limiter and meter on ingester init

quickwit/quickwit-proto/build.rs, quickwit/quickwit-proto/protos/quickwit/indexing.proto, quickwit/quickwit-proto/src/indexing/mod.rs, quickwit/quickwit-proto/src/types/mod.rs, quickwit/quickwit-proto/src/types/pipeline_uid.rs
Introduce a `PipelineUid` type for #4191.
Add unit tests
=> Introduce `PipelineUid` type

quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/models.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-ingest/src/ingest_v2/workbench.rs, quickwit/quickwit-proto/protos/quickwit/ingester.proto, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs, quickwit/quickwit-proto/src/ingest/ingester.rs, quickwit/quickwit-proto/src/ingest/mod.rs
=> Create and init shards on ingesters via control plane

quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/ingest_v2/workbench.rs
=> Delete shards from routing table on `ShardNotFound` persist failure

quickwit/quickwit-indexing/src/source/ingest/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-proto/src/ingest/mod.rs, quickwit/quickwit-proto/src/types/position.rs
=> Handle shard not found error in fetch stream and souce

monitoring/grafana/dashboards/ingesters.json, monitoring/grafana/dashboards/searchers.json, quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs, quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/metrics.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/mrecordlog_utils.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/lib.rs, quickwit/quickwit-proto/src/control_plane/mod.rs, quickwit/quickwit-proto/src/ingest/mod.rs
Add request counter and histogram. Track WAL usage.
Checked the metrics are properly exported in Prometheus.
=> Add Prometheus metrics to router and ingester

quickwit/quickwit-serve/src/rest.rs
Trying to fix this issue https://github.com/quickwit-oss/quickwit/issues/4278
=> append extra http headers for any reqeust

quickwit/quickwit-ingest/src/errors.rs, quickwit/quickwit-proto/src/ingest/mod.rs, quickwit/quickwit-search/src/error.rs, quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
https://github.com/quickwit-oss/quickwit/issues/4289
=> add IngestV2Error to IngestServiceError conversion

quickwit/quickwit-serve/src/elastic_search_api/model/field_capability.rs, quickwit/rest-api-tests/scenarii/es_field_capabilities/0001-field-capabilities.yaml
add undocumented `type` in field capabilities
add ignore_unavailable parameter
https://github.com/quickwit-oss/quickwit/issues/4298
=> add undocumented `type` in field capabilities

quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/scheduling_logic.rs
=> bugfix control plane

quickwit/quickwit-jaeger/src/lib.rs, quickwit/quickwit-proto/protos/quickwit/search.proto, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs, quickwit/quickwit-search/src/leaf.rs, quickwit/quickwit-search/src/lib.rs, quickwit/quickwit-search/src/list_fields.rs, quickwit/quickwit-search/src/list_terms.rs, quickwit/quickwit-search/src/root.rs, quickwit/quickwit-search/src/service.rs, quickwit/quickwit-search/src/tests.rs, quickwit/quickwit-serve/src/elastic_search_api/model/field_capability.rs, quickwit/quickwit-serve/src/jaeger_api/rest_handler.rs, quickwit/rest-api-tests/scenarii/es_field_capabilities/0001-field-capabilities.yaml, quickwit/rest-api-tests/scenarii/es_field_capabilities/_setup.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_field_capabilities/_setup.quickwit.yaml, quickwit/rest-api-tests/scenarii/es_field_capabilities/_teardown.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_field_capabilities/_teardown.quickwit.yaml
Prepare for multi otel traces indexes, coming in #4311
=> Allow index patterns in list terms.

quickwit/quickwit-codegen/example/src/codegen/hello.rs, quickwit/quickwit-codegen/example/src/lib.rs, quickwit/quickwit-codegen/src/codegen.rs, quickwit/quickwit-ingest/src/codegen/ingest_service.rs, quickwit/quickwit-metastore/src/metastore/mod.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.indexing.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.router.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs, quickwit/quickwit-serve/src/lib.rs
I attempted to stack two layers (metrics and trace) on a client with `shared_layer` and it did not end well, so I decided to fix this issue. Fixes #3808.
Updated unit tests.
=> Stack layers instead of overriding them

config/quickwit.yaml, docs/configuration/node-config.md, quickwit/Cargo.lock, quickwit/quickwit-codegen/README.md, quickwit/quickwit-codegen/example/Cargo.toml, quickwit/quickwit-codegen/example/src/codegen/hello.rs, quickwit/quickwit-codegen/example/src/lib.rs, quickwit/quickwit-codegen/src/codegen.rs, quickwit/quickwit-config/resources/tests/config/quickwit.json, quickwit/quickwit-config/resources/tests/config/quickwit.toml, quickwit/quickwit-config/resources/tests/config/quickwit.yaml, quickwit/quickwit-config/src/node_config/mod.rs, quickwit/quickwit-config/src/node_config/serialize.rs, quickwit/quickwit-ingest/src/codegen/ingest_service.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-metastore/src/tests/mod.rs, quickwit/quickwit-proto/Cargo.toml, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.indexing.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.router.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs, quickwit/quickwit-search/Cargo.toml, quickwit/quickwit-search/src/client.rs, quickwit/quickwit-serve/src/grpc.rs, quickwit/quickwit-serve/src/lib.rs, quickwit/quickwit-serve/src/search_api/mod.rs
Per title.
Tested manually locally.
=> Make gRPC message size configurable

docs/get-started/tutorials/tutorial-aws-lambda-simple.md
Add missing deploy command and other minor improvments.
=> Fixes and clarifications of the simple Lambda tutorial

docs/reference/aggregation.md
=> document API endpoint for aggs

quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs
fix https://github.com/quickwit-oss/quickwit/issues/4214
=> generate replication seqno just before sending a message

quickwit/quickwit-config/resources/tests/config/quickwit.json, quickwit/quickwit-config/resources/tests/config/quickwit.toml, quickwit/quickwit-config/src/node_config/serialize.rs
Fix a small issue introduced  #4440, but somehow CI has been passing since, and tests started failing in my local dev env only today.
=> Fix index config tests

quickwit/quickwit-common/src/pubsub.rs
Heavy logging has been sufficient to hit the 1sec limit.
=> Increasing pubsub timeout to 10s.

quickwit/quickwit-serve/src/elasticsearch_api/model/cat_indices.rs, quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0021-cat-indices.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/_setup.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/_setup.quickwit.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/_teardown.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/_teardown.quickwit.yaml
=> handle empty indices in cat indices

quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0020-stats.yaml
=> fix empty index in _stats API

quickwit/Cargo.lock, quickwit/quickwit-common/Cargo.toml, quickwit/quickwit-common/src/retry.rs
=> Prevents the exponential backoff from overflowing after 64 attempts.

quickwit/quickwit-search/src/list_fields.rs, quickwit/rest-api-tests/scenarii/es_field_capabilities/0001-field-capabilities.yaml
=> remove field presence in _field_caps

quickwit/quickwit-common/src/stream_utils.rs, quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs, quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-ingest/src/ingest_v2/state.rs, quickwit/quickwit-proto/protos/quickwit/ingester.proto, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs, quickwit/quickwit-serve/src/health_check_api/handler.rs, quickwit/quickwit-serve/src/lib.rs
=> Open WAL asynchronously

docs/distributed-tracing/otel-service.md, docs/get-started/quickstart.md, docs/guides/schemaless.md, docs/ingest-data/ingest-api.md, docs/ingest-data/ingest-local-file.md, docs/log-management/otel-service.md, docs/log-management/send-logs/using-vector.md
suggest better default for commit timeout in doc
=> doc: make commit timeout 10s when no --force, and 30s when --force

docs/configuration/node-config.md
=> doc: fix tab rendering issue

quickwit/Cargo.lock, quickwit/quickwit-cluster/Cargo.toml, quickwit/quickwit-cluster/src/lib.rs, quickwit/quickwit-cluster/src/metrics.rs, quickwit/quickwit-janitor/src/actors/delete_task_service.rs
A counter for sent and received chitchat messages. The point is to detect a network saturation that would result in messages being dropped.
=> Added metrics for chitchat.

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-cluster/Cargo.toml, quickwit/quickwit-cluster/src/lib.rs, quickwit/quickwit-cluster/src/metrics.rs
Per title.
`c test -p quickwit-cluster --lib`
=> Report number of bytes sent/received via gossip in metrics

quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs, quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs, quickwit/quickwit-control-plane/src/model/mod.rs, quickwit/quickwit-control-plane/src/model/shard_table.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/metrics.rs, quickwit/quickwit-ingest/src/ingest_v2/state.rs, quickwit/quickwit-ingest/src/lib.rs, quickwit/quickwit-opentelemetry/src/otlp/logs.rs, quickwit/quickwit-opentelemetry/src/otlp/mod.rs, quickwit/quickwit-opentelemetry/src/otlp/traces.rs, quickwit/quickwit-proto/protos/quickwit/control_plane.proto, quickwit/quickwit-proto/protos/quickwit/ingest.proto, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs, quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.rs, quickwit/quickwit-proto/src/ingest/mod.rs, quickwit/quickwit-proto/src/types/index_uid.rs, quickwit/quickwit-serve/src/lib.rs
Reset shards by asking the control plane which shards to delete or truncate.
=> Reset shards on startup or when WAL is almost full

quickwit/quickwit-serve/src/elasticsearch_api/model/search_query_params.rs, quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs, quickwit/rest-api-tests/scenarii/sort_orders/0001-sort-elasticapi.yaml
remove source in es params (this param does not exist)
remove fields in response (wrong format and ignores parameters)
=> remove source in es params, remove fields in response

quickwit/quickwit-common/src/pubsub.rs, quickwit/quickwit-indexing/src/models/shard_positions.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-serve/src/lib.rs
=> Remove timeout from shard positions callbacks.

quickwit/quickwit-metastore/src/metastore_resolver.rs
=> Add support for gcs file backed metastore.

quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
=> Fix unit test

docs/deployment/deployment-modes.md
outdated info in docs
I'm not sure if 0.8 Q2 is correct
=> update date in docs

quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs, quickwit/quickwit-ingest/src/ingest_v2/idle.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/models.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-ingest/src/ingest_v2/state.rs, quickwit/quickwit-serve/src/lib.rs
Close shards that have not been written to in the last 15 minutes
- Tested locally
=> Close idle shards after 15 minutes

quickwit/quickwit-common/src/tower/metrics.rs
Fix metrics biased by canceled futures.
Added unit test.
=> Emit gRPC metrics on drop

Dockerfile
Tested with `docker build ...` then `docker run ... --version`
=> Add `cURL` to Docker image and update to Debian “bookworm”

config/quickwit.yaml
=> add partial_request_cache_capacity to quickwit.yaml

quickwit/quickwit-ingest/src/ingest_v2/debouncing.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/ingest_v2/routing_table.rs
=> Debounce open shards request to control plane

quickwit/quickwit-config/src/node_config/serialize.rs, quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-control-plane/src/debouncer.rs, quickwit/quickwit-indexing/src/actors/indexing_service.rs, quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs, quickwit/quickwit-integration-tests/src/tests/index_tests.rs, quickwit/quickwit-rest-client/src/rest_client.rs
Re-enabled debouncer and fixed ingest v2 happy path test. `test_single_node_cluster` needs more work, I'll open a separate PR.
=> Re-enable rebuild indexing plan debouncer

quickwit/quickwit-proto/src/search/mod.rs
use `mem::discriminant` instead of custom value
=> use mem::discriminant

quickwit/quickwit-search/src/collector.rs
=> move segment_ord into search_after_order precompute, fix comment

quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/ingest_v2/workbench.rs
Retry on `NoShardsAvailable`. Fix #4681.
Added unit tests and updated current unit tests.
=> Retry on `NoShardsAvailable`

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-ingest/src/ingest_api_service.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/metrics.rs, quickwit/quickwit-ingest/src/ingest_v2/mrecordlog_utils.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-ingest/src/mrecordlog_async.rs, quickwit/quickwit-ingest/src/queue.rs
Per title.
`c test --manifest-path quickwit/Cargo.toml -p quickwit-ingest --lib`
=> Report WAL allocated bytes in Prom metrics

quickwit/quickwit-serve/src/elasticsearch_api/mod.rs, quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
=> handle track_total_size on request body

quickwit/quickwit-cli/src/main.rs
=> Set recursion limit to 256 in quickwit-cli to fix the release image

quickwit/quickwit-common/src/metrics.rs, quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-indexing/src/actors/indexer.rs, quickwit/quickwit-indexing/src/models/indexed_split.rs, quickwit/quickwit-indexing/src/models/processed_doc.rs, quickwit/quickwit-indexing/src/models/raw_doc_batch.rs, quickwit/quickwit-indexing/src/source/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-search/src/thread_pool.rs, quickwit/quickwit-serve/src/decompression.rs
=> Added metrics tracking the memory usage in the index writer.

quickwit/quickwit-common/src/metrics.rs, quickwit/quickwit-common/src/stream_utils.rs, quickwit/quickwit-indexing/src/actors/indexer.rs, quickwit/quickwit-indexing/src/models/processed_doc.rs, quickwit/quickwit-indexing/src/models/raw_doc_batch.rs, quickwit/quickwit-indexing/src/source/ingest/mod.rs, quickwit/quickwit-indexing/src/source/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/fetch.rs, quickwit/quickwit-ingest/src/ingest_v2/metrics.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-proto/src/ingest/ingester.rs, quickwit/quickwit-proto/src/ingest/mod.rs, quickwit/quickwit-serve/src/decompression.rs
Track in-flight data in fetch and multi-fetch streams
Added unit tests for tracked senders.
=> Track in-flight data in fetch and multi-fetch streams

quickwit/Cargo.lock, quickwit/quickwit-common/src/metrics.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/replication.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-proto/src/ingest/ingester.rs, quickwit/quickwit-proto/src/ingest/mod.rs, quickwit/quickwit-serve/src/elasticsearch_api/bulk_v2.rs
Per title.
Checked metrics in Grafana
=> Track bytes in-flight in ingester `persist` and `replicate` methods

quickwit/quickwit-search/src/collector.rs, quickwit/quickwit-search/src/lib.rs, quickwit/quickwit-search/src/top_k_collector.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0008-sort_by.yaml
- **move segment top k collector**
- **specialized top n collection**
=> top n collector specialization

config/tutorials/otel-traces/kafka-source.yaml, quickwit/quickwit-common/src/rate_limited_tracing.rs, quickwit/quickwit-config/src/source_config/mod.rs, quickwit/quickwit-config/src/source_config/serialize.rs, quickwit/quickwit-indexing/src/actors/doc_processor.rs, quickwit/quickwit-opentelemetry/src/otlp/logs.rs, quickwit/quickwit-opentelemetry/src/otlp/mod.rs, quickwit/quickwit-opentelemetry/src/otlp/traces.rs
=> Parse OTLP logs in doc processor

quickwit/quickwit-actors/src/tests.rs, quickwit/quickwit-cli/src/lib.rs, quickwit/quickwit-common/src/stream_utils.rs, quickwit/quickwit-control-plane/src/ingest/wait_handle.rs, quickwit/quickwit-directories/src/hot_directory.rs, quickwit/quickwit-ingest/src/ingest_v2/debouncing.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/ingest_v2/workbench.rs, quickwit/quickwit-metastore/src/metastore/file_backed/lazy_file_backed_index.rs, quickwit/quickwit-metastore/src/metastore/postgres/factory.rs, quickwit/quickwit-search/src/top_k_collector.rs, quickwit/rust-toolchain.toml
=> Update Rust version to 1.77

quickwit/quickwit-storage/src/local_file_storage.rs
Fixes #4834
Not at all, simple string update.
=> Fix error message claiming non-regular files are directories

quickwit/quickwit-common/src/tower/transport.rs, quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-control-plane/src/tests.rs, quickwit/quickwit-integration-tests/Cargo.toml, quickwit/quickwit-serve/src/lib.rs
Per title.
- Verified logs output `2024-03-29T00:38:43.814Z  INFO quickwit_serve: control plane is ready`
=> Fix control plane readiness

quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-control-plane/src/model/mod.rs, quickwit/quickwit-control-plane/src/model/shard_table.rs, quickwit/quickwit-ingest/src/ingest_v2/state.rs
These logs are related to the removal of shards.
=> adding more logs to the control plane.

distribution/ecs/README.md
=> Fix terraform README formatting

docs/configuration/index-config.md, quickwit/quickwit-config/src/index_config/mod.rs
=> Fix misleading docs about timestamp_field location

quickwit/quickwit-search/src/collector.rs
store variable directly instead of `QuickwitCollector`
=> replace QuickwitCollector in IncrementalCollector

quickwit/quickwit-serve/src/metrics.rs, quickwit/quickwit-serve/src/rest.rs
Per title.
Checked metrics in local Grafana dashboard
=> Add method and status code label to HTTP metrics

quickwit/quickwit-cli/src/main.rs, quickwit/quickwit-common/src/metrics.rs
Here is the line:
quickwit_build_info{build_date="2024-04-19T01:24:49Z",commit_hash="d2d5809922a0ef04ec7586048d66db819528c128",target="aarch64-apple-darwin",version="0.8.0-nightly"} 1
=> Added a build_info metric

docs/reference/rest-api.md
fix #4851
~~Describe how you tested this PR.~~
=> update delete query documentation

Makefile, quickwit/Cargo.lock, quickwit/Makefile, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs, quickwit/quickwit-serve/src/elasticsearch_api/bulk_v2.rs, quickwit/quickwit-serve/src/elasticsearch_api/model/bulk_body.rs, quickwit/quickwit-serve/src/elasticsearch_api/model/bulk_query_params.rs, quickwit/quickwit-serve/src/elasticsearch_api/model/cat_indices.rs, quickwit/quickwit-serve/src/elasticsearch_api/model/error.rs, quickwit/quickwit-serve/src/elasticsearch_api/model/mod.rs, quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs, quickwit/rest-api-tests/run_tests.py, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/0001-malformed-action.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/0002-validation-failed-index-missing.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/0003-validation-failed-no-requests-added.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_ctx.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_ctx.quickwit.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_ctx.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/0001-index-not-found.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_ctx.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_ctx.quickwit.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_ctx.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_setup.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_teardown.elasticsearch.yaml
Per title.
- added integration tests
=> Populate `items` field from Elastic bulk error

quickwit/quickwit-search/src/leaf.rs
fix #4935 
cc @fmassot 
tested manually. i tried to add some basic regression test, though testing the actual behaviour is kinda hard. It depends on having a request matching only some documents, with time bounds matching others, and importantly not matching everything (or we don't emit time bounds).
=> fix timestamp rewrite on boolean should

quickwit/quickwit-serve/src/elasticsearch_api/filter.rs, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/0004-put-request.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_setup.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_setup.quickwit.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_teardown.elasticsearch.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_teardown.quickwit.yaml, quickwit/rest-api-tests/scenarii/sort_orders/_teardown.quickwit.yaml
likely fix #4995
added integration test, passing on both quickwit and elastic
=> support bulk ingest over PUT

distribution/ecs/README.md, distribution/ecs/quickwit/variables.tf, docs/deployment/node-sizing.md, docs/get-started/node-sizing.md
Add a doc entry to help users dimension their QW clusters.
=> Initiate node sizing docs

docs/configuration/metastore-config.md, docs/configuration/node-config.md
Fixes some inacuracies regarding the polling interval configurations for file backed metastores.
=> Fix polling interval docs

docs/configuration/source-config.md
The sentence was a bit ambiguous.
NA
=> Clarify docs about Kafka enable.auto.commit

quickwit/Cargo.lock, quickwit/Cargo.toml
=> patch one_shot dependency

quickwit/quickwit-query/src/query_ast/user_input_query.rs, quickwit/rest-api-tests/docker-compose.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/0005-query_string_query.yaml
fix #5021
pulled integration test from #5022, added unit test in the query parser here https://github.com/quickwit-oss/tantivy/pull/2416
=> support range query over default field

quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs, quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/models.rs, quickwit/quickwit-ingest/src/ingest_v2/state.rs
Per title. Fixes #5065.
Updated unit tests.
=> Start advertising shards on persist, fetch, or recovery

docs/reference/aggregation.md
https://github.com/quickwit-oss/quickwit/issues/5120
=> Update term aggregation order docs

quickwit/quickwit-serve/src/elasticsearch_api/model/error.rs, quickwit/quickwit-serve/src/rest_api_response.rs
Logging internal server error causes.
=> Logging internal server error causes.

quickwit/quickwit-common/src/metrics.rs, quickwit/quickwit-serve/src/metrics_api.rs
This tweaks the logic behind the `/metrics` endpoint in order to properly log encoding errors. It also switches the existing code to use a pre-allocated String buffer, skipping some small reallocations while encoding and avoiding parsing already valid UTF-8 content.
=> serve/rest: improve prometheus metrics encoding

quickwit/Cargo.lock, quickwit/quickwit-control-plane/src/model/shard_table.rs
1 shard every 2 seconds vs 5 seconds before.
=> More aggressive shard scale up settings.

quickwit/quickwit-ingest/src/ingest_v2/ingester.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/ingest_v2/routing_table.rs
Consider ingesters returning `ResourceExhausted` temporarily unavailable and report them as such, forcing the CP to open a new shard on another ingester. In addition, ingesters now reject `InitShards` requests when their WAL is full.
Added and updated unit tests.
=> Consider ingesters returning `ResourceExhausted` temporarily unavailable

quickwit/quickwit-common/src/shared_consts.rs, quickwit/quickwit-config/src/cluster_config/mod.rs, quickwit/quickwit-config/src/node_config/mod.rs, quickwit/quickwit-control-plane/src/control_plane.rs, quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs, quickwit/quickwit-ingest/src/lib.rs, quickwit/quickwit-serve/src/ingest_api/rest_handler.rs, quickwit/quickwit-serve/src/lib.rs
=> Plugging the shard throughput limit configuration to the ingest

docs/configuration/index-config.md, quickwit/quickwit-query/src/tokenizers/mod.rs
=> add raw_lowercase tokenizer

quickwit/quickwit-query/src/query_ast/wildcard_query.rs, quickwit/quickwit-query/src/tokenizers/mod.rs, quickwit/quickwit-query/src/tokenizers/tokenizer_manager.rs, quickwit/quickwit-search/src/root.rs
fix normalizer used for the `raw_lowercase` tokenanizer
related to #3918
=> wildcard casing

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit/quickwit-ingest/src/ingest_v2/mod.rs, quickwit/quickwit-ingest/src/ingest_v2/router.rs, quickwit/quickwit-ingest/src/ingest_v2/routing_table.rs, quickwit/quickwit-ingest/src/ingest_v2/workbench.rs
=> Avoid retrying right away on shards that have been rate limited in the

distribution/lambda/README.md, distribution/lambda/cdk/cli.py, distribution/lambda/cdk/stacks/examples/mock_data_stack.py, quickwit/Cargo.lock, quickwit/quickwit-lambda/Cargo.toml
Closes https://github.com/quickwit-oss/quickwit/issues/4734 
https://github.com/quickwit-inc/terraform/actions/runs/10158775985
=> Lambda maintenance

CONTRIBUTING.md
close: #5322 
I realized that some commands are wrong in the guide.
I corrected them in this PR.
=> Fix wrong command names in CONTRIBUTING.md

docs/get-started/tutorials/tutorial-hdfs-logs.md
close: #5320 
I've been playing with Quickwit with the documents and found an improvement in the doc.
I fixed a link here.
=> Make the link to the correct page

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-query/src/query_ast/range_query.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0007-range_queries.yaml, quickwit/rest-api-tests/scenarii/es_compatibility/_setup.quickwit.yaml
enable range queries on str based fast field queries
update tantivy
closes https://github.com/quickwit-oss/quickwit/issues/5091
closes https://github.com/quickwit-oss/quickwit/issues/5090
=> enable str fast field range queries

.github/actions/cargo-build-macos-binary/action.yml
=> Fix x86 macos nightly

quickwit/quickwit-search/src/client.rs, quickwit/quickwit-search/src/metrics.rs
Add some basic search metrics. Will add some more in follow up PR.
=> Add some additional search metrics

quickwit/quickwit-cluster/src/cluster.rs, quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs, quickwit/quickwit-indexing/src/actors/indexing_service.rs, quickwit/quickwit-indexing/src/models/indexing_statistics.rs
=> Adding fingerprint to task in cluster state.

docs/configuration/node-config.md, docs/get-started/tutorials/trace-analytics-with-grafana.md, docs/reference/metrics.md
=> document searcher config request_timeout_secs

quickwit/quickwit-config/src/source_config/mod.rs
Allow to use a Pulsar instance which enable TLS
On our internal Pulsar cluster
=> Fix pulsar uri scheme

quickwit/quickwit-actors/src/mailbox.rs
The goal here is to offer a way to spot a possible leak (diverging number of actors).
=> Adding an actor inbox gauge.

quickwit/quickwit-indexing/src/source/pulsar_source.rs
gracefully close the Pulsar consumer
=> Fix pulsar finalize

docs/reference/aggregation.md
document missing parameter and improve clarity
closes #5496
=> document missing agg parameter

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-cluster/src/cluster.rs, quickwit/quickwit-serve/src/developer_api/server.rs
=> Updating chitchat

quickwit/quickwit-index-management/src/garbage_collection.rs
hammering the metastore on airmail.
By default it is disabled.
This feature can be enabled with "QW_MAX_SPLIT_DELETION_RATE_PER_SEC".
=> Adding some kind of throttling on the janitor to prevent it from

quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-doc-mapper/Cargo.toml, quickwit/quickwit-doc-mapper/benches/doc_to_json_bench.rs, quickwit/quickwit-doc-mapper/benches/routing_expression_bench.rs
refactor bench and add dynamic mapping bench
=> extend json parse bench

quickwit/quickwit-serve/src/jaeger_api/parse_duration.rs
https://github.com/quickwit-oss/quickwit/issues/5511
=> bugfix jaeger duration parse error

quickwit/quickwit-storage/src/cache/byte_range_cache.rs, quickwit/quickwit-storage/src/cache/memory_sized_cache.rs, quickwit/quickwit-storage/src/file_descriptor_cache.rs, quickwit/quickwit-storage/src/metrics.rs, quickwit/quickwit-storage/src/split_cache/split_table.rs
add metrics for cache eviction
=> add eviction metrics to caches

quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
Per title.
Ran `quickwit-metastore` test suite with the `postgres` feature enabled and checked the logging output.
=> Log PostgreSQL metastore error

quickwit/quickwit-cli/src/tool.rs, quickwit/quickwit-indexing/src/actors/mod.rs, quickwit/quickwit-indexing/src/lib.rs
wait for merge to complete before exiting
fix #5494
tested manually that the problem is no longer reproducible
=> wait for merge at end of local ingest

docs/reference/rest-api.md
=> Add missing Ingest API section header

docs/reference/metrics.md
Quick document fixup - the metric name was incorrect.
Used Grafana judiciously 😄
=> Fix metric name in docs

quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs, quickwit/quickwit-integration-tests/src/tests/basic_tests.rs, quickwit/quickwit-integration-tests/src/tests/ingest_v1_tests.rs, quickwit/quickwit-integration-tests/src/tests/ingest_v2_tests.rs, quickwit/quickwit-integration-tests/src/tests/mod.rs, quickwit/quickwit-integration-tests/src/tests/no_cp_tests.rs, quickwit/quickwit-integration-tests/src/tests/otlp_tests.rs, quickwit/quickwit-integration-tests/src/tests/sqs_tests.rs, quickwit/quickwit-integration-tests/src/tests/update_tests/doc_mapping_tests.rs, quickwit/quickwit-integration-tests/src/tests/update_tests/mod.rs, quickwit/quickwit-integration-tests/src/tests/update_tests/restart_indexer_tests.rs, quickwit/quickwit-integration-tests/src/tests/update_tests/search_settings_tests.rs, quickwit/quickwit-metastore/src/metastore/control_plane_metastore.rs, quickwit/quickwit-serve/src/lib.rs
Closes https://github.com/quickwit-oss/quickwit/issues/5570
Integration tests
=> Fix and test clusters without control plane

docs/reference/query-language.md, quickwit/quickwit-doc-mapper/src/query_builder.rs, quickwit/rest-api-tests/scenarii/es_compatibility/0005-query_string_query.yaml
=> Add wildcard docs

quickwit/Cargo.toml, quickwit/deny.toml, quickwit/quickwit-ui/package.json
Probably doesn't matter because we don't publish QW as a lib, but it doesn't hurt being consistent.
=> Fix license field in Cargo toml

docs/configuration/index-config.md, docs/ingest-data/ingest-api.md, quickwit/quickwit-doc-mapper/src/doc_mapper/field_mapping_entry.rs
Closes https://github.com/quickwit-oss/quickwit/issues/5682
=> Fix the docs for json and dynamic fields

.github/workflows/ci.yml
Lint CI is currently broken: https://github.com/quickwit-oss/quickwit/actions/runs/13495946893/job/37703419643?pr=5690
=> Pin cargo deny version

quickwit/quickwit-indexing/src/actors/uploader.rs
The upload actor spawns a task that is never joined, meaning that all errors go unnoticed. 
N/A, only adding some rare extra logs.
=> Add logs when upload task fails

LICENSE-3rdparty.csv, quickwit/Cargo.lock, quickwit/Cargo.toml, quickwit/quickwit-serve/Cargo.toml, quickwit/quickwit-serve/src/grpc.rs, quickwit/quickwit-serve/src/lib.rs
=> Implement gRPC health service

.github/workflows/publish_docker_images.yml, Dockerfile, distribution/docker/ubuntu/Dockerfile, docs/get-started/installation.md
=> Fix remaining references to AGPL 

docs/overview/architecture.md
=> Fix typo -- scehduler Closes #5744

quickwit/quickwit-cli/src/tool.rs, quickwit/quickwit-cluster/src/change.rs, quickwit/quickwit-cluster/src/cluster.rs, quickwit/quickwit-cluster/src/grpc_gossip.rs, quickwit/quickwit-cluster/src/grpc_service.rs, quickwit/quickwit-cluster/src/lib.rs, quickwit/quickwit-cluster/src/node.rs, quickwit/quickwit-common/src/tower/mod.rs, quickwit/quickwit-common/src/tower/transport.rs, quickwit/quickwit-config/src/lib.rs, quickwit/quickwit-config/src/node_config/mod.rs, quickwit/quickwit-config/src/serde_utils.rs, quickwit/quickwit-lambda/src/indexer/ingest/helpers.rs
By default, the behavior is unchanged.
=> Adding keep alive setting.

quickwit/quickwit-opentelemetry/src/otlp/logs.rs, quickwit/quickwit-opentelemetry/src/otlp/traces.rs, quickwit/quickwit-storage/src/cache/byte_range_cache.rs
=> Disabling clippy on lints that we cannot do anything about.

quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/scheduling_logic.rs
This if was unintentionally left out of https://github.com/quickwit-oss/quickwit/pull/5791, sorry
=> Fix missing condition for scaling warning

quickwit/quickwit-indexing/src/actors/merge_planner.rs, quickwit/quickwit-indexing/src/merge_policy/const_write_amplification.rs, quickwit/quickwit-indexing/src/merge_policy/stable_log_merge_policy.rs
Closes https://github.com/quickwit-oss/quickwit/issues/5810
=> Fix panic when changing merge policy configs

quickwit/quickwit-common/src/runtimes.rs
This changes the result for 3vcpu and 2vcpus.
In that case, dedicated one vcpus to non-blocking tasks was judged overkill.
=> Tweaking the number of threads to attribute to the different runtimes

quickwit/quickwit-search/src/list_fields.rs
- Performs the removal of the `_dynamic.` prefix on field names before sorting.
- Runs the merges in the searcher thread pool
In progress
=> Fix leaf list fields merging logic
