quickwit-oss/quickwit

.github/workflows/ci.yml

Restrict CI to Rust files so that CI does not run unnecessarily.

Restrict CI to Rust files

---

storage/src/error.rs
storage/src/lib.rs
storage/src/object_storage/error.rs
storage/src/object_storage/s3_compatible_storage.rs
storage/src/ram_storage.rs
storage/src/storage.rs

Backporting this patch from the Common Crawl repo. I fixed a few things while I was at it (doc, missing retries).
The implementation is trivial for ram storage. For S3, we issue a head object request. A `404` or `NoSuchKey` response means that the object does not exist.
It is used in CommonCrawl to check for the presence of a success file.
The patch was tested while I was building the Common Crawl index. That's how I found out about the Rusoto bug.

Add `exists` method to `Storage` trait

---

quickwit-cli/Cargo.toml
quickwit-cli/src/cli.yaml
quickwit-cli/src/main.rs

- generate CLI from YAML file
- set up CLI for the `new`, `index`, `search` and `delete` commands
- pass CLI args to placeholder functions
In debug mode, I ran all the commands adding arguments one by one. For instance:
```bash
RUST_LOG=debug cargo run -- index --index-path ~/foo --input-path ~/bar --temp-dir ~/tmp --num-threads 4 --heap-size 4gib --overwrite
May 14 12:23:50.563 DEBUG quickwit_cli: indexing index_path="/home/guilload/foo" input_path="/home/guilload/bar" temp_dir="/home/guilload/tmp" num_threads=4 heap_size=4294967296 overwrite=true  
```

Implement CLI  subcommand stubs

---

quickwit-metastore/Cargo.toml
quickwit-metastore/src/error.rs
quickwit-metastore/src/lib.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs

Add a single file meta store implementation.
Simply serialize all of the splits associated with a single index into one large JSON file.
#12

Add single file metastore implementation

---

Cargo.toml
quickwit-cli/src/main.rs
quickwit-hot-directory/Cargo.toml
quickwit-hot-directory/src/caching_directory.rs
quickwit-hot-directory/src/debug_proxy_directory.rs
quickwit-hot-directory/src/hot_directory.rs
quickwit-hot-directory/src/lib.rs
quickwit-hot-directory/src/storage_directory.rs

We need the hot-directory implementation in the cli
Added `quickwit-hot-directory` from quickwit barrel

Add hot-directory module from barrel

---

quickwit-metastore/src/error.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs

Fix metastore bugs.
Fixed a bug that the internal state of the metastore is updated even when writing to the storage fails.
In addition, when an existing index is specified in the argument of the `create_index` function of `Metastore` trait, the index has opened, but the function name does not match the behavior, so the `create_index` function and the `open_index function` are now prepared separately.
Ran `cargo test test_single_file_metastore`

Fix metastore bugs

---

Cargo.toml
quickwit-directories/Cargo.toml
quickwit-directories/src/caching_directory.rs
quickwit-directories/src/debug_proxy_directory.rs
quickwit-directories/src/hot_directory.rs
quickwit-directories/src/lib.rs
quickwit-directories/src/storage_directory.rs

- Renamed quickwit-hotdirectory into quickwit-directories.
- Added docstring and lint rule to check for missing docstrings.

Renamed qwt-hotdirectory into qwt-directories and added docstring.

---

quickwit-cli/src/cli.yaml
quickwit-cli/src/main.rs

This changes the type of URI parameters in arguments to String instead of Pathbuf, and some minor code quality stuff.
- in tracing the % and ? modifier are indented as follow
`key = ?value` as opposed to `key =? value`
- removing unwrap that are justified but not required. (Being able to grep for unwrap and expect is quite comfortable.)

Minor fixes in quickwit-cli

---

quickwit-metastore/src/error.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs

If the index is not loaded into the cache, load it from storage in a lazy manner.
https://github.com/quickwit-inc/quickwit/issues/50
The open_index function of the `Metastore` trait will be moved to the private function of the `SingleFileMetastore`.
Change functions that operate splits, such as `list_splits`, `stage_split`, `publish_split`, `mark_split_as_deleted` and `delete_split` to lazily load the index's metadata set into the cache if the index is not open.
Ran `cargo test -- --nocapture test_single_file_metastore`

If the index is not loaded into the cache, load it from storage.

---

quickwit-metastore/src/metastore/single_file_metastore.rs

Delete async from SingleFileMetastore::new().
It doesn't have to be async.
Ran `cargo test -- --nocapture test_single_file_metastore`

Delete async from SingleFileMetastore::new()

---

quickwit-storage/src/lib.rs
quickwit-storage/src/local_file_storage.rs
quickwit-storage/src/storage.rs

[Issues-59](https://github.com/quickwit-inc/quickwit/issues/59)
Implemented fix for LocalFileStorage to transparently create & remove intermediate directories

Fixed LocalFileStorage bug

---

quickwit-storage/src/lib.rs
quickwit-storage/src/prefix_storage.rs
quickwit-storage/src/ram_storage.rs

The current RamStorageFactory only resolves storage on this single uri `ram://`
@fulmicoton  has implemented a PrefixStorage that is used now in the RamStorageFactory in order to support multiple uri 
for RamStorage.

Prefix Storage Implementation

---

quickwit-cli/Cargo.toml
quickwit-cli/src/main.rs
quickwit-core/src/index.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs

Following the index metadata change in #55, this PR adds an Index uri to the index metadata and makes it possible for users to specify an index_uri in the IndexMetadata passed in the create_index API.

Changes in create_index and IndexMetada API

---

quickwit-cli/src/main.rs
quickwit-core/src/index.rs
quickwit-core/src/indexing/index.rs
quickwit-doc-mapping/Cargo.toml
quickwit-doc-mapping/src/all_flatten_mapper.rs
quickwit-doc-mapping/src/default_mapper.rs
quickwit-doc-mapping/src/lib.rs
quickwit-doc-mapping/src/mapper.rs
quickwit-doc-mapping/src/wikipedia_mapper.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs

This PR aims at solving issue #28
It's definitely not the implementation that we target but there is the trait and basic implementations that we can use to index wikipedia.
This will be followed by another PR for the full implementations of default doc mapper and all flatten doc mapper.

Add doc mapper basic implementations

---

quickwit-core/src/indexing/document_indexer.rs
quickwit-core/src/indexing/split.rs
quickwit-core/src/indexing/split_finalizer.rs

The indexing needed some enhancements
Changed split publishing to happen at the end but still need to be atomic [see](https://github.com/quickwit-inc/quickwit/issues/71)
Run the command `quickwit-cli index --index-uri 'file://./data' --input-path ./wiki-articles-10000.json`

Publish splits at the end

---

quickwit-cli/src/cli.yaml
quickwit-cli/src/main.rs
quickwit-doc-mapping/src/default_mapper.rs
quickwit-doc-mapping/src/mapper.rs

We need to support doc mapper options in CLI when creating an index
[Issue 79](https://github.com/quickwit-inc/quickwit/issues/79)
Added changes to parse and extract 
- Doc mapper type  
- Doc mapper configuration path
Ran the create command

Added doc mapper options CLI

---

quickwit-cli/src/main.rs
quickwit-core/src/index.rs
quickwit-core/src/indexing/index.rs
quickwit-doc-mapping/src/default_mapper.rs
quickwit-doc-mapping/src/mapper.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs

The metastore needs to store the document mapper. 
[Issue 80](https://github.com/quickwit-inc/quickwit/issues/80)
- Add serialization attributes to store document mapper type in the index metadata
- Refactored `create_index` and `index_data` interface
Run the local command

Persist doc mapper In IndexMetadata

---

quickwit-core/src/indexing/document_indexer.rs
quickwit-core/src/indexing/index.rs
quickwit-core/src/indexing/split.rs
quickwit-core/src/indexing/split_finalizer.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs

We need a way in the Metastore to have an all-or-nothing behavior during split publishing. 
[See Issue 71](https://github.com/quickwit-inc/quickwit/issues/71)
- Changed metastore publish split interface to accepts multiple split at once.
- Updated indexing command to use this new interface 
Run the create & index command on a local wikipedia corpus.
`cargo run -- new --index-uri file://./data --no-timestamp-field --doc-mapper-type wikipedia`
`cargo run -- index --index-uri file://./data --input-path ./wiki-articles.json`

Atomically publish splits

---

quickwit-core/src/indexing/document_indexer.rs
quickwit-doc-mapping/Cargo.toml
quickwit-doc-mapping/src/default_mapper.rs
quickwit-doc-mapping/src/wikipedia_mapper.rs

Currently, the indexing command was faking documents.
Removed the `todos` to replace with the real `DocMapper` from the metastore.
Run the create & index command on a local Wikipedia corpus.
`cargo run -- new --index-uri file://./data --no-timestamp-field --doc-mapper-type wikipedia`
`cargo run -- index --index-uri file://./data --input-path ./wiki-articles.json`
or
`cargo run -- new --index-uri s3://quickwit-dev/evance/data --no-timestamp-field --doc-mapper-type wikipedia`
`cargo run -- index --index-uri s3://quickwit-dev/evance/data --input-path ./wiki-articles.json`
Note: *This could be a good opportunity to try indexing the Wikipedia corpus on our main branch now*

Integrated DocMapper into indexing

---

quickwit-cli/src/main.rs
quickwit-core/src/indexing/document_indexer.rs
quickwit-storage/src/local_file_storage.rs

A useless split folder is created in the indexing target folder after the index command.
[See Issue 92](https://github.com/quickwit-inc/quickwit/issues/92)
- Removed the temperary fix we previously had in `SingleFileStorageFactory::from_uri()` 
- simplified last split sending code
Changed the number of docs per split and indexed wikipedia.json on file:// and s3

Remove dangling split folder

---

quickwit-cli/Cargo.toml
quickwit-cli/src/cli.yaml
quickwit-cli/src/main.rs
quickwit-core/Cargo.toml
quickwit-core/src/indexing/document_indexer.rs
quickwit-core/src/indexing/index.rs
quickwit-core/src/indexing/split.rs
quickwit-core/src/lib.rs
quickwit-core/src/test_utils.rs

This PR adds a TestIndex struct that makes unit testing simpler.
To make it possible it, the temp_dir is passed as `Arc<TempDir>` in order to rely on RIIA to remove this scratch directory.

Added a TestIndex struct to make our test more testable.

---

quickwit-metastore/src/metastore/single_file_metastore.rs
quickwit-search/src/lib.rs

[See Issue](https://github.com/quickwit-inc/quickwit/issues/104)
implemented a simple way of return lower/upper bounds as i64::MIN and i64::MAX

Half-open time interval

---

installer
installer.sh

[See Issue 154](https://github.com/quickwit-inc/quickwit/issues/154)
Implement packaging via shell script that can be used to download the latest stable release of `quickwit-cli` binary
The following command was run on Ubuntu, Macos
```bash
curl -L https://raw.githubusercontent.com/quickwit-inc/quickwit/fix-issue-154/installer | sh
```
- We still need to test on more machines to build for other CPU type/architecture 
- We currently only have these binaries:
quickwit-cli-aarch64-apple-darwin
quickwit-cli-x86_64-apple-darwin
quickwit-cli-x86_64-unknown-linux-gnu

Package Installer

---

Cargo.toml
quickwit-cli/Cargo.toml
quickwit-cli/src/main.rs
quickwit-serve/Cargo.toml
quickwit-serve/src/lib.rs
quickwit-telemetry/Cargo.toml
quickwit-telemetry/src/lib.rs
quickwit-telemetry/src/payload.rs
quickwit-telemetry/src/sender.rs
quickwit-telemetry/src/sink.rs

This PR adds a telemetry sender.
By design it cannot send more than 10 events a minute and do one request per minute.
The information that is being send can be eyeball in a single file.
If it fails, it does so silently.
Using npx http-echo-server and by hardcoding the URL to http://localhost:3000

Added a function to send telemetry to Quickwit's server.

---

quickwit-cli/Cargo.toml
quickwit-cli/tests/cli.rs
quickwit-cli/tests/helpers.rs

Search and serve commands need to be tested in the integration tests. [See issue 161](https://github.com/quickwit-inc/quickwit/issues/161)
Added changes to tests for:
- CLI search
- Serve & API seach

Serve & Search in integration tests

---

quickwit-common/src/lib.rs
quickwit-storage/src/object_storage/s3_compatible_storage.rs

Fix invalid index uri error message [See](https://github.com/quickwit-inc/quickwit/issues/132)
Implemented validation enforcing index uri format.
refactored s3Compatible `parse_split_uri` to `parse_uri`

Index Uri error message

---

.github/workflows/publish.yml
installer
quickwit-telemetry/Cargo.toml

We need to automate building Quickwit binaries build. [See](https://github.com/quickwit-inc/quickwit/issues/168)
using CI and `quickwit-inc/upload-to-github-release@v1` to upload the binaries.
Testing the resulting binaries on platforms I have: macos-10.15, ubuntu-20.04

Automate Binary Build

---

quickwit-telemetry/src/sink.rs

It may be difficult for users to identify quickwit.dev as one of our official domain.
The telemetry domain should lead to our official domain.

Using telemetry.quickwit.io instead of telemetry.quickwit.dev

---

quickwit-cli/src/cli.yaml
quickwit-cli/src/main.rs

Automatically generate host key path.
See #246.
Closes #246.
Automatically generate the host key path from `--host-key-path-prefix`, `--host` and `--port`.
When run `quickwit serve --host=0.0.0.0 --index-uris=file:///tmp/quickwit/indices/hdfslogs-idx --port=8080`, the host key file will be created at `/tmp/quickwit-host-key-0.0.0.0-8080`.
`cargo test -- --nocapture test_parse_serve_args`

Automatically generate host key path.

---

quickwit-cli/src/cli.yaml
quickwit-cli/src/main.rs
quickwit-cli/tests/cli.rs

Rename CLI option to singular.
See #245.
`cargo test -- --nocapture test_parse_serve_args`
Closes #245

Rename CLI option to singular.

---

quickwit-cli/src/main.rs
quickwit-telemetry/src/lib.rs
quickwit-telemetry/src/sender.rs

Closes https://github.com/quickwit-inc/quickwit/issues/253
- Added about text to the CLI that also make mention of the telemetry if enabled
```
./quickwit
Quickwit CLI 0.1.0
Quickwit, Inc. <hello@quickwit.com>
Indexing your large dataset on object storage & making it searchable from the command line.
Telemetry Enabled
USAGE:
...
```

Display CLI metadata

---

quickwit-index-config/src/default_index_config/default_config.rs
quickwit-search/src/collector.rs
quickwit-search/src/service.rs

Closes #272 
The ordering was inverted in the Order trait, but inverted again in the PartialOrder trait too.

Fixing topK collection in QuickwitCollector #272

---

quickwit-serve/src/lib.rs

#267 
If its own address is included in the `--peer-seed`, skip it.
Closes #267

Fix bug in peer seed option.

---

Cargo.lock
quickwit-index-config/src/error.rs
quickwit-metastore/src/metastore_resolver.rs
quickwit-search/src/client_pool.rs
quickwit-search/src/client_pool/search_client_pool.rs
quickwit-search/src/error.rs
quickwit-search/src/root.rs
quickwit-search/src/service.rs
quickwit-serve/src/error.rs
quickwit-serve/src/grpc_adapter.rs
quickwit-serve/src/rest.rs
quickwit-storage/Cargo.toml
quickwit-storage/src/error.rs
quickwit-storage/src/storage_resolver.rs

Closes #269.
SearchError are JSON serialized automatically by the grpc adapter.
Upon one leaf failure the whole request now fails (before it was just ignore the single leaf error).
We do not hold the search pool lock forever in the root and in the assign_client method.

Improves Error handling and different bugs.

---

quickwit-search/src/client.rs
quickwit-search/src/client_pool.rs
quickwit-search/src/client_pool/search_client_pool.rs
quickwit-search/src/root.rs

add wrapped client with socket_addr to always have the context to which a client connects to.

add wrapped client with socket_addr

---

docs/reference/cli.md
docs/reference/telemetry.md
quickwit-cli/src/cli.yaml

I wish we owned `quickwit.com` but for now, we'll have to do with `.io` :)

Fix Quickwit domain name

---

quickwit-proto/proto/search_api.proto
quickwit-proto/src/quickwit.rs
quickwit-search/src/client_pool/search_client_pool.rs
quickwit-search/src/collector.rs
quickwit-search/src/leaf.rs
quickwit-search/src/root.rs

extend leaf return value to return aggregated errors
wrap tonic error to add affected split_ids
add error analyzer
This PR is incomplete for retries, the anyhow error needs to be switched to thiserror in order to return more context.
To avoid merge conflicts, I'll merge this first

collect search into results per node

---

quickwit-cli/src/cli.yaml
quickwit-cli/src/lib.rs
quickwit-cli/src/main.rs
quickwit-cli/tests/cli.rs
quickwit-core/src/index.rs
quickwit-core/src/indexing/index.rs
quickwit-core/src/indexing/mod.rs
quickwit-core/src/indexing/split.rs
quickwit-core/src/lib.rs
quickwit-telemetry/src/payload.rs

Closes https://github.com/quickwit-inc/quickwit/issues/207
Add `gc` command that removes old staged and deleted split files from the index.
- Changing manually some split state from the metastore file and running the `gc` command.

Add gc (garbage collect) command

---

Cargo.lock
quickwit-cli/Cargo.toml
quickwit-cli/src/cli.yaml
quickwit-cli/src/lib.rs
quickwit-cli/src/main.rs
quickwit-cli/tests/cli.rs
quickwit-core/src/index.rs
quickwit-metastore/Cargo.toml
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs
quickwit-search/src/root.rs

Closes https://github.com/quickwit-inc/quickwit/issues/320
- Added `update_timestamp`  member to `SplitMetadata` for tracking when the split was last updated in the metastore
- Added a `grace-period` flag to the `gc` command (default is `1h` 1 hour)
- Supported grace-period format: `[0-9]+[smhd]`
- 2s -> 2 seconds (Not sure allowing seconds, but it was useful for testing)
- 2m -> 2 minutes
- 2h -> 2 hours
- 2d -> 2 days
Run the gc command while poking around the metastore file
`./quickwit gc --index-uri file://home/evance/quickwit/data --grace-period 10m`

Add garce-period flag to gc command

---

quickwit-cluster/src/cluster.rs

https://github.com/quickwit-inc/quickwit/issues/333
Wait for a small amount of time that the message sent and received that the member left the cluster as a temporary fix. 
```
cargo test -- --nocapture  test_cluster_multiple_node
```

Add sleep for leaving the cluster.

---

quickwit-cli/src/lib.rs
quickwit-cli/tests/cli.rs
quickwit-proto/proto/search_api.proto
quickwit-proto/src/quickwit.rs
quickwit-search/src/client_pool.rs
quickwit-search/src/client_pool/search_client_pool.rs
quickwit-search/src/collector.rs
quickwit-search/src/error.rs
quickwit-search/src/leaf.rs
quickwit-search/src/lib.rs
quickwit-search/src/root.rs
quickwit-serve/src/rest.rs

add retry mechnism for failed splits
Retry nodes are either all nodes in case all requests failed or only the (partial successfull) nodes.
When there are issue regarding caching, this retry logic may not work well. When a node partially fails, the split will choose the same node again, because the same algorithm (rendezvous hashing) is used.

add retry mechanism

---

docs/reference/cli.md
docs/reference/telemetry.md
quickwit-telemetry/src/lib.rs

- Rename `DISABLE_QUICKWIT_TELEMETRY` env variable to `QUICKWIT_DISABLE_TELEMETRY`
- Document env variables in CLI reference

Rename and document environment variables

---

.github/workflows/dockerhub.yaml

Moving to the `quickwit` org on Docker Hub.
You can't create an access token at the org level on Docker Hub, so `DOCKERHUB_USERNAME` is actually my personal Docker Hub username... and the publish step pushes on the `quickwit/quickit` repo.

Update Docker Hub workflow

---

quickwit-storage/src/object_storage/s3_compatible_storage.rs

https://github.com/quickwit-inc/quickwit/issues/259
Change credential timeout to 5secs from the default (30secs).
Rename the credential file to a different name, and then run the following command:
```
cargo r new --index-uri s3://quickwit-dev/my-hdfs --index-config-path ./hdfslogs_index_config.json --overwrite
```
Closes #259

Change credential timeout.

---

quickwit-core/src/index.rs
quickwit-core/src/indexing/document_indexer.rs
quickwit-core/src/test_utils.rs
quickwit-directories/src/caching_directory.rs
quickwit-directories/src/hot_directory.rs
quickwit-index-config/src/default_index_config/default_config.rs
quickwit-index-config/src/default_index_config/field_mapping_entry.rs
quickwit-index-config/src/query_builder.rs
quickwit-metastore/src/metastore/single_file_metastore.rs
quickwit-metastore/src/metastore_resolver.rs
quickwit-search/src/client_pool/search_client_pool.rs
quickwit-search/src/collector.rs
quickwit-search/src/leaf.rs
quickwit-serve/src/lib.rs
quickwit-storage/src/cache/in_ram_slice_cache.rs
quickwit-storage/src/cache/storage_with_cache.rs

Following the release of Rust 1.54, I fixed a bunch of new Clippy warnings and replaced some calls to `map` with `into_keys()` or `into_values()` wherever possible.
I suspect this will PR will require an update of the builder image to pass CI.

Upgrade to Rust 1.54

---

docs/getting-started/quickstart.md

installer does not install in PATH
Closes #361
To be honest, it hasn't. Looked for a `make doc` or some kind of way to run the documentation localy without taking too much time and stopped here :)  I checked the output md was correct.

lint(quickstart): Invoke command with ./

---

Cargo.lock
quickwit-index-config/Cargo.toml
quickwit-index-config/src/default_index_config/default_config.rs
quickwit-index-config/src/default_index_config/field_mapping_entry.rs
quickwit-index-config/src/default_index_config/field_mapping_type.rs

Code cleanup
I am not a fan of the following pattern, which needlessly creates an intermediate vector for error handling purposes:
```rust
values
.iter()
.map(...)
.collect::<Result<Vec<_>, _>>()?
.into_inter()
.flatten()
.collect()
```
Instead, let's rely on `process_results` from `itertools`. I also fixed some documentation along the way.
No functional changes were made in this PR.

Clean up code in field mapping parsing functions

---

quickwit-cli/tests/helpers.rs

Closes https://github.com/quickwit-inc/quickwit/issues/384
Fixed by setting `AWS_DEFAULT_REGION` env variable during test

Fix GC test

---

quickwit-serve/Cargo.toml
quickwit-serve/src/lib.rs
quickwit-serve/src/quickwit_cache.rs
quickwit-storage/src/cache/storage_with_cache.rs
quickwit-storage/src/lib.rs

The current QuickwitCache router logic is broken.
Path::ends_with has a very different different semantic than str::ends_with. It only check if the last element (here the filename) is a perfect match with the given suffix. 

Bugfix cache router

---

quickwit-core/src/index.rs
quickwit-core/src/indexing/split.rs
quickwit-index/src/actors/packager.rs
quickwit-index/src/actors/publisher.rs
quickwit-index/src/actors/uploader.rs
quickwit-index/src/models/packaged_split.rs
quickwit-index/src/models/uploaded_split.rs
quickwit-metastore/src/lib.rs
quickwit-metastore/src/metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs
quickwit-metastore/src/tests.rs
quickwit-search/src/lib.rs
quickwit-search/src/root.rs
quickwit-search/src/search_stream/root.rs
quickwit-storage/src/bundle_storage.rs
quickwit-storage/src/lib.rs

This PR refactors the organisation of the split file.
The split file is now the concatenation
- concatenated files (does not contain hotcache anymore)
- FOOTER - bundle meta data (file offsets)
- FOOTER - bundle meta data len
- FOOTER - hotcache
- FOOTER - hotcache len
The element marked footer are what we need to download in order to open a split in one fetch.

Only keep the footer offsets in the metastore

---

quickwit-cli/tests/cli.rs
quickwit-search/src/client.rs
quickwit-search/src/collector.rs
quickwit-search/src/error.rs
quickwit-search/src/leaf.rs
quickwit-search/src/search_stream/collector.rs
quickwit-search/src/search_stream/leaf.rs
quickwit-search/src/search_stream/root.rs
quickwit-search/src/service.rs
quickwit-serve/src/grpc_adapter/search_adapter.rs
quickwit-storage/src/error.rs

Fixes #483 #484 
Bonus: 
- the leaf stream return a search error and not a tonic status
- add tests at the root and leaf levels
- add test on the cli (csv output)
Not included:
- tests on collector: some important changes are coming soon and I would prefer to implement tests at this moment
- tests on performance would be nice

Fix #483, #484 and above all handle errors happening in search stream leaves.

---

Cargo.lock
quickwit-core/src/lib.rs
quickwit-indexing/src/lib.rs
quickwit-indexing/src/test_utils.rs
quickwit-search/Cargo.toml
quickwit-search/src/lib.rs
quickwit-search/src/root.rs
quickwit-search/src/search_stream/leaf.rs
quickwit-search/src/search_stream/root.rs
quickwit-serve/Cargo.toml
quickwit-serve/src/lib.rs

This PR moves test_utils from quickwit-core to quickwit-utils.
The idea is that this code is useful for testing quickwit_indexing, but depending on quickwit-indexing would create a loop dependency.

Moving test utils to quickwit-indexing.

---

CONTRIBUTING.md
Cargo.lock
Makefile
quickwit-cli/Cargo.toml
quickwit-cli/src/main.rs
quickwit-directories/src/storage_directory.rs
quickwit-search/Cargo.toml
quickwit-search/src/client.rs
quickwit-search/src/fetch_docs.rs
quickwit-search/src/leaf.rs
quickwit-search/src/root.rs
quickwit-search/src/search_stream/leaf.rs
quickwit-search/src/search_stream/root.rs
quickwit-serve/Cargo.toml
quickwit-serve/src/grpc_adapter/search_adapter.rs
quickwit-serve/src/rest.rs
quickwit-swim/src/cluster.rs
quickwit-swim/src/cluster_config.rs
quickwit-swim/src/errors.rs
quickwit-swim/src/member.rs
quickwit-swim/src/membership.rs
quickwit-swim/src/state.rs

This PR works with a jaeger instance that you can start with the following command:
`docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 jaegertracing/all-in-one:latest`
TODO

Add tracing with jaeger

---

quickwit-cluster/src/error.rs
quickwit-cluster/src/service.rs
quickwit-proto/proto/cluster.proto
quickwit-proto/src/cluster.rs
quickwit-serve/src/grpc_adapter/cluster_adapter.rs
quickwit-serve/src/http_handler/cluster.rs

Rename gRPC structs such as `LeaveResult` to `LeaveResponse`. More renaming PRs will come. 
No new unit tests were added.

Rename cluster RPCs *Result -> *Response

---

.localstack/init.sh
CONTRIBUTING.md
Makefile
docker-compose.yml
quickwit-common/src/lib.rs

Set up  Docker Compose to manage our growing list of external services.
Ran `make docker-compose-up` and `QUICKWIT_ENV=local cargo test --all-features` locally.

Set up Docker Compose and make command for running external services

---

Makefile

Reverting Makefile. `not` is not  present by default

Reverting Makefile to avoid using not.

---

Makefile

Re-enable error message in `make fmt` command
```sh
guilload@modern14 ~/W/r/quickwit (guilload--re-enable-make-fmt-error-message)> rustup toolchain remove nightly
info: uninstalling toolchain 'nightly-x86_64-unknown-linux-gnu'
info: toolchain 'nightly-x86_64-unknown-linux-gnu' uninstalled
guilload@modern14 ~/W/r/quickwit (guilload--re-enable-make-fmt-error-message)> make fmt
Formatting Rust files
Toolchain 'nightly' is not installed. Please install using 'rustup toolchain install nightly'.
guilload@modern14 ~/W/r/quickwit (guilload--re-enable-make-fmt-error-message)> rustup toolchain install nightly
guilload@modern14 ~/W/r/quickwit (guilload--re-enable-make-fmt-error-message)> make fmt
Formatting Rust files
guilload@modern14 ~/W/r/quickwit (guilload--re-enable-make-fmt-error-message)> …
```

Re-enable error message in `make fmt` command

---

quickwit-proto/proto/search_api.proto
quickwit-proto/src/quickwit.rs
quickwit-search/src/client.rs
quickwit-search/src/client_pool.rs
quickwit-search/src/cluster_client.rs
quickwit-search/src/collector.rs
quickwit-search/src/leaf.rs
quickwit-search/src/lib.rs
quickwit-search/src/retry/search.rs
quickwit-search/src/retry/search_stream.rs
quickwit-search/src/root.rs
quickwit-search/src/service.rs
quickwit-serve/src/grpc_adapter/search_adapter.rs

Rename `LeafSearchResult` to `LeafSearchResponse`.
`cargo test`

Rename `LeafSearchResult` to `LeafSearchResponse`

---

quickwit-indexing/src/source/kafka_source.rs

In CI env, the test for the Kafka source sometimes fails because messages are packed into 2 batches instead of 1. With this PR, assertions are performed on a merged batch.
Ran failing test locally.

Fix flaky Kafka source unit test

---

quickwit-actors/src/actor.rs
quickwit-actors/src/channel_with_priority.rs
quickwit-actors/src/lib.rs
quickwit-actors/src/mailbox.rs
quickwit-actors/src/universe.rs
quickwit-indexing/src/actors/indexer.rs
quickwit-indexing/src/actors/merge_planner.rs
quickwit-indexing/src/actors/packager.rs
quickwit-indexing/src/actors/pipeline_supervisor.rs
quickwit-indexing/src/actors/publisher.rs
quickwit-indexing/src/models/indexer_message.rs
quickwit-indexing/src/models/merge_planner_message.rs
quickwit-indexing/src/source/file_source.rs
quickwit-indexing/src/source/vec_source.rs

Two of quickwit actors (the indexer and the merge planner)
have a special message to instruct them to exit and success.
This change makes it into an actual command.
The aim is not just to factorize the logic, it is also to make
it possible for the ParallelActor (in an upcoming PR) to properly
react to this command.

Adding `Command::Success`.

---

Cargo.lock
quickwit-core/Cargo.toml
quickwit-directories/Cargo.toml
quickwit-index-config/Cargo.toml
quickwit-indexing/Cargo.toml
quickwit-search/Cargo.toml
quickwit-storage/Cargo.toml

It includes an update to 0.16.1 but also includes #526 (changing
the fst block size).

Bumping tantivy version.

---

Cargo.lock
quickwit-indexing/Cargo.toml
quickwit-indexing/src/source/kafka_source.rs

Sometimes a partition actually exists but `fetch_watermarks` throws `UnknownPartition` in CI env. I can't pinpoint what the problem exactly is. However, I've read a few things [here](https://github.com/confluentinc/confluent-kafka-python/commit/e2e0d9639b94064adba26d0f8a6c9417ac01a79c#diff-bffdbc99865016864a28a771105a44f1c75cce3b0cc6b16cca5808b9e2918919R424) and [there](https://issues.apache.org/jira/browse/KAFKA-6829) that seem to indicate that the issue comes from `librdkafka`. Retrying seems like the way to go.
Just unit testing, which is insufficient. Unfortunately, I'm unable to reproduce the error locally. I'm hoping that the spurious error will disappear after this PR is merged.

Retry transient error when fetching watermarks in Kafka source

---

.dockerignore
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/publish_main_docker_image.yaml
.github/workflows/publish_release_docker_image.yaml
.github/workflows/release.yml
Cargo.lock
Dockerfile
quickwit-indexing/Cargo.toml

Publish Docker image to Docker Hub at `quickwit/quickwit:main` on push to main branch.

Publish Docker image to Docker Hub on push to main branch

---

quickwit-indexing/src/merge_policy.rs

The point is to bound the resulting split to
`max_merge_docs* 2` instead of `max_merge_docs * merge_factor`.
Closes #575

Allow for splits involving less than `merge_factor` splits.

---

quickwit-proto/proto/search_api.proto
quickwit-proto/src/quickwit.rs
quickwit-search/src/client.rs
quickwit-search/src/cluster_client.rs
quickwit-search/src/fetch_docs.rs
quickwit-search/src/lib.rs
quickwit-search/src/retry/mod.rs
quickwit-search/src/root.rs
quickwit-search/src/service.rs
quickwit-serve/src/grpc_adapter/search_adapter.rs

Rename `FetchDocsResult` to `FetchDocsResponse`.
Compiled locally.

Rename `FetchDocsResult` to `FetchDocsResponse`

---

quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/mod.rs

The current implementation prevents from setting Kafka parameters other than `bootstrap.servers`, `group.id`, and `enable.partition.eof`. This PR allows passing any parameter via `client_params`.
Unit tests

Pass any client config parameters through source parameters

---

.github/workflows/release.yml
Dockerfile
quickwit-cli/Cargo.toml

This works by adding a `release-feature-set` feature in quickwit-cli.
- `--all-features` does not work with `cargo install`
- Release binaries github actions now rely on `release-feature-set`
- Docker container also relies on `release-feature-set`

Define a default set of release-flags.

---

quickwit-indexing/src/source/kafka_source.rs

The integration test suite for the Kafka source is behind another feature flag that I missed when testing #592...
```sh
make docker-compose-up DOCKER_SERVICES=kafka
cargo test --all-features -p quickwit-indexing
```

Fix Kafka source integration test suite

---

quickwit-actors/src/actor_handle.rs
quickwit-actors/src/spawn_builder.rs
quickwit-indexing/src/actors/pipeline_supervisor.rs

Bugfix: Stopping the merge planner cannot rely on healthcheck
The mechanic that decide whether the merge planner should be
stopped is broken.
Indeed, it relies on the idea that the packager healthcheck is faulty
while the merge_planner is healthy and running, but these calls
happen right after the overall healthcheck has been called.
The progress is therefore always reset at this point and the condition
never triggers.

Bugfix packager state

---

quickwit-actors/src/actor.rs
quickwit-indexing/src/source/file_source.rs
quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/mod.rs
quickwit-indexing/src/source/vec_source.rs

Allow customizable source names. Since sources are all wrapped in a `SourceActor`, logs do not display the source type:
```
Sep 28 19:25:07.322  INFO quickwit_actors::spawn_builder: spawn-async actor="holy-quickwit_indexing::source::SourceActor-708J"
```
There might be a better place/way to implement this. I'm also wondering whether we should change the `name(&self) -> String` signature to `name(&self) -> &str`. 

Customize source actor name

---

quickwit-indexing/src/actors/garbage_collector.rs
quickwit-indexing/src/actors/indexer.rs
quickwit-indexing/src/actors/merge_executor.rs
quickwit-indexing/src/actors/merge_planner.rs
quickwit-indexing/src/actors/merge_split_downloader.rs
quickwit-indexing/src/actors/packager.rs
quickwit-indexing/src/actors/publisher.rs
quickwit-indexing/src/actors/uploader.rs
quickwit-indexing/src/merge_policy.rs
quickwit-indexing/src/models/indexed_split.rs
quickwit-indexing/src/models/merge_scratch.rs
quickwit-indexing/src/models/packaged_split.rs
quickwit-indexing/src/models/publisher_message.rs

- We should decide and log the split id as early as the first doc is added in the indexer actor.
- log the time to search.
- Add separator to merge operation split ids
- remove redundant log lines
- Log a message when merge executor starts.
- set split id for merge in merge planner
- GC needs to log files it deletes
Closes #600

Better logging

---

quickwit-proto/proto/search_api.proto
quickwit-proto/src/quickwit.rs
quickwit-search/src/cluster_client.rs
quickwit-search/src/search_stream/collector.rs
quickwit-search/src/search_stream/leaf.rs
quickwit-search/src/search_stream/mod.rs
quickwit-search/src/search_stream/root.rs
quickwit-serve/src/lib.rs
quickwit-serve/src/rest.rs

add's an optional `partitionByFastField` option in the `search/stream` that will partition the values of the requested fast field. 
Internally for now 
* Some refactoring in the collector code because there is a lot of similar looking code 
* Some automated tests for the feature

Partitionned search stream

---

quickwit-cli/src/lib.rs
quickwit-cli/src/main.rs

Fix #559 
Notes: I tried to use a common `registry` variable but I had some types incompatibility so I ended up with a `if` and `else`.
Locally only.

Add QUICKWIT_JAEGER_ENABLED env variable to enable jaeger tracing.

---

quickwit-index-config/src/config.rs
quickwit-index-config/src/default_index_config/default_config.rs
quickwit-index-config/src/default_index_config/field_mapping_entry.rs
quickwit-index-config/src/wikipedia_config.rs
quickwit-indexing/src/actors/indexer.rs

Modified parsing functions to work on owned values rather than references.
```sh
make docker-compose-up
QUICKWIT_ENV=local cargo test --all-features
```

Avoid cloning values when going from JSON `Value` to `Document`

---

quickwit-core/src/index.rs
quickwit-indexing/src/actors/garbage_collector.rs
quickwit-indexing/src/actors/pipeline_supervisor.rs
quickwit-indexing/src/actors/publisher.rs
quickwit-indexing/src/garbage_collection.rs
quickwit-storage/src/bundle_storage.rs

Closes https://github.com/quickwit-inc/quickwit/issues/573
Fixed GC Actor integration into pipeline
Run indexing

Fix GC actor integration

---

quickwit-search/src/leaf.rs

Logging SPLIT_FOOTER_CACHE_CAPACITY only once.

---

docs/getting-started/quickstart.md

This updates the quickstart document to include the metastore-related arguments in the quickwit commands.
Note that this has been tested with the current `main` branch, so this should only be published on the quickwit website once this command line API change makes it to the current release (which 0.1.0 may not have).
I followed the quickstart document with quickwit built from source and ran the original and changed commands on my local machine.
This fixes #737.

update quickstart docs to work with metastore

---

quickwit-storage/src/local_file_storage.rs

Fixes this error:
```
error: 1 positional argument in format string, but no arguments were given
--> quickwit-storage/src/local_file_storage.rs:228:59
|
228 |                         .with_error(anyhow::anyhow!("File {} is actually a directory")))
```
`cargo build`

Fix error message in `LocalFileStorage::file_num_bytes`

---

quickwit-indexing/src/actors/pipeline_supervisor.rs

I had to revert the commit on the span because the generation was not updated.

Revert pipeline span commit and really add generation in pipeline logs

---

quickwit-index-config/src/default_index_config/default_config.rs

I introduced it myself [here](https://github.com/quickwit-inc/quickwit/commit/675c34eae89911d74a47186ee925ca442969a062#diff-b8ed3d934c98138499585cd3031bd4d0f27abbeb925fd4724a6630b65bcfadc0)
But we cannot support it.

Disable u64 timestamp field which was introduced by error.

---

quickwit-cli/src/lib.rs
quickwit-common/src/lib.rs
quickwit-directories/src/bundle_directory.rs
quickwit-indexing/src/actors/merge_executor.rs
quickwit-indexing/src/actors/merge_split_downloader.rs
quickwit-indexing/src/actors/packager.rs
quickwit-indexing/src/actors/uploader.rs
quickwit-indexing/src/lib.rs
quickwit-indexing/src/merge_policy.rs
quickwit-indexing/src/models/packaged_split.rs
quickwit-indexing/src/split_store/indexing_split_store.rs
quickwit-indexing/src/split_store/local_split_store.rs
quickwit-indexing/src/split_store/mod.rs
quickwit-metastore/src/metastore/single_file_metastore.rs
quickwit-search/src/leaf.rs
quickwit-storage/src/bundle_storage.rs
quickwit-storage/src/cache/storage_with_cache.rs
quickwit-storage/src/lib.rs
quickwit-storage/src/local_file_storage.rs
quickwit-storage/src/object_storage/s3_compatible_storage.rs
quickwit-storage/src/payload.rs
quickwit-storage/src/prefix_storage.rs
quickwit-storage/src/ram_storage.rs
quickwit-storage/src/split.rs
quickwit-storage/src/storage.rs
quickwit-storage/tests/s3_storage.rs

Don't materialize the single split file in packager.rs, instead stream the compute bundle from the files in uploader.rs. This will save IOPS.
cargo test

stream split bundle on the fly

---

quickwit-actors/src/actor.rs
quickwit-actors/src/actor_state.rs
quickwit-actors/src/async_actor.rs
quickwit-actors/src/sync_actor.rs
quickwit-actors/src/tests.rs

Two new states are now replacing the `Running` state:
- `Processing`: it corresponds to an actor that is processing messages, it has at least one message
- `Idle`: when an actor has no more message to process, it goes in `Idle` state.
It will be useful to define the right condition to terminate the indexing pipeline.

Add new states to actors.

---

.github/workflows/publish_cross_images.yml
Cross.toml
Makefile

Fix part of https://github.com/quickwit-inc/quickwit/issues/715
> @guilload We would also like to move all the images into this account https://hub.docker.com/orgs/quickwit, while creating a single image repository for all cross-images like quickwit/cross-builder:$tag with tag being the architecture target of the image.
So far making the `aarch64-unknown-linux-musl` has been harder than I anticipated. In the meantime,  this takes care of moving the cross images to our official Quickwit dockerhub account and automating the build & push process
pushed the newly built cross images

Build & push cross images 

---

quickwit-search/src/leaf.rs
quickwit-search/src/lib.rs
quickwit-search/src/search_stream/leaf.rs
quickwit-search/src/thread_pool.rs

`quickwit_spawn_blocking` was a good candidate too.
I am a tad afraid that the difference in semantic is
not really a detail.
Contrary to spawn_blocking, with this function,
if noone await the result, no work is done.

Renaming qspawn_blocking.

---

Makefile
build/cross-images/x86_64-unknown-linux-musl.dockerfile

Closes https://github.com/quickwit-inc/quickwit/issues/761
Reason of the failure: https://github.com/alexcrichton/cmake-rs/issues/131
Added convenience make commands in the meantime. You need to install [cross](https://github.com/rust-embedded/cross)
- `make build-x86_64-unknown-linux-gnu`
-  `make build-aarch64-unknown-linux-gnu`
-  `make build-x86_64-unknown-linux-musl`
Run the build on CI

Fix failing build

---

README.md

As we have moved to Discord from Gitter, I have updated the Chat URL in the README.
By clicking on the Chat link in the README.

Update Chat link to Discord

---

quickwit-search/src/search_stream/leaf.rs

Limit the overall amount of running leaf requests with
SPLIT_STREAM_CONCURRRENCY.
Closes #422

Limit the overall amount of running leaf requests with

---

quickwit-cli/src/stats.rs
quickwit-indexing/src/actors/garbage_collector.rs
quickwit-indexing/src/actors/merge_executor.rs
quickwit-indexing/src/lib.rs
quickwit-indexing/src/test_utils.rs
quickwit-metastore/src/lib.rs
quickwit-metastore/src/metastore/mod.rs
quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit-metastore/src/metastore/single_file_metastore.rs
quickwit-metastore/src/postgresql/model.rs
quickwit-metastore/src/split_metadata.rs
quickwit-search/src/root.rs
quickwit-search/src/search_stream/root.rs
quickwit-serve/src/lib.rs

Rename `SplitInfo` to `Split`. I also squizzed in a light refactor in the Postgres metastore.

Rename `SplitInfo` to `Split`

---

quickwit-backward-compat/build.rs
quickwit-backward-compat/test-data/index-metadata/unversioned.expected.json
quickwit-backward-compat/test-data/index-metadata/v0-cb4b352caf8990d0e7a54582a4478cd5.expected.json
quickwit-backward-compat/test-data/index-metadata/v0-cb4b352caf8990d0e7a54582a4478cd5.json
quickwit-cli/src/main.rs
quickwit-cluster/src/cluster.rs
quickwit-config/resources/tests/index_config/hdfs-logs.json
quickwit-config/resources/tests/index_config/hdfs-logs.toml
quickwit-config/resources/tests/index_config/hdfs-logs.yaml
quickwit-config/resources/tests/server_config/server.json
quickwit-config/resources/tests/server_config/server.toml
quickwit-config/resources/tests/server_config/server.yaml
quickwit-config/src/index_config.rs
quickwit-config/src/server_config.rs
quickwit-indexing/src/actors/indexer.rs
quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit-indexing/src/merge_policy.rs
quickwit-serve/src/lib.rs

- Use gRPC and discovery ports relative to REST port
- Rename `split_max_num_docs` to `split_num_docs_target`
- Simplify `get_resource_path`

Use gRPC and discovery ports relative to REST port

---

Cargo.lock
quickwit-metastore/Cargo.toml
quickwit-metastore/src/metastore/single_file_metastore/mod.rs
quickwit-metastore/src/metastore/single_file_metastore/single_file_metastore_factory.rs
quickwit-telemetry/Cargo.toml

This adds the possibility to configure a polling period for a given SingleFileMetastore by appending a uri fragment to tis uri like this: `s3://my_bucket/blabla#period=30s`
Closes #839

Added polling for the SingleFileMetastore.

---

quickwit-core/src/index.rs
quickwit-indexing/src/actors/garbage_collector.rs
quickwit-indexing/src/garbage_collection.rs
quickwit-metastore/src/metastore/file_backed_metastore/index.rs
quickwit-metastore/src/metastore/mod.rs
quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit-metastore/src/split_metadata.rs

I noticed that nobody uses the term "scheduled" for deletion. Instead, we all use "marked", so I figured I'd rename the enum. The metastore API is already named `mark_for_deletion`.
This change is backward compatible.

Rename `ScheduledForDeletion` to `MarkedForDeletion`

---

Makefile
quickwit-cli/tests/cli.rs

- Add placeholders for AWS keys, it's necessary if you don't have an `~/.aws/config`. That's my case on my fresh laptop setup.
- Fix process stdout capture. Honestly, I don't why the current way does not work T_t
Ran `make test-all` locally

Fix integration test suite

---

Cargo.lock
quickwit-cli/src/index.rs
quickwit-cli/src/lib.rs
quickwit-cli/src/service.rs
quickwit-cli/src/source.rs
quickwit-cli/src/split.rs
quickwit-cli/tests/cli.rs
quickwit-common/src/uri.rs
quickwit-core/src/index.rs
quickwit-indexing/src/test_utils.rs
quickwit-metastore/Cargo.toml
quickwit-metastore/src/lib.rs
quickwit-metastore/src/metastore/file_backed_metastore/file_backed_metastore_factory.rs
quickwit-metastore/src/metastore_resolver.rs

It is necessary to be able to run several
sources targetting the same index for instance.
The metastore uri resolver is a singleton now too.
Closes #926

Singletonning the file backed metastore

---

docs/reference/index-config.md
docs/reference/ports.md
quickwit-common/src/net.rs
quickwit-config/src/server_config.rs
quickwit-search/src/lib.rs
quickwit-serve/src/lib.rs

Closes #901
- people can optionally pass a port when defining their peer nodes.
Making it possible to run several node on the same computer.
Previously all nodes were assumed to share the same SWIM
listen port, preventing running several quickwit instance
on the same node.
- peer node address can now be IPv6
IPv6 was broken due to the parsing of format!("{}:{}") idiom.
- Change in the base port -> service port logic.
In addition this PR change the base port -> service
port logic.
Before:
Rest port (TCP) = Base port
GRPC port (TCP) = Base port + 1
SWIM port (UDP) = Base port + 2
After:
Rest port (TCP) = Base port
GRPC port (TCP) = Base port + 1
SWIM port (UDP) = Base port
The reason for this is that in the configuration,
the user needs to know about the rest port and the SWIM
port.
To make …

Peer-seed port story (Issue/901)

---

Cargo.lock
quickwit-backward-compat/build.rs
quickwit-backward-compat/test-data/file-backed-index/v0-cd9b0bf64dbb7af9e92bfed8a569c890.expected.json
quickwit-backward-compat/test-data/file-backed-index/v0-cd9b0bf64dbb7af9e92bfed8a569c890.json
quickwit-backward-compat/tests/test_backward_compatibility.rs
quickwit-cli/Cargo.toml
quickwit-indexing/Cargo.toml
quickwit-metastore/Cargo.toml
quickwit-metastore/src/lib.rs
quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs
quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit-metastore/src/metastore/file_backed_metastore/store_operations.rs
quickwit-metastore/src/split_metadata.rs

Improve serialization format of `quickwit.json` file. Fixes #266.
```json
{
"index": {},
"splits": [{}, {}],
"version": 0
}
```
- Added backward-compatibility tests
- Ran `make test-all` command

Improve serialization format of `quickwit.json` file

---

quickwit-cli/src/index.rs
quickwit-search/src/search_response_rest.rs
quickwit-serve/src/rest.rs

I removed from the search CLI command the conversion of a search response into a rest search response because it didn't show the errors. However, this was a bad choice as when you print the `SearchResponse` it's quite ugly... see at the end the example.
This PR reintroduces the use of `SearchResponseRest` and add a new attribute `errors` to show errors.
```
{
"json": "{\"_source\":[\"{\\\"id\\\":19162108755,\\\"event_type\\\":\\\"IssueCommentEvent\\\",\\\"actor_login\\\":\\\"fulmicoton\\\",\\\"repo_name\\\":\\\"quickwit-inc/quickwit\\\",\\\"created_at\\\":1638497795000,\\\"action\\\":\\\"created\\\",\\\"number\\\":831,\\\"title\\\":\\\"Missing allocation in LZ4 compression buffer.\\\",\\\"labels\\\":[\\\"bug\\\"],\\\"ref\\\":null,\\\"additions\\\":null,\\\"deletions\\\":null,\\\"commit_id\ …
```

Add errors attributes to rest search response.

---

quickwit-cli/tests/cli.rs
quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit-metastore/src/metastore/file_backed_metastore/store_operations.rs

Rename `quickwit.json` to `metastore.json`. Something we discussed with @fmassot. WDYT @fulmicoton?

Rename `quickwit.json` to `metastore.json`

---

quickwit-backward-compat/build.rs
quickwit-backward-compat/tests/test_backward_compatibility.rs
quickwit-cli/src/index.rs
quickwit-cli/src/lib.rs
quickwit-cli/src/source.rs
quickwit-config/src/index_config.rs
quickwit-indexing/src/test_utils.rs
quickwit-metastore/src/error.rs
quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs
quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit-metastore/src/metastore/index_metadata.rs
quickwit-metastore/src/metastore/mod.rs
quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit-metastore/src/postgresql/model.rs
quickwit-metastore/src/tests.rs

- Stores sources in hashmap rather than vector.
- Add and implement `add_source` and `delete_source` metastore APIs
- added unit tests
- ran `make test-all`

Add and implement `add_source` and `delete_source` metastore APIs

---

quickwit-common/src/net.rs

127.0.0. is accepted as valid by some DNS server (discovered as I was
tethering on my phone)

Unit test fix.

---

quickwit-cli/src/index.rs

I was confused by the following output as I was running the clickhouse tutorial.
```
❯ quickwit index create --index gh-archive --index-config gh-archive-index-config.yaml
2021-12-30T15:33:56.635Z  INFO quickwit: version="0.1.0" commit="30eb30b"
2021-12-30T15:33:56.636Z  WARN quickwit_config::config: Peer seed list is empty.
2021-12-30T15:33:56.636Z  INFO quickwit_cli: Loaded Quickwit config. config_uri=file:///home/fulmicoton/git/clickhouse-test/datadir/config/quickwit.yaml config=QuickwitConfig { version: 0, node_id: "node-wispy-SV6b", metastore_uri: "file:///home/fulmicoton/git/clickhouse-test/datadir/qwdata/indexes", default_index_root_uri: "file:///home/fulmicoton/git/clickhouse-test/datadir/qwdata/indexes", data_dir_path: "./qwdata", indexer_config: IndexerConfig { …
```

Changing log line when index uri is missing.

---

quickwit-doc-mapper/src/tag_pruning.rs
quickwit-indexing/src/actors/packager.rs
quickwit-indexing/src/merge_policy.rs
quickwit-metastore/src/split_metadata.rs
quickwit-search/src/lib.rs

I update the merge policy so that we can correctly identify the splits to demux.
Few notes:
I was very surprised by the usage of the special tag `tag_field!` which indicates that, for a given split, the field is registered as `tagged`, I was expecting a special tag like "indicates that there are no tags in a split" like described in #887 examples. It's working well and I understand why this is like this, it was just me that did not understand correctly the usage.
Just to be clear, I will rewrite the example I wrote in #887:
`split_1`: no tag values => metadata contains `tag_field!`
`split_2`: contains one value `tag_field:value` => metadata contains `tag_field:value` and `tag_field!`
`split_3`: too many tag values => metadata tags is empty
`split_4`: `tag_field` was not configured as a …

Update demux maturity implementation with the new tag system.

---

quickwit-cli/src/generate_markdown.rs
quickwit-cluster/src/cluster.rs
quickwit-swim/src/member.rs
quickwit-swim/src/membership.rs
quickwit-swim/src/state.rs

Check SocketAddr when node joins cluster to avoid duplicates when node-id changes
Fixes #1018

check SocketAddr when node joins cluster

---

quickwit-actors/src/kill_switch.rs

As discussed, setting log level to debug for kill switch activation message.

Set log level to debug for kill switch activation message

---

quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit-doc-mapper/src/default_doc_mapper/mod.rs

Limit field names to 255 characters. I also went to great length to display nicer error messages when a field name is invalid.
- added unit tests
- ran `make test-all`

Limit field names to 255 characters

---

docs/administration/cloud-env.md

update cloud env

---

docs/reference/rest-api.md

improve GET docs
Remove Format block with reference to POST/PUT, there are no POST/PUT
rename searchFields parameter to searchField

Fix Rest API docs

---

quickwit-doc-mapper/src/error.rs
quickwit-proto/src/lib.rs
quickwit-search/src/leaf.rs
quickwit-search/src/root.rs
quickwit-serve/src/error.rs

before
```
"error": "Search error. Internal error: `[SplitSearchError { error: \"InvalidQuery(\\\"Invalid query syntax: `Field does not exists: '\\\\\\\"asdf\\\\\\\"'`\\\")\", split_id: \"01FS4C5YHK92E1VB1AHSQ26B7X\", retryable_error: true }]`.."
```
after
```
"error": "Search error. Internal error: `(Invalid query: Field does not exists: '\"asdf\"', split_id: 01FS4C5YHK92E1VB1AHSQ26B7X)`."
```

improve rest api error formatting

---

.github/workflows/ci.yml
quickwit-cli/src/index.rs
quickwit-cli/src/split.rs
quickwit-search/src/service.rs

Remove the use of a custom container.
Added clippy suggestion from rust 1.58
Added Makefile rules to refresh the quickwit-builder image used in CI.

Pleasing clippy after rust 1.58.

---

.github/workflows/coverage.yml
CONTRIBUTING.md
Makefile
docs/reference/storage-uri.md
quickwit-cli/tests/cli.rs
quickwit-cli/tests/helpers.rs
quickwit-common/src/lib.rs
quickwit-metastore/src/metastore_resolver.rs
quickwit-serve/src/lib.rs
quickwit-storage/src/error.rs
quickwit-storage/src/lib.rs
quickwit-storage/src/object_storage/mod.rs
quickwit-storage/src/object_storage/s3_compatible_storage.rs
quickwit-storage/src/object_storage/s3_compatible_storage_uri_resolver.rs
quickwit-storage/src/storage_resolver.rs
quickwit-storage/tests/s3_storage.rs

This removes our trickery to use localstack,
and replaces it by a way to set a specific
endpoint via an environment variable:
`QW_S3_REGION`.
Closes #1037

Adds support for custom s3 endpoint.

---

.github/workflows/coverage.yml

This is a tricky problem.
In the current setting, localstack should be accessed via localhost,
not localstack.
This is because right now the CI tests are running on a host,
not in a dockerized environment.
(The services are running in containers)
I am not entirely sure how this is used to work.

Fixing the coverage CI.

---

quickwit-search/src/root.rs

This PR is first attempt to fix issue-1086 where query should be validated against current/last schema before dispatching to leaf node. It also tries to refactor/optimize code a bit to be (a bit) safer and faster.
What is not covered:
- Stream API (I think it's better to make it in another PR)

ISSUE-1086 Check and validate the query against the last schema before dispatching

---

.github/workflows/publish_cross_images.yml
quickwit-search/src/retry/search_stream.rs

add unit tests for search stream retry policy, address this [issue](https://github.com/quickwit-oss/quickwit/issues/1111)
`cargo test test_retry_policy_search_stream`

ISSUE-1111 add tests for search stream retry policy

---

docs/guides/tutorial-hdfs-logs.md
quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit-doc-mapper/src/doc_mapper.rs

`store_source` set to true makes a lot of sense...
However we already set each individual field store attribute in the
schema to true.
Having both set to true is redundant and needlessly inflates the
index size.
Closes #1132

Sets default for store_source to false.

---

docs/reference/query-language.md

If we want to include a literal backtick character within a code span, we should use multiple backticks as the delimiter.
Before the fix:
After:

docs: fix a format error

---

quickwit-cli/tests/cli.rs
quickwit-search/src/search_response_rest.rs
quickwit-serve/src/cluster_api/rest_handler.rs
quickwit-serve/src/search_api/rest_handler.rs

Closes #1197
This PR will make query params, json payload and json response fields in *snake_case* naming convention.
Note: This is a BREAKING CHANGE.

Unify naming convention in REST API

---

Cargo.lock
quickwit-cli/src/index.rs
quickwit-cli/src/split.rs
quickwit-directories/Cargo.toml
quickwit-doc-mapper/Cargo.toml
quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit-indexing/Cargo.toml
quickwit-metastore/Cargo.toml
quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs
quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit-metastore/src/split_metadata.rs
quickwit-metastore/src/tests.rs
quickwit-serve/Cargo.toml

remove chrono
chrono dependency on diesel not removed

remove chrono

---

.github/workflows/coverage.yml

Re-enabled code coverage

---

Dockerfile

`docker build .` fails on `main` due to the new native dependencies for `librocksdb-sys`. This PR adds them to fix the build.
`docker build -t qw . && docker run -it qw run` locally.

Update dockerfile with new native dependencies

---

Cargo.lock
quickwit-cli/Cargo.toml
quickwit-cli/src/lib.rs
quickwit-cli/src/source.rs
quickwit-cli/src/split.rs

- Bump tabled from 0.5.0 to 0.6.0
- Rotate source table (cf. `quickwit source describe` command)
Fixes #914

Bump tabled from 0.5 to 0.6 and left rotate source table

---

quickwit-indexing/src/source/kafka_source.rs

Replace the convoluted `stream.take_until(...)` with the more standard `tokio::select! {...}`.

Record progress after each message received

---

docs/reference/cli.md
quickwit-cli/src/index.rs
quickwit-cli/src/main.rs
quickwit-cli/tests/cli.rs
quickwit-core/src/index.rs
quickwit-core/src/lib.rs
quickwit-indexing/src/models/indexing_directory.rs

As per title. I wonder whether this option should be enabled by default, though.

Rename `clean_cache` option to `clear-cache` and document

---

quickwit-directories/src/union_directory.rs

Per title. Fixes #543.
`RUST_BACKTRACE=full cargo test -p quickwit-directories`

Add unit tests for union directory

---

docs/reference/source-config.md
quickwit-indexing/src/source/file_source.rs
quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit-indexing/src/source/source_factory.rs
quickwit-indexing/src/source/vec_source.rs
quickwit-indexing/src/source/void_source.rs

Auto-generate a group ID derived from the source ID for debugging purposes.
Fixes #1069.

Auto-generate Kafka group ID

---

docs/reference/cli.md
quickwit-cli/src/index.rs
quickwit-cli/src/main.rs
quickwit-cli/tests/cli.rs

Clear the cache by default. Use `keep-cache` option to preserve the cache.

Clear cache unless instructed otherwise

---

quickwit-indexing/src/source/file_source.rs
quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit-indexing/src/source/vec_source.rs

Display source ID in logs:
```
2022-04-11T16:13:07.739Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=FileSource{source_id=.cli-ingest-source}}: quickwit_actors::runner: actor-exit actor_id=SourceActor-empty-R0Ps exit_status=Success
```
The output is quite ugly in my option. I'm open to suggestions.
- ran `quickwit index` and displayed logs

Display source ID in logs

---

docs/reference/quickwit-config.md
quickwit-cluster/src/cluster.rs
quickwit-cluster/src/lib.rs
quickwit-config/resources/tests/config/quickwit.json
quickwit-config/resources/tests/config/quickwit.toml
quickwit-config/resources/tests/config/quickwit.yaml
quickwit-config/src/config.rs

Fixes #1283
- Updates scuttlebutt to use https://github.com/quickwit-oss/scuttlebutt/pull/36
- Add the optional `cluster_name` config param, with a default value of "Test cluster"
- Add a new unit test to confirm that four nodes with different cluster names settle correctly into 2x2
Only unit test for now, we should test it a bit more manually before the v0.3 release
- We should expose the cluster name in the UI too
- Do we want to print a warn log if using the default value? I would, but I'm not sure whether that's in line with the project's logging policy.

Add new cluster_id config option

---

docs/reference/cli.md
quickwit-cli/src/generate_markdown.rs

- generate doc for `quickwit split mark-for-deletion` command
- misc. fixes
Inspected rendered markdown on GitHub

Generate doc for `quickwit split mark-for-deletion` command

---

quickwit-cluster/src/cluster.rs

Increased `wait_secs` value to 30s. There's really no harm in setting a high value since `wait_for_members` returns whenever the predicate holds true. `wait_secs` is just an upper bound.
Fixes #1313.

Fix flaky cluster tests

---

docs/guides/tutorial-hdfs-logs-distributed-search-aws-s3.md
docs/guides/tutorial-hdfs-logs.md
quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit-doc-mapper/src/doc_mapper.rs
quickwit-proto/proto/search_api.proto
quickwit-proto/src/quickwit.rs
quickwit-search/src/fetch_docs.rs
quickwit-search/src/lib.rs
quickwit-search/src/root.rs

Formatting returned documents.
Before this PR, documents are just json serialized
by tantivy.
This is bad because:
- object fields are not constructed,
- cardinality is ignored, and all fields are wrapped in arrays,
- the dynamically mapped fields are added in `_dynamic`,
This PR adds a method to the `DocMapper` in
order to format JSON Object for documents.
This formatting happens at the root level, in order
to use the same DocMapper (output format) for all hits.
In addition, the _source field used to be stored in
text field. After this change, the _source field is stored in a
JSON field, and returned as a JSON Object (it used to be a JSON
serialized string within the json document).
Closes #1325
Closes #1293

Added a `doc_to_json` in the DocMapper.

---

Cargo.lock
quickwit-cli/Cargo.toml
quickwit-cli/src/split.rs

- add `mark-for-deletion` flag (alias `mark`) to `quickwit split list` command; fixes #403 
- reorder command options; fixes #1288 
- misc. refactors
- ran `make-test-all`
- ran command manually

Add `mark-for-deletion` flag to `quickwit split list` command

---

quickwit-cli/src/cli.rs
quickwit-cli/src/index.rs
quickwit-cli/src/main.rs
quickwit-cli/src/service.rs
quickwit-cli/src/source.rs
quickwit-cli/src/split.rs
quickwit-config/src/config.rs
quickwit-config/src/lib.rs

- Set default config location to `./config/quickwit.yaml`; fixes #1339
- Warn user when default cluster ID is used; fixes #1314
- ran a bunch of commands with `--config` at various positions.

Set default config location to `./config/quickwit.yaml`

---

Cargo.lock
quickwit-cli/src/index.rs
quickwit-cli/src/lib.rs
quickwit-cli/src/source.rs
quickwit-common/Cargo.toml
quickwit-common/src/uri.rs
quickwit-config/src/config.rs
quickwit-config/src/index_config.rs
quickwit-core/src/index.rs
quickwit-core/src/lib.rs
quickwit-indexing/src/actors/indexer.rs
quickwit-metastore/src/metastore_resolver.rs
quickwit-search/src/search_client_pool.rs
quickwit-search/src/search_stream/leaf.rs
quickwit-serve/src/index_api/rest_handler.rs

- Validate config URIs (metastore URI, index URI, index root URI), fixes #1061

Validate config URIs

---

quickwit-cli/src/cli.rs

Require subcommands and display help when no subcommand is provided, fixes #1372.
```sh
> QW_CONFIG=foo cargo run
error: 'quickwit' requires a subcommand but one was not provided
USAGE:
quickwit [OPTIONS] <SUBCOMMAND>
For more information try --help
```

Require subcommands

---

Cargo.lock
quickwit-core/Cargo.toml
quickwit-directories/Cargo.toml
quickwit-doc-mapper/Cargo.toml
quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit-doc-mapper/src/lib.rs
quickwit-doc-mapper/src/query_builder.rs
quickwit-indexing/Cargo.toml
quickwit-metastore/src/metastore/index_metadata.rs
quickwit-search/Cargo.toml
quickwit-storage/Cargo.toml

```
Fix how quickwit handles "." in field names.
After this PR we still accept field names with a ".".
On the query side this dot then needs to be escaped with a backslash
to disambiguate it from the "." of Json fields, and the "." of
object fields.
Under the hood, we still rely on tantivy's query parser.
The hack consists in escaping the tantivy field name itself.
This PR updates tantivy in order to include
https://github.com/quickwit-oss/tantivy/pull/1356.
Closes #1338
Closes #1334
```

Fixing how we handle "."

---

quickwit-directories/src/hot_directory.rs

Always store the termdict indices in the hotcache.
Before it could be skipped if it was greater than 10mb,
but Quickwit does not work at all if it not there.
Such size was uncommon and due to a misconfiguration.
We are mitigating the size problem independently.
Closes #1366
I verified manually that the bug described in #1366 was sovled.
```
cargo run --release  -- index search --index hackernews_5 --query "Ambulance"
Finished release [optimized] target(s) in 0.27s
Running `target/release/quickwit index search --index hackernews_5 --query Ambulance`
{
"num_hits": 9,
"hits": [
{
"id": 16203439,
"text": "Be the real super hero not by the super powers but by the deeds that matter, save the life of the Civilians in the city in the most realistic Rescue Simulation Games of time, Ambulance …
```

Always store the termdict indices in the hotcache.

---

docs/reference/index-config.md

Update docs to recommend avoiding `.` in field names

Doc on avoiding `.` in field names

---

Cargo.lock
quickwit-core/Cargo.toml
quickwit-directories/Cargo.toml
quickwit-doc-mapper/Cargo.toml
quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit-doc-mapper/src/lib.rs
quickwit-doc-mapper/src/query_builder.rs
quickwit-doc-mapper/src/tokenizers.rs
quickwit-indexing/Cargo.toml
quickwit-indexing/src/actors/indexer.rs
quickwit-indexing/src/actors/merge_executor.rs
quickwit-indexing/src/actors/packager.rs
quickwit-search/Cargo.toml
quickwit-search/src/leaf.rs
quickwit-storage/Cargo.toml

update tantivy
skip tokens longer than 100 for raw tokenizer, set tokenizer when opening Index and in query_parser
change default tokenizer for JSON to the 'default' tokenizer
Fixes https://github.com/quickwit-oss/quickwit/issues/1392
Fixes https://github.com/quickwit-oss/quickwit/issues/1370

skip long tokens in raw tokenizer

---

Cargo.lock
quickwit-core/Cargo.toml
quickwit-directories/Cargo.toml
quickwit-doc-mapper/Cargo.toml
quickwit-indexing/Cargo.toml
quickwit-search/Cargo.toml
quickwit-storage/Cargo.toml

The target PR in tantivy is https://github.com/quickwit-oss/tantivy/pull/1367
Closes #1411
A unit test was added on tantivy side and the ticket example has been tested and yielded the following result.
```json
{
"num_hits": 3,
"hits": [
{
"attributes": {
"syslog": {
"facility": "daemon",
"procid": 7816,
"version": 2
}
},
"body": "<26>2 2022-05-10T17:59:56.706Z for.us benefritz 7816 ID715 - A bug was encountered but not in Vector, which doesn't have bugs",
"name": "ID715",
"severity": "ERROR",
"timestamp": 1652205596
},
{
"attributes": {
"syslog": {
"facility": "daemon",
"procid": 7816,
"version": 2
}
},
"body": "<26>2 2022-05-10T17:59:56.706Z for.us benefritz 7816 ID715 - A bug was encountered but not in Vector, which doesn't have bugs",
"name": "ID715",
"severity": "ERROR",
"timestamp": …
```

Updates tantivy for bugfix in json value serializaton.

---

quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs

dissallow unknown fields for json options, same behaviour as other option types

disallow unknown fields for json options

---

quickwit-config/src/index_config.rs

Allowing an empty field mappings. (makes sense in dynamic mode)

Allow for an empty field_mappings.

---

quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit-doc-mapper/src/doc_mapper.rs

Following #1393, the default tokenizer given when deserializing
JsonOptions (the tokenizer property is missing), and the
Default::default implementation are inconsistent.
This is a problem because Default::default is used when deserializing
the doc mapping if the entire `QuickwitJsonOption` is missing.

Bugfix: tokenizer for default `QuickwitJsonOption` should be default.

---

quickwit-proto/build.rs
quickwit-proto/src/cluster.rs
quickwit-proto/src/quickwit.rs
quickwit-proto/src/quickwit_ingest_api.rs
quickwit-serve/src/search_api/rest_handler.rs

Remove camelCase from Rust structs/enums generated from protobuf.

---

Cargo.lock
config/quickwit.yaml
quickwit-cli/tests/helpers.rs
quickwit-cluster/Cargo.toml
quickwit-cluster/src/cluster.rs
quickwit-cluster/src/error.rs
quickwit-cluster/src/lib.rs
quickwit-common/src/net.rs
quickwit-config/src/config.rs
quickwit-search/Cargo.toml
quickwit-search/src/rendezvous_hasher.rs
quickwit-search/src/search_client_pool.rs
quickwit-serve/Cargo.toml

Updating chitchat.
Unit test are now for the most part using the mock transport, removing the need for port allocation.
The address resolution logic is also simplified.
Finally the gossip interval is shortened.
`cargo test test_cluster` now finishes in 4s. (17s before)

Updating chitchat

---

quickwit-search/src/search_client_pool.rs
quickwit-serve/src/grpc.rs
quickwit-serve/src/index_api/rest_handler.rs
quickwit-serve/src/lib.rs
quickwit-serve/src/search_api/rest_handler.rs

We add a search service to address REST requests in the UI of index-only
nodes as quickfix for #1482.
It will only address the root part of the requests.
That search service is not mounted as a gRPC service and hence will not address
leaf requests.
We also return an explicit error if there are no search nodes in the cluster.
(before we were panicking).
Closes #1482

Add a search service to address REST requests on indexer only nodes.

---

Cargo.lock
quickwit-common/src/uri.rs
quickwit-serve/Cargo.toml
quickwit-serve/src/lib.rs

Implements ensuring Quickwit cluster is only run when certain conditions are met.
Closes https://github.com/quickwit-oss/quickwit/issues/1233

Ensure cluster is not miss-configured

---

docs/reference/query-language.md

Parenthesis to factor targetted field in queries is
not supported.
Closes #1130

Fixing documentation about parenthesis.

---

quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit-doc-mapper/src/default_doc_mapper/mod.rs
quickwit-doc-mapper/src/doc_mapper.rs
quickwit-doc-mapper/src/query_builder.rs
quickwit-doc-mapper/src/sort_by.rs
quickwit-search/src/tests.rs

fixes #1454
validate sort_by_field for the config and query
```
➜  quickwit-indices curl -sS 'http://127.0.0.1:7280/api/v1/air_quality/search?query=*&max_hits=10&sort_by_field=NO2'
{
"InternalError": "(Internal error: `Field \"NO2\" is not a fast field.`., split_id: 01G380H2WYF5H0PGX52HYW89TD), (Internal error: `Field \"NO2\" is not a fast field.`., split_id: 01G380HBYE77GZ85AE0EVZR9NK), (Internal error: `Field \"NO2\" is not a fast field.`., split_id: 01G380HNSXBFCJ4G6BPNKS4PG9)"
}⏎
➜  quickwit-indices curl -sS 'http://127.0.0.1:7280/api/v1/air_quality/search?query=*&max_hits=10&sort_by_field=NO2'
{
"InvalidQuery": "Sort by field must be a fast field, please add the fast property to your field `NO2`."
}⏎
➜  quickwit-indices curl -sS …
```

validate sort_by

---

.dockerignore
.github/actions/build-docker/action.yml
.github/workflows/publish_nightly_packages.yml
.github/workflows/publish_release_packages.yml
Dockerfile

Adds docker image build to ci 
Part of https://github.com/quickwit-oss/quickwit/issues/1219
@fmassot  I think what we are missing is having the binaries build for `.github/workflows/publish_release_packages.yml`
Should I add it here?

Docker image build 

---

Dockerfile

We knew this sed can break :)
We added one space in the config file so currently quickwit starts on 127.0.0.1 in the container.
I built the docker image and tested it.

Fix sed in Dockerfile

---

docs/tutorials/kafka.md

Apart that, it works like a charm. Note that the commit timeout is 60 seconds and the ingestion throughput is not sufficiently hight to trigger a commit when ingested docs reaches `max_docs`.

Minor fixes on kafka tutorial.

---

quickwit-search/src/error.rs
quickwit-search/src/root.rs
quickwit-serve/src/error.rs

```
➜  quickwit-indices curl -sS 'http://localhost:7280/api/v1/hdfs/search?query=*&max_hits=0&start_offset=40000000'
{
"InvalidArgument": "max value for start_offset is 10_000, but got 40000000"
}⏎
```

set max value for start_offset

---

docs/reference/rest-api.md

I amended the docs following the discussion on discord.
Closes https://github.com/quickwit-oss/quickwit/issues/1525
We can still switch to `index` action instead of `create` in this PR @fulmicoton

Elasticsearch create semantic note

---

Cargo.lock
quickwit-aws/Cargo.toml
quickwit-aws/src/error.rs
quickwit-aws/src/retry.rs
quickwit-config/src/index_config.rs
quickwit-config/src/lib.rs
quickwit-config/src/source_config.rs
quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/kinesis/api.rs
quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit-indexing/src/source/kinesis/mod.rs
quickwit-indexing/src/source/kinesis/shard_consumer.rs
quickwit-indexing/src/source/mod.rs
quickwit-storage/src/object_storage/error.rs
quickwit-storage/src/object_storage/s3_compatible_storage.rs

This PR brings various fixes and improvements to the Kinesis source:
- Fix `RegionOrEndpoint` enum serialization
- Fix Kinesis source actor timeout
- Increase (slightly) Kinesis shard consumer polling interval
- Retry on Kinesis `ProvisionedThroughputExceeded` errors
- Implement connectivity check for the Kinesis source
- Remove dead code
- Ran `make test-all` command
- Tested manually on empty stream, then stream loaded with malformed data, then stream loaded with GH Archive data

Fix Kinesis source

---

quickwit-indexing/src/source/kafka_source.rs

Fix Kafka source timeout. Currently, the actor times out when the topic is empty.
Tested manually on empty topic :/

Fix Kafka source timeout

---

quickwit-indexing/src/source/ingest_api_source.rs

Changed `current_offset` type from u64 to Option<u64> to signify none value at the start. 
Closes https://github.com/quickwit-oss/quickwit/issues/1551

Fixed infinite loop on ingest source error

---

quickwit-serve/src/error.rs
quickwit-serve/src/rest.rs

fixes #1564
```
➜  quickwit-indices curl -X POST http://127.0.0.1:7280/api/v1/hdfs/ingest --data-binary @./wiki-articles_number_small.json
{
"error": "Internal server error."
}⏎
➜  quickwit-indices curl -X POST http://127.0.0.1:7280/api/v1/hdfs/ingest --data-binary @./wiki-articles_number_small.json
{
"error": "The request payload is too large"
}⏎
```

return correct error status to http client

---

quickwit-cli/build.rs
quickwit-cli/src/generate_markdown.rs
quickwit-cli/src/main.rs

Display nightly in `quickwit version` command. Fixes #1531.
Without tag:
```sh
> cargo build
> ./target/debug/quickwit --version
Quickwit 0.3.0-nightly (54be83d03 2022-05-31)
```
With tag:
```sh
> git tag v0.3.0
> cargo build
> ./target/debug/quickwit --version
Quickwit 0.3.0 (54be83d03 2022-05-31)
```
Without git:
```sh
> mv .git .gitt
> cargo build
> ./target/debug/quickwit --version
Quickwit 0.3.0-nightly (unknown unknown)
```

Display nightly in `quickwit version` command

---

quickwit-indexing/src/split_store/indexing_split_store.rs

New logging info:
`2022-06-01T09:05:28.622Z  INFO {actor=quickwit_indexing::actors::indexing_service::IndexingService}:{msg_id=1}::{index=hdfs-logs gen=0}:{actor=Uploader}:{msg_id=5 num_splits=1}: quickwit_indexing::split_store::indexing_split_store: store-split-remote-success split_size_in_megabytes=1 num_docs=10000 elapsed_secs=0.013303875 throughput_mb_s=75.16607 is_mature=false`

Add 'num_docs' info when login a store split remote succes.

---

quickwit-cluster/src/cluster.rs
quickwit-cluster/src/service.rs
quickwit-proto/proto/cluster.proto
quickwit-proto/src/cluster.rs
quickwit-ui/cypress/integration/homepage.spec.js
quickwit-ui/src/utils/models.ts
quickwit-ui/src/views/ClusterMembersView.tsx

Display cluster ID in logs and UI. Fixes #1315.
Before:
```
2022-06-01T21:35:04.479Z  INFO quickwit_cluster::cluster: Create new cluster. member=Member { node_unique_id: "node-green-PJji", generation: 1654119304, gossip_public_address: 127.0.0.1:7280, is_self: true } listen_addr=127.0.0.1:7280
2022-06-01T21:35:04.480Z
```
After:
```
2022-06-01T22:03:25.197Z  INFO quickwit_cluster::cluster: Joining cluster. cluster_id=quickwit-default-cluster node_id=node-nameless-HM3k listen_address=127.0.0.1:7280 gossip_address=127.0.0.1:7280
```

Display cluster ID in logs and UI

---

quickwit-cli/build.rs
quickwit-cli/src/main.rs

Display target in `quickwit --version` command output. Fixes #1588.
```bash
$ cargo run -- --version
Quickwit 0.3.0-nightly (x86_64-unknown-linux-gnu 8c554bd9d 2022-06-01)
```

Display target in `quickwit --version` command output

---

quickwit-cli/src/split.rs

Display split state in `split list` command output. Fixes #1590.

Display split state in `split list` command output

---

quickwit-storage/src/object_storage/s3_compatible_storage.rs

Strip trailing slash from custom S3 endpoint URL. Fixes #1595.

Strip trailing slash from custom S3 endpoint URL

---

Cargo.lock
quickwit-aws/Cargo.toml
quickwit-indexing/Cargo.toml
quickwit-storage/Cargo.toml
quickwit-storage/src/object_storage/s3_compatible_storage.rs

Disables http2 to fix bug with gcloud
Google cloud storage allows http2, but hyper's http2 client
does not seem to support it properly, leading to an error.
This PR manually disables http2.
Closes #1584

force http1

---

Cargo.lock
quickwit-aws/Cargo.toml
quickwit-aws/src/lib.rs
quickwit-indexing/src/source/kinesis/api.rs
quickwit-indexing/src/source/kinesis/helpers.rs
quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit-indexing/src/source/kinesis/mod.rs
quickwit-storage/Cargo.toml
quickwit-storage/src/object_storage/s3_compatible_storage.rs

This solve a bug observed in CI.
Since we upgrade rusoto, by default, its http client does not allow
http (as opposed to https) connections.
This was spotted and fixed for the S3 storage unix test, but the problem
is still there for Kinesis.
This PR makes sure that both kinesis and s3 actually use the same code
to create their http client.
It also shares the logic used to get credentials.

Factorized the http client and the credential provider used in rusoto.

---

quickwit-cli/src/index.rs
quickwit-cli/tests/cli.rs
quickwit-core/src/index.rs
quickwit-core/src/lib.rs
quickwit-indexing/src/actors/indexing_service.rs
quickwit-indexing/src/actors/mod.rs

Deletes the local indexing directory for an index when the index is removed.
Closes https://github.com/quickwit-oss/quickwit/issues/1569

Clean indexing directory

---

quickwit-ui/src/components/ApiUrlFooter.tsx

implemented a fallback when the user is not in a secure context to be able to copy the API Url to clipboard.
Closes https://github.com/quickwit-oss/quickwit/issues/1628

Fix Copy ApiURL to clipboard

---

quickwit-cli/src/split.rs

```
quickwit-indices quickwit split describe --index air_quality --config=quickwit.yaml --split 01G380H2WYF5H0PGX52HYW89TD --verbose
Split
+----------------------------+----------+-----------+--------------------------------+--------------------------------+------------+
|             ID             | Num docs | Size (MB) |           Created at           |           Updated at           | Time range |
+----------------------------+----------+-----------+--------------------------------+--------------------------------+------------+
| 01G380H2WYF5H0PGX52HYW89TD | 1000062  | 388       | 2022-05-17 3:21:12.0 +00:00:00 | 2022-05-17 3:21:12.0 +00:00:00 | [*]        |
+----------------------------+----------+-----------+--------------------------------+--------------------------------+---------- …
```

use tabled for split describe

---

quickwit-actors/src/mailbox.rs
quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit-indexing/src/actors/mod.rs
quickwit-indexing/src/actors/publisher.rs
quickwit-indexing/src/actors/sequencer.rs
quickwit-indexing/src/actors/uploader.rs

File uploads are done concurrently.
They may end in a different order than they started.
Before this PR, maintaining the ordering was the job of the publisher.
After this PR, this sequencing logic is done by a dedicated actor
called Sequencer.
The purpose of this PR is to pave the way to make the Publisher a
singleton Service/Actor (as opposed to one actor per index).
We do not want to observe orders for all indices.
One slow upload on one index does not need to delay the publication of
split for all indices. It was therefore necessary to keep the sequencing
within the per-index indexing pipeline.
Besides, it separate the concern, and makes the unit test & logic much
cleaner.

Introducing a sequencer actor.

---

README.md

Fix expired link to index config doc in README.

Fix expired link to index config doc in README

---

CHANGELOG.md
Cargo.lock
quickwit-actors/Cargo.toml
quickwit-aws/Cargo.toml
quickwit-cli/Cargo.toml
quickwit-cluster/Cargo.toml
quickwit-common/Cargo.toml
quickwit-config/Cargo.toml
quickwit-core/Cargo.toml
quickwit-directories/Cargo.toml
quickwit-doc-mapper/Cargo.toml
quickwit-indexing/Cargo.toml
quickwit-ingest-api/Cargo.toml
quickwit-metastore/Cargo.toml
quickwit-proto/Cargo.toml
quickwit-search/Cargo.toml
quickwit-serve/Cargo.toml
quickwit-storage/Cargo.toml
quickwit-telemetry/Cargo.toml
scripts/release.sh

Release Quickwit 0.3.1:
- updated CHANGELOG
- cleaned up Cargo.toml files
- added release script for bumping Quickwit version
- bumped Quickwit from 0.3.0 to 0.3.1
- GH Archive tuto

Release Quickwit 0.3.1

---

.dockerignore
.github/actions/build-docker/action.yml
Dockerfile
Makefile
config/quickwit.yaml
distribution/docker/alpine/Dockerfile
quickwit-cli/src/index.rs
quickwit-cli/src/service.rs
quickwit-cluster/src/cluster.rs
quickwit-cluster/src/lib.rs
quickwit-common/src/net.rs
quickwit-common/src/uri.rs
quickwit-config/src/config.rs
quickwit-core/src/index.rs
quickwit-indexing/src/lib.rs
quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit-search/src/lib.rs
quickwit-search/src/search_client_pool.rs
quickwit-serve/src/grpc.rs
quickwit-serve/src/lib.rs
quickwit-serve/src/rest.rs
quickwit-storage/src/storage_resolver.rs
quickwit-ui/Makefile

Add misc. fixes for Kubernetes support;
- pass non-resolved peer seed addresses to Chitchat
- pass public gRPC address to Chitchat
- add overrides for cluster ID, node ID, ... to `quickwit run` command
- misc. cleanups
- Ran on local Minikube cluster

Add misc. fixes for Kubernetes support

---

docs/get-started/quickstart.md

When performing "Create your first index" on quickstart, I noticed that the config file name specified in the CLI command was different from the config file name displayed.

small fix setting filename in "quickstart.md "

---

quickwit-storage/Cargo.toml
quickwit-storage/src/cache/memory_sized_cache.rs
quickwit-storage/src/cache/mod.rs
quickwit-storage/src/cache/quickwit_cache.rs
quickwit-storage/src/cache/stored_item.rs

The new policy is like LRU, except we avoid admitting
a new item if it would mean evicting an item that has been accessed
in the last 60s.
The goal is to behave better on scan access patterns, without being as aggressive as
using a MRU strategy.
Closes #1714

Tweaking cache eviction policy to help with super large queries.

---

Cargo.lock
config/quickwit.yaml
quickwit-cluster/src/lib.rs
quickwit-common/Cargo.toml
quickwit-common/src/net.rs
quickwit-config/src/config.rs

- Add public IP to node config
- Infer public IP from network interfaces if necessary.
Fixes #1661
This is what [memberlist](https://github.com/hashicorp/memberlist/blob/696ff46201c1b64d31b60d57971d07d8cf15df7a/net_transport.go#L130) does:
1. Use public IP from env var or config if provided
2. Use any private IP from network interfaces if listen address is unspecified (`0.0.0.0`)
3. Use `listen_address`.
- Tested on my machine

Make advertise IP configurable and sniff it when necessary

---

quickwit-search/src/collector.rs
quickwit-search/src/filters.rs
quickwit-search/src/search_stream/collector.rs
quickwit-search/src/search_stream/leaf.rs

Closes #1751
Related to #1749 (does not address the case where the entire split is
within the timestamp bounds)

Improve fast field warm up logic

---

quickwit-ingest-api/src/queue.rs

We are using one column family per index and a shared WAL for
all column family.
RocksDB seem to not being able to truncate the WAL itself
on delete range unfortunately, and the default policy tends
to be per-cf which leads to a very high disk usage
when using a lot of indexes.
This PR force flush once the WAL reaches 100MB.
This is quite low, to avoid the push service to block
for too long.

RocksDB configuration.

---

Cargo.lock
quickwit-indexing/src/actors/indexer.rs
quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit-indexing/src/actors/merge_executor.rs
quickwit-indexing/src/actors/packager.rs
quickwit-indexing/src/actors/publisher.rs
quickwit-indexing/src/actors/uploader.rs
quickwit-indexing/src/models/indexed_split.rs
quickwit-indexing/src/models/mod.rs
quickwit-indexing/src/models/packaged_split.rs
quickwit-indexing/src/models/publisher_message.rs
quickwit-indexing/src/models/raw_doc_batch.rs
quickwit-indexing/src/source/file_source.rs
quickwit-indexing/src/source/ingest_api_source.rs
quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit-indexing/src/source/vec_source.rs
quickwit-metastore/src/backward_compatibility_tests/index_metadata.rs
quickwit-metastore/src/checkpoint.rs
quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index.rs
quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit-metastore/src/metastore/mod.rs
quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit-metastore/src/tests.rs

Refactoring to prepare partitioning.
- NewSplit and Replace messages are merged.
- Delta is extracted from the IndexedSplitmessage
- Added a CheckpointDelta / SourceCheckpointDelta distinction.
- Moved source_id into the checkpoint delta.

First stab: extracting the checkpoint delta from the indexed split.

---

quickwit-config/resources/tests/source_config/kafka-source.json
quickwit-config/src/source_config.rs
quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit-metastore/src/backward_compatibility_tests/index_metadata.rs

Simplify tokio select loop using  `consumer.recv()` directly rather than `consumer.stream()`
Ran Kafka source on an empty topic.

[Kafka source] Use `consumer.recv()` directly rather than `consumer.stream()`

---

install.sh

- Removed options for non-pre-built binaries architecture from install script
Closes https://github.com/quickwit-oss/quickwit/issues/1808

Updated Install script

---

.localstack/init.sh
Makefile
docker-compose.yml

I've been running the tests on an M1 Mac and Docker may not have the best performance in this scenario. The tests pass for me about 20% of the time with various failures due to latency issues. This PR fixes one particular issue that I was seeing in the startup of the localstack container. The container runs the script that creates the bucket in the background which meant the container would be considered up and the tests would start running before the bucket was actually created. There is a surprising amount of latency in the bucket creation on my machine. Once the bucket gets created successfully the problem tests will pass but stopping the docker services will bring the issue back.
```
make test-all
make docker-compose-down
make test-all
```

Improve the reliability of the localstack container startup for tests

---

.github/workflows/coverage.yml
Dockerfile

Somehow `protoc` is no longer available when building Quickwit. I suspect this has to do with #1820, but I don't really have the time to investigate further. So, installing `protoc` manually moving forward.
Built Docker image locally/

Fix proto build

---

Cargo.lock
quickwit-cli/Cargo.toml
quickwit-cli/src/index.rs
quickwit-cli/src/lib.rs
quickwit-cli/src/service.rs
quickwit-cli/src/source.rs
quickwit-cli/src/split.rs
quickwit-cli/src/template.rs
quickwit-cluster/src/lib.rs
quickwit-common/Cargo.toml
quickwit-common/src/net.rs
quickwit-common/src/uri.rs
quickwit-config/Cargo.toml
quickwit-config/resources/tests/config/quickwit.json
quickwit-config/resources/tests/config/quickwit.toml
quickwit-config/resources/tests/config/quickwit.yaml
quickwit-config/src/config.rs
quickwit-config/src/index_config.rs
quickwit-config/src/lib.rs
quickwit-config/src/templating.rs
quickwit-indexing/Cargo.toml
quickwit-search/src/search_stream/leaf.rs
quickwit-serve/Cargo.toml
quickwit-serve/src/lib.rs
quickwit-serve/src/node_info_handler.rs

Closes #1011, #1742 
This PR separates the `QuickwitConfig` into two structs: `QuickwitConfig` and `QuickwitConfigObject`, and adds templating support to config files.
- `QuickwitConfig` is now only responsible for deserializing data. All other logic (value transformations, checking validities, accessing values) are transferred to `QuickwitConfigObject`
- `QuickwitConfigObject` does not have any accessor functions (one exception is `peer_seed_addrs` for DNS resolution purposes); instead, all of the required config values are generated when the config is initialized.
- All of the `QuickwitConfig` accesses are changed to `QuickwitConfigObject`.
- `StorageConfig` is removed because it is currently not used.
- Added templating support with docker-like syntax. For example:
> quickwit.yaml
> …

Decouple configuration parsing logic from validation and transformation

---

quickwit-cluster/src/cluster.rs
quickwit-cluster/src/lib.rs
quickwit-search/src/lib.rs
quickwit-search/src/search_client_pool.rs

Refactor a bit how we build cluster members and how we use it.
One benefit is that you can define the search client pool without depending on `Cluster` and thus `Chitchat`. This is nice for testing purposes. This will help me to test the upcoming `MetastoreService`.
Waiting for `make test-all` results...

Enrich cluster member struct with services and gRPC address.

---

quickwit-cluster/src/lib.rs

Bug introduced in my previous PR #1838.
No test failed on this :/

Fix wrong gossip advertise addr set when starting the cluster.

---

quickwit-config/src/config.rs
quickwit-config/src/lib.rs
quickwit-search/src/fetch_docs.rs
quickwit-search/src/leaf.rs
quickwit-search/src/lib.rs
quickwit-search/src/search_stream/leaf.rs
quickwit-search/src/service.rs
quickwit-search/src/tests.rs
quickwit-storage/src/cache/mod.rs
quickwit-storage/src/cache/quickwit_cache.rs
quickwit-storage/src/cache/storage_with_cache.rs
quickwit-storage/src/lib.rs

I think it would be nice to remove all these once cells for a bunch of parameters, caching and semaphores.
What do you think?
I need to clean a bit the code but you will get the idea.
`make test-all` passing except for kafka but I need to check if I have the same issue on main.

Add a search context to search queries.

---

Cargo.lock
quickwit-doc-mapper/Cargo.toml
quickwit-doc-mapper/src/routing_expression/mod.rs
quickwit-indexing/src/actors/indexer.rs
quickwit-indexing/src/actors/merge_executor.rs
quickwit-indexing/src/actors/merge_planner.rs
quickwit-indexing/src/actors/mod.rs
quickwit-indexing/src/actors/packager.rs
quickwit-indexing/src/actors/uploader.rs
quickwit-indexing/src/models/indexed_split.rs
quickwit-indexing/src/models/packaged_split.rs
quickwit-indexing/src/test_utils.rs
quickwit-metastore/src/backward_compatibility_tests/split_metadata.rs
quickwit-metastore/src/split_metadata.rs
quickwit-metastore/src/split_metadata_version.rs
quickwit-metastore/src/tests.rs
quickwit-metastore/test-data/file-backed-index/v0-41c287d5b41d3247e3394574c7f3618c.expected.json
quickwit-metastore/test-data/file-backed-index/v0-6e3177e8924ef49dbdd8dcac421b0642.expected.json
quickwit-metastore/test-data/file-backed-index/v0-7ccb0811468081880595c160fa16fef7.expected.json
quickwit-metastore/test-data/file-backed-index/v0-7e1e1d06f4d5d051134c6ec82c09a55f.expected.json
quickwit-metastore/test-data/file-backed-index/v0-92a02bbda38485cfb39171b0b2fee51f.expected.json
quickwit-metastore/test-data/file-backed-index/v0-f4bcb5a22eb3fb4f663463adb38a057b.expected.json
quickwit-metastore/test-data/split-metadata/v0-a56cdae1f7333d023f1d6303ed5fd301.expected.json
quickwit-metastore/test-data/split-metadata/v0-noversion.expected.json
quickwit-metastore/test-data/split-metadata/v1-3fa70f6513f800c681c0c317d89d4298.expected.json
quickwit-metastore/test-data/split-metadata/v1-b9a036ccc850646c89bc008c65c4249f.expected.json
quickwit-metastore/test-data/split-metadata/v1-c7b54a9dfd9b75174914d063df366aa6.expected.json
quickwit-metastore/test-data/split-metadata/v1-c7b54a9dfd9b75174914d063df366aa6.json

Added partition_id to split metadata data.
The `partition_id` is required for the merge planner to avoid
merging  splits with different `partition_id`.
Related to #1796 and #1795
This PR also changes the hasher for the SipHasher, since nothing
ensures that the implementation of the DefaultHasher won't change
in the future.
Finally, it seeds the hash using the expression itself, to avoid
a class of collisions that could happpen with a change in the partition
logic.

Added partition_id to split metadata data.

---

Cargo.lock
quickwit-cli/Cargo.toml

yaml feature of clap is not used
`cargo test`

remove unused feature

---

Cargo.lock
config/quickwit.yaml
config/tutorials/gh-archive/index-config.yaml
quickwit-actors/src/envelope.rs
quickwit-actors/src/mailbox.rs
quickwit-indexing/Cargo.toml
quickwit-indexing/src/actors/indexer.rs
quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit-indexing/src/source/file_source.rs
quickwit-indexing/src/source/ingest_api_source.rs
quickwit-indexing/src/source/kafka_source.rs
quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit-indexing/src/source/mod.rs
quickwit-indexing/src/source/source_factory.rs
quickwit-indexing/src/source/vec_source.rs
quickwit-indexing/src/source/void_source.rs
quickwit-metastore/src/checkpoint.rs
quickwit-metastore/src/lib.rs
quickwit-metastore/src/split_metadata.rs
quickwit-storage/src/storage_resolver.rs

I moved the event handling logic into the main actor using sync channels in the consumer context. This simplifies the code, removes the need for messing with the tokio runtime, and makes testing easier.
Pending

Handle rebalance events in source rather than consumer context

---

docs/guides/schemaless.md

Caught a minor error while linking the doc, gave the file a quick look :)

Fix typo in schemaless guide

---

quickwit-cluster/src/lib.rs

Cluster setup was losing the advertise address set in `QW_ADVERTISE_ADDRESS` which prevents the cluster from working in K8s with a separate Metastore process.
```
2022-09-02T16:25:44.514Z  INFO quickwit_config::config: Using advertise address from environment variable `QW_ADVERTISE_ADDRESS`. advertise_address=192.168.86.168
...
2022-09-02T16:25:44.519Z  INFO quickwit_cluster::cluster: Joining cluster. cluster_id=quickwit-default-cluster node_id=node-1 grpc_public_addr=127.0.0.1:7281 available_services={Indexer, Searcher, Metastore} gossip_listen_addr=127.0.0.1:7280 gossip_public_addr=192.168.86.168:7280 peer_seed_addrs=
```
```
make test-all
```
Manual testing to confirm correct address shows up.
```
2022-09-02T16:11:03.488Z  INFO quickwit_config::config: Using advertise address from …
```

Cluster setup not using the correct advertise address for grpc

---

quickwit-cli/src/index.rs
quickwit-cli/src/main.rs
quickwit-cli/tests/cli.rs
quickwit-core/src/index.rs
quickwit-metastore/src/metastore/mod.rs

Improve CLI docs and add prompt to confirm overwrite. By default, the answer is no.
A flag "-y --assume-yes" is here  
I like having a better XP on the CLI. Unfortunately, the current code I introduce is lame as it's very specific to one command.
I think other risky operations should behave the same way. 
With the current tests.

Improved CLI docs and add prompt to confirm index create overwrite.

---

quickwit/Cargo.lock
quickwit/quickwit-actors/src/tests.rs
quickwit/quickwit-core/Cargo.toml
quickwit/quickwit-directories/Cargo.toml
quickwit/quickwit-doc-mapper/Cargo.toml
quickwit/quickwit-indexing/Cargo.toml
quickwit/quickwit-indexing/README.md
quickwit/quickwit-indexing/src/actors/doc_processor.rs
quickwit/quickwit-indexing/src/actors/index_serializer.rs
quickwit/quickwit-indexing/src/actors/indexer.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/actors/mod.rs
quickwit/quickwit-indexing/src/actors/packager.rs
quickwit/quickwit-indexing/src/models/indexed_split.rs
quickwit/quickwit-indexing/src/models/indexing_statistics.rs
quickwit/quickwit-indexing/src/models/mod.rs
quickwit/quickwit-indexing/src/models/prepared_doc.rs
quickwit/quickwit-indexing/src/models/publish_lock.rs
quickwit/quickwit-indexing/src/source/file_source.rs
quickwit/quickwit-indexing/src/source/ingest_api_source.rs
quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/source/vec_source.rs
quickwit/quickwit-indexing/src/source/void_source.rs
quickwit/quickwit-janitor/Cargo.toml
quickwit/quickwit-metastore/src/backward_compatibility_tests/index_metadata.rs
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-storage/Cargo.toml

This PR changes the threading model of indexing in order to deal with high number of partitions.
- building tantivy document was done in the indexer task
- updating the in-memory datastructure used to build the index was done in an index spawned by tantivy's IndexWriter. One index per-partition. <- this was the problematic part.
- docstore building (mostly zstd compression) was also done on a tantivy dedicated thread.
- index serialization (tantivy's `index_writer::commit`) was done in the packager.
- building tantivy document was done in a different actor called DocProcessor
- updating the in-memory datastructure used to build the index is done in the indexer taks directly, using a new API added in tantivy.
- docstore building (mostly zstd compression) is still done in a tantivy …

Partition friendly threading model for indexing.

---

.github/workflows/coverage.yml
docker-compose.yml

Before this upgrade, I was not able to get the Kafka and ZooKeeper containers in healthy mode on my M2. This upgrade seems to fix my issue.

Upgrade Kafka and ZooKeeper Docker images to Confluent 7.2.1

---

quickwit/quickwit-actors/src/actor_handle.rs
quickwit/quickwit-actors/src/command.rs
quickwit/quickwit-actors/src/supervisor.rs

After removing the use of the Kill message,
some actors could be stuck awaiting for a message, and never checking for possible message.
Relying on a Kill message is not an option, due to the recycling of mailbox introduced in the supervisor PR.
The fix consists in adding a Nudge message that
is No-op.

Failpoint test fix.

---

quickwit/quickwit-config/src/config.rs

Make QuickwitConfig `data_dir` to accept both file protocol uris and path.
Closes https://github.com/quickwit-oss/quickwit/issues/1996

Make QuickwitConfig.data_dir_path accept file://

---

quickwit/quickwit-config/src/config.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/lib.rs
quickwit/quickwit-indexing/src/split_store/indexing_split_store.rs
quickwit/quickwit-indexing/src/split_store/local_split_store.rs
quickwit/quickwit-indexing/src/split_store/mod.rs

Implemented a `SplitStoreSpaceQuota` that is shared across SplitStores
Closes https://github.com/quickwit-oss/quickwit/issues/855

Fix SplitStore size constraints

---

quickwit/quickwit-actors/src/tests.rs
quickwit/quickwit-indexing/src/source/mod.rs

Attempt to fix source actor timeout reported in #2004. Recording progress after each pass through the `emit_batches` method seems to fix the issue, but I feel like this problem should be addressed in the actor framework, so I attempted to reproduce the bug in a unit test in the actors' crate. Without success, alas.
Successfully spawned 50 indexing pipelines consuming an empty topic on my local branch. I was not able to do so on `main`.

Fix source actor timeout

---

quickwit/quickwit-actors/benches/bench.rs

in actors bench.
```
cargo clippy --all-targets --tests
Checking quickwit-actors v0.3.1 (/Users/fmassot/Documents/quickwit/repos/quickwit-2/quickwit/quickwit-actors)
warning: redundant pattern matching, consider using `is_ok()`
--> quickwit-actors/benches/bench.rs:96:19
|
96 |         while let Ok(_) = rx.recv().await {
|         ----------^^^^^------------------ help: try this: `while (rx.recv().await).is_ok()`
|
= note: `#[warn(clippy::redundant_pattern_matching)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pattern_matching
warning: `quickwit-actors` (bench "bench") generated 1 warning
Finished dev [unoptimized] target(s) in 0.55s
```

Please clippy.

---

quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-cluster/src/lib.rs
quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs
quickwit/quickwit-search/src/search_client_pool.rs
quickwit/quickwit-serve/src/cluster_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-serve/src/test_utils/rest_client.rs
quickwit/quickwit-serve/src/tests.rs

Fix #1982.
And I also changed a bit the way we use the member watcher.
Note:  the current watcher is broken if we want to use up-to-date properties of cluster members. Example: we start a node with the server `searcher` and restart afterward with another server. Chitchat will probably not detect a change in readiness and the member watcher of other nodes will not receive member changes. And the other nodes will have their search pool with this no-more searcher node.
PTAL.

Fix and clean cluster members.

---

quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs
quickwit/quickwit-janitor/src/actors/delete_task_service.rs
quickwit/quickwit-janitor/src/actors/mod.rs
quickwit/quickwit-janitor/src/janitor_service.rs
quickwit/quickwit-metastore/test-data/file-backed-index/v0-b3d35a1f7e54163927ae797e03ecb6ba.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0-b3d35a1f7e54163927ae797e03ecb6ba.json
quickwit/quickwit-proto/build.rs
quickwit/quickwit-proto/src/quickwit_metastore_api.rs
quickwit/quickwit-serve/Cargo.toml
quickwit/quickwit-serve/src/delete_task_api/handler.rs
quickwit/quickwit-serve/src/delete_task_api/mod.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/rest.rs

Fix #1939 
Two endpoints were added:
- GET `/api/v1/{index-id}/delete-tasks` returns all delete tasks of a given index.
- POST `/api/v1/{index-id}/delete-tasks` create a new delete task. The payload is a dedicated `DeleteQueryRequest` and the created `DeleteTask` is returned.
There is one current limitation that we should track in a dedicated issue: when a user create a delete task, we do not immediately trigger a refresh on the delete task planner, the user will have to wait 60 seconds before seeing some planned delete operations.

Add delete query REST API.

---

quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/merge_policy/mod.rs
quickwit/quickwit-indexing/src/merge_policy/nop_merge_policy.rs
quickwit/quickwit-indexing/src/models/indexing_directory.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/split_store/local_split_store.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs

Limit the number of indexing pipelines that can be spawned concurrently.

Limit the number of indexing pipelines that can be spawned concurrently.

---

quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs

Found a bug as I was implementing support for `unix_ts_nanos` for OpenTelemetry.
Added unit test.

Fix datetime parsing when using strftime format

---

quickwit/quickwit-indexing/Cargo.toml
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/mod.rs
quickwit/quickwit-indexing/src/actors/publisher.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-indexing/src/lib.rs
quickwit/quickwit-indexing/src/models/mod.rs
quickwit/quickwit-indexing/src/models/publisher_message.rs
quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs

Fix #1940 
This PR updates the `Uploader` actor to bypass the `Sequencer` when it's not needed (that is for merge & delete pipelines).
It's still a draft as I need to add a test. Even if the code is not "beautiful" as I'm just using enums to handle the case where we use the sequencer and the case where we use the publisher, I think it's worth it as it removes the sequencer from 2 pipelines.

Remove sequencer from merge pipelines.

---

quickwit/quickwit-actors/src/actor.rs
quickwit/quickwit-actors/src/envelope.rs
quickwit/quickwit-actors/src/spawn_builder.rs
quickwit/quickwit-indexing/src/actors/index_serializer.rs
quickwit/quickwit-indexing/src/actors/indexer.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/actors/merge_split_downloader.rs
quickwit/quickwit-indexing/src/actors/packager.rs
quickwit/quickwit-indexing/src/actors/publisher.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-indexing/src/merge_policy/mod.rs
quickwit/quickwit-indexing/src/models/indexed_split.rs
quickwit/quickwit-indexing/src/models/packaged_split.rs
quickwit/quickwit-indexing/src/models/publisher_message.rs
quickwit/quickwit-indexing/src/split_store/indexing_split_store.rs

Closes #2055 
Before this PR actors would be executed on a root span that was
associated to their execution loop.
That span would be gigantic and would never be closed.
In addition, the message spans did not have any associated name by
default. This solution made logs that looked good in stdout but were
terribly broken when consumed as traces in a tool like jaeger.
The following PR fixes the issue by removing the crazy root span.
It also does something a tiny bit more ambitious by creating a root span
per indexing batch. The batch follows the split, so that it is easier
to inspect how a trip travels through the indexing pipeline.
It is also possible to see the associated context, timings etc.
for each split creation or merge operation.
Closes …

Fixes tracing in indexing

---

docs/configuration/index-config.md
quickwit/Cargo.lock
quickwit/quickwit-doc-mapper/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_parsing.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/lib.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs

- Simplify logic for parsing and validating input formats
- Improved parsing performance
- Removed `unix_ts_secs` as default input format
- Added a bunch of unit tests
```sh
cargo test --manifest-path quickwit/Cargo.toml -p quickwit-doc-mapper
```

Refactor datetime type logic

---

config/quickwit.yaml
config/tutorials/otel-trace/index-config.yaml
quickwit/Cargo.lock
quickwit/quickwit-opentelemetry/Cargo.toml
quickwit/quickwit-opentelemetry/src/otlp/trace.rs
quickwit/quickwit-proto/build.rs
quickwit/quickwit-proto/src/opentelemetry.proto.collector.logs.v1.rs
quickwit/quickwit-proto/src/opentelemetry.proto.collector.trace.v1.rs
quickwit/quickwit-proto/src/opentelemetry.proto.common.v1.rs
quickwit/quickwit-proto/src/opentelemetry.proto.logs.v1.rs
quickwit/quickwit-proto/src/opentelemetry.proto.resource.v1.rs
quickwit/quickwit-proto/src/opentelemetry.proto.trace.v1.rs
quickwit/quickwit-serve/src/grpc.rs

Per title.
```
QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER=1 QW_ENABLE_OPENTELEMETRY_OTLP_SERVICE=true OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:7281 RUST_BACKTRACE=1 RUST_LOG=info,quickwit=info,quickwit_jaeger=debug cargo run --manifest-path quickwit/Cargo.toml --all-features -- index create --index-config config/tutorials/otel-trace/index-config.yaml --overwrite --yes
```
then
```
QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER=1 QW_ENABLE_OPENTELEMETRY_OTLP_SERVICE=true OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:7281 RUST_BACKTRACE=1 RUST_LOG=info,quickwit=info,quickwit_jaeger=debug cargo run --manifest-path quickwit/Cargo.toml --all-features -- run
```

Implement dummy OpenTelemetry OTLP service for ingesting traces

---

quickwit/quickwit-indexing/src/actors/indexing_service.rs

Caching merge policy is useless and adds a bit of noise in the code. Their construction is more or less free.

Refactoring: Stop caching MergePolicy object.

---

quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-config/src/source_config.rs
quickwit/quickwit-indexing/src/source/mod.rs

Changed some internal object id prefix from  `.` to `_`
Closes https://github.com/quickwit-oss/quickwit/issues/2069

Fix internal objects id prefix

---

docs/configuration/node-config.md
quickwit/quickwit-config/resources/tests/config/quickwit.json
quickwit/quickwit-config/resources/tests/config/quickwit.toml
quickwit/quickwit-config/resources/tests/config/quickwit.yaml
quickwit/quickwit-config/src/config.rs
quickwit/quickwit-config/src/index_config.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs
quickwit/quickwit-janitor/src/actors/delete_task_service.rs
quickwit/quickwit-janitor/src/lib.rs
quickwit/quickwit-serve/src/delete_task_api/handler.rs

Added `max_concurrent_split_upload` config parameter to IndexerConfig
Closes https://github.com/quickwit-oss/quickwit/issues/2080

Make max concurrent split upload configurable

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-common/src/fs.rs
quickwit/quickwit-core/src/index.rs
quickwit/quickwit-core/src/lib.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/ingest_api_garbage_collector.rs
quickwit/quickwit-indexing/src/actors/merge_split_downloader.rs
quickwit/quickwit-indexing/src/lib.rs
quickwit/quickwit-indexing/src/models/indexing_directory.rs
quickwit/quickwit-indexing/src/models/mod.rs
quickwit/quickwit-indexing/src/split_store/indexing_split_store.rs
quickwit/quickwit-indexing/src/split_store/local_split_store.rs
quickwit/quickwit-indexing/src/split_store/mod.rs
quickwit/quickwit-indexing/src/split_store/split_store_quota.rs
quickwit/quickwit-indexing/src/test_utils.rs
quickwit/quickwit-storage/src/split.rs

It was tested via unit testing and by indexing wikipedia, and looking at the evolution of the datadir/cache directory.
`--keep-cache` was tested too.
After the fix, there is only one split cache shared
by all of the indexes.
Splits are all stored without any specific hierarchy in the
`data_dir/cache` directory.
The split cache evicts oldest splits first, and introduces
an extra constraint on the creation date to make sure
dangling splits eventually get removed even when the split is not under
capacity pressure.
---
The Local Split Store is a local cache used to improve the performance of indexing nodes.
Its purpose is simple: when a new split is freshly created, it is usely merged
very rapidly after.
In order to prevent this merge to force its download, we store it in the …

Issue/2022     Simplifies and fixes the local split cache.

---

quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/tests.rs
quickwit/quickwit-metastore/test-data/index-metadata/v2-530db64d96f5702110983c32d628efa6.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v2-530db64d96f5702110983c32d628efa6.json

Currently, it's very easy to not get any stale splits if there are more than 100 immature splits... which can happen very easily.
This PR tries to mitigate the issue by:
- fetch 1000 splits
- order splits also by publishing date (it was already ordered by delete_opstamp) to get old split first
I put a longer polling loop on the delete task planner to avoid sending the same operations twice or even more.

Improve fetch of stale splits.

---

quickwit/quickwit-actors/src/actor.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs

.progress() is quite confusing. It just returns a `Progress` object. I added a `must_use` attribute to prevent misuse in the future.

Bugfix: Replacing .progress() where .record_progress() was meant

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_type.rs
quickwit/quickwit-indexing/src/actors/doc_processor.rs
quickwit/quickwit-search/src/tests.rs

Changed the `Cargo.toml` to point a more recent version of tantivy which serialises the bytes field correctly now.
A check was added in `test_single_node_simple` in `quickwit-search/src/tests.rs` with a bytes field and updated all tests to match this behaviour.

Update tantivy to allow bytes field indexing

---

quickwit/quickwit-indexing/src/actors/merge_executor.rs

Test updated to check if num_merge_ops is unchanged.
Two `record_progress` were added too as I got some actor timeout error during my tests.

Fix merge_num_ops set on a split after a delete operation.

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/models/indexing_service_message.rs

Fix #2062 and partially #1981
Partially because the logs end up like this:
```
2022-10-19T18:45:18.936Z  INFO quickwit_actors::spawn_builder: actor-exit actor_id=IndexingPipeline-twilight-8Ygs exit_status=Success
2022-10-19T18:45:18.938Z  INFO quickwit_actors::spawn_builder: actor-exit actor_id=quickwit_indexing::actors::indexing_service::IndexingService-blue-Swh0 exit_status=Quit
2022-10-19T18:45:18.938Z ERROR quickwit_actors::actor: actor-failure actor_name="quickwit_indexing::actors::indexing_service::IndexingService-blue-Swh0" actor_exit_status=Quit
2022-10-19T18:45:19.939Z  INFO quickwit_actors::spawn_builder: actor-exit actor_id=Scheduler-icy-gsOt exit_status=Killed
2022-10-19T18:45:19.939Z ERROR quickwit_actors::actor: actor-failure actor_name="Scheduler-icy-gsOt" …
```

Fix merge CLI command.

---

quickwit/quickwit-indexing/src/split_store/indexing_split_store.rs
quickwit/quickwit-storage/src/bundle_storage.rs
quickwit/quickwit-storage/src/cache/storage_with_cache.rs
quickwit/quickwit-storage/src/debouncer.rs
quickwit/quickwit-storage/src/local_file_storage.rs
quickwit/quickwit-storage/src/object_storage/azure_compatible_storage.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs
quickwit/quickwit-storage/src/prefix_storage.rs
quickwit/quickwit-storage/src/ram_storage.rs
quickwit/quickwit-storage/src/storage.rs
quickwit/quickwit-storage/tests/azure_storage.rs

We want to be able to add some throttling to the
download of merge splits.
The current Storage API does not make that possible. This PR adds a new method called `.copy_to` that
target an `AsyncWrite` rather than a `File` as a
destination.

Added a copy_to method to the Storage.

---

quickwit/quickwit-metastore/migrations/postgresql/2_create-splits.up.sql
quickwit/quickwit-metastore/migrations/postgresql/6_delete-update-index-update-timestamp-on-split-update-trigger.up.sql

Restore the initial migration file and drop the trigger in another migration.
Ran the up migration on an erroring database.

Fix database migrations

---

quickwit/quickwit-cli/src/cli.rs
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/source.rs
quickwit/quickwit-cli/src/split.rs

Fix CLI inconsistencies:
Try local CLI + run tests
- Fix the display order of some commands (1. config, 2. index, 3. source/split, 4. other options) 
- Add aliases (`ls` for list, `del` for delete, `desc` for describe)
- Remove data-dir when not necessary
close #1320

Fix CLI inconsistencies #1320

---

quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-cli/src/source.rs

Fix #2197
Note: I used transpose to keep the same order of columns/rows.
Output:
```
quickwit source list --index wikipedia  --config ../config/quickwit.yaml
+-------------+------------+---------+
|              Sources               |
+-------------+------------+---------+
| ID          | Type       | Enabled |
+-------------+------------+---------+
| _ingest-api | ingest-api | true    |
+-------------+------------+---------+
```
```
quickwit describe --source _ingest-api --index wikipedia  --config ../config/quickwit.yaml
+---------+-------------+
|        Source         |
+---------+-------------+
| ID      | _ingest-api |
+---------+-------------+
| Type    | ingest-api  |
+---------+-------------+
| Enabled | true        |
+---------+-------------+
+-----+-------+
| Parameters  | …
```

Display source enabled in source describe/list commands.

---

quickwit/quickwit-common/src/runtimes.rs

Our code coverage CI has been failing for a while, and installing `libsasl2` did not solve the issue. The current issue is one of the tests I refactored was throwing an error like this: 
```
test test_ingest_docs_cli ...  Num docs       5 Parse errs     0 PublSplits   1 Input size     0MB Thrghput  0.00MB/s Time 00:00:02
Num docs       5 Parse errs     0 PublSplits   1 Input size     0MB Thrghput  0.00MB/s Time 00:00:03
Num docs       5 Parse errs     0 PublSplits   1 Input size     0MB Thrghput  0.00MB/s Time 00:00:04
ok
test test_ingest_docs_cli_keep_cache ... FAILED
failures:
---- test_ingest_docs_cli_keep_cache stdout ----
---------------------------------------------------
Connectivity checklist 
✔ metastore
✔ storage
✔ _cli-ingest-source
thread 'main' panicked at 'Cannot drop a …
```

Fix tokio runtime error in code coverage

---

docs/configuration/node-config.md
quickwit/quickwit-config/src/config.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
quickwit/quickwit-indexing/src/actors/mod.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-indexing/src/metrics.rs
quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs

Using a different number of concurrent uploads
for the indexing pipeline and the merge pipeline.
This PR also increases the number of concurrent uploads from 4 to 12.
With this setting, the indexing pipeline therefore gets 6 and 6.
Closes #2129

Separating the semaphore limiting concurrent uploads.

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-cli/src/service.rs
quickwit/quickwit-cli/src/source.rs
quickwit/quickwit-cli/src/split.rs
quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-common/src/uri.rs
quickwit/quickwit-config/Cargo.toml
quickwit/quickwit-config/resources/tests/config/quickwit.json
quickwit/quickwit-config/resources/tests/config/quickwit.toml
quickwit/quickwit-config/resources/tests/config/quickwit.yaml
quickwit/quickwit-config/src/config.rs
quickwit/quickwit-config/src/config_value.rs
quickwit/quickwit-config/src/index_config.rs
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/qw_env_vars.rs
quickwit/quickwit-config/src/service.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_format.rs

Set default env variables for main node config parameters such `QW_CLUSTER_ID`, `QW_NODE_ID`. The values are loaded independently from the CLI parameters when the config object is built.
Added a bunch of unit tests.
Try it yourself:
```sh
> QW_CLUSTER_ID="dev-cluster" \
QW_NODE_ID="node-0" \
QW_ENABLED_SERVICES="indexer,searcher,metastore" \
QW_DATA_DIR="qwdata/node-0" \
QW_METASTORE_URI="qwdata/indexes#polling_interval=5s" \
QW_DEFAULT_INDEX_ROOT_URI="qwdata/indexes" \
cargo run --manifest-path quickwit/Cargo.toml --all-features -- run
```

Set default env variables for main node config parameters

---

quickwit/quickwit-search/src/search_response_rest.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

Hoisted snippets field at the top level  of the search rest response.
Closes https://github.com/quickwit-oss/quickwit/issues/2052

Fix search rest response (snippet)

---

quickwit/Cargo.lock
quickwit/quickwit-common/src/metrics.rs
quickwit/quickwit-indexing/src/actors/index_serializer.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/actors/merge_planner.rs
quickwit/quickwit-indexing/src/actors/merge_split_downloader.rs
quickwit/quickwit-indexing/src/actors/packager.rs
quickwit/quickwit-indexing/src/actors/publisher.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-indexing/src/merge_policy/mod.rs
quickwit/quickwit-indexing/src/metrics.rs
quickwit/quickwit-indexing/src/models/indexed_split.rs
quickwit/quickwit-indexing/src/models/merge_scratch.rs
quickwit/quickwit-indexing/src/models/packaged_split.rs
quickwit/quickwit-indexing/src/models/publisher_message.rs
quickwit/quickwit-janitor/Cargo.toml
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
quickwit/quickwit-janitor/src/lib.rs
quickwit/quickwit-janitor/src/metrics.rs

Fix #2136
And:
- add gauges on the number of ongoing merge/delete operations
- add an observable state for merge planner and delete planner. I will add in a separated PR a REST endpoint to retrieve the ongoing delete operations, this can be helpful when checking what's the planner is doing.

Track merge operations in merge and delete planner.

---

quickwit/quickwit-indexing/failpoints/mod.rs

Tested locally
```
cargo test --test failpoints --features fail/failpoints
running 10 tests
test test_merge_executor_controlled_directory_kill_switch ... ok
test test_failpoint_publisher_panics_right_away ... ok
test test_failpoint_no_failure ... ok
test test_failpoint_publisher_panics_after_one_success ... ok
test test_failpoint_uploader_after_panics_right_away ... ok
test test_failpoint_publisher_after_panics_right_away ... ok
test test_failpoint_packager_panics_after_one_success has been running for over 60 seconds
test test_failpoint_packager_panics_right_away has been running for over 60 seconds
test test_failpoint_uploader_panics_after_one_sucess has been running for over 60 seconds
test test_failpoint_uploader_panics_right_away has been running for over 60 seconds
test …
```

Fix failpoint test.

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-common/src/metrics.rs
quickwit/quickwit-metastore/Cargo.toml
quickwit/quickwit-metastore/src/lib.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_metastore_factory.rs
quickwit/quickwit-metastore/src/metastore/instrumented_metastore.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/metrics.rs

- Counts the number of requests for each metastore call.
- Counts the number of failed calls
- Records the duration of the calls.
- Warn on slow call (1s threshold)
- Launched quickwit and visited `http://localhost:7280/metrics`
- Introduced some sleep statements here and there to test the slow call warning
- Introduced some errors to hit the error code path
```
2022-11-03T16:03:46.899Z  WARN quickwit_metastore::metastore::instrumented_metastore: Slow metastore operation. operation="index_metadata" duration_millis=5002 index_id="otel-trace-v0"
```

Instrument metastore calls

---

quickwit/quickwit-janitor/src/garbage_collection.rs
quickwit/quickwit-storage/src/lib.rs

Verifies that the GC drops staged and marked splits after the corresponding grace periods.
:)

Add some gc tests

---

Dockerfile
distribution/docker/alpine/Dockerfile

Remove sed commands from Dockerfiles. We can use `QW_LISTEN_ADDRESS` directly.
```
docker build -t quickwit/quickwit:guilload .
docker run -it quickwit/quickwit:guilload run
2022-11-08T21:19:22.426Z  INFO quickwit_cli: Loaded Quickwit config. config_uri=file:///quickwit/config/quickwit.yaml config=QuickwitConfig { version: 0, cluster_id: "quickwit-default-cluster", node_id: "node-broken-VAOu", enabled_services: {Indexer, Searcher, Janitor, Metastore}, rest_listen_addr: 0.0.0.0:7280
```

Remove sed commands from Dockerfiles

---

quickwit/quickwit-indexing/failpoints/mod.rs

The latest PR by me has inadvertently broken code cov because it uses the old version of `list_splits`, this wasn't picked up in CI because we don't seem to enable the feature. :(

Fix failpoints / code cov

---

quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-cluster/src/lib.rs
quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs
quickwit/quickwit-search/src/search_client_pool.rs
quickwit/quickwit-serve/src/lib.rs

For the umpteenth time this year, I got confused between `node_id`, `node_unique_id`, `NodeId`, `generation`. `enabled_services` vs `available_services` in the cluster code, so I renamed a few attributes and added some comments here and there to hopefully make things easier to read and understand.
Test suite

 Refactor `ClusterMember` and `Cluster::new`

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/Cargo.toml
quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-cli/tests/helpers.rs

This PR finalizes the CLI test suite. With this PR, tests no longer spawn separate processes.
- Refactored `create_logs_index` and `ingest_docs` to run CLI functions.
- Refactored `test_cmd_create`
- Refactored `test_cmd_help`
- Added some helper methods to `TestEnv`
- Removed `assert_cmd` dependency

Refactor helpers in CLI test suite

---

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/tests.rs

Fixes #2281 
This fixes the bug introduced by #2152 and adds unit tests to prevent this error from re-occurring.

QW-2281: Fix timestamp filters for PSQL

---

quickwit/quickwit-storage/src/local_file_storage.rs

We prevent people from using relative path including a `..` in the FileStorage.
Closes #53

Reduce attack surface on the FileStorage.

---

quickwit/quickwit-cli/src/cli.rs
quickwit/quickwit-cli/src/main.rs

This adds the ability to pass a `--no-ansi-logging` flag or `QW_NO_ANSI_LOGGING` environment variable in order to disable tracing_subscriber from injecting ANSI terminal codes, reducing the noise when logging to things like files which do not support rendering the codes.

QW-2273: Add the ability to disable ANSI terminal codes in logging.

---

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs

- Remove transaction from `stage_split`
- Fix `update_index_update_timestamp`
Replayed gRPC requests and observed a 20-15s second improvement (70-75s vs. 90-100s)

Remove transaction from `stage_split`

---

.github/workflows/publish_docker_images.yml
Dockerfile
Makefile
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/Makefile
quickwit/quickwit-cli/src/generate_markdown.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-serve/Cargo.toml
quickwit/quickwit-serve/build.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/node_info_handler.rs
quickwit/quickwit-serve/src/rest.rs

- Allow propagation of commit info to Docker via build args
- Set commit info in CI env and pass to Docker
Ran `make docker-build` locally, launched container, and got following build info:
```json
{
"build_date": "2022-11-12T20:03:31Z",
"build_profile": "release",
"build_target": "aarch64-unknown-linux-gnu",
"cargo_pkg_version": "0.3.1",
"commit_date": "2022-11-12T19:47:59Z",
"commit_hash": "3c5996f75ac08f4711f5ab89e695fbd0e69bde12",
"commit_short_hash": "3c5996f",
"commit_tags": [
"guilload"
],
"version": "0.3.1-nightly"
}
```

Set up build info in Docker env

---

quickwit/quickwit-metastore/migrations/postgresql/7_delete-split-table-triggers.up.sql
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs

While testing and profiling queries on a large database, I notice we still have a few triggers on the splits table that add some additional overhead to each update we perform on the table, although the overhead is not extreme, it is not minimal either.
This PR removes the triggers as we can perform all of the trigger's functions as part of the queries invoking the trigger, some of the logic with the `CASE` statements are probably unnecessary depending on the desired behaviour we want, but I thought it's best not to change the behaviour in this PR.

Remove all `splits` table triggers from the Postgres metastore. 

---

quickwit/quickwit-indexing/src/actors/indexing_service.rs

Ok, this PR is lame... 
The alternative would be to have an assert with a timeout. Maybe we could add this as a util function for our tests. I'm not very fond of it though :/

Wait 2 heartbeats before asserts.

---

docs/reference/cli.md
docs/reference/rest-api.md

Add documentation to stress that timestamps pruning should be specified in seconds and why.
Closes https://github.com/quickwit-oss/quickwit/issues/2140

Document timestamp pruning

---

quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs

Set to 30 seconds.
We are monitoring slow operations on the metastore via logs and metrics so I think it's fine to increase the timeout to a greater value to:
- avoid stopping all the indexing pipeline for one slow operation (this happens a few times on my use case but there is not need to stop)
- avoid repetitive failures when the database is slow or on a query that is retrieving a lot of splits, this can happen if quickwit did not run correctly during a few hours. For example, the merge pipeline has stopped and we have possibly more than 100 000 small splits in the db. Queries can be quite slow and a low timeout will not let Quickwit return in to a normal mode.

Increase grpc metastore timeout for production usage.

---

quickwit/quickwit-janitor/src/actors/garbage_collector.rs

Truncates the number of file entries we display after a GC cycle has run to avoid flooding the logs with too much information. Instead, we now log a few entries and then how many splits in total were deleted.

Reduce GC noise in logging

---

quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs
quickwit/quickwit-serve/src/health_check_api/handler.rs
quickwit/quickwit-serve/src/health_check_api/mod.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-serve/src/test_utils/rest_client.rs

Per title.
Ran `quickwit run` locally and `curl`ed the two health endpoints.

Move `/api/v1/health` routes to `/health`

---

quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
quickwit/quickwit-indexing/src/actors/merge_planner.rs

The mailbox created for the MergePlanner was ignoring the actor defined QueueCapacity, and using an unbounded QueueCapacity.

Fixes BackPressure.

---

docs/reference/query-language.md
quickwit/Cargo.lock
quickwit/Cargo.toml

Also updated documentation, to explain how nested structure can be searched.
Closes #2312
Tested on quickiwt by indexing a single document 
`{"resource": {"k8s.container.name": "prometheus"}}`
and searched it with quickwit.

Update tantivy to fix json path search escaping '.'

---

quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/lazy_file_backed_index.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit/quickwit-storage/src/local_file_storage.rs

Writing in the file storage was not atomic.
So if some other process was polling the file storage for instance, it could end up reading some version of the meta file that was partially written, and therefore invalid JSON.
This is the bug that was observed in #2304.
This PR also prevents the file metastore from reloading the data due to the polling loop, if it is the process acactually writing the metastore.
Closes #2304

Fixes Bug in FileStorage

---

docs/configuration/index-config.md
docs/reference/query-language.md
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-search/src/tests.rs

Adds an expand_dot option (defaults to true) allowing`k8s.component.id:quickwit` to match 
`{"k8s.component.id:"quickwit"}`... Hence removing the need for escaping.
Closes #2345

Quickwit json expand dot options

---

quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs

Took advantage of `DateTime` being a `Copy` type to remove the intermediate conversions from microseconds to milliseconds.

Timestamp conversion refactor

---

quickwit/quickwit-core/src/lib.rs
quickwit/quickwit-indexing/failpoints/mod.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/test_utils.rs
quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
quickwit/quickwit-janitor/src/actors/delete_task_service.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_metastore_factory.rs
quickwit/quickwit-search/src/search_stream/leaf.rs
quickwit/quickwit-search/src/tests.rs
quickwit/quickwit-serve/src/delete_task_api/handler.rs

The test sandbox used to rely to the global quickwit metastore uri resolver.
As a result tests could interfere one with another.
This PR makes sure that each tests gets its own MetastoreUriResolver.
Closes #2368

More isolation for the test sandbox.

---

quickwit/quickwit-metastore/src/metastore/grpc_metastore/mod.rs
quickwit/quickwit-metastore/src/tests.rs

This PR adjusts the metastore test so that we're more forgiving towards the potential of network latency and similar affecting the GRPC metastore tests.
The flaky-ness of this test is due to the fact that we're comparing timestamps in a relatively short time frame while we're only accurate to 1 second.
This means under the right amount of network latency and time, it's possible for the sixth split to be within the range we're filtering out (which it shouldn't do).
The solution to this is to extend the time we wait for by another second (making it `3` seconds) and then filtering out splits which are older than `2` seconds ago so that there is no potential overlap between the sixth split's timestamp and the selection timestamp.
I've ran this several times now in loops and haven't observed …

Fix `test_metastore_list_splits` flaky test

---

quickwit/quickwit-indexing/src/actors/merge_executor.rs

fix #1960 
I created an index with a single document repeated thousands of times and one other document. On delete, the split containing only repeated document get marked for deletion, the split with one document left is... left with one document.

delete segment when last document get deleted

---

quickwit/quickwit-actors/src/actor_handle.rs
quickwit/quickwit-actors/src/supervisor.rs
quickwit/quickwit-actors/src/tests.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
quickwit/quickwit-indexing/src/source/void_source.rs
quickwit/quickwit-janitor/src/janitor_service.rs

Rename `Supervisable::health` to `harvest_health` to inform the caller that the method performs a side-effect. 
`cargo test --manifest-path quickwit/Cargo.toml --all-features --no-run` (the test suite is broken)

Rename `Supervisable::health` method to `harvest_health`

---

quickwit/quickwit-actors/src/actor.rs
quickwit/quickwit-actors/src/lib.rs
quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-actors/src/spawn_builder.rs
quickwit/quickwit-indexing/README.md
quickwit/quickwit-indexing/src/actors/merge_planner.rs
quickwit/quickwit-indexing/src/merge_policy/mod.rs

Fixes the merge planner.
This PR tweaks the way the merge planner schedules its merge operation
in a subtle way to avoid adding a lot of large merge operations at the
same time... Hence stalling smaller, with a larger bang-for-the-buck
merge operations.
This is done by stopping queue merge operations as soon as push back is
experienced.
Closes #2348

Fixes the merge planner.

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/mod.rs
quickwit/quickwit-indexing/src/models/indexing_service_message.rs
quickwit/quickwit-indexing/src/models/mod.rs
quickwit/quickwit-indexing/src/test_utils.rs

Closes #2308 
This adds a new handler for detaching a given merge pipeline, which lets us detach both the indexing and merge pipelines to avoid the indexing service from killing the merge pipeline.
This also inadvertently fixed a small bug where merge pipeline counters were not set until the actor tries to clean them up.
Existing tests have been adjusted to use the new way of spawning merge pipelines, and the new handler has got a test.

QW-2308: Adjust indexing service to let CLI detach merge pipeline.

---

quickwit/quickwit-actors/src/registry.rs
quickwit/quickwit-cli/src/source.rs
quickwit/quickwit-common/src/net.rs
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/routing_expression/mod.rs
quickwit/quickwit-indexing/failpoints/mod.rs
quickwit/quickwit-indexing/src/actors/doc_processor.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/source/ingest_api_source.rs
quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit/quickwit-indexing/src/source/kinesis/shard_consumer.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/source/vec_source.rs
quickwit/quickwit-indexing/src/source/void_source.rs
quickwit/quickwit-indexing/src/test_utils.rs
quickwit/quickwit-metastore/src/backward_compatibility_tests/mod.rs
quickwit/quickwit-search/src/tests.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/node_info_handler.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

Make a  clear difference `serde_json::Value` from `tantivy::schema::Value`
Closes https://github.com/quickwit-oss/quickwit/issues/2338

Differentiate serde_json-value from tantivy-value

---

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/tests.rs

Inside a transaction, this will lock the index row for an upcoming update.
Added a test. The test does fail without the fix.

Select index for update

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
quickwit/quickwit-indexing/src/actors/merge_planner.rs
quickwit/quickwit-indexing/src/actors/mod.rs
quickwit/quickwit-indexing/src/models/merge_statistics.rs

Fixes how we run the merge CLI command to use the new ability to detach the merge pipeline itself.
We then check the number of ongoing merges and wait until that number has reached `0` or the actor has exited.

QW-2404: Fix merge CLI command.

---

quickwit/quickwit-metastore/migrations/postgresql/8_delete-update-timestamp-on-indexes-table.up.sql
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/index_metadata/mod.rs
quickwit/quickwit-metastore/src/metastore/index_metadata/serialize.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/metastore/postgresql_model.rs
quickwit/quickwit-metastore/src/tests.rs
quickwit/quickwit-metastore/test-data/file-backed-index/v0.4-6c9e39c3826b9ca97f8a9760f50ee0f6.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.4-6c9e39c3826b9ca97f8a9760f50ee0f6.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.4-c5c7464b71b9edfa6ad4291b081212e5.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.4-c5c7464b71b9edfa6ad4291b081212e5.json

This drops the `update_timestamp` field as part of the index metadata and applies any migrations needed for PostgreSQL.
Tests involving the update_timestamp on the index have been adjusted.

QW-2409: Ditch `update_timestamp` from index metadata.

---

quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-janitor/src/garbage_collection.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/tests.rs

Remove transaction from `delete_splits` and update index update timestamp in the same query. 
In addition, I have modified the behavior of the method:
- Attempting to delete staged splits returns an error
- We no longer return an error when some splits are not found (but we log a warning)
Updated unit test.

Remove transaction from `delete_splits`

---

quickwit/quickwit-actors/src/actor.rs

The entire logging is removed, since it was redundant with the logging spawn_builder.
Closes #2426

Removes error log when actor exits.

---

quickwit/Cargo.lock
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/source.rs
quickwit/quickwit-core/Cargo.toml
quickwit/quickwit-core/src/index.rs
quickwit/quickwit-core/src/lib.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs

Add REST endpoints for creating/deleting for index/source resources.
Some remarks:
- all nodes can respond. A node that does not run the metastore service will send the gRPC request to the metastore node. 
- creating a file source is somewhat broken. We only support indexing a local file, this means that the file needs to be on the indexer...
- when we create a source, we do a connectivity check, this is done by the node receiving the request. This means that this must be able to connect to kinesis, kafka or have access to the file if it's a file source.
If this PR is ok, I'm going to add an update index endpoint in a separate PR. We can authorize the update on the merge pocliy / retention policy and on some indexing settings.

Add REST endpoints for creating/deleting for index/source resources.

---

quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/tests.rs

- Remove transaction from marked splits for deletion
- Display a warning when some splits are not found rather than returning an error
- Updated and completed unit test

Remove transaction from marked splits for deletion

---

quickwit/quickwit-config/src/index_config/mod.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs
quickwit/quickwit-doc-mapper/src/doc_mapper.rs
quickwit/quickwit-doc-mapper/src/routing_expression/mod.rs
quickwit/quickwit-indexing/src/actors/indexer.rs
quickwit/quickwit-metastore/test-data/file-backed-index/v0.4-4e2d5b064b59353c0370cde4e2343a1c.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.4-4e2d5b064b59353c0370cde4e2343a1c.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.4-8747a2719c5372014a04bbc616666a97.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.4-8747a2719c5372014a04bbc616666a97.json

The branch name is misleading.
The default value of max_num_partitions is now 200.
It is required, but users can set it to 2^32 if they want a "die before mixing partitions" behavior.
If the max_num_partitions is exceeded, we log a warning with the number of max_num_partitions, but also the number of docs in the workbench when it happens.
Closes #2458.

No modulo in the partitioning logic.

---

quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs

fixed duplicate field handling in DocMapper.
Closes https://github.com/quickwit-oss/quickwit/issues/2475

Fixed doc-mapping duplicate field 

---

docs/get-started/installation.md

fix #1775
I added only packages I actually needed to run quickwit. I got no complain about make/cmake/pkg-config on neither platform so I assume they are probably no longer needed.
install the dependencies in `ubuntu:latest`, `amazonlinux:latest` and `archlinux:latest` and verify `cargo run --release` print quickwit help message

add docs about required system dependencies

---

quickwit/quickwit-janitor/src/actors/delete_task_service.rs
quickwit/quickwit-serve/src/delete_task_api/handler.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/rest.rs

Running the delete task creation handler on all nodes.
The delete task creation/list handlers where needlessly requiring
or were executed on the DeleteTaskService but were
simply interacting with the Metastore.
After the modification, the handler runs on all rest API
and discuss directly with the Metastore.
Closes #2507

Running the delete task creation handler on all nodes.

---

docs/guides/schemaless.md

Closes #2538 
Updates the index configs in the guides section of the docs (notably https://quickwit.io/docs/guides/schemaless) to be in line with the 0.4 schemas.

Update schemaless guide.

---

quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-ui/src/views/NodeInfoView.tsx

- Added more info in the app version display like: `Quickwit 0.4.0-nightly (586a6f8 2022-12-02T03:00:00Z)`
- Fixed build info API URL.

More info in app version

---

build/cross-images/aarch64-unknown-linux-gnu.dockerfile
build/cross-images/x86_64-unknown-linux-gnu.dockerfile

Update cross image version with clang 3.9

---

quickwit/quickwit-aws/src/error.rs
quickwit/quickwit-aws/src/retry.rs
quickwit/quickwit-indexing/src/source/kinesis/api.rs
quickwit/quickwit-indexing/src/source/kinesis/shard_consumer.rs

Localstack updated the mock library they use for Kinesis, which improves a few things and makes some other worse.
Ran Kinesis test suite locally.

Retry on LimitExceeded errors and ignore some Kinesis tests

---

.github/workflows/ci.yml

The current CI code is referring to the latest version of a binary build on a mold's creator.
That's a recipe for breaking CI, exposing ourselves to change of API (unlikely for a linker but well), supply chain attack etc, change of licenses (for CI that's ok but for building our binares that would have been a disaster).
Let's stick to the stock linker.

Remove mold usage in CI.

---

quickwit/quickwit-indexing/src/actors/indexing_service.rs

Simplify indexing pipeline freeze test to avoid flakyness.

---

quickwit/quickwit-metastore/src/checkpoint.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/metastore/postgresql_model.rs
quickwit/quickwit-metastore/src/tests.rs

- Remove 2 round trips in publish splits transaction. 
- Remove ability to re-publish a published split (but reapplying a non-empty checkpoint delta is not possible anyway)
- Updated test suite

Remove 2 round trips in publish splits transaction

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-actors/src/tests.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
quickwit/quickwit-storage/Cargo.toml

Updating to tokio 1.23 and updating unit tests.

---

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/tests.rs

Having to clean up the database when a test fails before re-running the suite is driving me insane.
```sh
cargo test --manifest-path quickwit/Cargo.toml --all-features -p quickwit-metastore -- --nocapture
```

Randomize index, split, and source ID in metastore test suite

---

docs/tutorials/tutorial-hdfs-logs.md

Following a conversation on Discord, knowing this tutorial is listed as the "Next tutorials" on the Quickstart page, I thought it would be good to still have the Docker commands here.
I did use them, and it would have saved me some time.
Using my little hands to type in a terminal.

docs(hdfs tutorial): Add Docker code examples

---

quickwit/quickwit-ui/src/components/QueryEditor/QueryEditor.tsx

Ensure an index is registered in the query editor component (Monaco editor) only once.
Manually reproduced and tested.
Closes https://github.com/quickwit-oss/quickwit/issues/2615

Fix duplicate fields in editor auto-completion

---

quickwit/Cargo.lock
quickwit/quickwit-aws/Cargo.toml
quickwit/quickwit-aws/src/retry.rs

Accelerates time in the aws retry unit test using quickwit-actors's time mocker.

quickwit-aws time mocking

---

CONTRIBUTING.md

After rust code was moved into the quickwit subdirectory some of the contributing guideline instructions no longer work. This commit tries to clarify these instructions by adding missing prerequisites, specifying directories where certain commands should be executed and adding config parameter where needed.
Closes #2668
Just followed the instructions on my machine.

Add clarifications to Contributing Guidelines

---

quickwit/quickwit-doc-mapper/benches/doc_to_json_bench.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit/quickwit-doc-mapper/src/doc_mapper.rs
quickwit/quickwit-doc-mapper/src/error.rs
quickwit/quickwit-indexing/src/actors/doc_processor.rs

Use `serde_json::Map<String, JsonValue>` instead of `&str` as input of the doc mapper parsing method so we can use the doc mapper directly on docs that already have been parsed as part of the transform process.
Indeed, I'm working on finalizing the VRL PR, and I'm making some changes to the doc processor. The code looks like this:
```rust
let doc_res = if let Some(transform) = self.transform_opt {
let vrl_value: VrlValue = transform.transform_doc(&json_doc)?;
let json_value: JsonValue = serde_json::to_value(vrl_doc).map_err(...);
let JsonValue::Object(json_obj) = json_value else ...
doc_mapper.doc_from_json_obj(json_obj)
} else {
doc_mapper.doc_from_json_str(&json_doc)
}
```
Without this change, we have to serialize the `VrlValue` to a JSON string and then back to a `JsonValue`. This is …

Change doc mapper signature

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-metastore/src/metastore/instrumented_metastore.rs
quickwit/quickwit-opentelemetry/Cargo.toml
quickwit/quickwit-opentelemetry/src/otlp/metrics.rs
quickwit/quickwit-opentelemetry/src/otlp/mod.rs
quickwit/quickwit-opentelemetry/src/otlp/trace.rs

Per title.
```
QW_ENABLE_JAEGER_SERVICE=true \
QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER=true \
QW_ENABLE_OPENTELEMETRY_OTLP_SERVICE=true \
OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:7281 \
RUST_BACKTRACE=1 \
RUST_LOG=info,quickwit=info,quickwit_jaeger=debug \
cargo run --manifest-path quickwit/Cargo.toml --all-features -- run
```

Instrument OTLP trace service

---

quickwit/quickwit-opentelemetry/src/otlp/trace.rs

This scope contains the collector name and version.
Deleted trace index and ran:
```
QW_ENABLE_JAEGER_SERVICE=true \
QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER=true \
QW_ENABLE_OPENTELEMETRY_OTLP_SERVICE=true \
OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:7281 \
RUST_BACKTRACE=1 \
RUST_LOG=info,quickwit=info,quickwit_jaeger=debug \
cargo run --manifest-path quickwit/Cargo.toml --all-features -- run
```
I also checked that the field was correctly populated in the UI. Once the data model and logic are stable, I will add some unit tests.

Store instrumentation scope

---

docs/configuration/index-config.md

This commit removes the section describing behavior with fields not defined in the config since it is obsolete and the new behavior is already covered in details in the previous section on the mapping mode.
It also clarifies the section describing behavior with missing fields, which currently doesn't mention that missing fast fields will cause the entire record to be rejected.
Manually verified that the newly documented behavior is indeed what happens.
Fixes #2711

Update doc sections describing indexing behavior

---

quickwit/quickwit-actors/src/channel_with_priority.rs
quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-actors/src/spawn_builder.rs
quickwit/quickwit-actors/src/tests.rs
quickwit/quickwit-actors/src/universe.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs

`try_recv` returning `None` means that the channel is empty but not necessarily drained, i.e., an actor can exist at the other end of the channel waiting on `send`. The only way to find out is to yield and check whether the channel is empty when the task is scheduled again.

Yield before calling on drained callback

---

quickwit/Cargo.lock
quickwit/quickwit-actors/src/universe.rs
quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-config/resources/tests/config/quickwit.json
quickwit/quickwit-config/resources/tests/config/quickwit.toml
quickwit/quickwit-config/resources/tests/config/quickwit.yaml
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/quickwit_config/mod.rs
quickwit/quickwit-config/src/quickwit_config/serialize.rs
quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-jaeger/Cargo.toml
quickwit/quickwit-jaeger/src/lib.rs
quickwit/quickwit-serve/src/grpc.rs
quickwit/quickwit-serve/src/lib.rs

Add Jaeger config

---

quickwit/quickwit-jaeger/src/lib.rs
quickwit/quickwit-opentelemetry/src/otlp/trace.rs

Jaeger does not display traces correctly when spans are unordered.
- inspected output visually

Stream spans ordered by trace ID

---

config/tutorials/stackoverflow/index-config.yaml
docs/get-started/quickstart.md

Replaces wikipedia dataset in the quickstart guide with the stackoverflow dataset. This new dataset not only has a timestamp but also contains some interesting elements such as tags and record types to make getting started more fun.
Besides replacing the dataset it also adds instructions on how to use docker image on Apple silicon based macOS systems and adds --rm flag to all docker instructions. Without the rm flag docker creates and keeps a new container for every execution and we start a new container at least 6 times during this tutorial.
Closes #1618
I visually inspected the markdown. I am not really sure how to render it into HTML the same way as it is done on the web site. 
I manually ran both CLI and docker commands on x86_64 Ubuntu 22.04.1 to make sure that the flow describe in …

Replace wikipedia with stackoverflow in quickstart

---

docs/reference/aggregation.md

Adds descriptions of newly added aggregations and clarifies some limitations and supported field types.
Fixes #2737
By manually running the queries and checking the tantivy code.

Add new aggregation (min, max, sum, value_count) description to docs

---

quickwit/Cargo.lock
quickwit/quickwit-serve/src/index_api/mod.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/rest.rs

Preparing #2717. We should do the toml/yaml parsing on the server side.

Add support of toml and yaml on index/source creation.

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-serve/Cargo.toml
quickwit/quickwit-serve/src/rest.rs

To make use of the openapi.json, I think it's worth serving the `swagger-ui`. It would help us discovering endpoints, and checking if there are some missing pieces. 
I'm not sure if this is a long term solution, but I believe it will help us and developers trying quickwit.

Add swagger-ui endpoint.

---

docker-compose.yml

Added azurite to run in the default ("all") profile in docker compose. Otherwise, it is not getting started when we try to start all services for testing.
By following instructions in CONTRIBUTING.md
Fixes #2751

Run azurite in all profile in docker-compose

---

quickwit/scripts/check_license_headers.sh

All headers were updated to 2023, so the license checker should also be updated.
Fixes #2767
By running `bash scripts/check_license_headers.sh`

Fix license header checker

---

quickwit/quickwit-jaeger/src/lib.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit/quickwit-opentelemetry/src/otlp/mod.rs
quickwit/quickwit-opentelemetry/src/otlp/trace.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/tests.rs

- Use `service_name` as tag field to prune splits
- Sort spans within a batch by trace ID and timestamp to improve compression and efficiency of trace IDs collector (upcoming PR)
- Partition trace index by service name % 100
- Use list terms query to list operations
- Filter operations by span kind
Ingested some traces and displayed them in Jaeger UI

Various tracing enhancements

---

quickwit/quickwit-grpc-clients/src/balance_channel.rs
quickwit/quickwit-indexing/src/indexing_client.rs
quickwit/quickwit-search/src/client.rs

This is a temporary fix until we land #2706.
- Launched Quickwit a few times and I no longer observe the noisy connection error on startup.

Set connection timeout to 5s on various clients

---

quickwit/Cargo.lock
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/jaeger_collector.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/tests.rs

Switch to a custom collector for aggregating trace IDs. This PR focuses on the plumbing part. I will follow up shortly with a second PR that implements an efficient algorithm.
- Tested with Jaeger

Switch to custom collector for aggregating trace IDs

---

quickwit/quickwit-actors/src/universe.rs
quickwit/quickwit-indexing/failpoints/mod.rs

If test fails with panic and universe drop is called it kills the test runner instead of displaying the first panic.
By manually breaking a test.
Relates to #2766

Universe shouldn't panic if thread is panicking

---

quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-indexing/failpoints/mod.rs

The code path was different depending on whether a backpressure counter was set or not. However, I believe we always want to `try_send` before `send`:
Before:
```rust
if let Some(backpressure_micros_counter) = backpressure_micros_counter_opt {
match self.inner.tx.try_send_low_priority(envelope) {
Ok(()) => Ok(response_rx),
Err(TrySendError::Full(msg)) => {
let now = Instant::now();
self.inner.tx.send_low_priority(msg).await?;
let elapsed = now.elapsed();
backpressure_micros_counter.inc_by(elapsed.as_micros() as u64);
Ok(response_rx)
}
Err(TrySendError::Disconnected) => Err(SendError::Disconnected),
}
} else {
self.inner.tx.send_low_priority(envelope).await?;
Ok(response_rx)
}
```
After:
```rust
match self.inner.tx.try_send_low_priority(envelope) {
Ok(()) => Ok(response_rx), …
```

Fix attempt to `try_send` before `send`

---

quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/lib.rs

Added tests to avoid clashes with field names used internally.
The main reason for this validation relaxation: `_my_field` seems quite common.

Authorize field names that starts with underscore.

---

quickwit/Cargo.lock
quickwit/quickwit-actors/src/actor.rs
quickwit/quickwit-actors/src/actor_context.rs
quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-codegen-example/Cargo.toml
quickwit/quickwit-codegen-example/src/error.rs
quickwit/quickwit-codegen-example/src/hello.rs
quickwit/quickwit-codegen-example/src/lib.rs
quickwit/quickwit-codegen/src/codegen.rs

Generate the boiler code necessary to use an actor's mailbox as a Tower service. That means that we can implement an endpoint as `fn hello<T>(message: HelloRequest) where T: tower::Service<HelloRequest>` and provide whichever Tower service implementation.
Under the hood, the call can be routed to a local implementation (actor or not) or a remote implementation via gRPC.
- Updated unit test

Add codegen for actor mailbox

---

quickwit/Cargo.lock
quickwit/quickwit-config/src/quickwit_config/mod.rs
quickwit/quickwit-ingest-api/Cargo.toml
quickwit/quickwit-ingest-api/src/lib.rs

Just use byte for ingest api config params. It's consistent with other params expressing bytes and it will make it easier to configure.
Fixes #2846

Use byte for ingest api config params.

---

quickwit/Cargo.lock
quickwit/quickwit-rest-client/Cargo.toml
quickwit/quickwit-rest-client/src/error.rs
quickwit/quickwit-rest-client/src/models.rs
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-serve/src/cluster_api/rest_handler.rs
quickwit/quickwit-serve/src/delete_task_api/handler.rs
quickwit/quickwit-serve/src/format.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/indexing_api/rest_handler.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

Currently, the body of API error responses can be very different. 
It can be of the form 
```json
{
"error": "error message that corresponds to error.to_string()",
}
```
or any errors that are JSON serializable. For example, with a `SearchError::InvalidQuery`, we are getting:
```json
{
"InvalidQuery": "Invalid query: a {message}"
}
```
The status code can be retrieved from the HTTP response.
I would like to make the following changes: make all errors return a JSON following this format:
```json
{
"message": "typically error.to_string()",
}
```
I have a preference for the field "message" rather than "error".

Standardize API error response.

---

quickwit/quickwit-cli/tests/cli.rs

The CLI interface of quickwit has a subcommand for deleting an index, given it's ID. The subcommand, except for dry-run, has no safety built-in. I thought about putting a `--yes` flag, like other subcommands in the CLI, but I feared that this may be disrupting for existing client's pipelines. This seems a more sensible choice because it doesn't interfere with existing processes in place and it can be used only where is necessary. It solves issue #2201. 
Added the relevant flags in the existing tests.

feature: added safe mode to delete index

---

quickwit/Cargo.lock
quickwit/quickwit-rest-client/Cargo.toml
quickwit/quickwit-rest-client/src/lib.rs
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs

REST client ingests files in batches of 10MiB or less.
- Added unit test for `BatchLineReader`
- Ingest one GH archive file with client

Ingest files in batches of 10MiB or less

---

docs/reference/cli.md
docs/reference/rest-api.md
quickwit/quickwit-cli/src/split.rs

TLDR.
Tested with `cargo run -- split list --index airmail-logs --output-format pretty_json`

Replace prettyjson by pretty_json to be consistent everywhere.

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-rest-client/src/rest_client.rs

Adding a progress bar to the ingest API.
- Tested with an input file
- Tested with stdin source
- The progress bar is hidden when the stdout is not a tty.

Add progress bar on ingest CLI command.

---

quickwit/quickwit-config/src/source_config/mod.rs

Closes #2899
Fixes the issue when deserializing YAML with the pulsar source parameters and authentication being provided as mentioned here https://github.com/dtolnay/serde-yaml/issues/342
This also adds some unit tests which were previously missed for the YAML deserializing.

QW-2899: Fix yaml deserialization issue and add tests

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-storage/Cargo.toml

Currently using `enable_reqwest_rustls` feature on all `azure_*` crates
Closes https://github.com/quickwit-oss/quickwit/issues/2929

Remove openssl dependency on azure 

---

quickwit/quickwit-config/src/quickwit_config/serialize.rs

This test is failing on my local laptop and failed also on [coverage](https://github.com/quickwit-oss/quickwit/actions/runs/4320005920/jobs/7539796621#step:13:1235)
Tested locally.

Fix typo in test_config_contains_wrong_values.

---

docs/get-started/tutorials/send-logs-from-vector-to-quickwit.md

In the tutorial for sending logs to the vector. There is an error on the vector configuration that causes an error, by default the sink vector `http` uses the HTTP method `GET` and quickwit responds with an HTTP 405 error when ingesting logs.
We need to explicitly define the use of the `POST` method.
Error in vector logs:
```
vector::internal_events::http_client: HTTP response. status=405 Method Not Allowed version=HTTP/1.1 ...
```
PR changes only documentation file.

Fix vector configuration in tutorial

---

quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-common/src/test_utils.rs
quickwit/quickwit-control-plane/Cargo.toml
quickwit/quickwit-control-plane/src/grpc_adapter.rs
quickwit/quickwit-control-plane/src/scheduler.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs

Several improvements were made:

Improve scheduling triggers. Fix #2659.

---

docs/reference/rest-api.md

Added documentation for describe_index endpoint in the API docs. Closes #2996

Docs added for describe_index API.

---

quickwit/quickwit-metastore/src/metastore/metastore_event_publisher.rs
quickwit/quickwit-serve/src/grpc.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-serve/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-serve/src/test_utils/rest_client.rs
quickwit/quickwit-serve/src/tests.rs

The control plane notifications are not working for 2 reasons:
- one is described in #2981
- in a cluster mode, the control plane is not notified as we don't instantiate the control plane client to send the notifications, so nothing is sent!

Fix control plane notifications

---

quickwit/quickwit-config/src/source_config/mod.rs

Closes #2972 
Adds the missing validator check to ensure the pulsar address starts with `pulsar://`.
This adds about as much validation as is possible with the limited amount of documentation available.

QW-2972: Add validator to pulsar address

---

docs/get-started/installation.md
docs/telemetry.md
quickwit/quickwit-cli/src/main.rs

- Small intro to present the 3 ways to install quickwit
- addition of macOS aarch64 binary link
- remove the small tutorial at the end, the link to the quickstart should be sufficient
- update telemetry doc
- change CLI tagline
```
Quickwit 0.4.0-nightly (5d57148 2023-02-25T10:11:11Z)
Index and search your data on object storage at any scale.
Find more information at https://quickwit.io/docs
Telemetry: enabled
```

Update installation page.

---

docs/distributed-tracing/index.md
docs/distributed-tracing/instrument-python-and-send-traces-to-quickwit.md
docs/distributed-tracing/use-jaeger-to-analyze-quickwit-traces.md
docs/log-management/index.md
quickwit/quickwit-opentelemetry/src/otlp/logs.rs
quickwit/quickwit-opentelemetry/src/otlp/trace.rs

- tracing commits every 5s by default
- removes QW_ENABLE_OTLP_ENDPOINT=true as it is the default
- we only talk about disabling that endpoint in one place and link that information somewhere else.
- adding a link to the tracing tutorial.
- Fixed instruction for linux
I could not test the changes so leaving as draft for the moment.

Minor changes meant to simplify the UX of tracing

---

quickwit/quickwit-serve/src/rest.rs

This fixes the incremental compilation issue by type-erasing the warp routes to stop the compiler getting confused by all of the generics.

Fix incremental compilation

---

docs/reference/rest-api.md
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs

Adds an option to force a commit or wait for the next commit while issuing a bulk request command.
See #2699
Added tests.

Add ?refresh parameter to /_bulk request

---

quickwit/Cargo.lock
quickwit/quickwit-config/Cargo.toml
quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-doc-mapper/src/doc_mapper.rs
quickwit/quickwit-indexing/Cargo.toml
quickwit/quickwit-indexing/benches/doc_process_vrl_bench.rs
quickwit/quickwit-indexing/src/actors/doc_processor.rs
quickwit/quickwit-indexing/src/models/raw_doc_batch.rs
quickwit/quickwit-indexing/src/source/file_source.rs
quickwit/quickwit-indexing/src/source/ingest_api_source.rs
quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit/quickwit-indexing/src/source/pulsar_source.rs
quickwit/quickwit-indexing/src/source/vec_source.rs
quickwit/quickwit-indexing/src/test_utils.rs
quickwit/quickwit-ingest-api/src/doc_batch.rs

This has two advantages:
1. Sometimes, when the source returns a `Bytes` object (mrecordlog, Kinesis), we can reuse the object as is and save an allocation.
2. We no longer have to check that the doc is valid UTF-8 in each source. The check is performed once in the doc processor when going from `&[u8]` to `JsonValue`

Switch `RawDocBatch.docs` from `Vec<String>` to `Vec<Bytes>`

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-doc-mapper/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/doc_mapper.rs
quickwit/quickwit-doc-mapper/src/lib.rs
quickwit/quickwit-doc-mapper/src/query_builder.rs
quickwit/quickwit-doc-mapper/src/tag_pruning.rs
quickwit/quickwit-doc-mapper/src/tokenizers.rs
quickwit/quickwit-opentelemetry/src/otlp/mod.rs
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/filters.rs
quickwit/quickwit-search/src/find_trace_ids_collector.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/search_stream/collector.rs
quickwit/quickwit-search/src/search_stream/leaf.rs
quickwit/quickwit-search/src/search_stream/mod.rs
quickwit/quickwit-search/src/tests.rs

Update tantivy and integrate the Columnar work
- Fast field readers become `Column`. Column dynamically handle
cardinality.
- Aggregation is getting an aggregation limits object.
- Minor changes.
Closes https://github.com/quickwit-oss/quickwit/issues/1548

Update tantivy and integrate the Columnar work

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-codegen/example/src/codegen/hello.rs
quickwit/quickwit-codegen/example/src/hello.proto
quickwit/quickwit-codegen/example/src/lib.rs
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-common/src/tower/box_layer.rs
quickwit/quickwit-control-plane/src/codegen/control_plane_service.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs
quickwit/quickwit-proto/Cargo.toml
quickwit/quickwit-serve/src/lib.rs

This adds the ability to add a layer for all client methods at once.

Implement `shared_layer` on service client builder

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-serve/Cargo.toml
quickwit/quickwit-serve/README.md
quickwit/quickwit-serve/elastic-api-generator/Cargo.toml
quickwit/quickwit-serve/elastic-api-generator/README.md
quickwit/quickwit-serve/elastic-api-generator/src/main.rs
quickwit/quickwit-serve/src/elastic_search_api/api_specs.rs
quickwit/quickwit-serve/src/elastic_search_api/mod.rs

To avoid polluting quickwit with unnecessary dependencies.
Closes #3104

Putting the elastic-api-generator in an independent project in order

---

quickwit/quickwit-cli/src/index.rs

Ensure that when a user answer `no` the index will not be deleted, this is done by moving the actual delete logic after confirming with the user.
The test suite was run locally and the following command were run to confirm the changes in behavior.
```sh
cargo r index create --index-config ../config/tutorials/hdfs-logs/index-config.yaml
cargo r index create --index-config ../config/tutorials/hdfs-logs/index-config.yaml # Answered no.
cargo r index describe --index hdfs-logs # return the information about the index.
cargo r index create --index-config ../config/tutorials/hdfs-logs/index-config.yaml # Answered yes.
cargo r index describe --index hdfs-logs # return 404 not found
```
I've looked at the test suite, we seem to run all the CLI test with `assume_yes` and skipping any prompt. …

Fix the delete index user confirmation

---

quickwit/quickwit-ingest/src/lib.rs
quickwit/quickwit-rest-client/src/rest_client.rs

Fixes handling of CommitType::Force and CommitType::WaitFor in the rest client.
Fixes #3196
Added 2 unit tests. I discovered the issue while working on #2984, so integration tests are almost ready, but I will push them as another PR.

Fix handling of commit parameters in rest client

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs

Bump regex from 1.7.3 to 1.8.1

---

Makefile
docker-compose.yml

Sets fixed versions for docker images, moves data volumes from temporary local directories to docker volumes and tweaks the healthcheck timeouts to reduce startup time.
Fixes #3184
I ran it multiple times on Mac OS and Ubuntu. In my testing the startup time for the docker-compose scripts is reduced from 30+ second (with occasional timeout) to 9-11 seconds.

Sets fixed version for docker compose images

---

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs

Removes the condition that has been causing
test_indexing_pipeline_all_failures_handling to hang in case of pipeline initialization failure. The test will still fail if the pipeline fails to start the first time, but it will not longer make the test to hang.
See #3206
It is fixing a test.

Prevent test_indexing_pipeline_all_failures_handling form hanging

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-opentelemetry/src/otlp/mod.rs
quickwit/quickwit-proto/protos/quickwit/search_api.proto
quickwit/quickwit-proto/src/quickwit.rs
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/cluster_client.rs
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/error.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs

switch to postcard for better datastructure support when sending intermediate results between nodes
Percentiles aggregation is broken currently. This fixes that

switch from serde_json to postcard

---

quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/test_utils/mod.rs
quickwit/quickwit-integration-tests/src/tests/basic_tests.rs
quickwit/quickwit-integration-tests/src/tests/index_tests.rs
quickwit/quickwit-rest-client/src/models.rs

Switches retry logic in cluster sandbox wait_for methods to use quickwit_common::test_utils::wait_for_server_ready. It also adds a retry logic for the first ingest commands after an index creation to make tests more reliable. Checking the number of running pipelines doesn't seem to do that trick.
Fixes #3230
Fixes #3214
It is refactoring tests.

Refactor cluster sandbox wait_for methods

---

quickwit/Cargo.lock
quickwit/quickwit-serve/src/search_api/rest_handler.rs
quickwit/rust-toolchain.toml

Bump Rust from 1.68 to 1.69

---

quickwit/quickwit-metastore/src/split_metadata.rs
quickwit/quickwit-serve/src/grpc.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/rest.rs

Runs gRPC and REST server handler in separate tasks.
This has NOT been observed to lower the latency of small requests,
but it makes more sense.

Runs gRPC and REST server in different tasks.

---

quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs

I'm making heavy use of this logic in an upcoming PR. I'm hoping to make the review easier by submitting this refactor first.
```bash
TEST_DATABASE_URL=postgres://quickwit-dev:quickwit-dev@localhost:5432/quickwit-metastore-dev cargo test --manifest-path quickwit/Cargo.toml -p quickwit-metastore --lib --all-features --
```

Improve file-backed metastore mutation logic

---

quickwit/quickwit-jaeger/src/lib.rs

TraceId in QwSpan/QwLink has already been decoded from base64, call `base64_decode(..)` will encounter error
manual testing: use jaeger-query to query tracing datas in quickwit

Fix the trace-id conversion

---

quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/tests/index_tests.rs

Adds integration tests for different commit modes.
Fixes #2699
It is a test.

Add e2e test for commit modes

---

quickwit/Cargo.lock
quickwit/quickwit-cli/src/service.rs
quickwit/quickwit-common/src/tower/mod.rs
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-serve/src/grpc.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-serve/src/tests.rs

- Add readiness signals for gRPC and REST servers
- Clean up shutdown signal handlers code
- updated unit test
- launched `quickwit run`

Add readiness signals for gRPC and REST servers

---

quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/tests/index_tests.rs

Certain rest client commands such as ingest may leave connection to the rest server open, which in turn prevents a quick graceful rest server shutdown. This change shuts down the rest clients before attempting to shutdown the server to ensure quick shutdown.
Fixes #3270
It is fixing tests.

Fixes graceful shutdown of cluster sandbox

---

quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/service.rs

Tested on an aggregation that was failing because the default aggregation limits were still used in the finalization step.

Pass aggregation limits when finalizing aggregation on the root node.

---

docs/reference/rest-api.md
quickwit/quickwit-ingest/src/lib.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs

Improves documentation of the ingest's refresh and bulk's commit query parameters. It also adds some comment to corresponding enums.
Fixes #3309
It is mostly documentation changes. I added a small test to ensure errors in refresh parameter values are handled.

Improve documentation of commit and refresh params

---

docs/configuration/index-config.md

Field `search_default_fields` for index search settings should be `default_search_fields`
Did some API tests according to the document. REST API returned error message when I specified `search_default_fields` when creating new index:
```json
{
"message": "Invalid config: Failed to read JSON file.: unknown field `search_default_fields`, expected `default_search_fields`."
}
```
Index created ok after changing the field name to `default_search_fields`

Incorrect field name within index config in document

---

docker-compose.yml

Bumps the version of pulsar-broker to 3.0.0. That's the first version that has an official arm64 docker image.
Fixes #2921
I have been using per-released version of this for about a month on Mac M1 directly as well as in an arm64 Ubuntu VM. It worked pretty well for me. I have occasional pulsar hiccups, but I am not sure they are mac-specific. Now that an official pulsar 3.0.0 image is published I think we should switch to it.

Updates version of pulsar-broker

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/split_store/indexing_split_store.rs

The idea is to keep benefiting from mmap's
good things (page cache, zero copy, read ahead)
but avoid the bad thing (getting oom killed due to some map paged being in resident memory even though we don't need them)
Closes #3299

madvise merge mmaps as sequential.

---

CHANGELOG.md
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-jaeger/src/lib.rs

Also populate `service.version` resource attribute in OTLP exporter.
- Launched quickwit locally with OTLP exporter enabled and queried `service.version` resource attribute via Jaeger UI

Query resource attributes when Jaeger request carries tags

---

quickwit/quickwit-integration-tests/src/tests/basic_tests.rs

Makes the basic integration tests less flaky by replacing sleep with active waiting.
Fixes #3351
I ran all tests on CI about 300 times to ensure this test is not as flaky as it used to be.

Improve basic-integration-tests

---

quickwit/Cargo.lock
quickwit/quickwit-cli/src/generate_markdown.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-serve/Cargo.toml
quickwit/quickwit-serve/src/build_info.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/node_info_handler.rs
quickwit/quickwit-serve/src/rest.rs

In the long run, I'd like to expose more info (ram, os, uptime, ...) so it's easy for our users to copy and paste this stuff when opening issues.
- Updated units test
- Hit endpoint

Expose the number of CPUs available on the node

---

.github/workflows/ui-ci.yml
quickwit/Cargo.lock
quickwit/Cargo.toml

This version of rustix no longer causes recompilation during tests runs while using VSCode. This commit also works around a bug introduced in rust 1.69.0 that was causing rebuilding between cargo build and cargo run.
Fixes #3346
That part was quite an adventure 😄

Upgrade rustix 0.36.13->0.36.14 and fix debug info

---

docs/reference/cli.md
docs/reference/rest-api.md
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-ui/src/components/IndexSummary.tsx
quickwit/quickwit-ui/src/utils/models.ts

Closes https://github.com/quickwit-oss/quickwit/issues/3320
Reordered display and added  `Size of published documents`
updated label

Display uncompressed document size in UI

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-common/src/binary_heap.rs
quickwit/quickwit-proto/build.rs
quickwit/quickwit-proto/protos/quickwit/search_api.proto
quickwit/quickwit-proto/src/lib.rs
quickwit/quickwit-proto/src/quickwit.rs
quickwit/quickwit-search/src/cluster_client.rs
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/leaf_cache.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/tests.rs
quickwit/rest-api-tests/rest_api_test.py
quickwit/rest-api-tests/scenarii/sort_orders/0001-sort.yaml
quickwit/rest-api-tests/scenarii/sort_orders/quickwit-sortorder.json
quickwit/rest-api-tests/scenarii/sort_orders/setup.quickwit.sh
quickwit/rest-api-tests/scenarii/sort_orders/split1.json
quickwit/rest-api-tests/scenarii/sort_orders/split2.json
quickwit/rest-api-tests/scenarii/sort_orders/teardown.quickwit.sh

This PR also makes sure we return "true sort values" in the REST payload. None is supported. Documents with None will get at the end of the SERP regardless of Ascending or Descending order.

Allow sort on dynamic field.

---

docs/get-started/quickstart.md
docs/guides/schemaless.md
docs/ingest-data/ingest-api.md

This commit adds --force or commit=force to all documentation examples that deal with ingestion of small files. I didn't add it to large dataset examples such as gh-archive and hdfs-logs due to possible failures outlined in #3137.
Fixes #3403
I ran this commands against locally running quickwit server.

Add force commit to documentation examples

---

quickwit/quickwit-common/src/temp_dir.rs

Fix test_directory_randomness on  case-insensitive filesystems.
Fixes #3419
It wasn't tested. I am running builds in VM on my mac and I don't have a bare metal setup at the moment. @guilload could you run it in your setup to see if this change indeed fixes the issue?

Fix test_directory_randomness

---

quickwit/quickwit-common/src/runtimes.rs
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs

Fix `RuntimeType::get_runtime_handle` when the `test` or `testsuite` features are missing.
`cargo build --manifest-path quickwit/Cargo.toml -p quickwit-common`

Fix `RuntimeType::get_runtime_handle`

---

quickwit/quickwit-indexing/Cargo.toml

The indexing `TestSandbox` now relies on the `testsuite` feature of `quickwit-common` to initialize the actor Tokio runtime.
`cargo test --manifest-path quickwit/Cargo.toml -p quickwit-search --lib --` (which is currently broken on main)

Fix indexing `TestSandbox`

---

docs/distributed-tracing/send-traces/using-otel-collector.md
docs/log-management/send-logs/using-otel-collector.md
quickwit/quickwit-opentelemetry/src/otlp/logs.rs

I did not find a good default search field for the otel traces index.
I can change that if @guilload you have a good idea.
Tested locally.

Add default search field for otel logs index.

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-cli/src/source.rs
quickwit/quickwit-cli/src/split.rs
quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-rest-client/src/models.rs
quickwit/quickwit-rest-client/src/rest_client.rs

Adds ability to specify operation timeouts for the rust client as well as different CLI commands. Takes a first stab at more conservative timeout defaults. These timeouts are still pretty much guesstimates at this point, but at least we now have a way to adjust default and override them from CLI.
Fixes #3137
By running automated tests as well as using our large examples from tutorial to see if they fail with new defaults.

Introduce REST client timeouts

---

docs/configuration/index-config.md
quickwit/quickwit-config/src/index_config/mod.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs
quickwit/quickwit-search/src/tests.rs
quickwit/quickwit-serve/src/delete_task_api/handler.rs

Makes the dynamic mode the default, and allow unspecified doc mapping
Accepting sort by score even if one of the default field does not have fieldnorm.
Minor code cleanup
Closes #2910

Default docmapper with dynamic mode.

---

quickwit/quickwit-indexing/src/actors/indexer.rs

The indexer fails to finalize because the serializer has already quit when handling the SIGINT signal. I don't think this change prevents us from discovering bugs in the future because actors already do a good job at surfacing their own errors.
Before:
After:

Fix error on log on SIGINT signal

---

docs/configuration/index-config.md
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/lib.rs
quickwit/quickwit-indexing/src/actors/indexer.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/actors/packager.rs
quickwit/quickwit-query/src/lib.rs
quickwit/quickwit-query/src/tokenizers.rs
quickwit/quickwit-search/src/leaf.rs

split tokenizer into tokenizer and normalizer
use normalizer for fastfield.
handle two tokenizer manager from tantivy
rise length limit for tokens to 255 bytes
update docs for normalizer
enable fast field tokenizer on Json
tested aggreggations on project airmail with lowercase

add fastfield normalizer

---

.github/workflows/coverage.yml

We want to correctly identify which PR is breaking CI.

Disabling cancelling concurrent coverage workflow.

---

config/quickwit.yaml

The template rendering function does render commented lines, which is an issue for mandatory parameters such as Azure `access_key`. 
```QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER=true \
OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:7281 \
QW_NODE_ID=node-1 \
QW_DATA_DIR=qwdata/node-1 \
cargo run --manifest-path quickwit/Cargo.toml -- run```

Fix quickwit.yaml by adding dummy default Azure access key

---

docs/configuration/node-config.md
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/service.rs

#3305 added a shared AggregationLimits on SearcherContext, but AggregationLimits tracks the memory itself and should not be shared.
closes #3503

remove shared AggregationLimits

---

.github/actions/cargo-build-macos-binary/action.yml
.github/actions/cross-build-binary/action.yml

Uploading nightly builds to a specific nightly release so that we can refer to the nightly build binaries using as stable URL.
Related to https://github.com/quickwit-oss/quickwit/issues/1585

Uploading nightly builds to a release

---

docs/reference/cli.md

Reformat common CLI option docs as a table to make them consistent with auto-generated documentation.
Fixes #3512
It's a doc.

Reformat common CLI option docs as a table

---

docs/configuration/index-config.md
quickwit/Cargo.lock
quickwit/quickwit-doc-mapper/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs

Fix #3531 
When we define the `timestamp_field` in the index config, we implicitly define it as a field path. Dots '.' is used as a field name separator. If a dot is part of a field name, it must be escaped.
This is the same logic for tag fields.
Example:
- `timestamp_field: object.timestamp` for a document like `{"object": {"timestmap": 10}}`
- `timestamp_field: my\\.timestamp` for a document like `{"my.timestamp": 10}`
Tests added.

Timestamp field can now be defined at any field mapping level

---

docs/get-started/installation.md

Make binaries link on `main-branch` of documentation point to nightly 
Closes https://github.com/quickwit-oss/quickwit/issues/1585

Add nightly binaries link to docs

---

docs/configuration/source-config.md
quickwit/quickwit-indexing/src/source/kafka_source.rs

quickwit auto generated group-id can't be used with Aliyun's kafka server.
this patch allows to customize kafka-source's `group.id` via `client_params` in source config.
deployed to my testing cluster, working well with Aliyun's kafka server

allow to customize kafka-source's group.id

---

docs/configuration/index-config.md
quickwit/quickwit-datetime/src/date_time_parsing.rs
quickwit/quickwit-datetime/src/lib.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs

This PR adds a new date input format `DateTimeInputFormat::TimestampFloat` and parses timestamps passed as floats.

Parse float timestamps

---

docs/configuration/index-config.md

In #3473 we changed the default tokenizer for the JSON field from default to raw. This commit reflects this change in the documentation.
Fixes #3557
It's a doc change.

Fix JSON Field docs

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-storage/Cargo.toml
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs

Previously, credentials and region provided in the storage config were ignored.

Honor credentials and region from S3 storage config if provided

---

quickwit/quickwit-codegen/example/src/codegen/hello.rs
quickwit/quickwit-codegen/example/src/lib.rs
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-control-plane/src/codegen/control_plane_service.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs

When you clone a mock, the expectations don't stick around, which causes some trouble when writing unit tests with a `quickwit_common::Pool` of mocks:
```rust
struct Pool<K, V> {
map: Arc<RwLock<HashMap<K, V>>>
}
impl Pool<K, V> where ... {
async fn get<Q>(&self, key: &Q) -> Option<V> where ... {
self.map.read().await.get(key).cloned() # <-- cloning the mock
}
}
```
This PR introduces a mock wrapper that allows mocks to be cloned using an `Arc`. The `Mutex` is mandatory because methods of service client traits are `&mut self`.

Clone mocks while keeping expectations around

---

config/quickwit.yaml

Adds the other options of `S3StorageConfig` to the example configuration and sets examples to defaults per https://quickwit.io/docs/configuration/node-config/#s3-storage-configuration

config: Added more S3StorageConfig options

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-actors/Cargo.toml
quickwit/quickwit-actors/src/actor.rs
quickwit/quickwit-actors/src/actor_context.rs
quickwit/quickwit-actors/src/envelope.rs
quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-actors/src/spawn_builder.rs
quickwit/quickwit-actors/src/supervisor.rs
quickwit/quickwit-actors/src/tests.rs
quickwit/quickwit-indexing/src/source/ingest_api_source.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/source/pulsar_source.rs

- Actors don't need to be `Sync` because they're behind channels and process messages sequentially
- Messages sent to actors don't need to be `Sync` either.
I used `SyncWrapper` in this PR to make the actor loop future `Sync`.
- added unit tests

Remove unnecessary `Sync` bounds in actor framework

---

docker-compose.yml

Updates versions of localstack and azure in docker-compose.
I have been troubleshooting running tests on arm64 Ubuntu, and as part of troubleshooting I have upgraded the version of these images. The test continue to fail on arm64 with the previous version as well as this one, but it works fine on amd64.

Bump versions of localstack and azure

---

quickwit/Cargo.lock
quickwit/quickwit-codegen/example/Cargo.toml
quickwit/quickwit-codegen/example/src/codegen/hello.rs
quickwit/quickwit-codegen/example/src/hello.proto
quickwit/quickwit-codegen/example/src/lib.rs
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-common/src/stream_utils.rs
quickwit/quickwit-control-plane/src/codegen/control_plane_service.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs

I want to support replications from primary shards to replica shards with streams rather than multiple requests/responses because the ordering of messages guaranteed by gRPC streams makes error handling much easier.
- Add unit tests

Add support for client-side streaming for code-generated gRPC clients

---

quickwit/Cargo.lock
quickwit/quickwit-control-plane/Cargo.toml
quickwit/quickwit-control-plane/src/indexing_plan.rs
quickwit/quickwit-control-plane/src/lib.rs
quickwit/quickwit-control-plane/src/scheduler.rs
quickwit/quickwit-serve/src/lib.rs

Replace ServiceClientPool with Pool in control plane services.
Updated existing tests to ensure compatibility with the new pool.

Refactor service pool in control plane service

---

.github/workflows/coverage.yml
docker-compose.yml

Run coverage workflow on BuildJet. The key was to increase the amount of memory while not increasing the number of jobs as quickly. Thanks for the tip @imotov.
Ran workflow multiple times:
https://github.com/quickwit-oss/quickwit/actions/runs/5520393533
https://github.com/quickwit-oss/quickwit/actions/runs/5520702941
https://github.com/quickwit-oss/quickwit/actions/runs/5520566576
https://github.com/quickwit-oss/quickwit/actions/runs/5521004488

Run coverage workflow on BuildJet

---

quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/lib.rs
quickwit/quickwit-serve/src/lib.rs

Introduces a distinct Control Plane component, which is now separate from the Indexing Scheduler.
See #3443
See #3622
By running existing tests.

Separate IndexingScheduler from Control Plane

---

quickwit/quickwit-opentelemetry/src/otlp/logs.rs

Motivation: the log message in put in `body.message` and we should tokenize it with the default tokenizer.

Fix otel log mapping.

---

docs/configuration/node-config.md
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/storage_config.rs

- Add Digital Ocean storage flavor
- Fix MinIO flavor
- Run the following integrating test on Digital Ocean:
```rust
fn test_suite_on_s3_storage_path_style_access() {
let s3_storage_config = S3StorageConfig {
force_path_style_access: true,
disable_multi_object_delete: true,
..Default::default()
};
let bucket_uri = append_random_suffix("s3://quickwit-integration-tests/test-path-style-access");
let test_runtime = test_runtime_singleton();
test_runtime.block_on(run_s3_storage_test_suite(s3_storage_config, &bucket_uri));
}
```
```bash
AWS_PROFILE=do \
AWS_REGION=nyc3 \
QW_S3_ENDPOINT=https://quickwit-integration-tests.nyc3.digitaloceanspaces.com \
cargo test --manifest-path quickwit/Cargo.toml -p quickwit-storage --all-features -- test_suite_on_s3_storage_path_style_access …
```

Add Digital Ocean storage flavor

---

quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-cli/src/service.rs
quickwit/quickwit-cli/src/tool.rs
quickwit/quickwit-cli/tests/helpers.rs
quickwit/quickwit-cluster/src/lib.rs
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-config/src/node_config/serialize.rs
quickwit/quickwit-indexing/src/lib.rs
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/tests/basic_tests.rs
quickwit/quickwit-integration-tests/src/tests/index_tests.rs
quickwit/quickwit-janitor/src/lib.rs
quickwit/quickwit-serve/src/elastic_search_api/bulk.rs
quickwit/quickwit-serve/src/elastic_search_api/mod.rs
quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/node_info_handler.rs

Rename the legacy `QuickwitConfig` to `NodeConfig`.

Rename `QuickwitConfig` to `NodeConfig`

---

docs/log-management/send-logs/using-otel-collector-with-helm.md
docs/overview/concepts/querying.md
docs/reference/rest-api.md
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/search_api/mod.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

- Expose sort by multiple fields in REST API
- Preserve `sort_by_field` parameter backward-compatibility
- Sort by `_score` sets `Desc` sort order by default
Updated unit tests

Expose sort by multiple fields in REST API

---

quickwit/quickwit-indexing/src/actors/indexing_service.rs

Spotted as I was reading some code in the indexing service.

Remove extra metastore call in indexing service

---

docs/configuration/index-config.md

and fix example config using _ in integers, which isn't supported
fix #3611

document `maturation_period`

---

.github/workflows/ci.yml

Added always() in step conditions to allow steps to run even if previous

---

quickwit/quickwit-common/src/uri.rs
quickwit/quickwit-config/src/node_config/serialize.rs

Fix https://github.com/quickwit-oss/quickwit/issues/2991
The goal is to ensure that protocol are well validated, instead of having some panic in later stage.
Before
```
url -XPOST http://localhost:7280/api/v1/indexes -H "content-type: application/yaml" --data-binary @example.yaml
curl: (52) Empty reply from server
```
After
```
curl -XPOST http://localhost:7280/api/v1/indexes -H "content-type: application/yaml" --data-binary @example.yaml
{
"message": "Invalid config: Failed to read YAML file.: Unknown URI protocol `http`.."
}
```
* manually by creating an index with an invalid `index_uri`
* added test in Uri

[fix] Quickwit panics while attempting to parse index_uri

---

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs

Reverts quickwit-oss/quickwit#3702. It broken the CI failpoints unit tests.

Revert "Making sure indexing pipeline terminates rapidly on our happy path."

---

quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-storage/src/lib.rs
quickwit/quickwit-storage/src/local_file_storage.rs
quickwit/quickwit-storage/src/object_storage/azure_blob_storage.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage_resolver.rs
quickwit/quickwit-storage/src/ram_storage.rs
quickwit/quickwit-storage/src/storage_factory.rs
quickwit/quickwit-storage/src/storage_resolver.rs

For #3443 I need to be able to perform initialization on storage factory level and in order to do that I need access to the config parameters during initialization rather than during storage resolution. This PR moves the storage config parameters to the storage initializer.
By running existing tests.

Refactor storage factory initialization

---

quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs

Timestamp and tag fields shouldnt start or end with dot
Fixes: https://github.com/quickwit-oss/quickwit/issues/3538
Co-authored-by: @sravan-s

validate tag timestamp

---

docs/internals/scroll.md
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-common/src/shared_consts.rs
quickwit/quickwit-janitor/src/actors/garbage_collector.rs
quickwit/quickwit-proto/protos/quickwit/search.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/client.rs
quickwit/quickwit-search/src/cluster_client.rs
quickwit/quickwit-search/src/fetch_docs.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/scroll_context.rs
quickwit/quickwit-search/src/search_job_placer.rs
quickwit/quickwit-search/src/service.rs
quickwit/quickwit-serve/Cargo.toml
quickwit/quickwit-serve/src/elastic_search_api/filter.rs
quickwit/quickwit-serve/src/elastic_search_api/mod.rs
quickwit/quickwit-serve/src/elastic_search_api/model/scroll.rs
quickwit/quickwit-serve/src/elastic_search_api/model/search_query_params.rs
quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs
quickwit/quickwit-serve/src/search_api/grpc_adapter.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs
quickwit/rest-api-tests/run_tests.py
quickwit/rest-api-tests/scenarii/es_compatibility/0011-scroll-api.yaml

Solution described in docs/internals/scroll.md.
Tests
Unit tests for the simplistic KV score.
Unit test for the scroll API
Rest API test comparing output from ElasticSearch.
Closing #3551

Added Scroll API

---

docs/get-started/installation.md

There were a few changes that the installation guide needed in order to be grammatically correct. This commit updates the guide with these changes.
As this was just some doc changes it does not require testing

Fix grammatical errors in the installation guide

---

quickwit/quickwit-storage/src/storage_resolver.rs

In #3709 there was a refactor that removed `StorageConfig` from the scope of the changed file in this commit. This was fine as the function `register` in StorageResolveBuilder did not need it anymore. However, the docs alluded to registering both a factory and a config. When running `make build-docs` for a different change I ran into this causing the command to fail. This change updates the docs so that they can build properly again.
I ran `make build-docs` to make sure they built and checked the output.

Fix broken doc link in quickwit-storage

---

Dockerfile
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-config/src/source_config/serialize.rs
quickwit/quickwit-indexing/Cargo.toml
quickwit/quickwit-indexing/src/source/gcp_pubsub_source.rs
quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/source/pulsar_source.rs
quickwit/quickwit-metastore/src/checkpoint.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs

Continuation of the great work of @magnalite and following advice of @guilload 
This PR, fix the compilation/formatting issues of the previous PR and put the code behind a flag `gcp-pubsub`
Also renamed everywhere `pubsub` by `gcp-pubsub` or `GcpPubSub` to reduce confusion with other pubsub system.
I didnt test it. It will be added in step 3
step 2: focus on supporting at-least-once delivery semantics for now and improve the current implementation as you suggested
step 3: add unit and integration tests for this source
step 4: test at scale (I can help with that and do so on our GCP account)
step 5: opportunistically support exactly-once delivery semantics

Gcp pubsub source

---

quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-cli/src/tool.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/tests.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/search_api/mod.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

Fixes #3554
Add `tool local-search` command  to reenable searching without starting a server.
One test added to check the parsing;
Tested locally on the [quickstart](https://quickwit.io/docs/get-started/quickstart/) StackOverflow dataset:
```console
tool local-search --index stackoverflow --query "search AND engine" --sort-by-field="-creationDate" --config ../config/quickwit.yaml
```

Add local search CLI.

---

quickwit/quickwit-query/src/elastic_query_dsl/mod.rs
quickwit/quickwit-query/src/elastic_query_dsl/term_query.rs
quickwit/quickwit-query/src/elastic_query_dsl/terms_query.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0015-terms-query.yaml

Implemented Elasticsearch's TermsQuery

---

.github/workflows/coverage.yml
docker-compose.yml
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-indexing/Cargo.toml
quickwit/quickwit-indexing/src/source/gcp_pubsub_source.rs

**PR is still in draft, few things I need to do before review**
Before adding new functionality to gcp pubsub indexer (`at_least_once` support), we want to be sure that basics functionality are working.
As suggested in https://github.com/quickwit-oss/quickwit/pull/3720#issuecomment-1675038458 this PR is adding basic integration test. 
We are also doing small improvement: upgrade the dependency, better support for GCP auth.
This pr is adding integration test :)

Add initial test for gcp pubsub indexer

---

quickwit/Cargo.toml
quickwit/quickwit-aws/Cargo.toml
quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-common/src/retry.rs
quickwit/quickwit-common/src/tower/mod.rs
quickwit/quickwit-common/src/tower/retry.rs
quickwit/quickwit-metastore/src/metastore/retrying_metastore/error.rs
quickwit/quickwit-metastore/src/metastore/retrying_metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/retrying_metastore/retry.rs
quickwit/quickwit-metastore/src/metastore/retrying_metastore/test.rs

Implement a Tower retry [policy](https://docs.rs/tower/latest/tower/retry/trait.Policy.html) based on `RetryParams`. Now we can layer a Tower [Retry](https://docs.rs/tower/latest/tower/retry/struct.Retry.html) service on top of our clients (ingester router, ingesters, control plane, ...). Fixes #3109.
Added unit test.

Implement Tower retry policy

---

quickwit/Cargo.lock
quickwit/Cargo.toml

Let's stick to 1.0.171 to avoid supply chain attacks.

`serde_derive` started shipping binaries for its macros.

---

quickwit/quickwit-actors/src/actor_context.rs
quickwit/quickwit-actors/src/actor_handle.rs
quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/tool.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs

This introduce a refresh observation method, that does not wait
for anything but just triggers an eventual refresh of the last
observation.
This method includes debouncing logic to avoid stacking up messages.
We then use it in supervisors, which the other merit of making the
Supervise handler return much faster.
Before we were waiting for the observation to timeout.
Closes https://github.com/quickwit-oss/quickwit/issues/3485

Prevent `Observe` messages from stacking up

---

quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/service.rs

Instead, of spawning N tasks and acquiring the semaphore within the tasks, we do the acquisition before spawning the task.
This has two effect:
- we end up running less tasks at a given time.
- In presence of concurrent request, we should naturally acquire permits in bulks (because we do not yield between each acquire)
In theory, the latter should decrease average latency. Ideally we should have some scheduler logic...
I opened a ticket to improve this.
https://github.com/quickwit-oss/quickwit/issues/3784

Change in the leaf search semaphore acquisition logic.

---

Dockerfile

Move away from deprecated nodesource installer script (https://github.com/nodesource/distributions#new-update-%EF%B8%8F).
Benefits of the change:
- avoid 60s deprecation wait in docker build
- the installer script might just be removed by nodesource some time in the future
Ran docker build locally.

Switch to recommended Node.js install in Dockerfile

---

docs/operating/aws-costs.md
docs/overview/introduction.md

reference blog post in cost section

---

quickwit/quickwit-codegen/example/src/codegen/hello.rs
quickwit/quickwit-codegen/example/src/hello.proto
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs
quickwit/quickwit-proto/protos/quickwit/control_plane.proto
quickwit/quickwit-proto/protos/quickwit/indexing.proto
quickwit/quickwit-proto/protos/quickwit/router.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.indexing.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.router.rs

With this change, you can read the comments directly on the generated code instead of returning to the proto files.
- Updated example.
- Inspected output of generated code.

Generate service trait with comments

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/models/indexed_split.rs
quickwit/quickwit-query/src/query_ast/user_input_query.rs

fix #3714 
tested manually
Could probably use some tests

add support for exist in query language

---

quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-cli/src/logger.rs
quickwit/quickwit-cli/src/main.rs

To have a unified tracing experience accross all binaries generated by Quickwit (e.g Lambda binaries added for https://github.com/quickwit-oss/quickwit/issues/3862), it is necessary to make the setup_logging_and_tracing public.
This is just refactoring and it builds.

Expose setup_logging_and_tracing

---

quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/tests.rs

return error when search with start_timestamp or end_timestamp but timestamp field is not defined in index
Check if timestamp field is not defined but start_timestamp or end_timestamp is set when searching
1, Create index without timestamp field defined
```
doc_mapping:
field_mappings:
- name: title
type: text
tokenizer: default
record: position
stored: true
- name: body
type: text
tokenizer: default
record: position
stored: true
- name: creationDate
type: datetime
fast: true
input_formats:
- rfc3339
precision: seconds
timestamp_field: creationDate
search_settings:
default_search_fields: [title, body]
indexing_settings:
commit_timeout_secs: 10
```
2, Injest data
```
./quickwit index ingest --index stackoverflow --input-pathstackoverflow.posts.transformed-10000.json --force
```
3, Search …

add more check logic when processing search request

---

quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-metastore/src/checkpoint.rs

Users rely on committed offsets to monitor ingestion lag and trigger retention.
If you wonder why I'm doing this now, I'm just trying to dust off old branches accumulating on my machine :)
- Added test

Commit Kafka offsets on suggest truncate

---

quickwit/quickwit-serve/src/elastic_search_api/filter.rs
quickwit/quickwit-serve/src/elastic_search_api/mod.rs

Some clients like the [opensearch-js](https://github.com/opensearch-project/opensearch-js/blob/9228ff101da32ad0d738addd5b9ca1150d8d70fb/api/api/ping.js#L50) send a HEAD request on the elasticsearch root endpoint to check if it's alive.
This PR adds the support of HEAD request on the `_elastic` endpoint, now returning a 200.

Support for head request on elasticsearch root endpoint.

---

quickwit/quickwit-serve/src/search_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/multi-indices/0001-muti_indices_query.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/multi-indices/_ctx.yaml

Reason: elasticsearch supports `,` and `2%C` as separators of index patterns.

Add support for url encoded commas in comma separated index patterns.

---

quickwit/quickwit-cluster/src/change.rs
quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-cluster/src/lib.rs

Emit `ClusterChange::Remove` only if node generation IDs match, which prevents client pools from evicting nodes that have just rejoined the cluster.
I reproduced the issue on 0.6.3 and manually verified that this PR fixes the bug. I'll shortly push a PR for `main`, which will contain a unit test.

Emit `ClusterChange::Remove` only if node generation IDs match

---

quickwit/quickwit-query/src/elastic_query_dsl/match_bool_prefix.rs
quickwit/quickwit-query/src/elastic_query_dsl/match_phrase_query.rs
quickwit/quickwit-query/src/elastic_query_dsl/match_query.rs
quickwit/quickwit-query/src/elastic_query_dsl/mod.rs
quickwit/quickwit-query/src/elastic_query_dsl/string_or_struct.rs
quickwit/quickwit-query/src/elastic_query_dsl/term_query.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0006-term_query.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0009-bool_query.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0016-misc-query.yaml

Refactor the string_or_struct logic and enables it for TermQuery.

---

quickwit/quickwit-indexing/src/actors/merge_planner.rs

This set is used as a filter.
We append `NewSplits` to it, and never remove any splits from it.
When it reaches a size that is too large, we rebuild it entirely.
Closes #3847

Introduce a `known_splits` set to discard redundant NewSplits messages.

---

quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/rest.rs

This change adds the ability for the user to configure the content limit for the ingest api. It is related to the feature request made in #3797.
I have tried adding unit tests but they were not working as expected. I wanted the PR out to get the initial comments, I will add the tests in a follow-up commit to this PR.

Add parameter to configure content limit for ingest api

---

quickwit/quickwit-indexing/src/source/ingest/mod.rs
quickwit/quickwit-ingest/src/ingest_v2/gc.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/models.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-proto/protos/quickwit/ingester.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-proto/src/ingest/ingester.rs

Before this change, indexers called truncate on leaders, and leaders replicated the truncation request on followers. After this change, indexers are responsible for calling `truncate` on both leaders and followers. Leaders are no longer in charge of replicating the request. 
That way, followers see their queues truncated even if leaders are unavailable. The code is also simplified.
Updated tests

Call `truncate` on leaders AND followers

---

quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/shards.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs

This change groups the subrequests by index UID and batches them.
No functional changes.

Perform a single mutation per index in file-backed metastore

---

quickwit/quickwit-doc-mapper/benches/doc_to_json_bench.rs
quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-ingest/src/ingest_v2/gc.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-proto/protos/quickwit/ingester.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs

Use a single lock for mrecordlog and ingester state to avoid deadlocks.
Updated unit tests but no functional changes.

Use same lock for mrecordlog and ingester state

---

.github/workflows/publish_nightly_packages.yml

The currently nightly build fails on ARM and no packages are published. It would be better to still get the X86 artifacts.

Don't failfast in nightly build matrices

---

.github/actions/cargo-build-macos-binary/action.yml
.github/actions/cross-build-binary/action.yml

We are still having errors in the frontend build in the nightly CI after https://github.com/quickwit-oss/quickwit/pull/3877.
From the logs, it seems `node-gyp` is not installed. Even though yarn seems to install it automatically, when we compare the logs of various runs, it seems that it does so in parallel, and there might be some race condition there that would explain the transient failures. Eagerly installing `node-gyp` might help.

Fix nightly builds

---

quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/control_plane_model.rs
quickwit/quickwit-control-plane/src/indexing_plan.rs
quickwit/quickwit-control-plane/src/indexing_scheduler.rs
quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-control-plane/src/lib.rs
quickwit/quickwit-control-plane/src/tests.rs
quickwit/quickwit-metastore/src/metastore/index_metadata/mod.rs
quickwit/quickwit-proto/src/types.rs

The control plane model now offers a concise view of the Metastore.
The indexing scheduler query the metastore at all.
This also cleans up the hack the populates the list of indexing task with ingest v2 tasks by mutating the list of tasks
Refactoring:
We rely on SourceUid more broadly in the code.
The unit test were using IndexUid in a broken way in places.
This is now fixed.
This PR introduces a LogicalIndexTask. The idea is to have it hold all
information necessary for us to do the placement.
Right now this means only the max pipeline per index parameter (allowing
us to remove the ugly lookup in the source config map).
We will need to also add information about the desired number of pipeline, possibly the leader/follower for locality, etc.
In the next PR we will most likely also break …

Extending the control plane model

---

quickwit/Cargo.lock
quickwit/Cargo.toml

The current pinned version ae1ca3f does not exist anymore.

Upgrade to latest main of mrecordlog

---

quickwit/quickwit-cli/src/tool.rs
quickwit/quickwit-cluster/src/change.rs
quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-cluster/src/lib.rs
quickwit/quickwit-cluster/src/member.rs
quickwit/quickwit-proto/src/types.rs

The issue is that the cluster logic keeps track of nodes joining and leaving using (`node_id`, `incarnation_id`), while client pools keep track of nodes using only `node_id`.
When a node restarts and becomes ready quickly, the new node (`node_id` + `incarnation_id + 1`) joins the cluster before the previous node leaves and the following cluster change events are triggered:
1. Add (`node_id` + `incarnation_id + 1`)
2. Remove (`node_id` + `incarnation_id`)
It translates at the pool level to:
1. Add `node_id`
2. Remove `node_id`
The bug used to be less visible because we used to diff the whole pool for each Chitchat event, but now the diff is at the node level (incremental).
To fix the issue, I only emit a  `Remove` event when incarnation IDs match. Additionally, when a node rejoins the …

Fix the cluster change stream when nodes rejoin the cluster quickly

---

quickwit/quickwit-cli/src/cli.rs
quickwit/quickwit-cli/src/logger.rs
quickwit/quickwit-cli/src/main.rs

Before this PR, NO_COLOR had to be true or false.
This PR interprets the environment variable as true for any value that is non empty as described in https://no-color.org/
This fixes the config in our own configuration:
https://github.com/quickwit-oss/quickwit/blob/kzf2f6aacca1cd645a473b7a9ec0707a6efc6e323/docs/log-management/send-logs/using-otel-collector-with-helm.md?plain=1#L75

Fix the NO_COLOR environment variable interpretation.

---

quickwit/quickwit-jaeger/Cargo.toml
quickwit/quickwit-opentelemetry/src/otlp/trace_id.rs
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/find_trace_ids_collector.rs

Avoiding base64 translation when serializing Traces with postcard
This PR also adds unit tests/proptest checking the serializing of
Vec<Span> with postcard.

Avoiding base64 translation when serializing Traces with postcard

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/tool.rs
quickwit/quickwit-jaeger/src/lib.rs
quickwit/quickwit-proto/protos/quickwit/search.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/leaf_cache.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

fix #3997
does not impact #3998 as it would need more work. Tracing uses aggregations, which don't profit from that optimization yet
created an index with single split documents, made a few query and verified `num_hits` was below what's expected when `count_all=false`, and normal when it's true or absent

plug exact count optimization

---

quickwit/quickwit-codegen/README.md
quickwit/quickwit-codegen/example/build.rs
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-ingest/build.rs
quickwit/quickwit-proto/build.rs

Issue: #3995
I have implemented a builder for the `Codegen` following the example described in #3995. I also replaced existing calls to `Codegen::run` and `Codegen::run_with_config` with the builder.
I removed `Codegen::run` as it is never called and I am unsure if it even makes sense to keep `run_with_config` separate from the builder. What do you think?
There are conversions from &[&str] to Vec<String> and back again in the builder which I don't like. However, I think overall it is the simplest implementation in this case as we avoid lifetimes and trait bounds. Apart from just merging `run_with_config` with the builder.
Upon writing this I realized that I forgot to update the codegen readme. I will update the readme once the implementation is approved (to avoid having to keep updating …

Introduce a builder for Codegen

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-metastore/Cargo.toml
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/metastore/postgresql_model.rs

This PR is a draft version to kickstart #3758. I used `sea_query` to update one sql query and I want to get the initial comments from @guilload on whether this is fine. If the `sea_query` implementation seems good, then I will continue with converting the remaining sql strings into the sea query orm syntax. Otherwise, I will try to reach other options.
This PR was tested using `cargo test --features=postgres`.

Update sql strings with sea_query sql statements

---

quickwit/quickwit-cli/src/service.rs
quickwit/quickwit-cli/tests/helpers.rs
quickwit/quickwit-codegen/example/src/codegen/hello.rs
quickwit/quickwit-codegen/example/src/lib.rs
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-common/src/uri.rs
quickwit/quickwit-config/src/index_config/mod.rs
quickwit/quickwit-config/src/index_config/serialize.rs
quickwit/quickwit-indexing/src/test_utils.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_metastore_factory.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/metastore_resolver.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.indexing.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.router.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-search/src/service.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-storage/src/local_file_storage.rs
quickwit/quickwit-storage/src/object_storage/azure_blob_storage.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs
quickwit/quickwit-storage/src/ram_storage.rs
quickwit/quickwit-storage/src/storage_resolver.rs
quickwit/quickwit-storage/tests/s3_storage.rs

Before, the protocol normalization behavior was different depending on whether the Uri was built with `from_well_formed` and `from_str`.
Also, `from_well_formed` was used over string passed via gRPC.

Making the contracts in Uri a tiny bit clearer.

---

quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/metastore/postgresql_model.rs

The change adds an order by clause to the sql query when the split id is provided. This fixes the bug reported by #4046 .
An unit test was to added to check if the correct query was being returned.

Update query to order by split id when offset is provided

---

quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/control_plane_model.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-janitor/src/actors/delete_task_service.rs
quickwit/quickwit-janitor/src/actors/garbage_collector.rs
quickwit/quickwit-janitor/src/actors/retention_policy_executor.rs
quickwit/quickwit-metastore/src/lib.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-metastore/src/tests/mod.rs
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-proto/src/metastore/mod.rs
quickwit/quickwit-search/src/error.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/multi-indices/0001-muti_indices_query.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/multi-indices/0002-muti_indices_scroll.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/multi-indices/0003-multi_indices_aggs.yaml

Fixes #4042
Tested with rest integration tests (checked against elasticsearch)

Bugfix #4042 - An index ptn not matching any index is ok.

---

quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/mod.rs

The allocation attempts to match the previous
plan as much as possible.
It also includes some hysteresis effect to avoid
flip flapping between two N and N+1 pipelines.
Closes #4010

Ensures the load of pipelines does not exceed 80%.

---

quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/mod.rs
quickwit/quickwit-integration-tests/Cargo.toml

The testsuite feature flag has for effect to change the janitor poll period. It is why one of the unit test was not passing when running cargo test from the `quickwit-integration-tests` directory.

Fixing unit tests.

---

quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/control_plane_model.rs
quickwit/quickwit-index-management/src/index.rs
quickwit/quickwit-metastore/src/tests/shard.rs

Restrict list shards to enabled ingest V2 sources

---

quickwit/quickwit-codegen/example/src/codegen/hello.rs
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-control-plane/src/tests.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs
quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/ingest_v2/workbench.rs
quickwit/quickwit-metastore/src/checkpoint.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/shards.rs
quickwit/quickwit-proto/protos/quickwit/control_plane.proto
quickwit/quickwit-proto/protos/quickwit/ingest.proto
quickwit/quickwit-proto/protos/quickwit/ingester.proto
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/protos/quickwit/router.proto
quickwit/quickwit-proto/protos/quickwit/search.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.indexing.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.router.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-proto/src/control_plane/mod.rs
quickwit/quickwit-proto/src/ingest/mod.rs

- Split `GetOrCreateOpenShardsReponse` into `successes` and `failures` to keep track of indexes/sources not found
- Remove leaders from ingester pool on transport error
- Tested locally

Handle index/source not found and timeout/transport errors

---

quickwit/quickwit-ingest/src/ingest_v2/fetch.rs

This partially fixes the deadlock observed in #4070. When the source shuts down, it does not close its connections to ingesters, which in turn can't shut down their gRPC servers.
To completely fix the issue, ingesters should close their shards and outgoing connections on shutdown. There's an issue already open.
I tested this PR on Paul's integration tests branch.

Abort fetch stream tasks upon dropping multi fetch stream

---

docs/configuration/source-config.md
quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/mod.rs

Previously, the source ignored the `auto.offset.reset` configuration parameter and always began consumption of a partition from the beginning. With this change, it now honors the client configuration. 
Added test

Honor `auto.offset.reset` parameter in Kafka source

---

quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/models.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs

If we delete the queue of a closed shard on truncate at EOF  and then the node crashes, upon restarting, the node is no longer aware of the closed shard, and any router that is also not aware of the shard being closed can recreate it...
- This scenario could use an integration test

Stop deleting queue on truncate at EOF

---

quickwit/quickwit-ingest/src/ingest_v2/fetch.rs

This change makes the contract of the fetch stream more clear. Previously, we couldn't tell upon receiving `None` for the next message whether consumption of the stream succeeded or not.

Close fetch stream with an error if it does not reach EOF

---

quickwit/quickwit-indexing/src/source/pulsar_source.rs

Closes #2897 
Confirms the layout of the position ID for pulsar message IDs and adds an explanation as to why the order is what it is.

QW-2897: Update pulsar message ID comment

---

quickwit/quickwit-search/src/root.rs

The "Merged leaf search response." log can get out of hand as it prints the entire response, including some binary vectors. This change keeps only some high level info about the respone.

Shorten overly verbose debug log

---

quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/models.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/ingest_v2/shard_table.rs
quickwit/quickwit-proto/protos/quickwit/control_plane.proto
quickwit/quickwit-proto/protos/quickwit/ingest.proto
quickwit/quickwit-proto/protos/quickwit/ingester.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.rs
quickwit/quickwit-proto/src/ingest/mod.rs

Fix #4023 
When a `ClosedShardsRequest` is sent to the ingester, we close the related shards if any, and add the Eof record. The fetch task is notified so the follower will receive the Eof record.
Test added to check the closing, the Eof record and the notification.
Note: I did not handle the closing of the shard on the replica. We could send a replication request to the replica and handle the eof position on the replica.

Add  ingester close shards gRPC

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-ingest/Cargo.toml
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/mod.rs
quickwit/quickwit-ingest/src/ingest_v2/mrecord.rs
quickwit/quickwit-ingest/src/ingest_v2/mrecordlog_utils.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-ingest/src/queue.rs
quickwit/quickwit-proto/protos/quickwit/ingester.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs

Bound memory and disk usage of mrecordlog.
There remain a few things to implement for the functionality to work correctly:
- handle `ResourceExhausted` failures in the router and control plane
- Replicate records on follower first then on leader (as opposed to leader first then follower currently)
I'll tackle those in two separate PRs.
- Updated existing unit tests

Bound memory and disk usage of mrecordlog

---

quickwit/quickwit-common/src/tower/rate.rs
quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/mod.rs
quickwit/quickwit-ingest/src/ingest_v2/rate_limiter.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-serve/src/lib.rs

Rate limit ingestion per shard to 5 MB/s, allowing bursts of 10 MB. Requests are rejected immediately to enable routers to retry another shard.
I will implement the router and control plane logic to handle rate limiting in separate PRs.

Rate limit ingestion per shard to 5 MB/s

---

quickwit/quickwit-common/src/stream_utils.rs
quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-indexing/src/source/ingest/mod.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs
quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/mod.rs
quickwit/quickwit-ingest/src/ingest_v2/models.rs
quickwit/quickwit-ingest/src/ingest_v2/mrecordlog_utils.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/ingest_v2/shard_table.rs
quickwit/quickwit-ingest/src/ingest_v2/test_utils.rs
quickwit/quickwit-proto/protos/quickwit/control_plane.proto
quickwit/quickwit-proto/protos/quickwit/ingest.proto
quickwit/quickwit-proto/protos/quickwit/ingester.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.rs
quickwit/quickwit-proto/src/ingest/ingester.rs
quickwit/quickwit-proto/src/ingest/mod.rs
quickwit/quickwit-serve/src/lib.rs

Add a `Decommission` RPC to ingesters. By default, ingesters are in `Ready` status. Upon receiving a decommissioning request, ingesters change their status to `Decommissioning`, close all their shards, become read-only and wait for them to be indexed by monitoring calls to `truncate`. When the indexing of all the shards is completed, ingesters transition to the `Decommissioned` status at which point they become safe to shut down.
I also added a `OpenObservationStream` RPC to ingesters, so we can track the status of the decommissioning process. In the future, we can enrich the `ObservationMessage` object to track more things.
- Add unit tests
- Tested manually

Implement ingester graceful shutdown

---

quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-common/src/pubsub.rs
quickwit/quickwit-common/src/shared_consts.rs
quickwit/quickwit-common/src/tower/event_listener.rs
quickwit/quickwit-control-plane/src/control_plane_model.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/mod.rs
quickwit/quickwit-control-plane/src/lib.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-indexing/src/models/mod.rs
quickwit/quickwit-indexing/src/models/shard_positions.rs
quickwit/quickwit-indexing/src/source/ingest/mod.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-metastore/src/checkpoint.rs
quickwit/quickwit-proto/src/types/mod.rs
quickwit/quickwit-proto/src/types/position.rs

Exposing the published position through chitchat.
The info is transmitted via an EventSubscriber at the same time as regular truncate:
- upon fetching the starting offset when assigning a shard to an IngestSource
- upon suggest truncate.
This PR does not include any code to remove sources yet. 
I created #4143 accordingly.

Exposing published position thru chitchat

---

quickwit/quickwit-storage/Cargo.toml
quickwit/quickwit-storage/src/lib.rs
quickwit/quickwit-storage/src/object_storage/azure_blob_storage.rs
quickwit/quickwit-storage/tests/azure_storage.rs
quickwit/quickwit-storage/tests/s3_storage.rs

I noticed I was building the Azure deps when testing `quickwit-ingest`.

Stop building Azure storage as part of `testsuite` feature

---

docs/get-started/tutorials/tutorial-hdfs-logs.md

The linked dataset https://quickwit-datasets-public.s3.amazonaws.com/hdfs-logs-multitenants.json.gz is the half of what is specified in the docs.

Fix docs to match linked dataset

---

quickwit/quickwit-doc-mapper/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/tokenizer_entry.rs
quickwit/quickwit-query/Cargo.toml

I noticed `lindera` was compiled as I was testing `quickwit-ingest`.
Tested with:
`cargo test --manifest-path quickwit/Cargo.toml -p quickwit-query`
`cargo test --manifest-path quickwit/Cargo.toml -p quickwit-doc-mapper`
`cargo test --manifest-path quickwit/Cargo.toml -p quickwit-indexing`

Take `multilang` feature out of `quickwit-doc-mapper/testsuite`

---

LICENSE.md

This PR adds a link to the local `LICENSE_AGPLv3.0.txt` file in the `README.md` file. This allows users to easily access and read the full Affero General Public License version 3.0 that our project uses.
This PR was tested by clicking on the newly added link in the `README.md` file. The link correctly redirects to the `LICENSE_AGPLv3.0.txt` file, confirming that the link has been successfully added and is functioning as expected.

 Add local AGPL license link in LICENSE.md

---

quickwit/quickwit-query/src/elastic_query_dsl/exists_query.rs
quickwit/quickwit-query/src/elastic_query_dsl/mod.rs
quickwit/quickwit-serve/src/elastic_search_api/model/multi_search.rs
quickwit/quickwit-serve/src/elastic_search_api/model/search_body.rs
quickwit/quickwit-serve/src/elastic_search_api/model/search_query_params.rs

ES compatible API does not accept malformed requests and returns `400` and the following body instead
```
{
"message": "unknown field `term`, expected one of `from`, `size`, `query`, `sort`, `aggs`, `track_total_hits`, `stored_fields`, `search_after` at line 1 column 7"
}
```
a unit test has been added, local testing with the change has been done as well
https://github.com/quickwit-oss/quickwit/issues/4132

fix: avoid parsing search malformed requests

---

quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-serve/src/rest.rs

Instead of relying on the hyper graceful shutdown, which does not shutdown in the presence of existing http connections.
Closes #4169

Changing the shutdown logic for the rest server.

---

quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-cluster/src/member.rs
quickwit/quickwit-cluster/src/node.rs
quickwit/quickwit-proto/src/indexing/mod.rs

Fixed the serialize deserialization of the indexing state to include
shard lists.
Before this, there was no notion of shards and indexers were just
exposing the number of pipelines per source_uid.
With ingest v2, the list of shard is part of indexing tasks, and the
control plane wants to diff against it.
The serialization format goes
`[1,2][3]` to express two pipelines with respectively shard [1,2] and
`[3]`.
For a source that does not have notion of shards, like kafka, two
pipelines simply look as follows: `[][]`
Also took it as an opportunity to clean up the code
and increase the test coverage.
I think we also used to not skip over tombstoned entries
Related with  #4174

Fixed the serialize deserialization of the indexing state to include 

---

quickwit/quickwit-indexing/src/actors/doc_processor.rs

As mentioned here  https://github.com/quickwit-oss/quickwit/issues/4113. To enhance warn log info.
```
2023-11-22T14:55:22.305Z  WARN quickwit_indexing::actors::doc_processor: index_id="gh-archive" source_id="_ingest-api-source" error=ValueError("created_at", "failed to parse datetime `2023-11-11 09:53:11.123456` using the following formats: `rfc3339`")
```

Add the index ID and source ID in the warn logs

---

.devcontainer/devcontainer.json
.devcontainer/post-create.sh
.devcontainer/welcome.txt

Fixes #4163 
I would like to propose adding a dev container configuration for GitHub Codespaces. This would make it easier for developers to set up their environment and work on the project without much hassle and effort. Setting up the project for the first time requires CMake, Docker, node, yarn, awslocal protoc and other tools. However, installing and configuring these tools manually can be time-consuming and error-prone, especially for new contributors or low-end machines. 
It would be nice to have a dev container configuration for GitHub Codespaces that would automate the setup of the development environment and provide a consistent and reproducible experience. This would make contributing to the project easier as it would:
- Lower the barrier to entry for new contributors due to the …

Feature: [Dev Experience] Add dev container configuration for GitHub Codespaces

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/Cargo.toml
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/lib.rs

Disclaimer: I _tried_ to push a good commit history; however, git is my greatest enemy. I failed miserably.
The new version looks like this:
Changes:
- Well, I think it satisfies every criterion on the #3999 
- Updated `tabled` version
- Uses `chrono` for parsing the timestamp
I know the question that everyone who sees the screenshot will ask. It's blatant;
**Q: WOW! That font looks so COOL! You must be a really cool person! A retro monospace font with some modern vibes to it?!?!?**
A: I know, I know. I really am cool. Thanks for asking. The font is [Berkeley Mono](https://berkeleygraphics.com/typefaces/berkeley-mono/). No I'm not sponsored
_Hopefully closes #3999_

Improve readability of the `index describe`

---

CONTRIBUTING.md
README.md

Closes #4163
This pull request updates the documentation to reflect the existing support for GitHub Codespaces in Quickwit. The aim is to guide contributors on how to leverage GitHub Codespaces for their development work on Quickwit.
The changes include:
- Updated the `README.md` to make it more clear
- Added a new section in the `CONTRIBUTING.md` file to highlight the support for GitHub Codespaces.
- Included a 'Open in GitHub Codespaces' badge in the `CONTRIBUTING.md` file for easy access.
These updates will help contributors easily understand how to use GitHub Codespaces when contributing to Quickwit, making the process more streamlined and accessible.
Manually testing the added links and badges and ensuring that they work as intended

Documentation Update for GitHub Codespaces Support

---

quickwit/Cargo.lock
quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-common/src/shared_consts.rs
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/control_plane_model.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/models/mod.rs
quickwit/quickwit-indexing/src/models/shard_positions.rs
quickwit/quickwit-indexing/src/source/ingest/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/shards.rs
quickwit/quickwit-metastore/src/metastore/postgresql_metastore.rs
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-proto/src/indexing/mod.rs
quickwit/quickwit-proto/src/types/mod.rs
quickwit/quickwit-proto/src/types/position.rs
quickwit/quickwit-serve/src/lib.rs

Its purpose is to encapsulate all of the logic used to maintained a
distributed eventually consistent view of the published shard positions
over the cluster.
From the user point of view, after instantiation
- indexing pipelines need to feed it with updates. (this happens on
suggest_truncate). This is done by publishing
`LocalShardPositionsUpdates` to the event broker.
- clients interested in updates can just subscript the
`ShardPositionsUpdate` object in the event broker. The event
received can come from a local indexing pipeline or anywhere in the
cluster.
The service takes care of deduping/ignoring updates when necessary.
The two object (Local and not) are very similar, but different in
semantics.
This PR includes the connection with the control plane deleting the shards from the …

Make the ShardPositions model into a ShardPositionsService actor

---

quickwit/quickwit-common/src/binary_heap.rs
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/find_trace_ids_collector.rs
quickwit/quickwit-search/src/leaf.rs

fix #3998 
build a "large" index of spans (~40m spans), set `searcher.max_num_concurrent_split_searches: 1` in quickwit.yaml, and verify most splits don't get searched at all. Query went from ~530ms to ~1.8ms (the newest splits underwent less merges, so they are much faster to search than some of the older splits)

 optimize trace collector

---

quickwit/quickwit-storage/src/cache/byte_range_cache.rs

when a `ByteRangeCache` has to store bytes for the range 0..100_000 and the range 100_000..100_100, it currently merged both range, issuing a memcpy which takes up to a few milliseconds. In practice this is almost never useful, as future get are unlikely to make a request that cross boundaries. This PR removes that merging on range that touch but do not overlap. When fetching from cache, if the cache realize it can only server a query by merging multiple ranges. This impact mostly the warmup of fastfields. On a sample `find_trace_ids` request, done on a single searcher over ~1b spans, it lowered query time from ~5.8s to ~4.1s
added unit test, manually checked there is a performance improvement

avoid unneeded copy on touching but non-overlaping byte ranges

---

quickwit/quickwit-control-plane/src/model/mod.rs
quickwit/quickwit-control-plane/src/model/shard_table.rs
quickwit/quickwit-proto/protos/quickwit/ingest.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.rs

as opposed to only open ones.
Closes shards are not necessarily entirely indexed yet. With this change, after a reload, the closed shards will be scheduling for indexing as usual, and will get cleaned up once they reach eof.
Closes #4176

Populates the control plane model will closed and open shards

---

quickwit/quickwit-actors/src/mailbox.rs
quickwit/quickwit-actors/src/spawn_builder.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs

The bug could surfaced on any actor looping alone, like the control plane.
Closes #4248

Remove race condition in actor framework

---

quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/lib.rs
quickwit/quickwit-ingest/src/semaphore_with_waiter.rs
quickwit/quickwit-proto/src/ingest/mod.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs

The idea is to ensure we have at most one write request waiting in the implicit mrecordlog mutex queue.
In addition, the semaphore limits the number of waiters, so that we can push the burden of retry to the client.

Guarding the router writer path with a semaphore.

---

docs/reference/es_compatible_api.md
quickwit/quickwit-search/src/leaf_cache.rs
quickwit/quickwit-search/src/root.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0008-sort_by.yaml

fix #4077 
I'm not sure what to add more than that line.
somewhat unrelated, document possible improvements to the `partial_request_cache`, that apply particularly to search_after

document search after

---

quickwit/quickwit-search/src/list_fields.rs
quickwit/quickwit-search/src/root.rs
quickwit/rest-api-tests/scenarii/es_field_capabilities/0001-field-capabilities.yaml

align the index pattern matching behaviour to elasticsearch.
That means empty results if the index pattern matches nothing but
contains a wildcard.
Error if any index pattern matches nothing but is exact.
https://github.com/quickwit-oss/quickwit/issues/4298

fix index pattern matching in fieldcaps

---

quickwit/quickwit-ui/src/views/IndexView.test.jsx
quickwit/quickwit-ui/src/views/IndexView.tsx

Use MUI's proposed react-router integration : https://mui.com/material-ui/react-breadcrumbs/#integration-with-react-router
- Checked _steps to reproduce_ in browser.
- Modified unit test to use a `BrowserRouter` context

Fix indexes breadcrum link, fixes #4326

---

quickwit/quickwit-indexing/src/actors/doc_processor.rs

Better logs when doc processing fails.

---

quickwit/quickwit-ui/src/components/QueryActionBar.tsx
quickwit/quickwit-ui/src/components/TimeRangeSelect.tsx

Make the TimeRangeSelect component reusable outside of the search scope by lifting its dependency on `SearchComponentProps`
Passes existing test suite (low bar). Fiddling in browser OK.

Decouple TimeRangeSelect component from search query

---

docs/reference/es_compatible_api.md
quickwit/quickwit-proto/protos/quickwit/search.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-serve/src/elastic_search_api/model/mod.rs
quickwit/quickwit-serve/src/elastic_search_api/model/search_body.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0018-search_after.yaml

The initial goal was to keep search after values in nanoseconds and use ES sort formatting.
But... the sort format is not supported in ES 7. To ease migration from ES/OS users, I set search after values in millis by default and added a sort format specific to quickwit to allow users to use search after values in nanoseconds.

Set search after values in millis by default.

---

quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/serialize.rs

Skip serializing empty shards since the feature is hidden and disabled by default. This way, we can still modify the serialization format without worrying about backward compatibility post `0.7`.

Skip serializing empty shards

---

docs/configuration/index-config.md
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/lib.rs
quickwit/quickwit-integration-tests/Cargo.toml
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/tests/index_tests.rs
quickwit/quickwit-jaeger/src/lib.rs
quickwit/quickwit-metastore/migrations/postgresql/13_migrate-otel-indexes-v0_6.down.sql
quickwit/quickwit-metastore/migrations/postgresql/13_migrate-otel-indexes-v0_6.up.sql
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/serialize.rs
quickwit/quickwit-opentelemetry/Cargo.toml
quickwit/quickwit-opentelemetry/src/otlp/logs.rs
quickwit/quickwit-opentelemetry/src/otlp/mod.rs
quickwit/quickwit-opentelemetry/src/otlp/span_id.rs
quickwit/quickwit-opentelemetry/src/otlp/trace_id.rs
quickwit/quickwit-opentelemetry/src/otlp/traces.rs
quickwit/quickwit-search/src/find_trace_ids_collector.rs
quickwit/quickwit-search/src/tests.rs
quickwit/quickwit-serve/src/jaeger_api/rest_handler.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

Improve otel traces index config, fixes #4218

---

quickwit/quickwit-indexing/src/split_store/indexing_split_store.rs
quickwit/quickwit-indexing/src/split_store/mod.rs

It is unused and triggers the following clippy warning on my machine after I ran `cargo clean`:
```bash
warning: unused import: `WeakIndexingSplitStore`
--> quickwit-indexing/src/split_store/mod.rs:24:52
|
24 | pub use indexing_split_store::{IndexingSplitStore, WeakIndexingSplitStore};
```

Remove `WeakIndexingSplitStore`

---

quickwit/quickwit-serve/src/jaeger_api/rest_handler.rs

Adjust `utoipa` configuration to enable inputs in jaeger swagger api
Launched Quickwit locally with the changes proposed
https://github.com/quickwit-oss/quickwit/issues/4329

fix: adjust utoipa configuration for jaeger swagger api playground

---

quickwit/quickwit-common/src/tower/pool.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/ingest_v2/routing_table.rs
quickwit/quickwit-ingest/src/ingest_v2/workbench.rs
quickwit/quickwit-proto/protos/quickwit/control_plane.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/ingest/mod.rs

Avoid evicting ingester node from IngesterPool when facing or a transport error.
Before when facing such error case, we were removing the faulty nodes from the pool, and
Nn code path would re-add it to the ingester pool. The ingester pool is also used by the ingest
source resulting in bug #4336.
After this patch:
When facing a transport error, we assume the targetted node is
unreachable and chitchat has just not detected this just yet.
In an ideal world we would inform chitchat about this, but it is a bit
difficult to do codewise.
Instead, we register the leader as unavailable for the span of the
workbench. It will then react as if it was out of the pool for
subsequent retries.
A GetOrCreatedShard will carry the information that the node was
unavailable, and the control plane will attempt …

Bugfix #4336: ingester leaving pool

---

quickwit/quickwit-metastore/src/metastore/file_backed_metastore/file_backed_index/serialize.rs

I chose to skip the serialization of empty shards in #4342 so we don't have to be backward compatible for an unreleased feature and introduced a bug in doing so. This PR recreates the empty upon deserialization if necessary.
I tested this change manually in my local environment.

Create empty shards if necessary

---

quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/model/mod.rs
quickwit/quickwit-control-plane/src/model/shard_table.rs
quickwit/quickwit-proto/protos/quickwit/control_plane.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-serve/src/debugging_api.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/openapi.rs
quickwit/quickwit-serve/src/rest.rs

fix #4288
add a `/debugging` endpoint (the name could use better ideas, maybe it should moved in the `/api/v1` namespace too?) which returns the state of the shard table and the indexing plan

add api endpoint to get some control-plan internal info

---

quickwit/Cargo.lock
quickwit/quickwit-ingest/Cargo.toml
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/mrecordlog_utils.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/ingest_v2/workbench.rs

Close shards on IO error. Since now we call `InitShards` on ingesters, I abandoned the idea of decommissioning ingesters on IO error.
Nope...
I tried:
1. Open the log
2. Change permissions of log files to read-only
3. Append records
It does not fail on my MacBook. I suspect the file descriptor is still "writeable".

Close shards on IO error

---

quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/mod.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/scheduling_logic.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/scheduling_logic_model.rs

capacities.
We do that simply by scaling the indexer capacities. First we scale the indexer capacities so that the sum of their capacities exceeds the total load of the source to assign.
If the packing algorithm fails, we inflates the capacities again by 10% and retry.
Closes #4290

Assign all sources/shards, even if this require exceeding the indexer

---

quickwit/quickwit-serve/src/elastic_search_api/filter.rs
quickwit/quickwit-serve/src/elastic_search_api/mod.rs
quickwit/quickwit-serve/src/elastic_search_api/model/field_capability.rs
quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs
quickwit/quickwit-serve/src/search_api/mod.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_field_capabilities/0001-field-capabilities.yaml

add `_elastic/_field_caps` API (`_elastic/{index}/_field_caps` is already supported)
Clear field.indices if it matches global indices
#4298
#3527

add _elastic/_field_caps API

---

quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-control-plane/src/ingest/mod.rs
quickwit/quickwit-control-plane/src/ingest/wait_handle.rs

The test was terminating without the retain shards call to actually happen.
The mockall code was panicking without failing the test due to some tokio::test quirk.
Closes #4391.

Fixing unit test

---

docs/configuration/node-config.md
docs/distributed-tracing/otel-service.md
docs/distributed-tracing/overview.md
docs/distributed-tracing/plug-quickwit-to-jaeger.md
docs/distributed-tracing/send-traces/using-otel-collector.md
docs/log-management/otel-service.md
docs/log-management/overview.md
docs/log-management/send-logs/using-otel-collector-with-helm.md
docs/log-management/send-logs/using-otel-collector.md
docs/log-management/supported-agents.md
docs/operating/upgrades.md

Update docs for 0.7

---

quickwit/quickwit-search/src/root.rs
quickwit/quickwit-serve/src/elastic_search_api/filter.rs
quickwit/quickwit-serve/src/elastic_search_api/mod.rs
quickwit/quickwit-serve/src/elastic_search_api/model/mod.rs
quickwit/quickwit-serve/src/elastic_search_api/model/search_query_params.rs
quickwit/quickwit-serve/src/elastic_search_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0019-count.yaml

add elastic search /{index}/_count API
add count optimization in search request to use metadata if possible

add es _count API

---

quickwit/quickwit-actors/src/actor_context.rs
quickwit/quickwit-actors/src/spawn_builder.rs
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/debouncer.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs
quickwit/quickwit-control-plane/src/lib.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/rest-api-tests/run_tests.py
quickwit/rest-api-tests/scenarii/aggregations/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/multi-indices/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/es_field_capabilities/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/qw_search_api/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/sort_orders/_setup.quickwit.yaml

After this change, the creation of a new plan will happen at most once by window of 5s. Outside of cooldown period, a (relevant) event triggers a RebuildPlan instant.
Related to #4407

Debouncing reschedule.

---

quickwit/quickwit-common/src/io.rs
quickwit/quickwit-config/resources/tests/config/quickwit.json
quickwit/quickwit-config/resources/tests/config/quickwit.toml
quickwit/quickwit-config/resources/tests/config/quickwit.yaml
quickwit/quickwit-config/src/index_config/mod.rs
quickwit/quickwit-config/src/index_config/serialize.rs
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-config/src/node_config/serialize.rs
quickwit/quickwit-indexing/src/actors/index_serializer.rs
quickwit/quickwit-indexing/src/actors/indexer.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs

This PR also removes the index label from the IO metrics. It also removes the limits for the delete pipeline.
Closes #4439

Make io limits for merges a node-level parameter.

---

quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs
quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/mod.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-ingest/src/ingest_v2/state.rs
quickwit/quickwit-storage/src/storage_resolver.rs

Put mrecordlog behind its own lock.
Ran unit tests

Put mrecordlog behind its own lock

---

quickwit/quickwit-search/src/root.rs
quickwit/rest-api-tests/scenarii/aggregations/0001-aggregations.yaml
quickwit/rest-api-tests/scenarii/aggregations/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/aggregations/_teardown.quickwit.yaml

empty indices return empty intermediate aggregation results. To get the
correct result structure we need to call `into_final` instead of early exit.
fixes #4437

fix agg result on empty index

---

quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/list_fields.rs
quickwit/quickwit-search/src/list_terms.rs
quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs
quickwit/quickwit-serve/src/elasticsearch_api/filter.rs
quickwit/quickwit-serve/src/elasticsearch_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/stats.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0020-stats.yaml

add /{index}/_stats API
add /_stats API
closes #3526

add es _stats API

---

quickwit/Cargo.lock
quickwit/quickwit-actors/src/scheduler.rs
quickwit/quickwit-actors/src/spawn_builder.rs
quickwit/quickwit-cli/Cargo.toml
quickwit/quickwit-common/Cargo.toml
quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-serve/src/lib.rs

By default, tokio-console labels its task using its spawning point. Since all actors are spawned from the same place they end up with the same label.
This introduce an API to optionally name tasks.
For actors, the actor's struct Name is used automatically.
If tokio-console is not enabled, this is no cost.

Allow naming tasks to differentiate actors in tokio-console.

---

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/source/file_source.rs

Closes https://github.com/quickwit-oss/quickwit/issues/4455
Added new unit tests.

Fix Gzip file source

---

quickwit/quickwit-serve/src/elasticsearch_api/filter.rs
quickwit/quickwit-serve/src/elasticsearch_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/cat_indices.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0021-cat-indices.yaml

add cat indices API

---

distribution/lambda/Makefile
distribution/lambda/cdk/cli.py
distribution/lambda/cdk/stacks/examples/mock_data_stack.py
docs/guides/e2e-serverless-aws-lambda.md

Currently, when destroying the stacks the buckets cannot be removed before emptying them manually. This PR improves the makefile to perform the bucket clean up automatically
Tested on both HDFS and mock data stack

Automatically empty buckets in Lambda examples

---

quickwit/quickwit-metastore/src/metastore/file_backed/lazy_file_backed_index.rs
quickwit/quickwit-metastore/src/metastore/file_backed/store_operations.rs

While running the REST API test suite, I observed a bunch of errors emitted by the file-backed indexes polling tasks. 
Ran the REST API test suite, and the error logs no longer appear.

Ignore index not found error in file-backed index polling task

---

quickwit/Cargo.toml
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/debouncer.rs
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/tests/index_tests.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
quickwit/quickwit-proto/src/ingest/mod.rs
quickwit/quickwit-proto/src/types/mod.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/openapi.rs
quickwit/rustfmt.toml

Indexer have some mechanic to treat shard not found errors as eof. The ShardNotFound error however was not properly transmitted through gRPC.

Solving the shard not found "error"

---

quickwit/quickwit-cli/src/generate_markdown.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-cli/src/service.rs
quickwit/quickwit-serve/src/build_info.rs

Log current Quickwit version on startup
Launched Quickwit with the change
https://github.com/quickwit-oss/quickwit/issues/4526

chore: log current Quickwit version

---

quickwit/quickwit-cli/src/service.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-serve/src/lib.rs

Per title. Fixes #4536 
- Sent Ctrl+C
- Sent SIGTERM (`kill -TERM <pid>`)

Handle SIGTERM shutdown signal

---

quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-ingest/src/ingest_v2/state.rs
quickwit/quickwit-janitor/src/actors/delete_task_service.rs

- Fixed race condition: the status was set to ready before setting the log to `Some`...
- Added some checks to return proper errors instead of panicking if some traffic hits the ingester while being initialized or or after failing to initialize.

Fix race condition during ingester state initialization

---

quickwit/quickwit-janitor/src/janitor_service.rs
quickwit/quickwit-janitor/src/lib.rs
quickwit/quickwit-serve/src/lib.rs

the delete task service makes numerous request to the metastore on startup (proportional to the number of indexes), but in practice it is often not used at all. This PR adds an environment variable `QW_DISABLE_DELETE_TASK_SERVICE` to disable that service entirely
verified the delete task service isn't started when the env var is present

add env var to disable delete tasks service

---

quickwit/Cargo.lock
quickwit/quickwit-common/Cargo.toml
quickwit/quickwit-common/src/rendezvous_hasher.rs
quickwit/rust-toolchain.toml

Updates Rust to 1.75 (#4367).
**Note:** _missing from this PR is the removal of async_trait as it is not a straightforward removal and the appropriate change for each use (253 instances in the code base) needs to be evaluated on a case by case basis:_
https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html
Dynamic dispatch still requires `async_trait` and public traits require a `trait_variant` macro as outlined in the blog post.
Running `make test-all`

Update rust version to 1.75.0

---

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs

Limit the number of merge pipelines that can be spawned concurrently to reduce the load on the megastore on startup.

Limit the number of merge pipelines that can be spawned concurrently

---

quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0022-source.yaml

support _source_excludes,_source_includes in ES API

---

quickwit/quickwit-query/src/query_ast/bool_query.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/search_query_params.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0023-extra_filters.yaml

add extra_filters to ES API. Useful for permission handling.
Closes #4576

add extra_filters parameter to ES API

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cluster/src/cluster.rs

This guards us from attempting to build ClusterMember / Node when the critical Key Values have not been transmitted yet.

Updated chitchat to include a liveness predicate.

---

quickwit/quickwit-indexing/src/models/shard_positions.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-serve/src/lib.rs

on startup.
Chitchat is started before everything else, so we might be missing some positions if we just start listening for updates.

Initializing the shard positions actor with the existing cluster state

---

quickwit/quickwit-index-management/src/index.rs
quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs
quickwit/quickwit-serve/src/elasticsearch_api/filter.rs
quickwit/quickwit-serve/src/elasticsearch_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/error.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/search_query_params.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0024-delete_indices.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/_teardown.elasticsearch.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/_teardown.quickwit.yaml

add support delete index in es API

---

quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/model/mod.rs
quickwit/quickwit-control-plane/src/model/shard_table.rs

fix #4623
position seemed to already be populated from metastore on restart (as per `/debugging`)
query `/debugging` while ingesting and verify that `.shard_table[].shards[].publish_position_inclusive` changes.
restart control_plane and verify position stays coherent/aren't reset

update shard_table position on ShardPositionsUpdate

---

quickwit/quickwit-cli/src/cli.rs
quickwit/quickwit-cli/src/logger.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-cli/src/service.rs
quickwit/quickwit-cli/tests/helpers.rs
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/log_level_handler.rs
quickwit/quickwit-serve/src/rest.rs

Usage example: just visit.
http://localhost:7280/api/v1/log_level?filter=debug,hyper=debug,tantivy=info,quickwit_serve=debug

Added a handler to dynamically change the log level.

---

quickwit/quickwit-metastore/migrations/postgresql/16_create-index-split-uid.down.sql
quickwit/quickwit-metastore/migrations/postgresql/16_create-index-split-uid.up.sql
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/metastore/postgres/utils.rs

fix part of #4658 (but we'll keep that open to explore other indexes we may want to add)
add an index on `splits(index_uid)`
fix #4666
use `index_uid IN (<list of index>)` instead of `index_uid = "index1" OR index_uid = "index2" OR ...` when querying multiple index.
tested by measuring time and checking query plan on an index with a few hundred thousand splits.
`SELECT * FROM "splits" WHERE "index_uid" = $1` is made ~1900x faster on that particular dataset using the index (from 5.8s to 3.1ms)
selecting with a list of 1k indexes, covering almost every split, is made ~3.5x faster (from 3s to 850ms) by using `IN` over many `OR`. Execution time and query plan are not affected by `IN` over a single `=` when searching with a single index

add postgresql index and use IN instead of many OR

---

quickwit/quickwit-serve/src/elasticsearch_api/model/multi_search.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0025-msearch.yaml

support _source_excludes,_source_includes, extra_filters in _msearch ES API

---

quickwit/quickwit-serve/src/index_api/rest_handler.rs

fix #4680 
tested by creating an invalid source:
```
2024-03-06T10:52:51.454Z  WARN quickwit_serve::index_api::rest_handler: failed to create source: invalid config: failed to parse YAML file: missing field `topic`
```

warn on index/source creation failure

---

quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-config/src/node_config/serialize.rs

On ECS when using CloudMap the tasks register to the service DNS entries as they are started. This check might fail because the other peers haven't registered yet. But the the DNS-based discovery mechanism implemented in Chitchat would have built the cluster successfully.

Remove seed resolution validation

---

Dockerfile
quickwit/quickwit-serve/src/lib.rs
quickwit/rust-toolchain.toml

ARM Docker image build fails consistently, hitting a recursion limit when evaluating `warp` filters:
- https://github.com/quickwit-oss/quickwit/actions/runs/8204806383/job/22440231908
- https://github.com/quickwit-oss/quickwit/actions/runs/8204258038/job/22440352796 (2 attempts)
- Set new recursion limit to 256 (default is 128)
- Upgraded Rust to 1.76
- Stop compiling some workspace crates (`lambda`, `codegen-example`, ...) that are unnecessary for generating the binary
https://github.com/quickwit-oss/quickwit/actions/runs/8206050080/job/22444278462

Fix ARM Docker image build

---

quickwit/quickwit-search/src/collector.rs
quickwit/rest-api-tests/run_tests.py
quickwit/rest-api-tests/scenarii/es_compatibility/0018-search_after.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0020-stats.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0021-cat-indices.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/_teardown.quickwit.yaml

`extract_typed_sort_value_opt` is in the collect hot loop and very performance sensitive. Delay conversion from u64 to actual type to harvest phase.
The impact on the histogram query time seems a little odd, probably related to some inlining. The impact on other sort query times roughly what I'd expect.

delay fast field type conversion to harvest phase

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-cluster/src/grpc_gossip.rs
quickwit/quickwit-cluster/src/grpc_service.rs
quickwit/quickwit-indexing/src/models/shard_positions.rs
quickwit/quickwit-proto/protos/quickwit/cluster.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.cluster.rs
quickwit/quickwit-storage/src/storage_resolver.rs

This PR flattens the shard position.
Before we were publishing positions as
`index_uid:sourceuid: {shardpositions map}`
This PR breaks it into one entry per shard.
Key: `index_uid:source_id:shard`
Value: `position`
It then solves the deletion problem by simply adding a TTL to all of these key values.
Closes #4143

Add a TTL to positions.

---

quickwit/quickwit-ingest/src/ingest_v2/fetch.rs

The statement `has_reached_eof = shard_state.is_closed() && to_position_inclusive >= *replication_position` was broken for shards closed while already drained because the initialization value of `to_position_inclusive` was `Beginning`.
Tested on Cicada, it helps, but there is another issue

Fix fetch task not signaling shard EOF

---

quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-control-plane/src/metrics.rs
quickwit/quickwit-control-plane/src/model/mod.rs
quickwit/quickwit-control-plane/src/model/shard_table.rs

This PR also removes the source id label (as it will always be ingest
v2). This is not much of a win since the overall metric cardinality does
not change.
It also removes `.all_shards_mut()` which was error-prone
as a client could break all kinds of invariants.

Open shards metrics was only updated on scale up/down.

---

quickwit/quickwit-codegen/example/src/codegen/hello.rs
quickwit/quickwit-codegen/example/src/lib.rs
quickwit/quickwit-codegen/src/codegen.rs
quickwit/quickwit-ingest/build.rs
quickwit/quickwit-ingest/src/codegen/ingest_service.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.cluster.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.indexing.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.ingester.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.ingest.router.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-proto/src/error.rs

Display gRPC status code, RPC name, error (Debug), and message.
Before:
```
[ERROR quickwit_proto::error] transport error error=transport error
[ERROR quickwit_proto::error] transport error error=transport error
```
After:
```
[ERROR quickwit_proto::error] gRPC transport error: error trying to connect: tcp connect error: Connection refused (os error 61) code=Unavailable rpc="hello"
[ERROR quickwit_proto::error] gRPC transport error: Timeout expired code=Cancelled rpc="hello"
```
It does seem like adding `error = ?source` just adds some noise since it's already included in the message:
```
[ERROR quickwit_proto::error] gRPC transport error: error trying to connect: tcp connect error: Connection refused (os error 61) code=Unavailable rpc="hello" error=tonic::transport::Error(Transport, …
```

Improve gRPC transport error logging

---

quickwit/quickwit-search/src/collector.rs
quickwit/rest-api-tests/run_tests.py

collect_block + using `first_vals` to batch fetch sort values

collect_block in QuickwitCollector

---

quickwit/quickwit-common/src/metrics.rs
quickwit/quickwit-indexing/src/actors/indexer.rs
quickwit/quickwit-indexing/src/metrics.rs
quickwit/quickwit-indexing/src/models/indexed_split.rs
quickwit/quickwit-ingest/src/ingest_v2/metrics.rs

This moves the WAL allocated memory into the inflight data metrics.

Wal allocated into inflight data

---

docs/get-started/query-language-intro.md
docs/reference/query-language.md

Piggybacking on @trinity-1686a's update proposal for the query language documentation in #4708.
I extracted and formatted a "friendly" version to be included in the _Getting started_ section of the docs and rewrote the refdoc in a more formal way
- Extract an introduction to the query language
- Rewrite the QL reference doc in a more systematic and exhaustive way.

Rewrite Query Language docs

---

docs/configuration/index-config.md
docs/internals/scroll.md
docs/reference/es_compatible_api.md
quickwit/quickwit-search/src/scroll_context.rs
quickwit/quickwit-search/src/service.rs

fix #4717
fix #4718
fix out of memory on crafted scroll_id causing to allocate up to 2**32-1 partial hits (roughly 200GB)

document scroll based on search after and docstore config

---

quickwit/Cargo.lock
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/model/mod.rs
quickwit/quickwit-control-plane/src/tests.rs
quickwit/quickwit-index-management/src/index.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-janitor/src/actors/delete_task_service.rs
quickwit/quickwit-janitor/src/actors/garbage_collector.rs
quickwit/quickwit-janitor/src/actors/retention_policy_executor.rs
quickwit/quickwit-metastore/Cargo.toml
quickwit/quickwit-metastore/src/metastore/file_backed/lazy_file_backed_index.rs
quickwit/quickwit-metastore/src/metastore/file_backed/mod.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/tests/index.rs
quickwit/quickwit-proto/build.rs
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-proto/src/metastore/mod.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs

Compress `ListIndexesMetadataResponse` payload and list shards in batches

---

quickwit/Cargo.lock
quickwit/quickwit-indexing/failpoints/mod.rs
quickwit/quickwit-ingest/Cargo.toml
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/mod.rs
quickwit/quickwit-ingest/src/ingest_v2/mrecordlog_utils.rs
quickwit/quickwit-ingest/src/ingest_v2/replication.md
quickwit/quickwit-ingest/src/ingest_v2/replication.rs
quickwit/quickwit-ingest/src/ingest_v2/state.rs

Handle IO errors in replication tasks

---

quickwit/quickwit-metastore/src/metastore/postgres/migrator.rs

fix #4746 
we get an `implementation of sqlx::Acquire is not general enough` error. To get around that, we use the hidden `run_direct`, which is made specifically to go arround that error. See also https://github.com/launchbadge/sqlx/issues/2016
created 2 dummy migrations, one valid and one invalid. Verify the 1st one doesn't get committed because the 2nd failed.

run migrations in a transaction

---

quickwit/quickwit-datetime/src/date_time_format.rs
quickwit/quickwit-datetime/src/date_time_parsing.rs

Handle missing year in date time parser

---

quickwit/quickwit-ingest/src/ingest_v2/fetch.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs

It is controlled by `QW_INGEST_BATCH_NUM_BYTES`.
The default is unchanged (1MiB), and the value is cached.

Added an environment to control ingest v2 fetch batch len.

---

quickwit/quickwit-config/src/index_config/mod.rs

"a week" does not seem to be a valid config for the retention period

Fix retention_period docs

---

quickwit/quickwit-ingest/src/ingest_v2/replication.rs

Fixes flaky tests on macOS.
Ran `cargo test --manifest-path quickwit/Cargo.toml -p quickwit-ingest --lib -- test_ingester_persist_replicate` multiple times

Increase replication request timeout for unit tests

---

docs/reference/rest-api.md

I couldn't access swagger at `/swagger-ui`. It seems to work at `/ui/api-playground` though.

Fix swagger url

---

docs/configuration/index-config.md
docs/reference/cli.md
docs/reference/rest-api.md
quickwit/quickwit-cli/src/generate_markdown.rs
quickwit/quickwit-cli/src/index/mod.rs
quickwit/quickwit-cli/src/index/update.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-config/src/index_config/mod.rs
quickwit/quickwit-integration-tests/src/tests/index_update_tests.rs
quickwit/quickwit-integration-tests/src/tests/mod.rs
quickwit/quickwit-metastore/src/lib.rs
quickwit/quickwit-metastore/src/metastore/control_plane_metastore.rs
quickwit/quickwit-metastore/src/metastore/file_backed/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed/mod.rs
quickwit/quickwit-metastore/src/metastore/index_metadata/mod.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/tests/index.rs
quickwit/quickwit-metastore/src/tests/mod.rs
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-proto/src/getters.rs
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-serve/src/index_api/mod.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs

Add an index update endpoint. For this first version, only `search_settings` and `retetention_policy` can be configured.
Notes:
- the janitor has a mechanism to [update the index metadata every hour](https://github.com/quickwit-oss/quickwit/blob/24dc8d5eab5b700a362e5e31f3fcd58e8c395ee0/quickwit/quickwit-janitor/src/actors/retention_policy_executor.rs#L175-L188), so the retention policy update will be taken into account at that moment
- `list_indexes_metadata` calls [are not proxied through the control plane](https://github.com/quickwit-oss/quickwit/blob/24dc8d5eab5b700a362e5e31f3fcd58e8c395ee0/quickwit/quickwit-metastore/src/metastore/control_plane_metastore.rs#L126-L131), so [each `root_search` goes directly to the metastore](https://github.com/quickwit-oss/quickwit/blob/24dc8d5eab5b700a3 …

Index configuration update

---

quickwit/quickwit-search/src/root.rs

group_by only groups consecutive elements.
the jobs are currently not grouped by index uid, which e.g. causes
1000 indices with 100 splits to emit 100k leaf requests instead of 1000 leaf requests.
This results in memory and performance issues.
The fix reduced query time from 9s to 1.6s and memory from 4.7GB to
780MB
Addresses #4855

Fix memory consumption/perf bug, group by index id

---

monitoring/grafana/dashboards/indexers.json
monitoring/grafana/dashboards/ingesters.json
monitoring/grafana/dashboards/metastore.json
monitoring/grafana/dashboards/searchers.json

Change Grafana dashboard timezone to browser from utc, users can see dashboard with the local time.

change dashboards 's timezone to null

---

quickwit/quickwit-common/src/metrics.rs
quickwit/quickwit-indexing/src/source/mod.rs

Right now we pollute our metrics with unused sources (like pulsar, kafka etc.).
After this PR, only sources that are actually used will show up.

Making the source in flight component lazy.

---

distribution/ecs/README.md
distribution/ecs/example/terraform.tf
distribution/ecs/quickwit/configs.tf
distribution/ecs/quickwit/iam.tf
distribution/ecs/quickwit/quickwit-control-plane.tf
distribution/ecs/quickwit/quickwit-indexer.tf
distribution/ecs/quickwit/quickwit-janitor.tf
distribution/ecs/quickwit/quickwit-metastore.tf
distribution/ecs/quickwit/quickwit-searcher.tf
distribution/ecs/quickwit/rds.tf
distribution/ecs/quickwit/service/ecs.tf
distribution/ecs/quickwit/service/variables.tf
distribution/ecs/quickwit/variables.tf

Add the possibility to use an external postgres for the metastore.
Also used the opportunity to add:
- extra ECR policies to enable using pul through cache
- configurable storage size
Tested in internal CI

External Postgres metastore for ECS distrib

---

quickwit/quickwit-common/src/tower/one_task_per_call_layer.rs
quickwit/quickwit-ingest/src/mrecordlog_async.rs
quickwit/quickwit-serve/src/grpc.rs
quickwit/quickwit-serve/src/lib.rs

Tested locally. It was very easy to reproduce the bug using a single instance + simian. When killing simian, the task was getting cancelled just like for grpc.
In order to add a debug rpc, I suggested trinity to node add this debug rpc in the service to avoid all of the needless serialization boilerplate, and instead started storing the `Ingester` in QuickwitService (which kind of makes sense in my opinion).
Unfortunately, this lead to this bug. I tried to keep the code dry by keep the list of layers in a method.
We can consider some refactoring later, but this should happen after #4867.

Apply the one task per call layer to the ingester on the local (non-grpc) path as well.

---

docs/reference/rest-api.md

Creating a file source of the API does not make much sense and is in contradiction with the source description which states that the source is used by the CLI only.
On the other hand, there is a tutorial to ingest data from pulsar so it should also be listed in the supported source type list.

Fix possible source types in docs

---

distribution/ecs/README.md
distribution/ecs/example/terraform.tf
distribution/ecs/quickwit/service/config.tf
distribution/ecs/quickwit/service/ecs.tf
distribution/ecs/quickwit/service/variables.tf
distribution/ecs/quickwit/variables.tf

To be able to use AWS services as sources (e.g Kinesis), it is useful to be able to provide custom roles to the indexer task.
To keep the user facing configuration as simple as possible, only indexers can have extra policies (other nodes are not supposed to interact with external AWS services).

Configurable IAM policies for ECS distrib indexers

---

quickwit/quickwit-metastore/migrations/postgresql/18_create-index-shard-index-uid.down.sql
quickwit/quickwit-metastore/migrations/postgresql/18_create-index-shard-index-uid.up.sql

Per title. I noticed that the queries `acquire_shards` and `delete_shards` are quite slow on Airmail.
Ran create/delete index queries against local Postgres db.

Add hash index on Posgtres column `shards.index_uid`

---

docs/ingest-data/kafka.md

It is common to used an externally managed Kafka service. In that case authentication is necessary, and it would be good to show that we support it.
Ran tests using aiven.io and the Quickwit Docker distribution.

Add doc section about secured Kafka

---

quickwit/quickwit-search/src/list_fields.rs
quickwit/quickwit-search/src/list_terms.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/search_job_placer.rs

Same bug as https://github.com/quickwit-oss/quickwit/pull/4880, but on
other code paths. unify code paths.

fix jobs group_by

---

distribution/ecs/README.md
distribution/ecs/example/image.tf
distribution/ecs/example/terraform.tf
distribution/ecs/example/vpc.tf
distribution/ecs/quickwit/service/config.tf
distribution/ecs/quickwit/service/ecs.tf

When pulling directly from Docker Hub, we often run into throttling and the deployment fails silently. Adding the option to use a pull through cache makes it a lot easier to test the ECS distribution.

Add pull through cache to ECS distrib

---

docker-compose.yml
quickwit/Cargo.lock
quickwit/quickwit-common/src/rand.rs
quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/source/file_source.rs
quickwit/quickwit-indexing/src/source/gcp_pubsub_source.rs
quickwit/quickwit-indexing/src/source/ingest/mod.rs
quickwit/quickwit-indexing/src/source/ingest_api_source.rs
quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/source/pulsar_source.rs
quickwit/quickwit-indexing/src/source/source_factory.rs
quickwit/quickwit-indexing/src/source/vec_source.rs
quickwit/quickwit-indexing/src/source/void_source.rs
quickwit/quickwit-indexing/src/test_utils.rs
quickwit/quickwit-proto/src/metastore/mod.rs

Ingest v2 gets its checkpoint from `acquire_shards`, whereas the Kafka source fetches its checkpoint on rebalance.

Load checkpoint lazily in sources

---

quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs

Add the ability to disable ingest v1 for projects such as Airmail or Cicada. This removes several metastore calls (`index _metadata` to spawn the pipeline, `list_splits` to spawn the merge pipeline, etc.).
Compared output for logs with and without en var.

Add ability to disable ingest v1

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit/quickwit-doc-mapper/src/query_builder.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-query/src/query_ast/range_query.rs
quickwit/quickwit-search/src/fetch_docs.rs
quickwit/quickwit-search/src/thread_pool.rs

likely to fix #4940 
useless without upgrading tantivy post https://github.com/quickwit-oss/tantivy/pull/2386

give tantivy a shared thread pool to run fetch doc on

---

quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/tests.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-metastore/src/lib.rs
quickwit/quickwit-metastore/src/metastore/control_plane_metastore.rs
quickwit/quickwit-metastore/src/metastore/file_backed/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/file_backed/file_backed_index/shards.rs
quickwit/quickwit-metastore/src/metastore/file_backed/mod.rs
quickwit/quickwit-metastore/src/metastore/index_metadata/mod.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/metastore/postgres/queries/indexes_metadata.sql
quickwit/quickwit-metastore/src/metastore/postgres/queries/shards/delete.sql
quickwit/quickwit-metastore/src/metastore/postgres/queries/shards/find_not_deletable.sql
quickwit/quickwit-metastore/src/tests/index.rs
quickwit/quickwit-metastore/src/tests/mod.rs
quickwit/quickwit-metastore/src/tests/shard.rs
quickwit/quickwit-proto/build.rs
quickwit/quickwit-proto/protos/quickwit/control_plane.proto
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.control_plane.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-proto/src/getters.rs
quickwit/quickwit-proto/src/metastore/mod.rs
quickwit/quickwit-proto/src/types/index_uid.rs
quickwit/quickwit-proto/src/types/shard_id.rs

Add a batch `indexes_metadata` API to the metastore and use it in the indexing service when spawning new indexing pipelines upon applying a new indexing plan.

Batch `index_metadata` calls in indexing service

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-metastore/src/metastore/file_backed/mod.rs
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/metastore/postgres/model.rs
quickwit/quickwit-metastore/src/metastore/postgres/queries/shards/list.sql
quickwit/quickwit-metastore/src/tests/shard.rs
quickwit/quickwit-proto/Cargo.toml
quickwit/quickwit-proto/src/types/index_uid.rs

Per title.
Updated unit tests.

Issue on query per list shards request instead of one per subrequest

---

.github/workflows/coverage.yml
quickwit/Makefile

fix #4963
increase stack size when running some tests which are particularly bad in that regard.
`make test-all` works again

slightly increase stack size in some tests

---

quickwit/quickwit-indexing/src/source/ingest/mod.rs
quickwit/quickwit-metastore/src/tests/shard.rs
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs

This should remove all warn logging `received an empty publish shard positions update`. We also start logging an info showing highlighting the race condition that was causing this warning log.
Closes #4888

Solving warn `received an empty publish shard positions update`.

---

quickwit/quickwit-cli/src/index/mod.rs
quickwit/quickwit-common/src/tower/rate_estimator.rs
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-serve/src/lib.rs

The CLI was showing the average rate since the CLI was started.
This PR changes it to an estimation over the last 2 seconds.

Fix the ingest rate displayed in the CLI.

---

quickwit/quickwit-cli/src/metrics.rs
quickwit/quickwit-common/src/metrics.rs
quickwit/quickwit-common/src/tower/metrics.rs
quickwit/quickwit-ingest/src/ingest_v2/metrics.rs
quickwit/quickwit-jaeger/src/metrics.rs
quickwit/quickwit-opentelemetry/src/otlp/metrics.rs
quickwit/quickwit-search/src/metrics.rs
quickwit/quickwit-serve/src/metrics.rs
quickwit/quickwit-serve/src/rest.rs

This PR also makes it possible to set specific buckets for histograms.
Cloes #4932

Added latency metrics for REST endpoint.

---

quickwit/quickwit-cluster/src/lib.rs

Cicada.
This PR lowers it to 2h.
For reminder, starting the detection of the node as dead, the node gets into a zombie state for 1h.
We do share its KVs.
From timeofdeath+1h to timeofdeath+2h, we won't share the node.
After 2h, we will delete the node from the state.
(We still do not really understand why the dead node number would keep increasing)

The super large grace period of 1 day has proved to be harmful on

---

.cargo/config.toml
.github/workflows/cbench.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
Dockerfile
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-cli/src/split.rs
quickwit/quickwit-cluster/src/metrics.rs
quickwit/quickwit-common/Cargo.toml
quickwit/quickwit-common/src/metrics.rs
quickwit/quickwit-common/src/runtimes.rs
quickwit/quickwit-common/src/thread_pool.rs
quickwit/quickwit-control-plane/src/metrics.rs
quickwit/quickwit-ingest/src/metrics.rs
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/error.rs
quickwit/quickwit-search/src/metrics.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/otlp_api/rest_handler.rs
quickwit/quickwit-storage/src/metrics.rs

@fulmicoton, @trinity-1686a, which metrics interest you: [`tokio-metrics`](https://crates.io/crates/tokio-metrics)?

Add Tokio runtimes metrics

---

quickwit/.cargo/config.toml
quickwit/quickwit-common/src/runtimes.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs

As spotted by @PSeitz, the unstealable lifo-slot is causing the
doc processor and the indexer to run on the same thread.
For the moment this is disabled by default and only apply to the
indexer blocking runtime.
lifo slot disabled
```
➜  quickwit-dynajson cat ~/data/gharchive.json | ./quickwit index ingest --index gharchive4
❯ Ingesting documents from stdin.
⠏ [00:01:56] 1.43 GiB/1.43 GiB (5.7 MiB/s)                                     Ingested ✔ documents successfully.
➜  quickwit-dynajson
➜  quickwit-dynajson ./quickwit index create --index-config ./index.yaml
```
with lifo slot
```
➜  quickwit-dynajson cat ~/data/gharchive.json | ./quickwit index ingest --index gharchive4
❯ Ingesting documents from stdin.
⠇ [00:00:23] 459.65 MiB/459.65 MiB (17.1 MiB/s)
⠋ [00:00:23] 459.65 MiB/459.65 …
```

Using a runtime with no lifo slot.

---

quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/find_trace_ids_collector.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/rest-api-tests/scenarii/aggregations/0001-aggregations.yaml

fix #4926
remove extended bounds from histogram aggregations at the leaf_search_single_split level.
This should make it possible for the partial request cache to hit on dashboards using that feature, such as grafana.
cc @PSeitz 
added integration test to verify the behavior doesn't change
added unit test to verify we rewrite the bounds at both top and leaf level
manually tested a few (manually wrote) aggregation and verify cache metrics record hits when expected.

rewrite agg extended bounds

---

quickwit/quickwit-actors/src/actor_context.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/search_query_params.rs
quickwit/quickwit-serve/src/format.rs

Bump Rust version and fix a few new clippy warnings.

Bump Rust to 1.78

---

quickwit/quickwit-serve/src/rest.rs

through the power of reordering error handlers, fix #4995
our rate-limited error is there, but we just handle some other errors before, so it seems like we don't get the error we expect
tested with `QW_INGEST_MAX_IN_FLIGHT=0` to always get the error

reorder error handlers

---

docs/configuration/node-config.md
quickwit/quickwit-storage/src/split_cache/split_table.rs

Improve the search split cache UX by:
- being strict on the number of split in the cache instead of letting it exceed the configured limit by one
- making the docs a bit more explicit

Improve search split cache docs

---

quickwit/quickwit-control-plane/src/control_plane.rs

Metastore errors that are not necessarily aborted require us to restart the CP actor to keep it in sync.
Closes #5014

Fix consistency between CP/metastore on auto-create index.

---

distribution/ecs/quickwit/outputs.tf

It is more consistent to expose all QW services as terraform outputs in the ECS distribution. It can also be usefull for testing the overall cluster readiness.
Internal CI

Add all services to ECS output

---

quickwit/Cargo.lock
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/root.rs

* optimization requests by passing threshold in leaf search
* Execute query.count() instead of QuickwitCollector for count searches
We have 100 concurrent split searches by default, but num_cpus worker
threads. This means most search futures will wait to be
scheduled. When they are scheduled they can check the new threshold from
the preceding searches and maybe skip the search.
Switches from Mutex to RWLock for the threshold since we read more often now.
Addresses https://github.com/quickwit-oss/quickwit/issues/5032
Local SSD:
https://qw-benchmarks.104.155.161.122.nip.io/?run_ids=1707,1708&search_metric=engine_duration
CI on S3:
https://qw-benchmarks.104.155.161.122.nip.io/?run_ids=1694,1710&search_metric=engine_duration
We run num_cpu full searches in some cases before the threshold …

count optimization for multisplits

---

docs/configuration/node-config.md

It seems from the code that the split store quota on the indexer side is global. This is also what is suggested in the docs [here](https://github.com/quickwit-oss/quickwit/blob/8ee25c972013e1f5f3acbb2c2cef23036cd5a6e9/docs/operating/data-directory.md#L51). 
NA

Fix indexing split store config docs

---

distribution/lambda/Makefile
distribution/lambda/cdk/cli.py
quickwit/quickwit-lambda/src/indexer/ingest/helpers.rs
quickwit/quickwit-lambda/src/indexer/ingest/mod.rs

Closes https://github.com/quickwit-oss/quickwit/issues/4381
Adds a workaround to a build issue introduced in https://github.com/quickwit-oss/quickwit/pull/4771 and caused by https://github.com/cargo-lambda/cargo-lambda/issues/649
Fixes source creation regression identified in https://github.com/quickwit-oss/quickwit/pull/4985#issuecomment-2116062230
Tested on an adhoc deployment and in internal CI

Various Lambda fixes

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-serve/src/rest.rs

It was caused by the output compression.
Closes #5049

Solving indexing regression

---

distribution/lambda/cdk/cli.py
quickwit/quickwit-lambda/src/searcher/api.rs
quickwit/quickwit-serve/src/index_api/mod.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs

Closes #5039.
Add `GET /api/v1/indexes` endpoint to Lambda Searcher to use quickwit Lambda as Grafana datasource.
1. Locally running Lambda searcher by using cargo lambda.
```
export AWS_ACCESS_KEY_ID="****"
export AWS_SECRET_ACCESS_KEY="****"
export AWS_SESSION_TOKEN="****"
export AWS_REGION="us-east-1"
export AWS_LAMBDA_HTTP_IGNORE_STAGE_IN_PATH="true"
export QW_LAMBDA_INDEX_BUCKET="quickwitlambdastack-quickwitindexstore****"
export QW_LAMBDA_INDEX_ID="hdfs-logs"
export QW_LAMBDA_METASTORE_BUCKET="quickwitlambdastack-quickwitindexstore****"
export RUST_LOG="quickwit=info"
cargo lambda watch
```
2. Setup Grafana (https://quickwit.io/docs/get-started/tutorials/trace-analytics-with-grafana)
- url: `http://host.docker.internal:9000/lambda-url/searcher/api/v1`
- Index ID: `hdfs-logs`
3. …

Add GET api/v1/indexes to Lambda searcher

---

quickwit/quickwit-ingest/src/queue.rs

I needed to look at the code to work out that I had bad permissions on `qwdata`.
Before,
````
thread 'main' panicked at /projects/quickwit/quickwit/quickwit-ingest/src/queue.rs:44:58:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
````
After,
```
✘ command failed: failed to start ingest v1 service
Caused by:
0: failed to open the ingest API record log located at `/noperm/qwdata/queues`
1: io error failed to create WAL directory `/noperm/qwdata/queues`: Permission denied (os error 13)
```

Show queues_dir_path on failed create

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/Cargo.toml
quickwit/quickwit-serve/Cargo.toml
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/pprof.rs
quickwit/quickwit-serve/src/rest.rs

This adds two routes to control pprof
Enable CPU profiling (100hz)
http://localhost:7280/pprof/start
Get the profile as flamegraph
http://localhost:7280/pprof/flamegraph
The routes are behind the `pprof` feature flag
`cargo install --locked --path . --features pprof`

enable pprof cpu profiling

---

quickwit/Cargo.lock
quickwit/quickwit-config/Cargo.toml
quickwit/quickwit-config/src/index_config/mod.rs
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper_builder.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/doc_mapper.rs
quickwit/quickwit-doc-mapper/src/doc_mapping.rs
quickwit/quickwit-doc-mapper/src/lib.rs
quickwit/quickwit-metastore/test-data/file-backed-index/v0.6.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.7.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.8.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.8.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.4.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.5.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.6.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.7.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.8.expected.json
quickwit/quickwit-metastore/test-data/index-metadata/v0.8.json
quickwit/quickwit-metastore/test-data/manifest/v0.7.expected.json
quickwit/quickwit-metastore/test-data/manifest/v0.8.expected.json
quickwit/quickwit-metastore/test-data/manifest/v0.8.json
quickwit/rest-api-tests/scenarii/aggregations/_setup.quickwit.yaml

Refactoring the `DefaultDocMapperBuilder` because I attempted to add a field to `DocMapping`, and the experience was frustrating, mostly because of the duplicated fields in the two structs.

Clean up `DefaultDocMapperBuilder`

---

distribution/ecs/README.md
distribution/ecs/example/terraform.tf
distribution/ecs/quickwit/configs.tf
distribution/ecs/quickwit/iam.tf
distribution/ecs/quickwit/quickwit-control-plane.tf
distribution/ecs/quickwit/quickwit-indexer.tf
distribution/ecs/quickwit/quickwit-janitor.tf
distribution/ecs/quickwit/quickwit-metastore.tf
distribution/ecs/quickwit/quickwit-searcher.tf
distribution/ecs/quickwit/service/ecs.tf
distribution/ecs/quickwit/service/variables.tf
distribution/ecs/quickwit/variables.tf

Currently, when using an external Postgres as metastore backend, we only support SSM. This small change leverages the fact that ECS supports both SSM and Secret Manager to inject secrets as environment variables.
Internal CI

Support secret manager for the URI

---

docs/configuration/index-config.md

There is a broken table in [the docs](https://quickwit.io/docs/configuration/index-config#search-settings):
I removed the linebreak in the description row.
Didn't test because couldn't find out how you build the docs 🙁, but the markdown looks ok now:

Remove newline in a table cell (`index-config.md`)

---

quickwit/Cargo.lock
quickwit/quickwit-cli/src/logger.rs
quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-common/src/runtimes.rs
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-config/src/storage_config.rs
quickwit/quickwit-lambda/src/environment.rs
quickwit/quickwit-lambda/src/indexer/environment.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-telemetry/Cargo.toml
quickwit/quickwit-telemetry/src/sender.rs

When the Airmail team modifies boolean environment variables, I don't know whether they actually remove them or update the values, so I'd be more comfortable shipping that PR before the next Airmail releases.

Take bool env var values into account instead of presence

---

distribution/lambda/README.md

add instructions to set up Grafana for Quickwit Searcher Lambda.
related PR: https://github.com/quickwit-oss/quickwit/pull/5069#issuecomment-2147449057
N/A

Add Grafana data source configuration instruction for Quickwit Searcher Lambda

---

quickwit/quickwit-proto/build.rs
quickwit/quickwit-proto/src/codegen/opentelemetry/opentelemetry.proto.collector.logs.v1.rs
quickwit/quickwit-serve/src/cluster_api/rest_handler.rs
quickwit/quickwit-serve/src/delete_task_api/handler.rs
quickwit/quickwit-serve/src/developer_api/log_level.rs
quickwit/quickwit-serve/src/developer_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs
quickwit/quickwit-serve/src/elasticsearch_api/filter.rs
quickwit/quickwit-serve/src/elasticsearch_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/quickwit-serve/src/health_check_api/handler.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/indexing_api/rest_handler.rs
quickwit/quickwit-serve/src/jaeger_api/rest_handler.rs
quickwit/quickwit-serve/src/node_info_handler.rs
quickwit/quickwit-serve/src/openapi.rs
quickwit/quickwit-serve/src/otlp_api/mod.rs
quickwit/quickwit-serve/src/otlp_api/rest_handler.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-serve/src/template_api/rest_handler.rs
quickwit/quickwit-serve/src/ui_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0020-stats.yaml

If a route matches, we want to run its handler, and upon failure, the last thing we want is for another overlapping route to be executed as a fallback.
To avoid this, we call recover on each individual routes that have no overlap with routes of lesser priority.

Adds recover_fn to many routes.

---

quickwit/quickwit-query/src/elastic_query_dsl/match_bool_prefix.rs
quickwit/quickwit-query/src/elastic_query_dsl/match_phrase_query.rs
quickwit/quickwit-query/src/elastic_query_dsl/multi_match.rs
quickwit/quickwit-query/src/elastic_query_dsl/range_query.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/search_body.rs

* [_source][1] schema
* [docvalue][2] schema
* [multi_match][3] schema
I've added additional fields as `serde_json::Value` to prevent complex struct definitions as we won't use them anyway.
Addressing https://github.com/quickwit-oss/quickwit/issues/5097
[1]: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-fields.html#source-filtering
[2]: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#docvalue-fields
[3]: https://opensearch.org/docs/latest/query-dsl/full-text/multi-match/#multi-match-query-types
I've tested it locally using queries taken from [OSD](https://gist.github.com/kuzaxak/a7579679c13f1d3e3019f4444e3d109b)
Additionally I've added some tests for multi_match parser code.

Add missing fields to ES compatible Query API

---

quickwit/quickwit-cli/src/main.rs

The new default value is num_cores / 3.
This value can be overridden using the QW_RUNTIME_NUM_THREADS environment variable.
Closes #5123

Changing the default number of threads for the main tokio runtime.

---

quickwit/quickwit-serve/src/developer_api/pprof.rs

Before this PR, fetch the flamegraph was stopping the profiling even if the duration was not elapsed yet.
After this PR, the flamegraph is only generated after the duration is elapsed (still defaulting to 30s).

Stop flamegraph only when the target duration is elapsed.

---

CONTRIBUTING.md
quickwit/Makefile

We use nextest in the CI to stabilize tests. This PR changes the Makefile to also use nextest.

Use nextest in Makefile

---

quickwit/quickwit-doc-mapper/src/default_doc_mapper/date_time_type.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/default_doc_mapper/mapping_tree.rs
quickwit/quickwit-doc-mapper/src/doc_mapper.rs
quickwit/quickwit-ingest/src/ingest_v2/doc_mapper.rs
quickwit/quickwit-search/src/collector.rs

This PR just removes the need to build documents when validating
documents.

Faster document validation

---

quickwit/quickwit-ingest/src/ingest_v2/ingester.rs

Check WAL capacity and apply rate limiting before validating docs.

Apply rate limiting before validating docs

---

quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/root.rs

due to the 1st case of what's described in https://github.com/quickwit-oss/quickwit/issues/3650 , it can happen that we return up to `start_offset + 2 * max_hits` documents instead of `max_hits`. This happens when a split first fails, and then succeed, but its result is just concatenated instead of doing a proper top-k.
The fix consist in dropping the tail hits at the same time as the hits that should be omitted due to start_offset are removed.
tested with a modified s3 that errors on a fraction of requests. Without the patch, i often get too many results (and sometime a double error so no response), with the patch, i either get the right number of docs, or said error.

remove hits beyond max requested hit

---

quickwit/quickwit-ui/src/services/client.test.ts
quickwit/quickwit-ui/src/services/client.ts

Fixes #5186
There was an unnecessary / in the URL.
Additionally, some browsers still successfully made the call.

Fix: Remove  / when calling search endpoint

---

docs/log-management/send-logs/using-vector.md

Without this change, Quickwit returns:
```
WARN quickwit_indexing::actors::doc_processor: doc mapper parse error: the document contains a field that is not declared in the schema: "service" index_id="otel-logs-v0_7" source_id="_ingest-api-source"
```
Integrating into the NixOS integration tests: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/vector/syslog-quickwit.nix

docs: Vector fixes

---

quickwit/quickwit-control-plane/src/model/shard_table.rs

Reverting the change in the shard opening rate limits.

---

quickwit/quickwit-common/src/tower/rate.rs
quickwit/quickwit-ingest/Cargo.toml
quickwit/quickwit-ingest/src/ingest_v2/rate_meter.rs

The point is to be able to remove the needless private function, and test public functions.

Minor refactoring in the rate limiter.

---

docs/reference/aggregation.md
quickwit/rest-api-tests/scenarii/aggregations/0001-aggregations.yaml

add test and docs for cardinality and extended_stats aggregation

---

quickwit/quickwit-common/src/pretty.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs

shorten apply-plan log

---

quickwit/quickwit-proto/protos/quickwit/search.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/search_response_rest.rs
quickwit/quickwit-search/src/service.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-serve/src/search_api/grpc_adapter.rs
quickwit/quickwit-serve/src/search_api/mod.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs

fix #5190
add api endpoint to get the quickwit and tantivy ast for a query, as well as what splits would be hit (taking into account time range and tags), and how many/what kind of storage request are to be expected for each split
tested manually plus added basic unit test

add api endpoint to get query ast

---

quickwit/quickwit-query/src/elastic_query_dsl/range_query.rs

Introduce the support for `format` parameter in `RangeQuery`
```sh
curl -X GET "http://localhost:7280/api/v1/_elastic/stackoverflow-schemaless/_search?pretty" -H 'Content-Type: application/json' -d'
{
"query": {
"range": {
"age": {
"gte": "2023-01-01",
"lte": "2023-12-31",
"boost": 2.0,
"format": "%Y-%m-%d"
}
}
}
}
```
https://github.com/quickwit-oss/quickwit/issues/5109

feat(es): respect format parameter in range query

---

quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs
quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-control-plane/src/ingest/mod.rs
quickwit/quickwit-control-plane/src/ingest/scaling_arbiter.rs
quickwit/quickwit-control-plane/src/model/shard_table.rs
quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs

throughput.
Scaling up relies on the short term average in order to rapidly react to a change in throughput, while scaling down and the indexing scheduler relies on the long term average.

Emitting both a short term average and a long term average of shard

---

quickwit/quickwit-ingest/src/ingest_api_service.rs
quickwit/quickwit-ingest/src/ingest_v2/doc_mapper.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/metrics.rs

Removing invalid docs from persistence.
This PR filters out invalid docs from batches before persisting the
batch.
That way, they won't be persisted in the mrecordlog and the
indexing pipeline will not have to parse them again (and log an error).
This PR also improves a little bit on the metric for ingested docs.
The num_docs and bytes metric now have a validity `label`, and the
point at which they are measured is documented in the metric description.
Closes #5205

Removing invalid docs from persistence.

---

quickwit/quickwit-common/src/shared_consts.rs
quickwit/quickwit-janitor/src/actors/garbage_collector.rs
quickwit/quickwit-search/src/root.rs

... with the environment variable QW_SPLIT_DELETION_GRACE_PERIOD_SECS.
The default is sensible for most case, but for project airmail, we need to be able to recover from a metastore backup that could be several hours old.

Make the split deletion grace period configurable.

---

quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-control-plane/src/model/shard_table.rs
quickwit/quickwit-proto/src/ingest/mod.rs

We have noticed after running for a long time, in airmail the distribution of shard count amongst ingester seems uniform, but one or two indexers are getting most of the throughput.
This could be caused by an indirect bias in the allocation of shard to
ingester. For instance, in airmail, most indexes are very small, but a
few of them are much larger. Small indexes have 1 shard with a very low
throughput. Large indexes on the other hands have several shards with
typically >2MB of throughut.
Larger indexes are also more subject to scale up/down, since other
indexes tend to stick to having 1 shard (we don't scale down to 0).
This PR tries to remove any possible bias when assigning / removing
shards in
- scale up
- scale down
- rebalance.
Scale up
---------------------------
This is the most …

Pick ingester at random when adding shards.

---

quickwit/quickwit-indexing/src/actors/indexer.rs
quickwit/quickwit-indexing/src/actors/merge_executor.rs
quickwit/quickwit-indexing/src/actors/merge_planner.rs
quickwit/quickwit-indexing/src/actors/packager.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-indexing/src/merge_policy/mod.rs
quickwit/quickwit-indexing/src/models/indexed_split.rs
quickwit/quickwit-indexing/src/models/split_attrs.rs
quickwit/quickwit-metastore/src/split_metadata.rs
quickwit/quickwit-metastore/src/split_metadata_version.rs
quickwit/quickwit-metastore/test-data/file-backed-index/v0.7.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.8.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.9.expected.json
quickwit/quickwit-metastore/test-data/file-backed-index/v0.9.json
quickwit/quickwit-metastore/test-data/split-metadata/v0.7.expected.json
quickwit/quickwit-metastore/test-data/split-metadata/v0.8.expected.json
quickwit/quickwit-metastore/test-data/split-metadata/v0.9.expected.json
quickwit/quickwit-metastore/test-data/split-metadata/v0.9.json

progress on #5084 
supersedes #4928 
added unit test

prevent merging splits with different doc mapping

---

quickwit/quickwit-ingest/src/ingest_v2/fetch.rs

Fix endless loop by temporarily increasing the buffer size.
Alternative would be to reject the message, but I'm not sure this should be done
here.
Based on proposed solution of @Stool233
Fixes #5240

fix endless loop in ingest_v2

---

distribution/kubernetes/README.md

Fix Helm documentation link from distribution/kubernetes README.
N/A

docs(dist/k8s): fix link to helm doc

---

docs/ingest-data/kafka.md

It is not clear from the docs where the certificate files must be mounted.
NA

Improve the Kafka authentication docs

---

quickwit/quickwit-search/src/leaf.rs

Recording failed splits even if task panicked.
Avoiding to use `join_all` on a Vec of task's JoinHandle.

Minor refactoring in leaf search.

---

quickwit/rest-api-tests/scenarii/aggregations/0001-aggregations.yaml
quickwit/rest-api-tests/scenarii/aggregations/0002-doc-len.yaml
quickwit/rest-api-tests/scenarii/aggregations/_setup.quickwit.yaml

Add a test to make sure large u64 are serialized correctly without truncation
closes https://github.com/quickwit-oss/quickwit/issues/5254

add test for term agg number serialization

---

quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs

only emit `FOR UPDATE` statements where they might be useful

use FOR UPDATE only when needed

---

Makefile
quickwit/Makefile
quickwit/quickwit-lambda/Cargo.toml
quickwit/quickwit-lambda/src/indexer/environment.rs
quickwit/quickwit-lambda/src/indexer/handler.rs
quickwit/quickwit-lambda/src/indexer/ingest/helpers.rs
quickwit/quickwit-lambda/src/indexer/ingest/mod.rs
quickwit/quickwit-lambda/src/indexer/model.rs
quickwit/quickwit-lambda/src/searcher/environment.rs

Bug introduced by https://github.com/quickwit-oss/quickwit/pull/5148
Also removed the overwrite option which was hardcoded and buggy anyway.
Added an end 2 end integration test exposed in the Makefile. Note that the test is currently failing until https://github.com/quickwit-oss/quickwit/pull/5330 is also merged.

Fix source path in Lambda distrib

---

quickwit/quickwit-cli/tests/cli.rs
quickwit/quickwit-indexing/src/source/doc_file_reader.rs

When ingesting a file that was already indexed using the file source, the indexing should be a successful noop. We currently get an error.

Fix file re-ingestion after EOF

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-doc-mapper/src/default_doc_mapper/default_mapper.rs
quickwit/rest-api-tests/scenarii/default_search_fields/0002_invalid_default_fields.yaml

fix using concatenate field as default search field
added unit test

support concatenated field as default search field

---

quickwit/quickwit-doc-mapper/src/query_builder.rs

fix a bug where `field:"short"* field:"not short"*` would succeed, but `field:"not short"* field:"short"*` would fail to load position, and return an error
tested manually, added unit test for the faulty code

fix warming-up position incorrectly when 2 phrase prefix query are issued for the same final term

---

quickwit/quickwit-query/src/query_ast/tantivy_query_ast.rs

this is akin to https://github.com/quickwit-oss/tantivy/pull/2449 (which runs optimization inside the query parser), but for ast not built through the query parser. Inspired by queries seen on airmail
added unit test to verify the optimizations are run, added prop-test to verify the optimizations never change the result of a query (which happened to be the case before)

lift clauses

---

quickwit/quickwit-integration-tests/src/tests/update_tests/doc_mapping_tests.rs

two test had the same index-id, which is my best guess as to why CI is currently red on main

rename index-id to hopefully fix coverage

---

quickwit/quickwit-index-management/src/index.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-janitor/src/actors/delete_task_planner.rs
quickwit/quickwit-metastore/src/metastore/file_backed/mod.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/tests/list_splits.rs
quickwit/quickwit-metastore/src/tests/split.rs

Reduce delete index concurrency to 5 and deserialize splits outside the Tokio runtime.

Reduce delete index concurrency to 5

---

quickwit/Cargo.lock
quickwit/quickwit-metastore/Cargo.toml
quickwit/quickwit-metastore/src/tests/mod.rs

Postgres tests tend to fail in coverage CI runs.

Fix flaky postgres tests

---

quickwit/quickwit-aws/src/lib.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs

may fix #5294
configure `StalledStreamProtectionConfig`. For some reason, when unconfigured, the default grace period is 5s, but when configured, the default is 20s.
If this doesn't fix #5294, we can do
```rs
StalledStreamProtectionConfig::enabled()
.upload_enabled(false)
.build()
``` 
to restore pre march behaviour. I believe it would be best to keep this enabled if possible, as it allows earlier detection of dead connections.
verified from aws debug logs that it picks the correct timeout

configure stalled stream protection

---

quickwit/quickwit-ingest/src/error.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/ingest_v2/workbench.rs
quickwit/quickwit-integration-tests/src/tests/ingest_tests.rs
quickwit/quickwit-serve/src/elasticsearch_api/bulk_v2.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs

Closes https://github.com/quickwit-oss/quickwit/issues/5351

Fix wait_for commit on ingest V2

---

quickwit/quickwit-jaeger/src/lib.rs

fix #5367
before, querying `trace-v0_7` would fail. Now both `trace-v0_7` and `trace-v0_9` works (though the improvement in #5358 is only available for v0_9)
tested on grafana ui

improve trace search backward compatibility

---

quickwit/quickwit-indexing/src/source/queue_sources/coordinator.rs
quickwit/quickwit-indexing/src/source/queue_sources/shared_state.rs
quickwit/quickwit-indexing/src/source/queue_sources/visibility.rs

Currently, shards are always reaquired when they re-appear in the SQS queue. We can limit this process to shards that are obviously stale based on their update timestamp.

Reacquire SQS shards only if they are stale

---

quickwit/quickwit-jaeger/src/lib.rs

fix a bug with jaeger search api returning all root span instead of matching ones.
The query was modified to be `Must(is_root) Should(TraceId1) Should(TraceId2)...`, which sounds like it limits more than just Shoulds would, but actually it means the Should only count for scoring (which we are not doing). What we ought to do is `Must(is_root) Must(Should(TraceId1) Should(TraceId2)...)` (must be root, and must match one of the trace id)

fix jaeger http endpoint

---

quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage_resolver.rs

memoize s3 client, keeping them until they seem unused. I don't think we ever use more than a single S3StorageConfig, so we could store a single value, but a map we gc seems less confusing if we start having multiple config at once
fix #4933 
fix #5236
ran a cluster and looked at searcher logs. Didn't look at janitor logs, though there is no reason for it to behave differently

memoize s3 client

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-aws/Cargo.toml
quickwit/quickwit-aws/src/error.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs

mark some S3 errors as retry-able. The code in qw-storage already uses `aws_retry()` on write requests. The actual error we get from GCS is `SlowDown`, but aws sdk contains a list of errors, so we that instead of hard-coding a single value;
improvement for #5211
added unit test to Storage::put for retry.

make some s3 error retryable

---

install.sh

when installing on amazonlinux via `install.quickwit.io`, i got the following error:
```
tar (child): gzip: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
we don't invoke gzip directly, but tar needs it to open a tar.gz.
For some reason `bc` is reported as missing, but the installation still continue and succeed

add gzip to commands needed for install

---

quickwit/quickwit-opentelemetry/Cargo.toml
quickwit/quickwit-opentelemetry/src/otlp/logs.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0021-cat-indices.yaml

Closes https://github.com/quickwit-oss/quickwit/issues/5311

Change default timestamps in OTEL logs

---

quickwit/quickwit-indexing/src/source/gcp_pubsub_source.rs
quickwit/quickwit-indexing/src/source/ingest/mod.rs
quickwit/quickwit-indexing/src/source/kafka_source.rs
quickwit/quickwit-indexing/src/source/kinesis/kinesis_source.rs
quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/source/pulsar_source.rs

Integration tests were sometimes failing because actor heartbeat is smaller in integ tests.
Running the OTLP integ tests in a loop never fails anymore.

Fix actor timeout in ingest integration tests

---

quickwit/quickwit-index-management/src/garbage_collection.rs

fix flakiness in `test_garbage_collect_fails_to_run_delete_on_one_index` introduced in #5380 
the test depends of the order in which we iterate over the map. Fixed by finishing the iteration before aborting the gc run

fix flaky test

---

quickwit/quickwit-index-management/src/garbage_collection.rs

make `delete_splits_marked_for_deletion` shorter. Before it used to show only a single index id, but with gc batching, it can now show thousands at once when that function returns an error.

shorten delete_splits_marked_for_deletion log

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-config/src/templating.rs
quickwit/quickwit-lambda/Cargo.toml
quickwit/quickwit-lambda/src/indexer/environment.rs
quickwit/quickwit-lambda/src/indexer/ingest/mod.rs
quickwit/quickwit-lambda/src/searcher/environment.rs
quickwit/quickwit-metastore/Cargo.toml

The regex for env variable interpolation in configs doesn't capture properly multiple variables in the same line.
Closes https://github.com/quickwit-oss/quickwit/pull/5403
Unit test + tests in the lambda package

Fix configuration interpolation

---

quickwit/quickwit-config/src/storage_config.rs
quickwit/quickwit-proto/protos/quickwit/search.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs
quickwit/quickwit-search/src/root.rs

log actual index_id patterns that are queried on leaf nodes
reduce log spam

improve logging

---

quickwit/quickwit-index-management/src/garbage_collection.rs
quickwit/quickwit-metastore/src/metastore/file_backed/file_backed_index/mod.rs
quickwit/quickwit-metastore/src/metastore/mod.rs
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/metastore/postgres/model.rs
quickwit/quickwit-metastore/src/metastore/postgres/utils.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/list_terms.rs

follow up to #5380
if a cluster generate less than 1k split per 10 minutes, everything was fine, but in case it would generate more than that, we have a slow down for 2 reasons:
- we no longer run 10 tasks in parallel
- we may get a batch of 1k splits from many different indexes, and get a 2nd batch from the same set of indexes, meaning more than one delete per index, despite having few splits to delete for each indexes. This can in theory cause us to do up to n_index time more delete calls to the metastore than necessary (caped to 1k)
Changes made:
- we run up to 10 deletion from storage + metastore concurrently
- we retrieve splits sorted by index_uid from metastore, so we don't do many delete per index
- we query for 10k splits instead of 1k: before we would query for 10 * 1k, but as …

batch delete from gc

---

docs/internals/ingest-v2.md
docs/overview/concepts/querying.md
docs/reference/rest-api.md
quickwit/quickwit-indexing/src/test_utils.rs
quickwit/quickwit-search/src/tests.rs

Kind of like the balrog that was awaken by the dwarfes mining mithril, this test was re-activated in CI by https://github.com/quickwit-oss/quickwit/pull/5392.
The default sort order was inverted in https://github.com/quickwit-oss/quickwit/pull/3726/files and this dormant test was not updated accordingly.
Test now passes.

Fix ancient test that recently re-surfaced

---

quickwit/quickwit-metastore/migrations/postgresql/22-change-splits-pkey.down.sql
quickwit/quickwit-metastore/migrations/postgresql/22-change-splits-pkey.up.sql
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/metastore/postgres/utils.rs

fix #5415
change the pkey of `splits`, remove hack to sort `splits` using an index from `indexes`
verified query plan was as expected after migration. Ran pgsql tests

change pkey on splits

---

.github/actions/cargo-build-macos-binary/action.yml
.github/actions/cross-build-binary/action.yml
.github/workflows/publish_docker_images.yml

Looks like the bump from actions/download-artifact 3 to 4 broke the docker CI (https://github.com/quickwit-oss/quickwit/actions/workflows/publish_docker_images.yml). This is an expected breaking change (https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes))

Upgrade actions/upload-artifact to match actions/download-artifact

---

quickwit/quickwit-serve/src/elasticsearch_api/bulk_v2.rs
quickwit/rest-api-tests/README.md
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/0006-partial-index-not-found.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_setup.elasticsearch.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/_teardown.elasticsearch.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_ctx.elasticsearch.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_ctx.quickwit.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_ctx.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_setup.elasticsearch.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/index_not_found/_teardown.elasticsearch.yaml

The bulk API should have its responses in the same order as the submitted actions (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-api-response-body)

Fix bulk api response order

---

quickwit/quickwit-cli/src/service.rs

With ingest V2, we wait for all data to be ingested before shutting down. For users trying out Quickwit in their terminal, this means that the process hangs when pressing Ctrl+C. This PR adds a listning task for a second Ctrl+C to forcefully shutdown quickwit.
Running Quickwit in a Bash terminal.

Enable force shutdown with 2nd Ctrl+C

---

quickwit/quickwit-metastore/migrations/postgresql/23_change-indexes-unique-index.down.sql
quickwit/quickwit-metastore/migrations/postgresql/23_change-indexes-unique-index.up.sql

The sql that is generated to expand an index name (index_id) into all of the matching index names uses the LIKE clause to do partial text matches. However, the only index on the index_id column utilizes the default btree configuration which can only do exact value comparisons. In environments with a large search volume over many thousands of indexes, this can be a bottle neck as the query will always do an full table scan. This drops and recreates the unique index on index_id to include the `varchar_pattern_ops` which allows for wildcard matching on a varchar column using the LIKE operator
Fixes: #5437
* Quickwit release binary built
* Docker docker compose started
* started quickwit metastore `quickwit run --service metastore
* Verify the unique index of the same name created with the …

fix(metastore): add index to support index name wildcard expansion

---

docs/configuration/source-config.md
quickwit/Cargo.lock
quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-indexing/src/source/file_source.rs
quickwit/quickwit-indexing/src/source/queue_sources/coordinator.rs
quickwit/quickwit-indexing/src/source/queue_sources/design.md
quickwit/quickwit-indexing/src/source/queue_sources/local_state.rs
quickwit/quickwit-indexing/src/source/queue_sources/shared_state.rs
quickwit/quickwit-indexing/src/source/queue_sources/visibility.rs
quickwit/quickwit-integration-tests/src/tests/sqs_tests.rs
quickwit/quickwit-metastore/src/metastore/file_backed/file_backed_index/shards.rs
quickwit/quickwit-metastore/src/metastore/postgres/metastore.rs
quickwit/quickwit-metastore/src/tests/shard.rs
quickwit/quickwit-proto/protos/quickwit/metastore.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.metastore.rs
quickwit/quickwit-rest-client/Cargo.toml
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs

Trigger the prune_shards endpoint from the SQS file sources.
Added integration test.

Garbage collect shards in SQS Filesource

---

quickwit/quickwit-integration-tests/resources/tests/documents_to_ingest.json
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/test_utils/mod.rs
quickwit/quickwit-integration-tests/src/tests/basic_tests.rs
quickwit/quickwit-integration-tests/src/tests/ingest_tests.rs
quickwit/quickwit-integration-tests/src/tests/otlp_tests.rs
quickwit/quickwit-integration-tests/src/tests/update_tests/search_settings_tests.rs

Uncomment some tests and remove some outdated workarounds in the integration tests:
- ingest retries do not seem to be required anymore
- isolated the failing test when ingesting data on a re-created index (and annotate it with #[ignore])
- grouped all the ingest tests into a single module (`ingest_tests`)
- better wording and small helper improvements

Cleanup integration tests

---

quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/root.rs

Added some basic num docs/splits stats on root/leaf search spans.

Enrich root/leaf search spans with number of docs and splits

---

docs/reference/es_compatible_api.md
quickwit/quickwit-cli/src/tool.rs
quickwit/quickwit-proto/protos/quickwit/search.proto
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs
quickwit/quickwit-search/src/cluster_client.rs
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/error.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/leaf_cache.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/scroll_context.rs
quickwit/quickwit-search/src/service.rs
quickwit/quickwit-search/src/tests.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/search_query_params.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/quickwit-serve/src/jaeger_api/rest_handler.rs
quickwit/quickwit-serve/src/search_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0012-scroll-api.yaml

```
Allowing failed splits in root search.
This PR adds a query string parameter (`allow_partial_search_results`) in
the elasticsearch api controlling encounterring an error on a subset
of the splits, should fail a search query or if a response
(reflecting the partial set of successful splits) should be returned.
It changes the behavior of the root search gRPC call, that will not return
an error in presence of partial split errors, but instead returns the list of splits that failed.
This PR also changes the default behavior of the elasticsearch rest API: following elasticsearch behavior on failing shards, quickwit will allow split errors.
The Quickwit API default behavior, on the other hand, is unchanged.
Closes #5411
```
(I also tested the option by removing splits on a running quickwit …

Allowing failed splits in root search.

---

monitoring/grafana/dashboards/searchers.json

without the datasource set to prometheus, it just returns an error:
```
Templating [instance]
Error updating options: JSON.parse: unexpected character at line 1 column 2 of the JSON data
```
Update: This happens if prometheus is not the default datasource

Fix grafana searchers dashboard

---

quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/metrics.rs
quickwit/quickwit-search/src/root.rs

Add number of splits per root/leaf search histograms

---

quickwit/quickwit-config/resources/tests/node_config/quickwit.json
quickwit/quickwit-config/resources/tests/node_config/quickwit.toml
quickwit/quickwit-config/resources/tests/node_config/quickwit.yaml
quickwit/quickwit-config/src/lib.rs
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-config/src/node_config/serialize.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-storage/src/lib.rs
quickwit/quickwit-storage/src/metrics.rs
quickwit/quickwit-storage/src/timeout_and_retry_storage.rs

This is done at a storage instead of the s3 client as the s3 client only had a global operation timeout parameter.
Here the timeout is proportional to the length (in byte) of the slice being downloaded.
By default, if the searcher config does not define a timeout explicitly, this PR is no-op.
Closes #5466

Introduce a searcher config option to timeout get requests.

---

quickwit/Cargo.lock
quickwit/Cargo.toml

For safety reason, for the moment, we point to an outdated version of pulsar-rs version with the same major version as what we were using
for the moment.

Stop relying on our own version of pulsar-rs

---

.github/workflows/ci.yml
quickwit/quickwit-opentelemetry/Cargo.toml
quickwit/quickwit-opentelemetry/src/otlp/mod.rs

Attributes are not supposed to carry nested values, but bodies can. Since we use the same function to convert OTLP values to JSON values, we should handle them in `oltp_value_to_json_value`. Closes #5458.
Updated unit tests.

Handle nested OTLP values in attributes and log bodies

---

quickwit/quickwit-serve/src/otlp_api/rest_handler.rs

allow specifying index in otel http protobuf api

---

docs/reference/es_compatible_api.md
quickwit/quickwit-query/src/elastic_query_dsl/bool_query.rs
quickwit/quickwit-query/src/query_ast/bool_query.rs
quickwit/quickwit-query/src/query_ast/mod.rs
quickwit/quickwit-query/src/query_ast/range_query.rs
quickwit/quickwit-query/src/query_ast/tantivy_query_ast.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0005-query_string_query.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0007-range_queries.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0009-bool_query.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0014-multi-match-query.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/0020-stats.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/_setup.elasticsearch.yaml
quickwit/rest-api-tests/scenarii/es_compatibility/_setup.quickwit.yaml

Adding support for minimum_should_match
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html
Fixing rest compatilibility tests.
Closes #4828

4829 minimum should match

---

quickwit/quickwit-serve/src/otlp_api/rest_handler.rs

allow providing index id through header instead of path params in otel http-grpc api
fix #5413
follow up to #5421

allow specifying otel index id in header

---

quickwit/quickwit-aws/src/error.rs

retry on S3 InternalError, it's most likely transient, despite not being marked as it in the sdk

retry on S3 internal error

---

quickwit/Cargo.lock
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/list_terms.rs
quickwit/quickwit-search/src/metrics.rs
quickwit/quickwit-search/src/search_permit_provider.rs
quickwit/quickwit-search/src/search_permits.rs
quickwit/quickwit-search/src/service.rs

Before this PR, we just used a semaphore to acquire a permit and start a new tokio task to run our single split search.
In pseudo code, a leaf_search would look like:
```
for split in splits {
let permit = semaphore.acquire().await;
tokio::spawn(async move {
single_split_search(split);
drop(permit)
})
}
```
The problem with this is that it allows interleaving split search from one search request with another one.
This interleaving strongly impacts search latency. For instance, one can imagine two queries A and B with 3 splits each. Executing as follows
| A | A | A | B | B | B |
offers a much short latency for A than
| A | B | B | A | B | A |
This PR also adds two metrics to monitor the number of queue single split search.

Prevents single split searches from different leaf_search from interleaving

---

quickwit/quickwit-serve/src/jaeger_api/model.rs
quickwit/quickwit-serve/src/jaeger_api/parse_duration.rs
quickwit/quickwit-serve/src/jaeger_api/rest_handler.rs

fix https://github.com/quickwit-oss/quickwit/issues/5511
completed unit tests

fix unit conversion in jaeger http search endpoint

---

quickwit/quickwit-search/src/search_job_placer.rs

Per title. Fixes #5507.
Ran `quickwit-search` unit tests.

Improve search job placer logging

---

quickwit/quickwit-doc-mapper/src/doc_mapper/doc_mapper_impl.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/field_presence.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/mapping_tree.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/tantivy_val_to_json.rs

move tantivy val to json to own module
remove duplicated conversion logic
move field_presence to own module

refactor doc mapper

---

quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-proto/src/codegen/jaeger/jaeger.api_v2.rs
quickwit/quickwit-proto/src/codegen/quickwit/quickwit.search.rs

remove duplicated code

---

quickwit/quickwit-codegen/example/src/lib.rs
quickwit/quickwit-serve/src/cluster_api/rest_handler.rs
quickwit/quickwit-serve/src/delete_task_api/handler.rs
quickwit/quickwit-serve/src/developer_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs
quickwit/quickwit-serve/src/elasticsearch_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs
quickwit/quickwit-serve/src/indexing_api/rest_handler.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/jaeger_api/rest_handler.rs
quickwit/quickwit-serve/src/node_info_handler.rs
quickwit/quickwit-serve/src/otlp_api/rest_handler.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-serve/src/template_api/rest_handler.rs
quickwit/quickwit-serve/src/ui_handler.rs
quickwit/rust-toolchain.toml

box warp routes to avoid super heavy types.
Performance impact should be okay, since these heavy types
are not cache friendly.
This reduces type complexity significantly, but some really long type chains remain.
I've identified two, but they may be more
1. Boxed or chains
2. Response type chains
We can replace the boxed or chains with a Vec, since they all contain the same
box type now. Such a type doesn't seem to exist in warp yet.
`cargo install --path .`
Compile time before
4m49s
Compile time now
4m14s
Tool to list heavy functions:
`
CARGO_PROFILE_RELEASE_LTO=fat cargo llvm-lines --release --bin quickwit > llvm_lines
`
Size down from 32MB to 22MB
update rust tool chain to 1.81 to fix compilation error (https://github.com/servo/rust-url/issues/992)
addresses #5539

box warp routes

---

quickwit/quickwit-indexing/src/actors/indexing_pipeline.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs
quickwit/quickwit-indexing/src/actors/uploader.rs
quickwit/quickwit-indexing/src/merge_policy/mod.rs
quickwit/quickwit-indexing/src/models/split_attrs.rs
quickwit/quickwit-janitor/src/actors/delete_task_pipeline.rs
quickwit/quickwit-metastore/src/split_metadata.rs

reduce time before maturity of a split based on time to end of retention
reduce likelihood of encountering #5431 . It can technically still happen if a split is subject to merge at time t, its merge start, and then subject deletion at time t+1 while the merge is still running, but that should be a much rarer occurrence. 
added unit test for new code

restrict maturity period to retention

---

.github/actions/cross-build-binary/action.yml
quickwit/Cross.toml

Current nightly builds are failing on ARM because of the transitive dep krb5-sys (imported by rdkafka SASL)
The issue started after https://github.com/quickwit-oss/quickwit/pull/5486 which upgraded the krb5-sys, in which https://github.com/MaterializeInc/rust-krb5-src/pull/27 somehow broke the cross build instead of fixing it.

Fix krb5 transitive dependency cross build

---

quickwit/quickwit-storage/src/object_storage/azure_blob_storage.rs

Fixes https://github.com/quickwit-oss/quickwit/issues/5552

Update azure multipart policy

---

quickwit/quickwit-serve/src/elasticsearch_api/bulk_v2.rs

Closes https://github.com/quickwit-oss/quickwit/issues/5565
N/A

Return 429 on ES API when no shards available

---

docs/reference/es_compatible_api.md
quickwit/quickwit-doc-mapper/src/query_builder.rs
quickwit/quickwit-integration-tests/src/tests/update_tests/mod.rs
quickwit/quickwit-query/src/elastic_query_dsl/match_query.rs
quickwit/quickwit-query/src/elastic_query_dsl/mod.rs
quickwit/quickwit-query/src/elastic_query_dsl/multi_match.rs
quickwit/quickwit-query/src/elastic_query_dsl/phrase_prefix_query.rs
quickwit/quickwit-query/src/elastic_query_dsl/query_string_query.rs
quickwit/quickwit-query/src/query_ast/full_text_query.rs
quickwit/quickwit-query/src/query_ast/phrase_prefix_query.rs
quickwit/quickwit-query/src/query_ast/user_input_query.rs
quickwit/quickwit-query/src/query_ast/wildcard_query.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0005-query_string_query.yaml

The `lenient` argument on the ES compat search API does not work properly when using a wildcard query.
Integ tests

Fix lenient option with wildcard queries

---

quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-common/src/rendezvous_hasher.rs
quickwit/quickwit-common/src/socket_addr_legacy_hash.rs
quickwit/quickwit-search/src/cluster_client.rs
quickwit/quickwit-search/src/search_job_placer.rs

Ensures the affinity function is the same as in Quickwit 0.8

---

quickwit/quickwit-jaeger/src/lib.rs

Right now, our quickwit span -> jaeger trace code doesn't support objects or null values and instead completely errors out which means that any trace where there is at least one span with an object with it does not work with Jaeger. I resolved this by adding support for Object and Null variants, encoding object keys delimited with `.`.
```
2024-12-07T11:42:07.655Z ERROR quickwit_serve::jaeger_api::rest_handler: failed to fetch traces error=Status { code: Internal, message: "Failed to serialize attributes: unexpected type `Object {}`", source: None }
```
https://github.com/quickwit-oss/quickwit/blob/53293792066aa7e5a0951d0be04fee94fc93cf0c/quickwit/quickwit-jaeger/src/lib.rs#L989
I opted to use iterools::Either because it was already available and avoids heap allocation except in the …

make jaeger span attribute-to-tag conversion exhaustive

---

quickwit/quickwit-datetime/src/java_date_time_format.rs

There is a `YearRepr::LastTwo` representation in the time crate, but the parser is unreliable, so let's only support `YearRepr::Full` for now. See also https://github.com/time-rs/time/issues/649.
`c t -p quickwit-datetime`

Remove support for 2-digit years in java datetime parser

---

quickwit/quickwit-config/src/node_config/serialize.rs

`unresolvable-host` resolves to `unresolvable-host` in some environments.
`c t -p quickwit-config`

Use `unresolvable.wikipedia.org` in `test_peer_socket_addrs`

---

quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs
quickwit/quickwit-serve/src/elasticsearch_api/filter.rs
quickwit/quickwit-serve/src/elasticsearch_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0027-cluster-health.yaml

implement `_elastic/_cluster/health` endpoint without support for any of its query parameters. 
I reused `cluster.is_self_node_ready()` to determine the health check.

partially implement _elastic/_cluster/health

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-common/src/path_hasher.rs
quickwit/quickwit-doc-mapper/Cargo.toml
quickwit/quickwit-doc-mapper/src/doc_mapper/doc_mapper_impl.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/field_presence.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/lib.rs
quickwit/quickwit-doc-mapper/src/query_builder.rs
quickwit/quickwit-query/Cargo.toml
quickwit/quickwit-query/src/query_ast/field_presence.rs
quickwit/quickwit-query/src/query_ast/full_text_query.rs
quickwit/quickwit-query/src/query_ast/phrase_prefix_query.rs
quickwit/quickwit-query/src/query_ast/range_query.rs
quickwit/quickwit-query/src/query_ast/utils.rs
quickwit/quickwit-query/src/query_ast/wildcard_query.rs
quickwit/quickwit-search/src/collector.rs
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/search_stream/leaf.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0011-exists-query.yaml
quickwit/rest-api-tests/scenarii/qw_search_api/0004_exists_search.yaml
quickwit/rest-api-tests/scenarii/qw_search_api/_setup.quickwit.yaml
quickwit/rest-api-tests/scenarii/qw_search_api/_teardown.quickwit.yaml

Closes https://github.com/quickwit-oss/quickwit/issues/5560

Fix existence queries for nested fields

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-doc-mapper/src/doc_mapper/mod.rs
quickwit/quickwit-doc-mapper/src/lib.rs
quickwit/quickwit-doc-mapper/src/query_builder.rs
quickwit/quickwit-doc-mapper/src/tag_pruning.rs
quickwit/quickwit-query/Cargo.toml
quickwit/quickwit-query/src/elastic_query_dsl/mod.rs
quickwit/quickwit-query/src/elastic_query_dsl/regex_query.rs
quickwit/quickwit-query/src/query_ast/field_presence.rs
quickwit/quickwit-query/src/query_ast/mod.rs
quickwit/quickwit-query/src/query_ast/regex_query.rs
quickwit/quickwit-query/src/query_ast/visitor.rs
quickwit/quickwit-query/src/query_ast/wildcard_query.rs
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/leaf.rs
quickwit/rest-api-tests/scenarii/es_compatibility/0005-query_string_query.yaml

fix #5306 #5061
add support for arbitrary wildcard through running them as automatons
also add support for regexes
added some tests, and tested manually

support arbitrary wildcard

---

docs/deployment/cluster-sizing.md
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/split_store/indexing_split_cache.rs
quickwit/quickwit-indexing/src/split_store/indexing_split_store.rs
quickwit/quickwit-indexing/src/split_store/mod.rs
quickwit/quickwit-indexing/src/split_store/split_store_quota.rs

Closes https://github.com/quickwit-oss/quickwit/issues/5591
Rework of https://github.com/quickwit-oss/quickwit/pull/4275

Some sanity rewrite of the LocalSplitStore

---

docs/internals/ingest-v2.md
docs/reference/cli.md
docs/reference/rest-api.md
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-ingest/src/error.rs
quickwit/quickwit-ingest/src/lib.rs
quickwit/quickwit-integration-tests/src/test_utils/cluster_sandbox.rs
quickwit/quickwit-integration-tests/src/tests/ingest_v2_tests.rs
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-serve/src/elasticsearch_api/bulk.rs
quickwit/quickwit-serve/src/ingest_api/mod.rs
quickwit/quickwit-serve/src/ingest_api/response.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/quickwit-serve/src/lib.rs

Currently ingest v2 only reports docs that couldn't be parsed correctly in metrics. This is even worse than ingest v1 that was just generating logs.
Unit and integration tests.

Detailed ingest response

---

quickwit/quickwit-config/src/index_config/serialize.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/mod.rs

Changed config to match https://github.com/quickwit-oss/quickwit/blob/e7dc8de8b6fd0e49fb3a32119ca2fa1fd88ba3aa/docs/configuration/index-config.md#L492-L504
Closes https://github.com/quickwit-oss/quickwit/issues/5571
Added unit test in index config

Fix default dynamic mapping config

---

quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-ingest/src/ingest_v2/routing_table.rs
quickwit/quickwit-ingest/src/ingest_v2/workbench.rs
quickwit/quickwit-proto/src/ingest/mod.rs

Return 429 instead of 503 when all the shards of an index are rate limited

---

quickwit/quickwit-ingest/src/ingest_v2/broadcast.rs
quickwit/quickwit-search/src/client.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/service.rs

The `root_search_requests_total` metric is not emitted because the search client is bypassed when searchers are hit directly, which most users do.
I moved the `leaf_search_requests_total` to `SearchServiceImpl` for the metric to appear consistently server-side.
Ran locally and checked metric in Grafana

Fix `root_search_requests_total` metric

---

quickwit/Cargo.toml

Effectively disabling the computation of a checksum for request bodies and preventing the following error:
```
storage error(kind=Internal, source=dispatch failure: other: RequestChecksumInterceptor modify_before_retry_loop interceptor encountered an error: error during request construction: Only request bodies with a known size can be checksum validated
```
This is a temporary fix. See #5649.

Pin `aws-sdk-s3` dep to 1.62

---

LICENSE-3rdparty.csv
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/Cargo.toml
quickwit/quickwit-cli/src/logger.rs
quickwit/quickwit-lambda/Cargo.toml
quickwit/quickwit-lambda/src/logger.rs

Update `opentelemetry*` and `tracing*` crates so we can attempt to use `opentelemetry-datadog` internally.
Tested locally. Enabled OTLP exporter, sent traces to OTEL collector, and then visualized traces in Jaeger.

Update `opentelemetry*` and `tracing*` crates

---

quickwit/Cargo.lock
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-rest-client/src/models.rs
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/search_response_rest.rs
quickwit/quickwit-serve/src/elasticsearch_api/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/mod.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/multi_search.rs
quickwit/quickwit-serve/src/elasticsearch_api/model/search_response.rs
quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs

Profiling showed that parsing the json serialized aggregation string returned by the root searcher into a `serde_json::Value` can take 5x time the memory size of the returned payload. On a loaded system, this can represent a lot of memory that is consumed even if results are served from cache.
By using `serde_json_borrowed::OwnedValue`, we can reduce this tp 3x the size of the returned payload.
Heaptrack profiling.

Reduce aggregation result footprint

---

quickwit/Cargo.toml
quickwit/quickwit-cli/src/logger.rs

Per title.
Ran locally and inspected logs manually

Output logs in JSON with `QW_LOG_FORMAT=json`

---

quickwit/quickwit-config/src/index_config/serialize.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/field_mapping_entry.rs
quickwit/quickwit-doc-mapper/src/doc_mapper/mod.rs

Revert https://github.com/quickwit-oss/quickwit/pull/5653 to avoid regressions.
We will then still need to fix the fact that CI didn't catch this (https://github.com/quickwit-oss/quickwit/issues/5681) and the fact that the docs are not aligned with the behavior (https://github.com/quickwit-oss/quickwit/issues/5682)
Note: if we decide to update the docs, don't forget to also update the tutorial https://github.com/quickwit-oss/quickwit/issues/5571

Revert "Fix default dynamic mapping config (#5653)"

---

docs/configuration/template-config.md
docs/reference/es_compatible_api.md
docs/reference/rest-api.md
quickwit/quickwit-config/src/index_template/serialize.rs
quickwit/quickwit-serve/src/template_api/rest_handler.rs

Closes https://github.com/quickwit-oss/quickwit/issues/4480
Navigating the swagger UI

Add template docs

---

docs/configuration/node-config.md

Document cooperative indexing

---

quickwit/quickwit-serve/src/delete_task_api/handler.rs

This seems to have been broken in https://github.com/quickwit-oss/quickwit/pull/3148
According to the docs, delete tasks should support default fields https://github.com/quickwit-oss/quickwit/blob/722cb877a611972f29167b11191aa0f6acb9c213/docs/reference/rest-api.md#L759
Unit tests.

Fix delete task not respecting default fields

---

.github/workflows/ci.yml
.github/workflows/ui-ci.yml

rustup no longer install toolchains on it's own based on `rust-toolchain.toml`, update ci to reflect that
see also https://blog.rust-lang.org/2025/03/02/Rustup-1.28.0.html

fix ci after rustup breaking change

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-common/Cargo.toml
quickwit/quickwit-common/src/fs.rs
quickwit/quickwit-config/src/node_config/serialize.rs

Helps with https://github.com/quickwit-oss/quickwit/issues/5589

Warn on startup when data dir is too small

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-indexing/src/actors/merge_executor.rs

Closes https://github.com/quickwit-oss/quickwit/issues/5687
The hotfix was already tested in real conditions.

Fix panic when merging long str columns

---

quickwit/quickwit-common/src/shared_consts.rs
quickwit/quickwit-config/src/cluster_config/mod.rs
quickwit/quickwit-config/src/node_config/mod.rs
quickwit/quickwit-control-plane/src/control_plane.rs
quickwit/quickwit-control-plane/src/ingest/ingest_controller.rs
quickwit/quickwit-control-plane/src/ingest/scaling_arbiter.rs
quickwit/quickwit-control-plane/src/model/shard_table.rs
quickwit/quickwit-serve/src/lib.rs

Indexers return a lot of 429 when ingest rates fluctuate, even if the overall indexing capacity (~5MB/core) is note reached. This PR makes some small parameter adjustments to decrease the overall error rates on typical workloads. It will be the topic for another issue/PR to introduce the structual changes that are necessary to improve the routing strategy.
- Customizable shard burst limit with default increased to 50MB: helps absorbing the load until the next scale up
- Shard scaling factor: helps keeping up with load fluctuations on workloads with high number of shards (e.g having +20MB/s on an index where the average ingest rate is 100MB/s is more likely than +20MB/s on an index where the average rate is 1MB/s)
Related to https://github.com/quickwit-oss/quickwit/issues/5270
Adhoc python …

Faster shard scaling

---

quickwit/quickwit-codegen/example/src/error.rs
quickwit/quickwit-codegen/example/src/lib.rs
quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-proto/src/metastore/mod.rs
quickwit/quickwit-serve/src/lib.rs

On Airmail, a large Quickwit deployment, we observe that loosing the metastore connectivity, even temporarily, triggers indexer pods restarts. The IndexingService not responding to liveness check because the actor is hanging on metastore requests.
Adding a timeout to metastore requests:
- creates more explicit error messages in cases where the IndexingService does fail because of metastore timeouts
- gives the indexer a chance to recover thanks to the metastore client retries
Unit test on the example GRPC stack.

Add timeout to metastore GRPC client

---

quickwit/quickwit-storage/src/local_file_storage.rs
quickwit/quickwit-storage/src/metrics.rs
quickwit/quickwit-storage/src/object_storage/azure_blob_storage.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs
quickwit/quickwit-storage/src/opendal_storage/base.rs

This PR adds 2 new metrics to track how many get_slice requests are being executed and how much data has been allocated for them. This memory is currently not tracked in anywhere, and it might take up significant space if downloading many large object slices in parallel.

Add in flight get slice metric

---

LICENSE-3rdparty.csv
Makefile
quickwit/Cargo.lock
quickwit/Cargo.toml

See https://github.com/quickwit-oss/chitchat/pull/155
Closes https://github.com/quickwit-oss/quickwit/issues/5135 
Closes https://github.com/quickwit-oss/quickwit/issues/5446

Fix chitchat dead node cleanup

---

quickwit/quickwit-serve/src/elasticsearch_api/rest_handler.rs

`buffer_unordered` will collect records in the order in which they complete. But we need to return data in the same order as user requested otherwise user can't match response with requests.
Fixes issue: https://github.com/quickwit-oss/quickwit/issues/5731
Manually using Grafana plugin

Fix order mismatch in elastic compatible `msearch` api

---

docs/reference/rest-api.md
docs/reference/updating-mapper.md
quickwit/quickwit-integration-tests/src/tests/update_tests/doc_mapping_tests.rs

Document https://github.com/quickwit-oss/quickwit/issues/5738
Add ignored integ test.

Document doc mapping update bug

---

quickwit/quickwit-serve/src/elasticsearch_api/bulk_v2.rs
quickwit/quickwit-serve/src/ingest_api/rest_handler.rs
quickwit/rest-api-tests/scenarii/es_compatibility/bulk/0007-illegal-index-name.yaml

When using index templates, specifying and index name that matches the pattern but has illegal characters results in a 429 response code instead of a 400.
Description of the problem:
- the index_id validity is not validated until the metastore is called
- calling `GetOrCreateOpenShards` with an invalid index_id on the metastore fails with MetastoreError::JsonDeserializeError
- a failure to call the metastore is logged but not repported to the ingest workbench
- because the router is not populated, the workbench fails with "shard not found errors" for the failing index but also other targetted indexes batched with it
The index id is now validated in `quickwit-serve`, before calling the ingest router (ES bulk and native APIs)
Added unit and integration (python) tests

Invalid index_id with ingest v2 returns 429 

---

quickwit/quickwit-common/Cargo.toml

When running 
```sh
cargo bench --package quickwit-actors --bench bench
```
, noticed that the `make_channel` method in the `quickwit-common` crate not work.  
It needs `#[cfg(feature = "tls")]` for `tonic::transport::ClientTlsConfig`.
cargo bench

Add tonic tls feature

---

docs/reference/es_compatible_api.md
quickwit/quickwit-search/src/cluster_client.rs
quickwit/quickwit-search/src/metrics.rs
quickwit/quickwit-search/src/scroll_context.rs
quickwit/quickwit-search/src/service.rs

The search after cache might get pretty big on a system with many scroll / search after queries. This PR adds a way to track its size.
This is part of the global effort to understand memory consumption on searchers.
Would add a test if we could merge https://github.com/quickwit-oss/quickwit/pull/5718 first.

Add total size bytes gauge for search after cache

---

docs/reference/rest-api.md
quickwit/quickwit-common/src/uri.rs
quickwit/quickwit-config/src/index_config/serialize.rs
quickwit/quickwit-serve/src/index_api/index_resource.rs
quickwit/quickwit-serve/src/index_api/rest_handler.rs

Users can set the the index_uri to be the root of a bucket, and this panics when calling the index update endpoint. This PR:
- replaces the panic with an Internal Server error
- makes it possible to update an index even if the index_uri is the root of a bucket

Fix index update endpoint panic when index_uri is the bucket root

---

quickwit/Cargo.lock
quickwit/quickwit-indexing/Cargo.toml
quickwit/quickwit-indexing/src/source/queue_sources/message.rs

When a file includes `:`, it gets converted to `%3A`, and doing `GetObject` fails.

URL decode s3 key in s3:ObjectCreated

---

quickwit/quickwit-indexing/src/actors/indexing_service.rs
quickwit/quickwit-indexing/src/actors/merge_pipeline.rs

increase timeout to make test not flaky (or way less, i wasn't able to make it fail again, but it's possible it would still do, just less often)
looped `cargo nextest` for a while

increase sleep time to make test not/less flaky

---

LICENSE-3rdparty.csv
quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cli/src/index.rs
quickwit/quickwit-cli/src/lib.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-rest-client/Cargo.toml
quickwit/quickwit-rest-client/src/error.rs
quickwit/quickwit-rest-client/src/rest_client.rs
quickwit/quickwit-storage/src/opendal_storage/base.rs
quickwit/quickwit-storage/src/opendal_storage/google_cloud_storage.rs

- Add `--retries` parameter to CLI commands
- Update OpenDAL
I got pulled into updating OpenDAL in order to use `reqwest-middleware` and `reqwest-retry`.
- Ran command locally with 10 retries against server that was not up yet. When I finally launched the server, the command succeeded

Add `--retries` parameter to CLI commands

---

quickwit/quickwit-indexing/failpoints/mod.rs
quickwit/quickwit-integration-tests/src/tests/tls_tests.rs

`test_merge_executor_controlled_directory_kill_switch` is failing since [this change](https://github.com/quickwit-oss/quickwit/pull/5704/files#diff-3e039cd511306f2cec6416a24e964d09696c0cb6d07092ec4683936c940ffd8cR118)

Fix coverage tests

---

quickwit/Cargo.lock
quickwit/quickwit-search/Cargo.toml
quickwit/quickwit-search/src/leaf.rs
quickwit/quickwit-search/src/lib.rs
quickwit/quickwit-search/src/list_fields.rs
quickwit/quickwit-search/src/list_terms.rs
quickwit/quickwit-search/src/metrics_trackers.rs
quickwit/quickwit-search/src/root.rs
quickwit/quickwit-search/src/service.rs
quickwit/quickwit-search/src/tests.rs

This PRs moves `[root|leaf]_search_requests_total` `[root|leaf]_search_request_duration_seconds` `[root|leaf]_search_targeted_splits` into tasks so that they are recorded even on future cancelation. This will help having a more accurate view on queries that timeout.

Record search metrics on cancelation

---

docs/reference/updating-mapper.md
quickwit/quickwit-common/src/lib.rs

Description:  
This pull request corrects minor typographical errors in the documentation and code comments. Specifically, it changes "otherise" to "otherwise" in the documentation and "extremly" to "extremely" in a code comment. These changes improve clarity and maintain consistency in the codebase. No functional code changes are included.

Fix Typos in Documentation and Comments

---

quickwit/quickwit-config/src/source_config/mod.rs
quickwit/quickwit-query/src/aggregations.rs

This pull request corrects minor typographical errors in comments and documentation to improve code clarity and maintain professionalism.

Fix Typos in Comments and Documentation

---

docs/operating/upgrades.md

After some issues raised in https://github.com/quickwit-oss/quickwit/issues/5787#issuecomment-2979470315, we should just recommend a full cluster restart when upgrading from 0.8.2 to main/0.9

Recommend a full cluster restart for upgrade

---

quickwit/quickwit-search/src/search_permit_provider.rs

Fix an unlikely but critical panic in the search permit provider.

Fix unlikely provider panic when requesting search permit

---

quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/README.md

Update the README to try to better match the implementation.

Update scheduling README

---

quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/mod.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/scheduling/scheduling_logic.rs

Closes https://github.com/quickwit-oss/quickwit/issues/4470
Closes https://github.com/quickwit-oss/quickwit/issues/5747
Closes https://github.com/quickwit-oss/quickwit/issues/4630
This addresses both the limitation that only 1 merge pipelines can run per indexer at any given time and the fact that nodes systematically end up with all pipelines of a source when using Kafka, even if the number of pipelines for that source is rather large.
Added unit test, should add more

Limit to 3 pipelines per node per source

---

docs/configuration/storage-config.md
quickwit/quickwit-config/src/storage_config.rs

Fixes #5822
Same approach as for garage.

Fix MinIO configuration to always set region to 'minio'

---

quickwit/quickwit-indexing/src/source/mod.rs
quickwit/quickwit-indexing/src/source/stdin_source.rs

Fixes #5772.
Tested the local ingest on the otel-logs-v0_9 index with the following json
```json
{"timestamp_nanos":1640995200000000000,"observed_timestamp_nanos":1640995200000000000,"service_name":"my-service","severity_text":"INFO","severity_number":9,"body":{"message":"User logged in successfully"},"attributes":{"user_id":"12345","endpoint":"/login"},"resource_attributes":{"host.name":"server-01","service.version":"1.0.0"}}
```

Fix stdin source registration for local-ingest tool. Fixes #5772.

---

quickwit/quickwit-actors/src/envelope.rs
quickwit/quickwit-actors/src/spawn_builder.rs

Reorganize the actor exit logs:
- explicit where the exit is coming from (initialization? hander? ...)
- remove `actor-failure` logs (redundant with `actor-exit`)
- remove redundant `?exit_status` and `cause?err` as both contain the error for the `ActorExitStatus::Failure(err)` variant
Example log lines:
```
2025-05-21T12:21:09.001Z  INFO quickwit_actors::spawn_builder: actor-exit actor_id="SourceActor-morning-3QVF" phase=running exit_status=Killed
2025-05-21T12:21:09.035Z  INFO quickwit_actors::spawn_builder: actor-exit actor_id="Indexer-blue-M2W5" phase=handling(quickwit_actors::command::Command) exit_status=Success
```

Log actor exit phase

---

docs/internals/split-format.md

The split_fields file added by Quickwit is not described in the split spec.

Add split_fields description to split spec

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-cluster/src/cluster.rs
quickwit/quickwit-control-plane/src/tests.rs
quickwit/quickwit-serve/src/lib.rs

Closes https://github.com/quickwit-oss/quickwit/issues/5787
Currently, Quickwit node would keep running if chitchat server stops (panic or error). This PR adds a watcher for this and stops the nodes if something goes wrong in chitchat.
This PR depends on https://github.com/quickwit-oss/chitchat/pull/162

Exit when chitchat server fails

---

quickwit/Cargo.lock
quickwit/Cargo.toml
quickwit/quickwit-indexing/src/source/kafka_source.rs

Bump rdkafka to fix some issue with kafka 4.X.X and kraft

Bump rdkafka to fix some issue with kafka 4.X.X and kraft

---

quickwit/quickwit-ingest/src/ingest_v2/mod.rs
quickwit/quickwit-opentelemetry/src/otlp/logs.rs
quickwit/quickwit-opentelemetry/src/otlp/traces.rs

Remove deduplication of logs and traces by service name and timestamp, which causes the issue reported in #5852. I chose to remove the sorting logic entirely. It's unclear if we get any performance from this, especially after merges occur. I was certainly guilty of premature optimization when I wrote this garbage :/

Remove deduplication of logs and traces by service name and timestamp

---

quickwit/quickwit-query/src/query_ast/term_query.rs
quickwit/quickwit-query/src/query_ast/utils.rs

Tantivy's PR https://github.com/quickwit-oss/tantivy/pull/2456 removed date truncation to the second in method `from_field_date` and introduced a new method `from_field_date_for_search` for this purpose.
> Fixes date truncation issue in Term, where DateTime was truncated to seconds precision unconditionally, but we only want to apply that truncation on the inverted index.
It seems that the method used by Quickwit to generate the Term struct during searches was never updated.
Added a unit test

fix: Use appropriate Term method for date search

---

monitoring/grafana/dashboards/searchers.json

I think this was a typo.
Honestly, I'm not sure this is useful to monitor. They are pretty much the same with the rate of total requests.

fix the PromQL for cache misses

---

quickwit/quickwit-search/src/list_fields.rs

Searchers sometime OOM when returning too many fields (~millions). This PR adds a hard limit on the number of fields that can be returned.
- configured through an env variable QW_FIELD_LIST_SIZE_LIMIT
- if there are more fields than the limit, a 500 error is returned

Add a hard limit on field list size

---

quickwit/quickwit-cli/src/logger.rs
quickwit/quickwit-cli/src/main.rs
quickwit/quickwit-common/src/cpus.rs
quickwit/quickwit-common/src/lib.rs
quickwit/quickwit-common/src/shared_consts.rs
quickwit/quickwit-control-plane/src/indexing_scheduler/mod.rs
quickwit/quickwit-index-management/src/garbage_collection.rs
quickwit/quickwit-ingest/src/ingest_v2/ingester.rs
quickwit/quickwit-ingest/src/ingest_v2/router.rs
quickwit/quickwit-search/src/list_fields.rs
quickwit/quickwit-serve/src/lib.rs
quickwit/quickwit-serve/src/load_shield.rs
quickwit/quickwit-serve/src/rest.rs
quickwit/quickwit-storage/src/object_storage/s3_compatible_storage.rs

- Add sensitive parameter so `get_from_env` functions can be used to get API keys, etc.

add sensitive param to get_from_env_opt

---

quickwit/quickwit-indexing/src/source/kinesis/kinesis_source.rs

Currently, the Kinesis source would panic when encountering resharding scenarios (shard splits/merges) because it attempted to create duplicate consumers for the same shard.
This occurred when:
1. The source initialized and created consumers for all shards (including closed parent shards)
2. Parent shard consumers would send ChildShards messages when reaching the end
3. The source would try to spawn consumers for child shards that were already created
This replaces the assertion with a check that safely skips duplicate consumer creation.
Fixes #5896
* Added the `test_kinesis_source_handles_resharding_with_split` test
```
cargo test -p quickwit-indexing --features kinesis,kinesis-localstack-tests test_kinesis_source_handles_resharding_with_split -- --ignored
```
* Verified with an actual …

Fix Kinesis source panic on resharding
